### ISSUE TITLE
Allow <length-percentage> in <keyframe-selector> when combined with <timeline-range-name>

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#10000]

**Comment by nathanbabcock** [comment]
Really sensible idea. Here's a supporting example that led me here:

![image](https://github.com/w3c/csswg-drafts/assets/9583103/751ab6c4-fc61-4914-92df-737e51b4dbc0)

https://codepen.io/nathanbabcock/pen/zYXmNwX

The goal is to add a gradient fade effect to the top/bottom of scrolling content as a subtle indication that there's more content in that direction. It should smoothly fade out when reaching the top or bottom of the scroll container (at an absolute pixel offset proportional to the length of the fade effect). Even with `animation-range`, there's no way to accomplish this effect without double-nesting the content in two separate divs: one to track offset from the top, and one to track offset from the bottom.

Bramus' proposal above would make it possible to express all the logic underneath a single `@keyframes` block.

**Comment by bramus** [comment]
After reading #10879, maybe we should allow `<length-percentage>` inside `<keyframe-selector>` in general, to open up the `scroll-timeline` case as well?

```css
@keyframes f {
  0% { translate: 0% 0%; } /* ✅ Allowed */
  150px { translate: 0% -100%; } /* ❌ Not allowed */
}

el {
  animation-name: f;
  animation-timeline: scroll();
}
```

_(These are the keyframes for something like [this shrinking header](https://scroll-driven-animations.style/demos/shrinking-header-shadow/css/) that animates using the `animation-range` `0px 150px`)_

If we don’t want this extra addition, the [current proposal](https://github.com/w3c/csswg-drafts/issues/10000#:~:text=name%3E%20%3Clength%2Dpercentage%3E%3F%20%5D%23-,Proposed%20Solution,-Allow%20%3Clength%2Dpercentage) can already work if we enable `scroll` to target the full range of the `ScrollTimeline` (see request [here](https://github.com/w3c/csswg-drafts/issues/9367#issuecomment-1905788011)):

```css
@keyframes f {
  scroll 0% { translate: 0% 0%; } /* ✅ Allowed */
  scroll 150px { translate: 0% -100%; } /* ❌ Not allowed */
}

el {
  animation-name: f;
  animation-timeline: scroll();
}
```
