### ISSUE TITLE
Request for New CSS Property: 'mask-rotation'

### ISSUE THREAD

**Issue by Thiago2104** [w3c/csswg-drafts#10024]
### Summary:
I am proposing the addition of a new CSS property, mask-rotation, to provide developers with more control over the orientation and rotation of CSS masks.

### Motivation:
Currently, CSS offers properties like `mask-size`, `mask-origin`, and `mask-position` for controlling the size, origin, and position of masks. However, there is no direct property to manage the rotation or orientation of the mask. This feature would be particularly useful for scenarios where precise control over the mask's rotation is required.

### Proposed Solution:
Introduce a new property, mask-rotation, that allows developers to specify the rotation angle for CSS masks. The property value could accept degrees (deg) as a unit, similar to how rotate works in transformations.

### Example:
```css
.element {
    mask-image: url('mask.png');
    mask-size: cover;
    mask-origin: center;
    mask-rotation: 45deg; /* Rotates mask-image 45 degrees clock-wise */
}
```
### Key Words:
The new property could have key words to specify the type of rotation and the axis where it is rotating:

- `right`: Rotate the mask 90 degrees
- `flip`: Rotate the mask 180 degrees
- `left`: Rotate the mask 270 degrees

Also, adding the axis to the key words specify the axis where it is rotating:

- 'x' (default): Rotates in clock-wise direction
- 'y': Rotates mask horizontally
- 'z': Rotates mask vertically

### Example:
```css
.element {
    mask-image: url('mask.png');
    mask-size: cover;
    mask-origin: center;
    mask-rotation: y right, flip; /* Rotates mask-image horizontally 90 degrees, and rotates mask 180 degrees clock-wise */
}
```
### Benefits:

- Enhances flexibility in designing complex visual elements.
- Provides a more comprehensive set of tools for controlling mask behavior.
- Enables masks complex animations.
- Aligns with existing CSS properties, making it intuitive for developers.

**Comment by fantasai** [comment]
We should do backgrounds and masking in conjunction here... and I wonder if it shouldn't be a more generic -transform property.

**Comment by SebastianZ** [comment]
This use case is covered by the `@image` rule we [resolved on](https://github.com/w3c/csswg-drafts/issues/6807#issuecomment-1248380039).

Examples:

```css
@image --rotate {
  rotate: 45deg;
}

@image --flip-vertically {
  transform: rotateX(180deg);
}

.element {
    mask-image: image(url('mask.png'), --rotate);
    mask-size: cover;
}

.element {
    mask-image: image(url('mask.png'), --flip-vertically);
    mask-size: cover;
}
```

This has two major advantages over new properties:

1. It can be used everywhere were images are allowed and is not limited to masks.
2. It allows all kinds of image manipulations and is not limited to rotations.

So I vote to close this in favor of the more general solution.

Sebastian

PS: @Thiago2104 Your second example rotates the image by 90 degrees along the y-axis, which effectively makes it invisible.

**Comment by Thiago2104** [comment]
Hi Sebastian

I've tried your proposal with a mask image animation that makes the mask to rotate 180deg when `.dark` tag triggers. I'm using an svg as the mask:
```css
@image --rotate {
  rotate: 180deg;
}
.light .alternate-gradient-bg{
    clip-path: circle(150% at 95.25% 90.5%);
    mask-image: none;
    mask-composite: exclude;
    mask-repeat: no-repeat;
    mask-size: 4500px;
    mask-position: bottom -2180px right -2180px;
    transition: 1s ease-out;
}
.dark .alternate-gradient-bg{
    clip-path: circle(4.4% at 95.25% 90.5%);
    mask-image: image(url("/BlackHole.svg"), --rotate);
    mask-composite: exclude;
    mask-repeat: no-repeat;
    mask-size: 100px;
    mask-position: bottom 20px right 20px;
    transition: 1s ease-out;
}
```
But what I got is that the tag `image` in the mask-image makes the mask of the svg to not being applied even without using the `@image` rule. 
What I currently have is a mask animation where the gradient background has a black hole mask, that when combined with clip-path and changing the mask-size, gives the illusion of the background being absorbed by a blackhole, the only thing left is making the mask to rotate from 0 to 180deg during transition so the black hole effect is done. That's why I'm proposing a mask-rotate property, so it is consistent with mask-size and mask-position properties on making mask animations.
