### ISSUE TITLE
[css-view-transitions-2] Specificity of the new :active-view-transition-type

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#10071]
In https://github.com/w3c/csswg-drafts/issues/9972 we resolved to rename `active-view-transition(params)` to `active-view-transition-type(params)` and add a no-params `active-view-transition`. 

Previously the specificity of `active-view-transition(params)` was 1 class-like if params was `*` and 2 class-like otherwise. For `active-view-transition-type(params)` params can't be `*`. So should it be 2 class-like specificity always? Or should it be 1 class-like?

**Comment by noamr** [comment]
Based on previous resolutions I think it needs to be that `active-view-transition` is one pseudo-class and `active-view-transition-type` is two; That would be reflecting the current status.

**Comment by nt1m** [comment]
I'm tempted to follow `:has()` or `:is()` here. So I guess it would equal a type selector.

**Comment by noamr** [comment]
> I'm tempted to follow `:has()` or `:is()` here. So I guess it would equal a type selector.

I'd say that if you have an active view transition it's more equivalent to a `:hover`, which gets 1-class specificity, it says something about the current state of the element, while `:has` and `:is` are only about the DOM structure.

**Comment by noamr** [comment]
Another way to look at this is that:
```css
html:active-view-transition {}
/* is equivalent to */
html.active-view-transition {}

/* and */
html:active-view-transition-type(slide)
/* is equivalent to */
html[active-view-transition-type="slide"]
```

So if we agree with this analogy, both pseudo-class should have a 1-class specificity.
