### ISSUE TITLE
[css-fonts-4] 90-degree oblique means?

### ISSUE THREAD

**Issue by SamB** [w3c/csswg-drafts#10084]
So I noticed that https://drafts.csswg.org/css-fonts-4/#propdef-font-style lets you do this:

https://developer.mozilla.org/en-US/play?id=RwqvczHT9BBF%2FM%2Fui2mK8HA%2BoFvn%2FYaKPD7JcaMY3ES4yxk%2BckvLxowPWfSIOAOGeAIk6TiLXNHbgkrG

```html
<body>Hi.</body>
```

```css
/* A font with no italic/oblique face */
@import url(https://cdn.jsdelivr.net/npm/@fontsource/unifont/index.min.css);

body {
  font-family: Unifont;
  font-style: oblique 90deg;
}
```

In Chrome, this apparently just synthesizes a 12 degree oblique or whatever, which is apparently totally okay because
the spec doesn't say which oblique faces a user agent may synthesize, so that's not super interesting.

Firefox seems to try to actually do 90 degree oblique, but it's a little hard to tell because I'm pretty sure the transformation isn't actually defined mathematically at that point?

What should actually happen here? It would probably be a good idea to at least add a note that ±90deg doesn't really make sense, suggest browsers consider clamping synthesis to a smaller range, and add wpt tests to make sure browsers at least don't crash if they actually try to synthesize that.

(Font designers would presumably be able to see that this does not make sense, and in any case, this spec doesn't seem to define validity for fonts themselves.)
