### ISSUE TITLE
[css-text-4] Japanese Paragraph-start Conventions in CSS need to be updated

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/csswg-drafts#10144]
CSS Text Module Level 4
8.5.3. Japanese Paragraph-start Conventions in CSS
https://drafts.csswg.org/css-text-4/#japanese-start-edges

> - Brackets flush with indent, flush with other lines (first scheme):
>   ```css
>   p { /* Flush alignment */
>     margin: 0;
>     text-indent: 1em;
>     text-spacing-trim: trim-auto;
>   }
>   ```
> - Brackets preserve fullwidth spacing on all lines (second scheme):
>   ```css
>   p { /* Fullwidth alignment */
>     margin: 0;
>     text-indent: 1em;
>     text-spacing-trim: space-all;
>   }
>   ```
> - Brackets hang in indent, flush with other lines (third scheme):
>   ```css
>   p { /* Hanging alignment */
>     margin: 0;
>     text-indent: 1em;
>     text-spacing-trim: trim-auto;
>     hanging-punctuation: first;
>   }
>   ```

In the second scheme, `text-spacing-trim: space-all` which is typographically very poor should be changed to `text-spacing-trim: normal`.

In the first and third schemes, `text-spacing-trim: trim-auto` is good but `text-spacing-trim: trim-start` would be more appropriate because:

- `trim-start` just changes the line start behavior and keeps the line end behavior as `normal`. This is good to show the differences between Japanese paragraph-start conventions.
- [JLREQ §3.1.9 Positioning of Closing Brackets, Full Stops, Commas and Middle Dots at Line End](https://www.w3.org/TR/jlreq/#positioning_of_closing_brackets_full_stops_commas_and_middle_dots_at_line_end) says “In principle, closing brackets (cl-02), commas (cl-07) or full stops (cl-06) at the line end have half em spacing after them. This half em spacing can be removed for line adjustment.” This corresponds to `trim-start`'s line end behavior, not `trim-auto`'s.
- Chromium supports `trim-start` but not `trim-auto` yet, unfortunately. (https://developer.chrome.com/blog/chrome-123-beta#the_css_text-spacing-trim_property says “The `text-spacing-trim` property accepts one of the following four values: `normal`, `trim-start`, `space-all`, and `space-first`.”)

So I suggest changing these examples as follows:

- Brackets flush with indent, flush with other lines (first scheme):
  ```css
  p { /* Flush alignment */
    margin: 0;
    text-indent: 1em;
    text-spacing-trim: trim-start;
  }
  ```
- Brackets preserve fullwidth spacing on all lines (second scheme):
  ```css
  p { /* Fullwidth alignment */
    margin: 0;
    text-indent: 1em;
    text-spacing-trim: normal;
  }
  ```
- Brackets hang in indent, flush with other lines (third scheme):
  ```css
  p { /* Hanging alignment */
    margin: 0;
    text-indent: 1em;
    text-spacing-trim: trim-start;
    hanging-punctuation: first;
  }
  ```
