### ISSUE TITLE
[css-cascade-6] reusable named scopes

### ISSUE THREAD

**Issue by mayank99** [w3c/csswg-drafts#10336]
_(This was originally posted in https://github.com/w3c/csswg-drafts/issues/9742#issuecomment-2002084564 but moved to its own issue later.)_

Proposal:

A scope _statement_, similar to a layer statement, could be used to create a reusable named scope. For example:

```css
@scope foo (.start) to (.end);
```

A reusable named scope can then be used without specifying `<scope-start>`/`<scope-end>`:

```css
@scope foo {
  p { color: red; }
}
```

The main thing this enables is avoiding the need to repeat selectors for every use.

---

Open questions:
- how do we handle duplicate scope names?
- how do we differentiate between [named scopes](https://github.com/w3c/csswg-drafts/issues/9742) and reusable named scopes? (different syntax?)

**Comment by romainmenke** [comment]
For `@media` this same feature is currently specified as `@custom-media` : https://drafts.csswg.org/mediaqueries-5/#custom-mq

```css
@custom-media --modern (color), (hover);

@media (--modern) and (width > 1024px) {
  .a { color: green; }
}
```

This separates declaring a scope and using a scope.
