### ISSUE TITLE
[css-values-5] Should an arbitrary substitution nested within another be accepted in context?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10337]
```css
@page { size: env(safe-area-inset-top, attr(size length)) }
```

Is `size` declared with a valid value?

`var(--custom, var(1))` must be invalid in any property value: the basic syntax of `var(1)` is checked, but should its validity in the context be checked?
