### ISSUE TITLE
[css-values-5] Should `<whole-value>` functions be parsed before the declaration value range?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10340]
CSS-wide keyword parsing should kick in first because `--custom: initial` should result to `--custom` being declared to its initial (guaranteed-invalid) value rather than the `<ident-token>` for `initial` (the result from matching against its value definition).

Arbitrary substitution parsing should then kick in before the value range because `--custom: var(1)` should be invalid. They should be parsed before `<whole-value>` because `display: var(--empty) first-valid(block)` should be valid (at parse time, at least).

Should `--custom: first-valid(not, whole) value` be valid?

**Comment by Loirooriol** [comment]
Unregistered custom properties just tokenize, except for a few things like `var()` and `env()`. So:
 - If `first-valid()` is a normal function, it's accepted, as a token.
 - Otherwise I guess it's invalid.

I don't see any reason to treat it specially, since unregistered custom properties accept almost everything?
I don't think it's likely that people will want `--foo: first-supported(var(b), var(--b))` to behave as `--foo: var(--b)` because `--foo: var(b)` is invalid.
I think it's more likely that people will want to defer the resolution of `first-supported`, e.g.

```css
:root {
  --color: first-supported(color(brand-new-color-space, ...), cyan);
}
.foo { color: var(--color) }
#bar something { color: var(--color) }
```
