### ISSUE TITLE
[css-ui-4] Extend the `outline` shorthand value to include offset

### ISSUE THREAD

**Issue by jossmac** [w3c/csswg-drafts#10381]
Proposal to extend the [outline](https://www.w3.org/TR/css-ui-4/#outline) shorthand value to optionally include an `outline-offset` value.

The desire for this change is to simplify/improve CSS variable declarations as complete design tokens. The [font](https://www.w3.org/TR/css-fonts-4/#propdef-font) shorthand property is terrific for this purpose. Borrowing from that API, a slash delimiter (`/`) would offer the opportunity to declare an optional offset value e.g.

```css
/* current */
:focus  {
  outline: 3px solid black;
  outline-offset: 2px;
}

/* proposed */
:focus  {
  outline: 3px solid black / 2px;
}
```

Abbreviated syntax:

```css
outline = 
  <'outline-color'> ||
  <'outline-style'> ||
  <'outline-width'>
  [ / <'outline-offset'> ]
```

Related:

- #8788 
- #10343
