### ISSUE TITLE
[selectors] Add selector match custom element

### ISSUE THREAD

**Issue by mantou132** [w3c/csswg-drafts#10407]
e.g: `:custom-element`

This pseudo-class can make the `@socpe` style not affect the content of the custom element:

```html
<style>
@scope (.main) to (:custom-element) {
  p { /** **/ }
}
</style>
<p>my content</p>
<any-custom-element>
  <p>component or third-party content</p>
</any-custom-element>
```

StackOverflow issue: https://stackoverflow.com/questions/31480950/custom-element-selector

**Comment by mantou132** [comment]
**Another real-world use case: CSS resets / framework preflights overriding custom element styles**

A concrete example of why this selector is needed comes from CSS resets like Tailwind CSS's preflight. Tailwind v4 ships a preflight that includes a universal rule:

```css
*, ::after, ::before, ::backdrop, ::file-selector-button {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  border: 0 solid;
}
```

This rule unintentionally overrides `:host` styles defined inside Web Components' Shadow DOM, because the custom element's host node still belongs to the document's style scope. Even though `:host` has higher specificity *within* the shadow tree, the document-level `*` selector wins for properties applied to the host element from outside.

See the related Tailwind discussion: https://github.com/tailwindlabs/tailwindcss/discussions/18628

The workaround today is either `!important` inside the component, or manually excluding elements from the reset — both of which are fragile and require component authors or framework users to know about this interaction ahead of time.

With a `:custom-element` pseudo-class (or equivalent), framework authors could write:

```css
*:not(:custom-element) {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  border: 0 solid;
}
```

This would make resets and preflights respect the boundary of custom elements by default, without requiring any special knowledge from component authors.
