### ISSUE TITLE
[css-anchor-position-1][css-position] behavior of position-area when no anchor is defined

### ISSUE THREAD

**Issue by Afif13** [w3c/csswg-drafts#10500]
I just tried the below code:

```css
.container {
  position: relative;
}
.element {
  position: absolute;
  inset-area: center;
  margin: auto;
}
```

And to my surprise, it center the absolute element. Demo: https://codepen.io/t_afif/pen/OJYwybK

Based on the [Specification](https://www.w3.org/TR/css-anchor-position-1/#inset-area) the propety applies to "positioned elements with a [default anchor element](https://www.w3.org/TR/css-anchor-position-1/#default-anchor-element)". Does it mean that any positioned element has a default anchor which is its containing block?

If it's the correct behavior, I think the Spec should clarify the "default anchor" part. Or maybe this is a bug and `inset-area` should have no effect?
