### ISSUE TITLE
[css-values-5] [css-overflow-4]How does `line-clamp` transition from `<integer>` to `auto` or `none`?

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#10502]
@andreubotella The current implementation of `line-clamp` in Chrome adds `auto` values, and the use case here is very much like the `height: 0` to `auto` scenario.

Will the `interpolate-size` property added a while ago work in this scenario?

Demo: https://codepen.io/yisi/pen/rNgojEx

cc @frivoal @tabatkins @dbaron @flackr

**Comment by yisibl** [comment]
cc @andreubotella

**Comment by andreubotella** [comment]
I don't know too much about `interpolate-size`, but the way that property is specified, it wouldn't apply to `line-clamp`, because the spec text specifically mentions interpolating between a length (such as `3px`, but not `3`), and an intrinsic size keyword. Although `auto` is an intrinsic size keyword for the `height` property because it denotes a size, `auto` for `line-clamp` does not denote a size.

Things get more complicated when you consider that the number of lines that `auto` corresponds to depends on the `height` and/or `max-height` properties. If those properties also transition during the `line-clamp` transition, then the transition will not look smooth. In particular, since the transition from `max-height: none` to `max-height: 200px` is discrete, if `line-clamp: 3` transitions to `line-clamp: auto` at the same time, then the number of lines before clamp might very well jump in the middle of the transition.

That said, I'm not familiar enough with transitions to know what the right behavior would be here.

**Comment by andreubotella** [comment]
Thinking about this again, I wonder what the use case would be to transition from clamping by a number of lines to clamping by a height.

Usually `line-clamp` indicates hidden content, and transitions based on that would usually expand back to the full size. And that would currently be possible with `line-clamp: auto`, by transitioning a set height to `auto`:

```css
.item {
  transition: height 3s;
  interpolate-size: allow-keywords;
  overflow: hidden;
}
.item.collapsed {
  line-clamp: auto;
  height: 4lh;
}
```

https://github.com/user-attachments/assets/e3525ee2-bce5-4fa3-8ce3-c41da09db292

----

Rather than the lines appearing or disappearing into the hidden overflow, you could also set `line-clamp: auto` on `.item` (so it's enabled on both sides of the transition) to change the number of clamped lines as the height animates. (Note that this could cause jank, since every frame would need a separate layout.) This doesn't seem to work currently in my implementation in Chromium, but it's probably a simple layout caching bug. This is what it'd look like:

```css
.item {
  line-clamp: auto;
  transition: height 3s;
  interpolate-size: allow-keywords;
  /* height: auto is implicit */
}
.item.collapsed {
  height: 4lh;
}
```

https://github.com/user-attachments/assets/9b01fed3-3b26-4eaa-be8e-f943c066a9c5

----

But maybe there are other use cases for transitioning between a number and `auto` that I haven't thought of.
