### ISSUE TITLE
[css-nesting-1] Clarify when nested rules are equivalents to `:is()`

### ISSUE THREAD

**Issue by paceaux** [w3c/csswg-drafts#10523]
### Could you provide clarity for when `:is()` is used for selectors

In the [examples](https://drafts.csswg.org/css-nesting-1/#syntax-examples) section, I spotted some examples that _seem_ to suggest contradictory situations where `:is()` is an equivalent to the nested code. 

This example suggests that `:is()` is an equivalent when there's a list of multiple selectors:

```css
/* multiple selectors in the list are all
   relative to the parent */
.foo, .bar {
  color: blue;
  + .baz, &.qux { color: red; }
}
/* equivalent to
  .foo, .bar { color: blue; }
  :is(.foo, .bar) + .baz,
  :is(.foo, .bar).qux { color: red; }
*/
```

And this seems consistent with this example, where it is not considered to be an equivalent to an `:is()`

```css

/* & doesn’t have to be at the beginning of the selector */

.foo {
  color: red;
  .parent & {
    color: blue;
  }
}
/* equivalent to
  .foo { color: red; }
  .parent .foo { color: blue; }
*/

```

However, I then see this example where there is _not_ a list of selectors, but it's called an "equivalent" of an `:is()`

```css
.ancestor .el {
  .other-ancestor & { color: red; }
}
/* equivalent to
  .other-ancestor :is(.ancestor .el) { color: red; }

```

The difference between the first and third examples is that in the first, the parent is a single selector while in the third there is a general-descendant selector. I wouldn't consider `.ancestor .el` to be a selector _list_ because there's no comma indicating more selectors. 

**Request**:
Could you please explicitly describe when nested CSS produces an equivalent to `:is()`. i.e.:

* in cases where there are selector lists, the lists will be considered arguments of `:is()`
* in cases where the selector is complex (having greater than 1 id, type, or class selector), it is considered an argument of `:is()`

### Could you provide clarity on the equivalency of `&` and `:is()`

In the draft, in the [section about mixing nesting rules and declarations](https://drafts.csswg.org/css-nesting-1/#mixing), There is this example 

```css
article {
  color: green;
  & { color: blue; }
  color: red;
}

/* equivalent to */
article { color: green; }
:is(article) { color: blue; }
article { color: red; }

/* NOT equivalent to */
article { color: green; }
article { color: red; }
:is(article) { color: blue; }
```

I understand the point about order. However, I also observe an _implication_ regarding what `&` does. This suggests that `&` will produce an `:is()` if it's neither preceded or seceded by another selector. 

However, this contradicts an earlier example:

```css
/* Somewhat silly, but & can be used all on its own, as well. */
.foo {
  color: blue;
  & { padding: 2ch; }
}
/* equivalent to
  .foo { color: blue; }
  .foo { padding: 2ch; }

```

**Request**
Could the incorrect example be removed? Or if they're somehow both correct, could you explain how?

### Could you explicitly call out the conditions under which `&&` would work. 

The specifications give this example

```css
/* Again, silly, but can even be doubled up. */
.foo {
  color: blue;
  && { padding: 2ch; }
}
/* equivalent to
  .foo { color: blue; }
  .foo.foo { padding: 2ch; }
*/
```

But it has also been made very clear that the `&` is not capable of sass-like concatenation. 

So then what is the output of these examples?
```css
  article {
    && {
      padding: 2ch;
  }
}

  .article {
    && {
     padding: 2ch;
  }
 }

#article {
  && {
    padding: 2ch;
  }
}

```
The examples, as they're given, suggest one of these produces an error:

```css

articlearticle {
  padding: 2ch;
}

.article.article {
  padding: 2ch;
}

#article#article {
  padding: 2ch;
}
```

_unless_ the `&` is actually _always_ an equivalent to `:is()`. In which case each condition produces valid selectors:

```css

article:is(article) {}
.article:is(.article) {}
#article:is(#article){}
```

But if this is the case, that contradicts [this example](https://www.w3.org/TR/css-nesting-1/#example-ee2b228d) where the `&` seems to be "consumed". 

**Request**
Could you expand the "Nesting Selector" section and explain _when_ `&` is an equivalent to `:is()`. Could you add a section that explicitly calls out how behavior may differ with a type selector? Maybe add an example of `&&` to the [slightly rephrased example with type selectors](https://www.w3.org/TR/css-nesting-1/#example-34e8e94f)

**Comment by mirisuzanne** [comment]
The `&` selector is _always equivalent_ to using `:is()` - they use the same mechanism. In some cases, both `&` and `:is()` are _also_ equivalent to a bare selector. Generally, for example, `:is(article)` and `article` are equivalent selectors. They are not the same selector, but they select the same thing at the same specificity. They are all three equivalent in this case:

```css
article { & { color: red; } }
:is(article) { color: red; }
article { color: red; }
```

In Sass, the `&` is literally replaced by another selector, which can result in concatenation. But in CSS, `&` _is the selector_ – just like `article` is a selector. So `&&` doesn't _become_ something else, it remains `&&` (a valid selector). But the result of that valid selector (in your example) is _equivalent to_ `:is(article):is(article)`, and not `articlearticle`.

The spec examples are not showing literal transformations that happen to your selector, they are showing alternative selectors that have equivalent results.

- You will always get an equivalent result by replacing `&` with `:is()`, because both selectors use the same underlying mechanism
- You will _sometimes also_ get an equivalent result by replacing `&` with a bare selector, because sometimes `:is(<selector>)` will behave the same as `<selector>` on its own

Does that make sense?

**Comment by paceaux** [comment]
@mirisuzanne Yes that does make sense and it is incredibly helpful. I want to make sure that I understand this behavior properly:

1. In all cases of nested selectors, the nearest "true equivalent" will be a selector that uses the `:is()` pseudo-selector
2. Both the parent *and* the nested selector(s) would be considered to be wrapped in an`:is()`  (e.g. `article { h1 {display: block}}` => `:is(article) :is(h1)`
3. the _unnested_ `&` ends up representing `*` (e.g. `& {display: block;}` => `:is(*) {display: block}`)
4. The nested `&` that doesn't have any inline selectors is a _single_ application of `:is()` where it's the _parent_ that's wrapped in an `:is()`. e.g. ( `section > article { & {display: block}}` => `:is(section > article)`
5. The nested `&` that _does have inline selectors_ is a multi-application of `:is()` because it comes from both parent and nested child. e.g. `section > article {main & {display: block}}` => `:is(main) :is(section > article) {display: block}`
 
6.  double-& is a double-chained `:is()`, but the reality is that it has nothing to do with what's nested. It's because nesting triggers children and parents to be wrapped in `:is()`, and in this case we've just chained our parent `:is()` together.  

```
article { /*:is(article):is(article) */
 && {
  display: block;
 }
}

.article {
 && { /* :is(.article):is(.article) */
   display: block;
 }
}
```

I know that the nesting behavior _superficially_ looks / acts like Sass. But what I'm really trying to understand is all the ways it _isn't like Sass_. 

Sass of course errors on a single nested `&`. It also wouldn't allow an unnested `&`, nor would it allow `&&`, all of which aren't problematic in CSS. 

Do you think it might be beneficial to explain explicitly in the documentation how nesting invokes `:is()` on both parent _and_ child, and to possibly even give an example of the unnested `&` so as to illustrate how it _also_ uses `:is()` ?

**Comment by mirisuzanne** [comment]
> I want to make sure that I understand this behavior properly:

No problem, glad that helped. In the meantime, I'm going to close this as 'question answered' if you don't mind.

> 1. In all cases of nested selectors, the nearest "true equivalent" will be a selector that uses the `:is()` pseudo-selector

right

> 2. Both the parent _and_ the nested selector(s) would be considered to be wrapped in an`:is()`  (e.g. `article { h1 {display: block}}` => `:is(article) :is(h1)`

no, only the `&` should be thought of as similar to `:is(<parent>)`

> 3. the _unnested_ `&` ends up representing `*` (e.g. `& {display: block;}` => `:is(*) {display: block}`)

No, see the [Editor's Draft](https://drafts.csswg.org/css-nesting/#nest-selector) (emphasis added): 

> When used in the selector of a nested style rule, the nesting selector represents the elements matched by the parent rule. _When used in any other context, it represents the same elements as `:scope` in that context (unless otherwise defined)._

This is also often equivalent to `:root`, when not in scoped situations. According to [this previous resolution](https://github.com/w3c/csswg-drafts/issues/8088#issuecomment-1371590352) it has a specificity of `0` in those situations.

> 4. The nested `&` that doesn't have any inline selectors is a _single_ application of `:is()` where it's the _parent_ that's wrapped in an `:is()`. e.g. ( `section > article { & {display: block}}` => `:is(section > article)`
> 5. The nested `&` that _does have inline selectors_ is a multi-application of `:is()` because it comes from both parent and nested child. e.g. `section > article {main & {display: block}}` => `:is(main) :is(section > article) {display: block}`

As far as I can tell, only the `&` should ever be treated 'like' `:is(<parent-selector>)`. There is never any need to think of the nested selector as though it is wrapped. I've confirmed that with a [quick test of the resulting specificity](https://codepen.io/miriamsuzanne/pen/abgbRoa) on codepen.

> 6. double-& is a double-chained `:is()`, but the reality is that it has nothing to do with what's nested. It's because nesting triggers children and parents to be wrapped in `:is()`, and in this case we've just chained our parent `:is()` together.
>
> ```
> article { /*:is(article):is(article) */
>  && {
>   display: block;
>  }
> }
> 
> .article {
>  && { /* :is(.article):is(.article) */
>    display: block;
>  }
> }
> ```
> 
The replacement is a metaphor, but a fairly reliable one. The `&` is a selector that matches the same elements as the parent selector, with `:is()`-like implications. And it can be chained as desired. 

The big difference here is that Sass does literal string replacement, which can change the selector meaning based on context – `.foo { &bar {}}` becomes `.foobar`. But CSS does not do any replacement, so the `&` selector has the same meaning no matter how you combine it with other things. It means: _the same elements as above_. In that case the direct `:is()` replacement doesn't work (`:is(.foo)bar`) – but the same meaning still holds. We just have to turn it around to get the equivalent `bar:is(.foo)`.

But yes, in your case, the chained-`is()` metaphor continues to be reliable.

> I know that the nesting behavior _superficially_ looks / acts like Sass. But what I'm really trying to understand is all the ways it _isn't like Sass_.
> 
> Sass of course errors on a single nested `&`. It also wouldn't allow an unnested `&`, nor would it allow `&&`, all of which aren't problematic in CSS.

Besides the impact on specificity, and the inability to do string-concatenation, [this thread](https://github.com/w3c/csswg-drafts/issues/8310) covers the biggest difference that I would note. Here's [a codepen demo of the difference](https://codepen.io/pen?editors=1100).

> Do you think it might be beneficial to explain explicitly in the documentation how nesting invokes `:is()` on both parent _and_ child and to possibly even give an example of the unnested `&` so as to illustrate how it _also_ uses `:is()` ?

I don't believe those assertions are correct. :) 

But it's possible @tabatkins will want to clarify some of the examples based on this conversation, I'm not sure.

**Comment by paceaux** [comment]
@mirisuzanne Thank you again for clarifying. I really appreciate you using the term, "chained `is()` metaphor," because that really helps solidify how one should understand what is happening. 

I would strongly encourage the specifications to use this terminology to help CSS users understand the mechanics. 


> As far as I can tell, only the & should ever be treated 'like' :is(<parent-selector>). There is never any need to think of the nested selector as though it is wrapped

The reason I made the conclusion, "oh, the parent should also be wrapped in `:is()` is because one of the examples suggests this:

```css
/* multiple selectors in the list are all
   relative to the parent */
.foo, .bar {
  color: blue;
  + .baz, &.qux { color: red; }
}
/* equivalent to
  .foo, .bar { color: blue; }
  :is(.foo, .bar) + .baz,
  :is(.foo, .bar).qux { color: red; }
*/

```

I'll weed out the parts that aren't related, and it looks like this:

```css
.foo, .bar {
   + .baz {
    color: red;
  }
}

/* equivalent to
  :is(.foo, .bar) + .baz { color: red; }
*/


```

[I ran some tests on specificity](https://codepen.io/paceaux/pen/MWMWzYL), and it appears that any time the parent selectors are a list, they get wrapped in `:is()`. 

Chrome's dev tools reports specificity and I experimented with my final ruleset and looked at the specificity. 

```css

.oof {
  + .baz { /*specificity 0,2,0*/
   color: orange
  }
}
.oof,
div.oof {
 + .baz { /* specificity 0,2,1 */
  color: orange;
 }
}
```

Is it more accurate to say, "the `&` should be thought of as similar to :is(<parent>), and any instance where the parent is a list should also be thought of as `:is(<parent>,<parent>`? 

_If_ that's the case, do you think it might be easier to simplify that "metaphor" as, "in cases of nesting, always think of the nested parent as wrapped in `:is()`. 

Your explanations have been great and I've found them very insightful; I really appreciate you correcting my assertions. 

Do you think that Section 3.2's examples could be rewritten and organized so as to only make one clear assertion at a time? The examples written in the spec are very long and often make several assertions in a single example. Complex (using `&` or not with multiple lines) come first, and simple examples (not using `&`, only being type selectors) are in the middle, while examples for nesting at-rules  are at the end. 

[Sass' own documentation for nesting](https://sass-lang.com/documentation/style-rules/) does a great job of providing increasingly-complex examples. Do you think the CSS spec could possibly consider even using Sass' exact examples? 

I know that the goal here is to not conflate or confuse CSS Nesting or Sass Nesting because the mechanisms are different. But given that Sass got there first (¿probably?), leaning on how Sass has documented behaviors like `&` with first simple examples, and then gradually increasing complexity, could help folks more clearly understand the differences. 

I'd love to see section 3.2 arranged so that the first examples had nothing to do with `&` at all, then went to lists in the parent, lists in the child, and then the special behavior of & all alone, then &&, and then the output preceding and following selectors. That would make it so much easier to track when `:is()` is relevant and when expectations should change.
