### ISSUE TITLE
[css-color-4]: Relative Colors doesn’t work with `calc(l + 10%)`

### ISSUE THREAD

**Issue by ai** [w3c/csswg-drafts#10571]
I found that this CSS doesn’t work in all browsers:

```css
.broken {
   --base: oklch(70% 0.1 30);
  background: oklch(from var(--base) calc(l - 10%) c h);
}
```

The only way to change lightness is to avoid `%` by using `calc(l - 0.1)`.

It looks confusing to me. But I don’t know what part of the spec prohibbits it.
