### ISSUE TITLE
[css-color-4]: light-dark() doesn’t work with Relative Colors 

### ISSUE THREAD

**Issue by ai** [w3c/csswg-drafts#10572]
There is some compatibility issue between Relative Colors and `light-dark()` in all browsers:

```css
.broken {
  --dynamic-bg: light-dark(oklch(70% 0 0), oklch(30% 0 0));
  background: oklch(from var(--dynamic-bg) l 0.05 160); /* browsers ignore it */
}
```

Maybe Relative Colors spec was created without thinking of `light-dark()`? But I think it really limits colors DX.

Demo: https://codepen.io/iskin/pen/yLWdxrR
