### ISSUE TITLE
[css-values-5] Boolean Values in CSS Custom Properties

### ISSUE THREAD

**Issue by brandonmcconnell** [w3c/csswg-drafts#10593]
## Abstract

This proposal aims to introduce native support for boolean values in CSS custom properties by allowing a new `<boolean>` type in the `@property` rule. This enhancement aligns with existing boolean handling mechanisms in the CSS engine and extends them to user-defined custom properties. It enables developers to leverage true boolean logic within CSS for more readable and maintainable styles.

## Motivation

Currently, CSS custom properties support a range of data types including numbers, lengths, colors, and strings, but they lack native support for boolean values. One common technique to work around this is to emulate boolean values using integers (`0` and `1`) or toggles using empty values ([`The -​-var: ; hack...`](https://lea.verou.me/blog/2020/10/the-var-space-hack-to-toggle-multiple-values-with-one-custom-property/)), which can be both error-prone and less intuitive.

Introducing a reusable `<boolean>` type will streamline conditional styling and improve readability and type safety.

### Declaring a Boolean Custom Property

```css
@property --selected {
  syntax: "<boolean>";
  initial-value: false;
  inherits: true;
}
```

Using `@property` is optional here, but it does yield some benefits in terms of type safety.

### Using Boolean Custom Properties

```css
label {
  --selected: false;
  &:has(:checked) { --selected: true; }
  grid-template-columns: auto if(var(--selected) ? 20px : 0);
  svg { opacity: if(var(--selected) ? 1 : 0); }
}
```

In this example, the custom property `--selected` is declared as a boolean type, simplifying its use in conditional logic.

Without this, a developer might resort to using mathematical expressions that—while equally dry and even shorter-form in this case—are not as intuitive and may take time to recognize that the math is essentially acting as a boolean switch.

Here is how that same example might look using a "math-based switch":

```css
label {
  --selected: 0;
  &:has(:checked) { --selected: 1; }
  grid-template-columns: auto calc(var(--selected) * 20px);
  svg { opacity: var(--selected); }
}
```

This is a simple example, but this mathematical approach can easily become more complex depending on the use case.

### Type Safety

By introducing a native boolean type, the CSS engine can ensure that only valid boolean values are assigned to boolean custom properties, thus reducing errors.

### Reusability and Maintainability

Boolean custom properties can be reused across multiple styles, reducing redundancy and making stylesheets more maintainable.

### JavaScript Interoperability

Boolean custom properties can be easily manipulated through JavaScript, allowing for dynamic and interactive style changes. The type safety can be enforced using the CSS `@property` rule.

Using JavaScript, developers can interact with and manipulate boolean custom properties while benefiting from type safety.

### Example with JavaScript

```html
<label id="checkbox-label">
  <input type="checkbox" id="checkbox">
  Check me
  <svg>Icon</svg>
</label>

<script>
  const checkbox = document.getElementById('checkbox');
  const label = document.getElementById('checkbox-label');

  checkbox.addEventListener('change', (event) => {
    label.style.setProperty('--selected', checkbox.checked);
  });

  // Observing boolean custom property changes
  const observer = new MutationObserver(() => {
    const selected = label.style.getPropertyValue('--selected') === 'true';
    console.log('Selected:', selected);
  });

  observer.observe(label, { attributes: true, attributeFilter: ['style'] });
</script>
```

In this example, the `--selected` custom property is directly manipulated using JavaScript, and changes are observed to reflect the dynamic state of the checkbox.

**Comment by Crissov** [comment]
While CSS has properties with just two valid values available, it does not have boolean values, i.e. keywords like `true` and `false`. This verbosity makes it easier to extend the property later on. Queries have boolean results, though. Pseudo functions need to return valid values, so cannot be boolean in the sense requested here. 

I understand that some authors use Custom Properties as if there were boolean values, probably because they are used to them from Javascript or other programming languages. I do not think this should be anything more than condoned by the specification. 

The furthest it could go, in my opinion, would be to add two descriptors to `@property` that would each take one value value that will be considered truish and falsish, respectively.

**Comment by romainmenke** [comment]
See : https://drafts.csswg.org/mediaqueries-5/#custom-mq

> If a `<media-query-list>` is given, the custom media query evaluates to true if the `<media-query-list>` it represents evaluates to true, and false otherwise. If true or false is given, the custom media query evaluates to true or false, respectively.

I think this request largely mirrors what is already specified for custom media queries.
(Although no implementer has taken up this part of the spec.)

**Comment by brandonmcconnell** [comment]
This is a model example from that draft `css-values-5` spec (re the [`if()` function](https://drafts.csswg.org/css-values-5/#if-notation)):
```css
.foo {
  --color: if(media(width >= 600px): blue; else: var(--foo));
}
```

It would be helpful to be able to re-use such a boolean condition, like this:
```css
@property --condition {
  syntax: "<boolean>";
  inherits: true;
  initial-value: false;
}

.foo {
  --condition: media(width >= 600px);
  color: if(var(--condition): blue; else: red);
  width: if(var(--condition): 20px; else: 10px);
}
```

**Comment by AtkinsSJ** [comment]
As an implementer I'd be in favour of a `<boolean>` type generally. I think that's already what the `@property` `inherits` descriptor's value wants to be.

**Comment by tabatkins** [comment]
We could add `true` and `false` specifically to the condition grammar as always-true and always-false values, sure. We already have `else` as a whole condition-clause that's always true (but it can't be combined with other things).

**Comment by brandonmcconnell** [comment]
@AtkinsSJ Good catch on the `@property`'s `inherits` descriptor! I hadn't considered that, even as I typed it.

**Comment by brandonmcconnell** [comment]
@tabatkins The goal here is to make conditional expressions like those arguments used in `if()` able to be stored in properly typed variables so they can be re-used there or other similar contexts.

For example, another function that accepts virtually any value(s) is `random()`, which could work in tandem with this proposed boolean type to produce a random boolean conditions:
```css
@property --random-condition {
  syntax: "<boolean>";
  inherits: true;
  initial-value: random(per-element, true, false);
}

.whack-a-mole {
  display: if(var(--random-condition): block; else: none);
}
```
