### ISSUE TITLE
[css-lists] HTML stylesheet should reset `list-item` counter for `<menu>`

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#10664]
https://html.spec.whatwg.org/multipage/rendering.html#lists

```css
ol, ul, menu { counter-reset: list-item; }
```

https://drafts.csswg.org/css-lists/#ua-stylesheet
```css
/* Set up ol and ul so that they scope the list-item counter */
ol, ul {
  counter-reset: list-item;
}
```

It's missing `<menu>`.
