### ISSUE TITLE
[css-counter-styles-3] Zhuyin (Mandarin Bopomofo) counter style

### ISSUE THREAD

**Issue by NightFurySL2001** [w3c/csswg-drafts#10685]
Propose to add Mandarin Bopomofo as a counter style in CSS. Although not as commonly used as Han numerals, it is sometimes used in sub-lists or headers, especially in dictionaries. The term "zhuyin" is used instead of "bopomofo" as the ordering is following modern Taiwanese Mandarin order (reference https://language.moe.gov.tw/001/Upload/files/site_content/M0001/juyin/html_ch/index.html) and not other bopomofo system. Other bopomofo ordering may be introduced at a later time.

Proposed ordering:
```css
@counter-style zhuyin {
  system: alphabetic;
  symbols: "\3105" "\3106" "\3107" "\3108" "\3109" "\310A" "\310B" "\310C" "\310D" "\310E" "\310F" "\3110" "\3111" "\3112" "\3113" "\3114" "\3115" "\3116" "\3117" "\3118" "\3119" "\311A" "\311B" "\311C" "\311D" "\311E" "\311F" "\3120" "\3121" "\3122" "\3123" "\3124" "\3125" "\3126" "\3127" "\3128" "\3129";
  /* ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ */
  suffix: "、";
}
```

Example:
![image](https://github.com/user-attachments/assets/69f6cf85-fbea-486c-b0d6-eea47de2fef2)
![image](https://github.com/user-attachments/assets/3adbca96-3195-444c-a546-9d5fed9e881c)
![image](https://github.com/user-attachments/assets/372d6089-dd48-4bfb-88c9-9e659a91c606)
