### ISSUE TITLE
[css-variables][css-pseudo] Question about setting variable values in pseudo classes

### ISSUE THREAD

**Issue by xgebi** [w3c/csswg-drafts#10778]
My colleague and I are trying to figure out if this is a browser bug (in all browsers) or an exception in a standard.

Let's say we have HTML

```HTML
<a href="https://codepen.io/">Codepen</a>
```

and CSS

```CSS
:root {
  --color: red;
}

a {
  color: var(--color);
}

a:hover {
  --color: green;
}

a:visited {
  --color: purple;
}
```

As the link is visited and last setting of `--color` is `purple`, the color of the text in the link should be purple. Except it's not, it remains `red`.

If this behavior with `:visited` was consistent with all pseudo-classes, I wouldn't question it as in the [spec](https://drafts.csswg.org/css-variables-2/#defining-variables) is written that variables apply to all elements and all pseudo-elements. On hover the text turns `green` with the code above in Firefox, Chrome and Safari.

[Codepen example](https://codepen.io/xgebi/pen/JjQZbJm)

My question is, is ignoring the setting of `--color` in `a:visited` a standards bug or should we make reports to browsers' issue trackers?

**Comment by svgeesus** [comment]
From [8.2. The Link History Pseudo-classes: :link and :visited](https://drafts.csswg.org/selectors-4/#visited-pseudo)

> Since it is possible for style sheet authors to abuse the :link and :visited pseudo-classes to determine which sites a user has visited without the user’s consent, UAs may treat all links as unvisited links or implement other measures to preserve the user’s privacy while rendering visited and unvisited links differently.

Using custom properties to probe `visited` status is an example of the behavior described, and thus browsers ignoring setting the property in a `:visited` is a measure to prevent that, and spec compliant. This is a privacy feature, not a bug.

**Comment by xgebi** [comment]
@svgeesus thank you

**Comment by tabatkins** [comment]
Yup, to get around this restriction you need to use separate "visited" variables, and then apply them in the pseudoclass, like:

```css
:root { 
  --link-color: red;
  --visited-color: purple;
}
a {
 color: var(--link-color);
}
a:hover {
  --link-color: green; /* or set this in a third variable at root for consistency, whatever */
}
a:visited {
  color: var(--visited-color);
}
```
