### ISSUE TITLE
[css-shadow-parts][css-nesting] is & allowed after ::part()

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#10788]
I don't think it's clear whether [the `&` selector](https://drafts.csswg.org/css-nesting-1/#nest-selector) is allowed after [the `::part()` pseudo-element](https://drafts.csswg.org/css-shadow-parts-1/#part).  At least, I read what I think are the relevant specs and I couldn't find any wording that gives me a clear answer.

For example, is the following CSS:

```css
:hover {
  ::part(mypart)& {
    text-decoration: underline;
  }
}
```

equivalent to:

```css
::part(mypart):hover {
  text-decoration: underline;
}
```

or is it invalid?

**Comment by dbaron** [comment]
Based on this test:

```html
<!DOCTYPE HTML>
<style>
  #host {
    padding: 3px;
    width: fit-content;
  }
  #host::part(p):hover {
    color: green;
  }
  :hover {
    #host& {
      background: aqua;
    }
    #host::part(p)& {
      background: lime;
    }
  }
</style>
<div id="host">
</div>
<script>
  let shadow = document.getElementById("host").attachShadow({mode: "open"});
  shadow.innerHTML = `<div part="p">this is the part, hover me</div>`;
</script>
```

this currently doesn't work in any of Chromium, Gecko, or WebKit.

**Comment by cdoublev** [comment]
According to this [comment](https://github.com/w3c/csswg-drafts/issues/9940#issuecomment-1941943995), `&` is a *a new **"simple"** selector* (`<simple-selector>`). So it can only replace `<type-selector> | <subclass-selector>`, not `<pseudo-class-selector>` in `<pseudo-compound-selector>`.

**Comment by tabatkins** [comment]
Yeah, per grammar that's not currently allowed. I don't see a big reason to disallow it, tho, since it's morally equivalent to an `:is()` which *is* allowed.

**Comment by tabatkins** [comment]
I'd like to revisit this. I'm fine if we *do* end up keeping the resolution, but from the minutes it doesn't look like it was argued very well. The only real comment aside from dbaron's introduction was referring to a comment about the current state of the grammar, and didn't reference *my* response to that comment.

My point is that `#host::part(p):is(:hover, :active)` is allowed and perfectly fine, so `:hover, :active { #host::part(p)& {...}}` is also meaningful and potentially useful. Similarly, `#host::part(p):is(div)` is *allowed* (but doesn't match anything; the contextual restriction against type selectors after a pseudo-element causes the `:is()` to consider its argument invalid), so `div { #host::part(p)& {...}}` is at least well-defined, if not *useful*.

**Comment by jpzwarte** [comment]
I just ran into this. 

This works: 
```css
    sl-month-view::part(finish) {
        background: var(--sl-color-success-plain);
        border-radius: 50%;
        color: var(--sl-color-text-inverted);
      }

      sl-month-view::part(finish):hover {
        background: var(--sl-color-success-bold);
      }
```

This doesn't: 

```css
    sl-month-view::part(finish) {
        background: var(--sl-color-success-plain);
        border-radius: 50%;
        color: var(--sl-color-text-inverted);

        &:hover {
          background: var(--sl-color-success-bold);
        }
      }
```

This is totally not obvious to me (let alone a web dev who does not read csswg issues on github).
