### ISSUE TITLE
[css-view-transitions-2] Use `@starting-style` to customize initial/final states of content pseudos

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#10789]
Currently, the default behavior for the content pseudo-elements (`::view-transition-old` and `::view-transition-new`) is to animate to/from `opacity: 0`. This is usually sufficient, and customizable by setting the pseudo-element style directly.
However, this means, for example, that custom cross-document exit transitions have to be defined in the new document.
Proposing that instead, we'd use the `@starting-style` for the old/new pseudo-element keyframes.

So for example given this CSS & script:
```css
.current { 
  @starting-style {
    scale: 0;
    opacity: 1;
  }
  view-transition-name: item;
}
```
```js
item1.classList.add("current");
document.startViewTransition(() => {
  item21classList.add("current");
  item2.classList.add("current");
});
```

Instead of the elements cross-fading, the old one would animate its scale to 0 and the new element would animate its scale from 0.

**Comment by nt1m** [comment]
Not sure I understand this, do you have some sample equivalent code of what this is trying to achieve?

**Comment by noamr** [comment]
> Not sure I understand this, do you have some sample equivalent code of what this is trying to achieve?

Of course!
I put a slightly better example in a [codepen](https://codepen.io/noamr/pen/XWLBXyN).
Let's say I have a counter, that uses view-transitions to animate when changing the number:
```html
<output style="view-transition-name: counter">0</output>
```

By default, changing the number would crossfade using opacity. If I want, instead, to have the old number slide out to the left and the new number to to slide in, I have to do this:
```css
@keyframes slide-out { 
  to { translate: -100%; } 
}
@keyframes slide-in { 
  from { translate: -100%; } 
}
:root::view-transition-old(counter) { 
  animation-name: slide-out; 
}
:root::view-transition-new(counter) { 
  animation-name: slide-in; 
}
```

I want to be able to do this using `@starting-style` instead:
```css
output {
  @starting-style {
     translate: -100%;
  }
}
```
