### ISSUE TITLE
[css-overflow] What counts as "immediately preceding" for `block-ellipsis`?

### ISSUE THREAD

**Issue by andreubotella** [w3c/csswg-drafts#10868]
`block-ellipsis`, which is one of the properties that `line-clamp` is a shorthand for, creates an ellipsis on the last line before clamp, if that line box "immediately precedes" the region break. Since `max-lines` creates a region break after a line box, when that property is used, the immediately preceding line box is clear. But when clamping by height, the interpretation of that isn't always clear.

My expectation is that a line box would get ellipsized if there is no content between it and the clamp point in the box tree, except that ancestor boxes of the line box can end in between:

```css
.clamp {
  line-clamp: auto;
  max-height: calc(5lh + 2 * 5px);  /* account for .inner's border */
  background-color: yellow;
  border: 5px solid black;
  padding: 5px;
}
.inner {
  background-color: orange;
  border: 5px solid brown;
}
```
```html
<div class="clamp">
  Line 1 <br>
  Line 2 <br>
  Line 3
  <div class="inner">
    Line 4 <br>
    Line 5
  </div>
  Line 6
</div>
```

![image](https://github.com/user-attachments/assets/46efe1dd-9b8e-4915-82a3-4111bca8a866)

But there wouldn't be an ellipsis if an entire box sits in between:

```css
.clamp {
  line-clamp: auto;
  max-height: 4lh;
  /* ... */
}
.h {
  height: 1lh;
  background-color: orange;
}
```
```html
<div class="clamp">
  Line 1 <br>
  Line 2 <br>
  Line 3 <br>
  <div class="h"></div>
  Line 4
</div>
```

![image](https://github.com/user-attachments/assets/0bc379d1-0d7d-4b1d-b732-63fd8190ec45)

My expectation is also that a line box would be ellipsized even it is contained inside a box with a non-overflowing `height` property. (This does not currently work in my in-progress implementation of `continue: collapse` in Chromium, though, and it would need some heavy refactoring before it would be possible.)

```css
.clamp {
  line-clamp: auto;
  max-height: calc(6lh + 2 * 5px);
  /* ... */
}
.inner {
  height: 3lh;
  /* ... */
}
```

![image](https://github.com/user-attachments/assets/10994917-d020-4d44-aa52-86feec3fe80c)

One interesting question is what to do when there are out-of-flow block-level elements, between the last line box and the clamp point. By the above definition, the line box shouldn't be ellipsized in that case. However, especially for an abspos box which is positioned elsewhere, it's possible that this would not be intuitive to authors.

```css
.clamp {
  position: relative;
  line-clamp: auto;
  max-height: 4lh;
  /* ... */
}
.abspos {
  position: absolute;
  top: 0;
  right: 0;
  width: 50px;
  height: 50px;
  background-color: orange;
}
```
```html
<div class="clamp">
  Line 1 <br>
  Line 2 <br>
  Line 3 <br>
  Line 4
  <div class="abspos"></div>
  Line 5
</div>
```

![image](https://github.com/user-attachments/assets/804ab213-475a-467f-8965-8214853c05bc)

cc @frivoal @bfgeek @emilio

**Comment by andreubotella** [comment]
cc @frivoal @fantasai @emilio @bfgeek 

Talking with Florian earlier, it looks like the "immediately preceding" spec text might have been written in the context of clamping by a number of lines and the possibility of clamping by a height was not considered at that time. Given that, should the last line box before the clamp point always be ellipsized?

**Comment by frivoal** [comment]
I've been going back and forth about this, and I think we should mostly keep the existing definition, but make an exception allowing for the anchor of out of flow elements (floats or abspos) between the last line and the clamp point.

I think the alternatives would be:
* have the ellipsis in the last line anyway, regardless of subsequent content

    If there is content after the last line box and before the clamp point, it can get quite strange to put the ellipsis on the last line anyway: Imagine a (block) image, a table, a flexbox… having the ellipsis, then some more content, then the break, is confusing.

    More over, as currently defined, this is an inheritable property, which affects all block containers. If we don't limit ourselves to the line immediately before the clamp point, then the last line of each clamped block would get an ellipsis, which would be very wrong in case of nested blocks.
    ```
    <style>
    .clamp { line-clamp: 3; }
    </sytle>
    <div class=clamp>
      Line 1
      <div>Line 2
        <div>Line 3
          <div>Line 4</div>
        </div>
      </div>
    </div>
    ```
    would result in
    ```
    Line 1…
    Line 2…
    Line 3…
    ```
    as each line, in its own container, is the last line before the clamp point (though not immediately).
* drop content from the end until the last thing is a line.
    Seems wasteful. If there's content and room to display the content, why not show it?
* if the last thing isn't a line, and there's room for a line, add one, and put the ellipsis there.
    I think this is going to run into a ton of complexity and corner cases, without even being clear that it's always desirable.

We could also change the property to be non inherited, and to apply to clamp containers / fragmentation containers only, instead of of block containers. It's not really clear that would help with this issue though. The behavior in case of nested formatting context would have to be described differently, and would likely behave differently at least in some cases, but the fundamental problem asked in this issue would remain.

So, all in all, I suspect we want to keep the current definition, but clarify "immediately preceding" to mean something like there being no content between that last line and the clamp point, other than out of flow content.

**Comment by frivoal** [comment]
Then again, in #7708, @tabatkins was arguing that height based clamping should still be clamping after a specific number of lines and dropping everything after that, even if there's room for more (non-line) content. It certainly is simpler (at least in the `continue: collapse` variant), but it seems less useful.

I wouldn't really mind dropping any out-of-flow content placed immediately after the last line due to that, but dropping block-level elements (that don't contain lines) even when they do fit seems unfortunate.

**Comment by frivoal** [comment]
That said, as long as we do that only for `continue: collapse`, and don't introduce this for `continue: discard`, I'm ok.

**Comment by andreubotella** [comment]
What should happen with `line-clamp: auto; height: 0`?

**Comment by frivoal** [comment]
> What should happen with `line-clamp: auto; height: 0`?

clamp point happens before the first line, so all content is dropped, and there's no line left to put the ellipsis in?

**Comment by andreubotella** [comment]
We had resolved that if the last thing that fits in the height is not a line, the ellipsis shouldn't be drawn on that line. But I don't think block-level abspos should count as "a thing" there.

Consider the following example:

```css
.clamp-by-lines {
  line-clamp: 2;
}
.clamp-by-height {
  line-clamp: auto;
  max-height: 2lh;
}
p { margin: 0 }
.abspos {
  position: absolute;
  top: 0;
  width: 50px;
  height: 50px;
  background-color: purple;
}
```
```html
<div class="clamp-by-lines">
  <p>Line 1</p>
  <p>Line 2</p>
  <div class="abspos"></div>
  <p>Line 3</p>
</div>
```

With `.clamp-by-lines`, the clamp point happens right after line 2, so that line gets the ellipsis; and the `.abspos` is after the clamp point but it still shows up because of #11379. However, if we instead set the `.clamp-by-height` class, the clamp point would be after the `.abspos` (since it takes up zero height in-flow), and therefore that would be "the last thing before the clamp point", meaning that line 2 would *not* have the ellipsis.

I think this behavior is unintuitive, and therefore we should either clamp after the last thing other than a block-level abspos that fits in the height, or to ignore immediately following block-level abspos when determining whether a line has the ellipsis (which should have the exact same behavior). The same would not apply to, say, a `position: relative` div containing only an abspos.
