### ISSUE TITLE
[css-ui] Colors to use for appearance:base `<select>`

### ISSUE THREAD

**Issue by josepharhar** [w3c/csswg-drafts#10909]
In [this issue](https://github.com/w3c/csswg-drafts/issues/10857), I proposed using system colors like Field and FieldText in the UA stylesheet. However, it was brought up that "There are alternatives that work in dark mode that don't involve light-dark() / system colors, while allowing easy overrides."

What foreground/background colors should we put in the UA stylesheet?

**Comment by LeaVerou** [comment]
`field` and `fieldtext` _should_ be responsive to dark/light mode by default, just like other system colors (e.g. `canvas` and `canvastext`).

And given the proposal to override system colors with page-specific design tokens (see #9660), it seems like system colors are absolutely the right choice here. Curious what alternatives @nt1m had in mind, because I can't think of any that don't involve either system colors or `light-dark()`.

**Comment by nt1m** [comment]
I presented this at TPAC:
- transparent background
- inherit color/font/etc.
- `border-color: currentColor`

**Comment by LeaVerou** [comment]
@nt1m what color would the dropdown have? Transparent?

**Comment by LeaVerou** [comment]
I’m confused; isn’t this what @josepharhar is proposing? 🤔

**Comment by nt1m** [comment]
The in-page control would use https://github.com/w3c/csswg-drafts/issues/10909#issuecomment-2384321591 , the picker would use system colors.

**Comment by LeaVerou** [comment]
Oh agreed on that (except `border-color: currentcolor` would be too harsh, so maybe something like `lab(currentcolor l a b / 50%)`)

**Comment by josepharhar** [comment]
Proposed resolution: use tim's proposed colors for base appearance select, with a system color for the popover's background color:
```css
select {
  border: 1px solid currentColor;
  background-color: color-mix(in lab, currentColor 10%, transparent);
  color: inherit;
}
select:enabled:hover {
  background-color: color-mix(in lab, currentColor 20%, transparent);
}
select:enabled:active  {
  background-color: color-mix(in lab, currentColor 30%, transparent);
}
::picker(select) {
  border: 1px solid rgba(0, 0, 0, 0.15);
  background-color: Field;
}
```

**Comment by josepharhar** [comment]
@nt1m what do you think we should do? Use transparency and currentColor for the in-page part and system colors for the picker? Or system colors for everything? Or something else?

**Comment by nt1m** [comment]
On a personal level, I still favor the first option. It's unopinionated and matches other HTML elements:

* `<div>`/other in-page elements use transparent backgrounds/currentColor (in-page form controls)
* `<dialog>`/popover use system colors (`::picker` falls into this category)

**Comment by josepharhar** [comment]
Thanks! How do these colors look? I made ::picker match the colors used for dialog and popover.
```css
/* Rules on select won't apply when select has a child button
 * because button already has borders, colors, and active/hover. */
select {
  border: 1px solid currentColor;
  background-color: color-mix(in lab, currentColor 10%, transparent);
  color: inherit;
}
select:enabled:hover {
  background-color: color-mix(in lab, currentColor 20%, transparent);
}
select:enabled:active  {
  background-color: color-mix(in lab, currentColor 30%, transparent);
}
::picker(select) {
  color: CanvasText;
  background-color: Canvas;
  border: solid;
}
```
Should we also have `:disabled` colors? Perhaps by setting `color` or `opacity`?

**Comment by emilio** [comment]
I'd prefer something like:

```css
select {
  border: 1px solid ButtonBorder;
  background-color: Button;
  color: ButtonText;

  &:enabled:hover {
    background-color: ButtonHover; /* new */
    color: ButtonHoverText; /* new */
  }
  &:enabled:active {
    background-color: ButtonActive; /* new */
    color: ButtonActiveText; /* new */
  }
}
```

Or so, where we define those colors to be something sensible.

**Comment by josepharhar** [comment]
I talked to @nt1m about colors for disabled and here is an option:
```css
select:disabled {
  color: color-mix(in srgb, currentColor 50%, transparent);
}
```

**Comment by josepharhar** [comment]
We also need colors for options. Similar to buttons, we could have these rules:
```css
select option:enabled:hover {
  background-color: color-mix(in lab, currentColor 20%, transparent);
}
select option:enabled:active {
  background-color: color-mix(in lab, currentColor 30%, transparent);
}
select option:disabled {
  color: color-mix(in lab, currentColor 50%, transparent);
}
```
