### ISSUE TITLE
[mediaqueries] `streaming` media feature for implementing streamer mode

### ISSUE THREAD

**Issue by nickserv** [w3c/csswg-drafts#10973]
I'm proposing `streaming` as a discrete [media feature](https://www.w3.org/TR/mediaqueries/#mq-features) with `active` and `none`, used when streaming software is running or not running (respectively). This could be used to implement a streamer mode feature to Discord's, which automatically hides sensitive information when streaming software is running.

**Comment by nickserv** [comment]
Example using `streaming` to toggle displaying the user's phone number on stream:

```css
@media (streaming: active) {
  .phone {
    display: none;
  }
}

@media (streaming: none) {
  .phone {
    display: block;
  }
}
```

```js
document.querySelector(".phone").style.display = window.matchMedia(
  "(streaming: active)",
).matches
  ? "none"
  : "block";
```
