### ISSUE TITLE
[css-cascade] A way to escape the current cascade layer and render styles in the parent layer (`@layer ..`)

### ISSUE THREAD

**Issue by benface** [w3c/csswg-drafts#11010]
My use case is a framework that lets you generate styles in a particular layer. For instance, Tailwind CSS v4 generates all the utility classes in a `utilities` layer (which I can customize). If I want some utilities to have lower precedence than others, I can wrap them in another layer since unlayered styles beat layered styles. But if I want some utilities to have _higher_ precedence than others, I am forced to resort to specificity hacks (e.g. `:is(#a, .my-actual-selector)`). It would be nice if I could wrap them in `@layer ..overrides` and they would win because I would define `overrides` after `utilities`.

**Comment by benface** [comment]
@flashymittens – How so? In the example I gave, layers are still useful as a way to define precedence.

```css
/* assume this stylesheet is imported in the `utilities` layer */

.bg-red {
  background-color: red;
}

@layer ../overrides {
  [forced-bg="blue"] {
    background-color: blue;
  }
}

```

**Comment by romainmenke** [comment]
I think the proper way would be for tailwind (as a style vendor) to organise its styles into a more specific cascade layer.

```css
@layer utilities.tailwind {
  color: green;
}
```

Then you can write your own utilities as:

```css
@layer utilities.my-styles {
  color: purple;
}
```

And organise your layers freely with:

```css
@layer utilities.my-styles, utilities.tailwind;
```

```css
@layer utilities.tailwind, utilities.my-styles;
```
