### ISSUE TITLE
[css-values] Proposal: `children-count()` function

### ISSUE THREAD

**Issue by kizu** [w3c/csswg-drafts#11068]
## Problem

In the https://github.com/w3c/csswg-drafts/issues/4559 it was resolved to add two new functions which are now in the [css-values-5 WD](https://www.w3.org/TR/css-values-5/): `sibling-count()` and `sibling-index()` as [tree-counting functions](https://www.w3.org/TR/css-values-5/#tree-counting) (I'm using that issue as a template for this one, thanks @argyleink!).

However, these functions only cover a subset of the needs authors have when it comes to knowing the number of items. Sometimes, you want to know that value not on the _item_, but on its _parent_ (and, sometimes, on another ascendant element — see my separate related proposal).

## Proposal

A new function: `children-count()`. Similar to `sibling-count()` and `sibling-index()`, it should report its values based on the element count, and not the node count.

It is a function that is _very_ similar to `sibling-count()`, but instead of counting _siblings_ counts _children_.

Similarly, could optionally accept a selector (see https://github.com/w3c/csswg-drafts/issues/9572) as a way to narrow down what is counted as a `child`.

Example usage:

> A square grid based on the children count

```CSS
.square-grid {
  display: grid;
  grid-template-columns: repeat(
    sqrt(children-count()),
    min-content
  );
}
```

### Do we still need `sibling-count()`?

Yes. While we could assign the `children-count()` to a registered custom property and inherit it on the children, this is rather cumbersome, and a native `sibling-count()` could be more performant.

### Other use cases

- I have the above in some other use cases in [my latest article](https://kizu.dev/tree-counting-and-random/).
- Any place that needs to change the parent's layout based on the children count: bento-layouts, layouts where children are absolutely positioned and we need to set the parent's dimensions, etc.
- I'll update this list with the links as I encounter them.

## See also

There is an additional proposal: `descendant-count()` that attempts to do a similar thing, but in a more flexible (and complicated for an implementation) way.

**Comment by Monknow** [comment]
I really like the possibility of doing both: counting the total number of items in the item and also in their parent. However, I feel like that's still limiting, why can't we count the number of items from any element and also decide which items get counted? 

Take the following HTML as an example:

```html
<div class="total"></div>

<ul>
	<li class="dairy">Milk</li>
	<li>Eggs</li>
	<li class="dairy">Cheese</li>
	<li class="dairy">Yogurt</li>
	<li>Bacon</li>
	<li>Bread</li>
</ul>
```

If I wanted to count all `li` elements, `sibling-count()` would force me to count the items from the item, `children-count()` from the parent, and there isn't a way to get the count from the `.total` element or any element outside of the parent. Alternatively, if I just want to count the elements of class `.dairy`, I couldn't. 

I feel like adding more functions for each case is counterintuitive, so why there shouldn't be a general `count()` function that takes as an argument the selector and returns as an integer the total items?

```css
count(ul > li) /* returns 6 */
count(ul > .dairy) /* returns 3 */
```

Based on the first examples by Adam Argyle here #4559, it could be changed from:

```css
ul > li {
  background-color: hsl(sibling-count() 50% 50%);
}
```

to:

```css
/* Changes the li color depending on how many .dairy elements are */
li {
  background-color: hsl(count(ul > .dairy) 50% 50%);
}

/* Changes the .total element color depending on how many li elements are */
.total {
  background-color: hsl(count(ul > li) 50% 50%);
}

/* We could have a keyword to go by the selector from where it's being called */
ul > li {
  background-color: hsl(count(selector) 50% 50%);
}
```

Applying a similar approach to the `sibling-index()` would have a lot more nuance, since it depends on the selector from where it's been called, but I think it should still be possible to get the index in a sibling group of the same class. Similar to what `:nth-of-type` does
