### ISSUE TITLE
[css-values-5] Introduce nth-item()

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#11103]
Back in <https://github.com/w3c/csswg-drafts/issues/5009#issuecomment-626072319> I summarized the various "conditional" things we might want to add. We've now added [the `if()` function](https://drafts.csswg.org/css-values-5/#if-notation), and the big one left from that summary list is `nth-item()` (called `nth-value()` in that comment, but we should be consistent with `random-item()`'s naming).

This is a fairly trivial addition functionality-wise, and it has two good arguments for including it:

1. As argued in the thread, it gives a complementary syntax for conditionals, letting you centralize the actual condition to one spot on your page and just use it to set an integer that'll select things from the list. That way, you don't have to repeat your conditions all over your page if you have a lot of things that'll use the same set of tests.
2. If you can do `random-item()` to select a *random* item from a list, surely you should be able to do `nth-item()` to select a *non-random* item from a list, that's just something authors will expect. ^_^

Syntax would just be:

```
random-item( <integer> , [ <declaration-value>? ]# )
```

And it'll select the nth argument according to the first argument, yielding the guaranteed-invalid value if the index goes past the end of the list.

Maybe the first arg can have an optional `clamp` keyword, which would make the index clamp to the largest valid index instead of being invalid, so authors can use the final argument as the "default" value.

**Comment by Crissov** [comment]
Would negative indices count from the end of the list? What would index `0` return then?

I’ve expressed a preference for a unified _select by index_ function before. I’m still in favor of it, but overall it’s just syntax details. 

~~~~ ebnf
select( random | <integer> , [ <declaration-value>? ]# )
~~~~

If this also supported _select by key_, we’d basically have a switch construct without fallthrough behavior. 

~~~~ ebnf
select( random | <integer> | <string> , [ [<string> :]? <declaration-value>? ]# )
~~~~

**Comment by tabatkins** [comment]
Since other indexed things in CSS (grid lines, notably) allow counting from the end with negative values, presumably we'd do the same. 0 would just be invalid (or clamped to 1, if we add the clamp option).

Selecting by random requires the fuller handling of random caching that `random-item()` provides. In theory it's possible to merge in the grammar, but in practice it would be more trouble than it's worth.

Selecting by key should be handleable by `if()`, with a touch more verbosity (you'd repeat the var() in each branch). If that ends up being too verbose because you're doing it a lot, `nth-item()` is already the intended way to fix that (use an `if()` to select an integer in one place, then use the integer to index a bunch of lists).

**Comment by tabatkins** [comment]
@LeaVerou I don't think I agree, at least not without a *lot* more support for list handling. *None* of the things you described appear to be doable in CSS even with a list type; they all require looping, variable assignment, etc. We'd have to introduce more functions to represent these operations.

And if we did introduce these additional functions, they don't, as far as I can tell, require any special "list" type; they can all be handled just fine by the existing infrastructure of "lists" being a convention for comma-separated items. Custom functions can take lists as an argument without any additional input from us (the caller would just wrap the list in `{}`, and the function can either splat it into another function directly or wrap it in more `{}` to re-group it if needed). Built-in functions haven't yet needed to worry about expressing lists as anything other than an n-ary set of arguments, but if we ever do, the same `{}` syntax works.

**Comment by LeaVerou** [comment]
After thinking about it some more, I agree with @tabatkins that we don't need a `<list>` type, passing variables around of comma-separated values would work fine.

I wonder if we could feed two birds with one scone by giving it a more general name (e.g. `get()` or `item()`) and allowing an optional `<ident>` label for each item. If a label is provided, the item can be accessed via either its label, or its index.

Percentages would also be incredibly useful, to use scales of values without needing to know the number of items. The percentage would be rounded to the nearest index.

Examples:

```css
--color-accent: #edf2ff, #dbe4ff, #bac8ff, #91a7ff, #748ffc, #5c7cfa, #4c6ef5, #4263eb, #3b5bdb, #364fc7;

background: item(var(--color-accent), 1); /* #edf2ff */
background: item(var(--color-accent), 50%); /* #748ffc */
background: item(var(--color-accent), 100%); /* #364fc7 */
```

```css
--color-accent: {lightest: #edf2ff, light: #dbe4ff, #bac8ff, #91a7ff, medium: #748ffc, 60: #5c7cfa, 70: #4c6ef5, #4263eb, dark: #3b5bdb, darkest: #364fc7};
/* All of the above still work, plus: */
background: item(var(--color-accent), lightest); /* #edf2ff */
background: item(var(--color-accent), medium); /* #748ffc */
background: item(var(--color-accent), darkest); /* #364fc7 */
```

Essentially an alternative way of doing #9992 that seems _much_ easier to implement.

**Comment by Crissov** [comment]
In [#4484](https://github.com/w3c/csswg-drafts/issues/4484#issuecomment-2707876141), Tab suggested to use `if()` for labeled maps. Likewise, this kind of mixed-index array could be done with a custom function. 

~~~~ css
@function --color-accent(--key) returns <color> {
--values:  #edf2ff, #dbe4ff, #bac8ff, #91a7ff, #748ffc, #5c7cfa, #4c6ef5, #4263eb, #3b5bdb, #364fc7;
  return: if(
    style(--key: "lightest"): item(var(--values), 1);
    style(--key: "light"): item(var(--values), 2);
    style(--key: "medium"): item(var(--values), 5);
    style(--key: 60): item(var(--values), 6);
    style(--key: 70): item(var(--values), 7);
    style(--key: "dark"): item(var(--values), 9);
    style(--key: "darkest"): item(var(--values), 10);
    else: item(var(--values), var(--key));
  );
}

background: --color-accent(1); /* #edf2ff */
background: --color-accent(50%); /* #748ffc */
background: --color-accent(100%); /* #364fc7 */
background: --color-accent("lightest"); /* #edf2ff */
background: --color-accent("medium"); /* #748ffc */
background: --color-accent("darkest"); /* #364fc7 */
~~~~

Yeah, that might need sugar coating indeed.

**Comment by LeaVerou** [comment]
The main thing is that functions are not scoped, but things like that could be (eg a warning callout may have a different accent color than a regular callout). Also, you don’t want to repeat a ton of logic with every scale.

**Comment by tabatkins** [comment]
> and allowing an optional <ident> label for each item.

Since the values are arbitrary, this is a little hard - you have to be able to tell whether the item contains the label or not. We can maybe handle this with an ident+colon, since you can use a `{...}` wrapper if your value does start with an ident and colon. But I probably would prefer to just do that with a second function that forces all items to have a label. (It could still allow selecting via index, too.)

(We have a similar issue in the `*-interpolate()` functions, where we'd like to let people just specify bare values and auto-distribute them like gradient stops, but the grammar is too ambiguous. We're gonna have to keep the colons, with some indicator that the stop is auto-placed, like `auto: foo` or something.)

> Percentages would also be incredibly useful, to use scales of values without needing to know the number of items. The percentage would be rounded to the nearest index.

...actually you can already do this, per spec. `random-item(fixed .5, ...)`, given a value between 0 and 1, will select an item from the list with each taking an equal share of the number range, for any number of items.

(But I think it's reasonable for `nth-item()` to take a % and do this, yeah, distinct from its behavior with ints.)

**Comment by tabatkins** [comment]
> Yeah, that might need sugar coating indeed.

Lol, yeah, `if()` is powerful and can handle the labeled-item case no problem, but it's a little verbose. That does mean we can maybe just wait to introduce a labeled-item function, tho, and see what the usage ends up being like.

**Comment by LeaVerou** [comment]
Fair. After all, design systems could simply use variables to map keys to indices. E.g.:

```css
:root {
	--color-accent: #edf2ff, #dbe4ff, #bac8ff, #91a7ff, #748ffc, #5c7cfa, #4c6ef5, #4263eb, #3b5bdb, #364fc7;
	--lightest: 1;
	--medium: 5;
	--darkest: 10;
}

.foo {
	background: item(var(--color-accent), var(--lightest)); /* #edf2ff */
	background: item(var(--color-accent), var(--medium)); /* #748ffc */
	background: item(var(--color-accent), var(--darkest)); /* #364fc7 */
}
```

**Comment by Crissov** [comment]
They could of course, but letting unprotected friendly keys cascade independently from the pseudo lists they are supposed to apply to, is just asking for trouble. (There may be theoretically benefits in having that flexibility but I do not see any.)

**Comment by tabatkins** [comment]
At that point, where you're defining things globally, you might as well define a function anyway and hide away the implementation details.

```css
@function --color(--which type(<custom-ident> | <integer>)) returns <color> {
  result: if(style(--which: lightest): nth-item(1, ...var(--color-accent)),
             style(--which: medium): nth-item(5, ...var(--color-accent)),
             style(--which: darkest): nth-item(10, ...var(--color-accent)),
             else: nth-item(var(--which), ...var(--color-accent))
  );
}
:root {
  --color-accent: ...;
}
.foo { color: --color(medium); }
```
