### ISSUE TITLE
[css-conditional-5]Add `scroll-state(scroll-to)` container feature queries

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#11191]
The `overflowing feature` in the current specification is confusing, and @fantasai expressed similar concerns in #11182.

CSS authors often prefer to get a sense of where the container has scrolled to, and then adapt behavior and style.

## Common use cases

1. Display a `back to top` button after scrolling to the bottom of the page.
2. in a horizontally scrolling table or carousel, when scrolling to the left or right, play a “rubber band” animation to indicate that the user has scrolled to the last page.

Demo:

https://github.com/user-attachments/assets/9d4bb71f-cb9a-42f6-8aa8-02241ffb8319

----

In addition, the current `overflowing feature` performs this once every time the page is loaded, which is undesirable in the above use case. This behavior should be avoided if you agree to add `scroll-to`.

**Comment by yisibl** [comment]
Thinking further, is it possible to allow `<length-percentage>`?  To do this, introduce the same `scroll-x/y` as `background-position-x/y`.

```css
/* Scroll to 200px from the top to display the Back to Top button */
@container scroll-state(scroll-y: 200px) {
  .back-to-top {
    display: block;
  }
}
```

This has functional overlap with `Scroll-driven Animations`, but I think it would be easier to use and more ergonomic.

**Comment by fantasai** [comment]
@yisibl At that point, I think you'll want to know the position of an element, not just an arbitrary length.

**Comment by yisibl** [comment]
Let's leave proposal [#issuecomment-2473522823](https://github.com/w3c/csswg-drafts/issues/11191#issuecomment-2473522823) aside for now.

I've re-updated the proposal to suggest that `scroll-to: right` becomes a syntactic sugar for `not scroll-state(scrollable: right), which would be easier to understand.

That is, the following two ways of writing are equivalent, but `scroll-to` reads better.

```css
@container not scroll-state(scrollable: right) {
  table {
    animation: slide-right .5s linear;
  }
}
```

```css
@container scroll-state(scroll-to: right) {
  table {
    animation: slide-right .5s linear;
  }
}
```
