### ISSUE TITLE
[css-overflow-5] Disabled scroll-button state and styling

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#11216]
When the scroll container is at the limit of scrolling in the given direction, the `::scroll-button` pseudo-elements for those directions should be treated as disabled. They should also be stylable in some way allowing developers to indicate this state.

Presumably this would be styled by:
```css
::scroll-button(<direction>):disabled {
  opacity: 0.6;
}
```
