### ISSUE TITLE
[css-selectors] Proposal: `>>` combinator to ensure all elements between an ancestor and a descendant match a given selector

### ISSUE THREAD

**Issue by benface** [w3c/csswg-drafts#11309]
I've needed something like this a few times, and I just thought of a way to express it.

Here's an example:

```html
<div class="group">
  <div> <!-- any number of element layers here -->
    <div class="yellow-bg-on-nearest-group-hover">
      This element should have a yellow background when the root `.group` is hovered, because it's
      the nearest one to this element.
    </div>
  </div>
  <div class="group">
    <div> <!-- any number of element layers here -->
      <div class="yellow-bg-on-nearest-group-hover">
        This element should have a yellow background only when the nearest `.group` is hovered,
        but not when other elements in the root `.group` are.
      </div>
    </div>
  </div>
</div>
```

Here's how I'm picturing it:

```css
.group:hover > .yellow-bg-on-nearest-group-hover,
.group:hover > :not(.group) >> .yellow-bg-on-nearest-group-hover {
  background-color: yellow;
}
```

That would be equivalent to something like this, but with an infinite number of `> :not(.group) >`:

```css
.group:hover > .yellow-bg-on-nearest-group-hover,
.group:hover > :not(.group) > .yellow-bg-on-nearest-group-hover, 
.group:hover > :not(.group) > :not(.group) > .yellow-bg-on-nearest-group-hover
.group:hover > :not(.group) > :not(.group) > :not(.group) > .yellow-bg-on-nearest-group-hover /* etc. */ {
  background-color: yellow;
}
```

It would basically repeat the selector that precedes `>>` an infinite number of times.

**Comment by benface** [comment]
I just realized that a similar "continuous" combinator but for sibling elements (`++`), rather than ancestor/descendant, could make sense too, though I don't have a strong use case for it.

**Comment by ByteEater-pl** [comment]
You may consider:
```css
@scope (.group:hover) to (.group:not(:hover)) {
	 .yellow-bg-on-nearest-group-hover {
		background-color: yellow;
	}
}
```
