### ISSUE TITLE
[css-transforms] Feature request: Animate a part of an element

### ISSUE THREAD

**Issue by FirstByteFirst** [w3c/csswg-drafts#11564]
Currently an animation animates a complete element. I propose transform-offset: x y w h that could animate a portion of an element.

x: Describes the X-postion of the part of the element to animate. Computed value must be between 0 and element width
y: Describes the Y-postion of the part of the element to animate. Computed value must be between 0 and element height
w: Describes the width of the part of the element to animate. Computed value must be between 0 and element width-x
h: Describes the height of the part of the element to animate. Computed value must be between 0 and element height-y

**Comment by fantasai** [comment]
@FirstByteFirst I don't understand the request here, can you explain it better, maybe with some examples?

**Comment by FirstByteFirst** [comment]
Thank you for reponding!

A usecase:

Some office buildings have an entrance made of two glass doors. When you approach the doors they open electrically; one goes to the left and one goes to the right. 

Now we have an image of these doors on our website. Let's try to create the animation to open the doors. Currently we can not do that because the animation works on the whole image; not the left or right part only. The CSS-code:

```css
@keyframes doorLeft {
	from {transform: translate3d(0, 0, 0);}
	to {transform: translate3d(-100%, 0, 0);}
}
@keyframes doorRight {
	from {transform: translate3d(0, 0, 0);}
	to {transform: translate3d(100%, 0, 0);}
}
.doors{
	animation: 
		1s linear doorLeft;
		1s linear doorRight;
	animation-offset 0 0 50% 100% , 50% 0 50% 100%; /* <- this is my proposal (feel free to find a better name) */
} 
```
More examples:
- In some SF-movies we see doors that open in 4 parts: each part diagonally moves to top-left, top-right, bottom-right and bottom-left resp.
- again an image: divide it in 20 vertical ribbons. Let the image come in by moving the ribbons one by one from the right to the left with a gap between each ribbon. When the ribbon comes on the destination the next ribbon decreases it gap till it reaches its destination also; and so one.
- a div containing several HTML-elements: divide it in 9 equal parts. Let them rotate out...
The possibilities are endless.

Did this made things clear?

**Comment by ydaniv** [comment]
@FirstByteFirst if you want to target different elements you should simply use different selectors:

```css
.door-left {
  animation: 1s linear doorLeft;
}

.door-right {
  animation: 1s linear doorRight;
}
```

Otherwise, seems like what you're asking is to get a clipped part of the element and animate that.

IMHO, I don't see a need to be able to target clip parts of elements, other than really esoteric visual effects.

Does this answer your question?
