### ISSUE TITLE
[css-variables] Applicable namespace rules for variable expansion

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1163]
This is pretty much the same issue as https://github.com/w3c/csswg-drafts/issues/757, so we may want a similar behavior.

```css
/* a.css */
@namespace foo "http://www.w3.org/1999/xhtml";
:root { --a: foo }
```
```css
/* b.css */
@namespace foo "http://www.w3.org/1999/xlink";
:root { --b: attr(var(--a)|href) }
```
```css
/* c.css */
@namespace foo "";
a:before { content: var(--b) }
```
