### ISSUE TITLE
`display: contents` with `nth-child` and other pseudo-classes

### ISSUE THREAD

**Issue by FrameMuse** [w3c/csswg-drafts#11647]
I was playing around `display: contents` and it seemed to be working fine until I applied `nth-child` selector. Shortly, it takes into account elements with `display: contents` as normal elements, which breaks `nth-child` matching.

**Example**

Where there are multiple .card elements, each one being wrapped into div with `display: contents`.

```css
.card:nth-child(2n):not(:last-child)::before {
  content: "";
  // ...
}
```

Maybe I misunderstood something, though I think it should work as well since `display: contents` should display an element as if it's not there, right?
