### ISSUE TITLE
[css-view-transitions] Same-document view transitions without JavaScript

### ISSUE THREAD

**Issue by benface** [w3c/csswg-drafts#11675]
Here's a potentially crazy idea, but I would love a way to harness the power of view transitions with CSS-only interactions such as `:hover`. For example, the following snippet could automatically move a kind of background "hover indicator" as different links are hovered:

```html
<nav>
  <a href="/home">Home</a>
  <a href="/about">About</a>
  <a href="/contact">Contact</a>
</nav>
```

```css
nav {
  display: flex;
  gap: 16px;
}

nav a::before {
  content: '';
}

nav a:hover::before {
  position: absolute;
  inset: -8px;
  background-color: #eee;
  border-radius: 9999px;
  view-transition-name: link-hover-indicator;
  view-transition-trigger: auto; /* this would mean it auto-detects when a different element/pseudo-element gets the same `view-transition-name` and transitions between the old and the new one */
}
```

I am very much expecting this to be closed as not technically feasible given the current design of view transitions, but I had to propose it. 😁
