### ISSUE TITLE
[mediaqueries-5] Allow comparators / ranges in style queries

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#11759]
The syntax of a `<style-feature>` is currently defined as “ a valid declaration, a supported CSS property, or a `<custom-property-name>`.”

The first part allows one to only do equality comparisons, like so:

```css
/* --num-children is exactly 10 */
@container style(--num-children: 10) {
  #target {
    background: red;
  }
}
```

What is currently not allowed is to do mathematical comparisons, which I think would be nice to add, allowing authors to do things like this:

```css
/* --num-children is 10 or greater */
@container style(--num-children >= 10) {
  #target {
    background: red;
  }
}
```

Or even this:

```css
#target {
  background: if(
    style(--num-children >= 10): red;
    style(--num-children >= 8): orange;
    style(--num-children >= 6): yellow;
    else: green;
  );
}
```

_(Assuming `if()` treats multiple conditions as if they were an `else if` – if not then the lines need to be reshuffled a bit)_

Or this:

```css
#target {
  background: if(
    style(--num-children >= 10): red;
    style(8 <= --num-children < 10): orange;
    style(6 <= --num-children < 8): yellow;
    else: green;
  );
}
```

**Comment by yisibl** [comment]
I remember some other issue mentioning this syntax before, but I can't find it.

**Comment by Silverium** [comment]
this looks more like a `switch case` and not an `if else` block I would refactor your proposal like
```css
#target {
  background: switch(
    style(--num-children >= 10): red;
    style(8 <= --num-children < 10): orange;
    style(6 <= --num-children < 8): yellow;
    default: green;
  );
}
```
