### ISSUE TITLE
[css-anchor-position] Let more pseudo-elements have implicit anchor elements

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#11792]
In #10494 we're discussing having `::scroll-marker-group` use its originating element as its "implicit anchor element", so as long as you don't override anything you can just immediately use `position: absolute; position-area: bottom center;` or similar to position the group.

@flackr brought up that it might make sense to extend this to more tree-abiding pseudos, and make them *all* use their originating element as their implicit anchor element. For example, `::before` would default to positioning relative to the element it's generated for.

This sounds like a reasonable idea? It's technically a behavior change, but only with regards to content that is setting the anchor-pos properties *on* pseudo-elements *without* setting a `position-anchor` value. That seems vanishingly unlikely at this point in the feature's life.

**Comment by xPaw** [comment]
I agree this would be useful for :before/:after to have implicit anchors. I updated my css tooltips to use anchors, and currently had to do this:

```css
.tooltipped {
	&:hover {
		anchor-name: --tooltip-anchor;

		&:after {
			position-anchor: --tooltip-anchor;
		}
	}

	&:focus-visible {
		anchor-name: --tooltip-anchor-focus;

		&:after {
			position-anchor: --tooltip-anchor-focus;
		}
	}
}
```
