### ISSUE TITLE
[css-overflow-5] scroll-marker-group on root scroller?

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#11802]
Should we allow `scroll-marker-group: before | after` on the root element? E.g.

```css
:root {
  scroll-marker-group: before;
}
:root::scroll-marker-group {
  position: fixed; 
  top: 8px;
}
```

This seems like reasonable behavior to me but would be slightly different than on typical overflow divs. In particular, the `::scroll-marker-group` can't be a sibling to the content, but will be more like a `::before` or `::after` pseudo-element being a regular child.
