### ISSUE TITLE
[css-forms-1] Should `field-sizing: content` be in base appearance stylesheet?

### ISSUE THREAD

**Issue by lukewarlow** [w3c/csswg-drafts#11838]
It's unclear to me what the sizing model for base appearance styled elements are but it feels like `field-sizing: content` should be the default behaviour.

**Comment by nt1m** [comment]
I'm not too sure about this, the majority of form controls I've seen are fixed size, including real-life physical form control on paper.

I wouldn't be closed to the idea though, if there is evidence that `field-sizing: content` wouldn't end up being a bogus default that constantly needs to get overridden.

**Comment by lukewarlow** [comment]
I suspect for textarea specifically it would be the better default. Even if the default stylesheet defined a min and max height of say 3lh. That way they can override those properties and it just work. Otherwise they'll have to set field-sizing too?

**Comment by lukewarlow** [comment]
Something like the below styles will give you field-sizing: content behaviour but with a default width and height for textual inputs and textareas. These styles mostly match the existing intrinsic sizes (though they're based on the ch unit for a very specific microsoft font so it's only approximate).

```css
textarea {
    field-sizing: content;
    width: 22ch;
    height: 2lh;
}

input:not([type=checkbox], [type=radio], [type=file], [type=color], [type=range]) {
    field-sizing: content;
    width: 20ch;
}
```

With this authors can get the auto growing behaviour by doing something like:

```css
textarea {
   height: auto;
   /* min-height max-height styles work to constrain size. */
}

input:not([type=checkbox], [type=radio], [type=file], [type=color], [type=range])  {
   width: auto;
   /* min-width max-width styles work to constrain size. */
}
```

**Comment by lukewarlow** [comment]
Also base appearance select effectively forces field-sizing: content to true (though currently the computed style still says fixed in chrome), so perhaps we should also add:

```css
select {
   field-sizing: content !important;
}
```

So that the behaviour is easier to debug?
