### ISSUE TITLE
[css-grid-2] Example 5 - Multiple issues

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11848]
Section 2.3 starts with the following example:

>  The following example justifies all columns by distributing any extra space among them, and centers the grid in the grid container when it is smaller than 100vh. 
>
> ```css
> main {
>   grid: auto-flow 1fr / repeat(auto-fill, 5em);
>   min-height: 100vh;
>   justify-content: space-between;
>   align-content: safe center;
> }
> ```

Issues:

1. The example omits setting `display: grid` on the `<main>` element, which means the grid properties are not applied.

2. The example sets the implicit grid rows to `1fr`, which causes each row (or even a single row) to expand to fill the available vertical space dictated by `min-height: 100vh`. Regardless of whether there is one row or multiple rows, all the rows take up the full available height, leaving no extra vertical space for the `align-content: safe center` property to have an effect.

Suggested revision:

```css
  main {
    display: grid;
    grid: auto-flow auto / repeat(auto-fill, 5em);
    min-height: 100vh;
    align-content: safe center;
  }
```
