### ISSUE TITLE
[css-forms-1] For `control-value()` to be useful it needs a way to convert to other types.

### ISSUE THREAD

**Issue by lukewarlow** [w3c/csswg-drafts#11842]
Currently CSS Forms defines `control-value()` to be able to return a string or number, but for this to be useful we would need a way to convert to other CSS types (https://github.com/w3c/csswg-drafts/issues/6408 ?).

Take `<progress>` as an example, it has a position property (which is probably more useful than the value one for this CSS func as it handles the maths between value and max to determine actual progress value) between 0 and 1. This is useful for sizing the fill portion of the control, but for that we'd need a way to make it a (percentage) length instead.

```css
progress::fill {
    inline-size: convert(calc(content-value(type(<number>)) * 100), type(<length>), "%");
}
```

Alternatively if we could pass other types into `content-value()` and the browser could do the conversion for us that'd also work?

```css
progress::fill {
    inline-size: calc(content-value(type(<length>), "%") * 100);
}
```

Either of these could also help with styling the color input too (along with #11837 )

The default style could be something like:

```css
input[type=color]::color-swatch {
     background-color: content-value(type(<color>)); /* or convert(content-value(), type(<color>)) */
}
```

**Comment by nt1m** [comment]
The current draft includes a type argument, I suppose that argument could just be extended to whatever people find useful.

I haven't really thought about it too much tbh

**Comment by SebastianZ** [comment]
With explicit type conversion as discussed in #6408, I think your examples would look different.

```css
progress::fill {
    inline-size: convert(calc(convert(content-value(), <number>) * 100), <percentage>);
}
```

and

```css
input[type=color]::color-swatch {
     background-color: convert(content-value(), <color>);
}
```

Note that there is no need for a `type()` function. And as @nt1m pointed out in the previous comment, it also isn't part of the draft spec.
With the type attribute from the spec., those examples should look like this:

```css
progress::fill {
    inline-size: convert(calc(content-value(<number>) * 100), <percentage>);
}
```

and

```css
input[type=color]::color-swatch {
     background-color: content-value(<color>);
}
```

-----

Though maybe it is also possible to make the return value of the function context-sensitive, i.e. let it return a `<number>` value for `<progress>`, `<input type="range">` and other elements, a `<color>` value for `<input type="color">`, a `<url>` value for `<input type="url">`, etc.

With that, you could skip the explicit type definition/conversion for the `content-value()` function for the given use cases and write this:

```css
progress::fill {
    inline-size: convert(calc(content-value() * 100), <percentage>);
}
```

and

```css
input[type=color]::color-swatch {
     background-color: content-value();
}
```

Sebastian
