### ISSUE TITLE
[css-forms-1] Double border style for progres, meter and input[type=checkbox][switch]

### ISSUE THREAD

**Issue by lukewarlow** [w3c/csswg-drafts#11841]
Per https://drafts.csswg.org/css-forms/#layout

Meter, Progress and switch inputs get a double border, once on the "host" element, once on the inner track.

```css
input:not([type=file], [type=range]),
...
::track,
meter,
progress {
  border: 1px solid currentColor;
  background-color: transparent;
}
```

I think the meter, and progress elements should be removed from this second rule (they also already get a transparent background-color from the base rule). [type=checkbox][switch] should also be added to the not selector on the first line.
