### ISSUE TITLE
[css-borders-4] How `corner-shape` generates triangles

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#11846]
In @LeaVerou's [tool](https://projects.verou.me/corner-shape/), the `bevel` value makes it easy to generate a triangle, but the current Chrome implementation doesn't work yet - is this a limitation of the current specification or an implementation issue?

Drawing triangles with CSS is a very common requirement, most commonly used for popovers for example.

<img width="300" src="https://github.com/user-attachments/assets/c1366c0f-5d07-4a12-8d41-654f147d856c"> <img width="200" src="https://github.com/user-attachments/assets/ba06552d-f8a0-46bc-95e1-3661e4e0dbb0">

```html
data:text/html;charset=UTF-8,<!DOCTYPE html>
<style>
div {
  width: 200px;
  height: 200px;
  background: hsl(320, 80%, 30%);
  corner-shape: bevel;
  border-radius: 100% 100% 0 0;
}
</style>
<div></div>
```

cc @noamr @smfr

**Comment by noamr** [comment]
The left picture uses different radius constraints for bevel from the ones for round... Those constraints aren't spec'ed yet.

The following draws a triangle atm:

```css
.bevel {
  background: rebeccapurple;
  border-radius: 200px 200px 0 0;
  width: 400px;
  height: 200px;
  corner-shape: bevel;
}
```
