### ISSUE TITLE
[css-forms-1] The styles for checkbox/radio seem like they need to use :checked?

### ISSUE THREAD

**Issue by mfreed7** [w3c/csswg-drafts#11894]
The proposed styles for checkbox/radio would seem to always show checkmarks/dots:

```css
input[type=checkbox]:not([switch])::checkmark {
    content: '\2713' / '';
}

input[type=radio]::checkmark {
    content: '';
    background-color: currentColor;
    display: inline-block;
    border-radius: 100%;
    height: 100%;
    width: 100%;
}
```

I think there needs to be a rule similar to `<select>`, or perhaps that one can just be made more general?

```css
:not(:checked)::checkmark {
  visibility: hidden;
}
```
