### ISSUE TITLE
[css-nesting?] Allow nesting `@media` inside `@font-face`

### ISSUE THREAD

**Issue by valtlai** [w3c/csswg-drafts#11940]
Spec: https://drafts.csswg.org/css-nesting/#conditionals (?)

Could we allow nesting `@media` at-rules inside `@font-face`?

My use case would be conditionally loading a hinted or unhinted font:

```css
@font-face {
  font-family: 'The Font';
  src: url(the-font-hinted.woff2);

  @media (resolution >= 2x) {
    src: url(the-font-unhinted.woff2);
  }
}
```

Without nesting support (or `if()` support, see #11941), we have to needlessly repeat the unchanged descriptors:

```css
@media (resolution < 2x) {
  @font-face {
    font-family: 'The Font';
    src: url(the-font-hinted.woff2);
  }
}

@media (resolution >= 2x) {
  @font-face {
    font-family: 'The Font';
    src: url(the-font-unhinted.woff2);
  }
}
```

This isn’t DRY and is annoying when there are a lot of `@font-face` rules.

**Comment by AtkinsSJ** [comment]
If I understand it correctly, you would be able to do this using [`if()`](https://drafts.csswg.org/css-values-5/#funcdef-if):
```css
@font-face {
  font-family: 'The Font';
  src: if(
    media(resolution >= 2x) : url(the-font-hinted.woff2);
    else : url(the-font-unhinted.woff2)
  );
}
```
