### ISSUE TITLE
[css-values-5] Allow `if()` in descriptors

### ISSUE THREAD

**Issue by valtlai** [w3c/csswg-drafts#11941]
Spec: https://drafts.csswg.org/css-values-5/#if-notation

Could we allow using the `if()` function in at-rule descriptors (if not already the case)?

My use case would be conditionally loading an hinted or unhinted font:

```css
@font-face {
  font-family: 'The Font';
  src: if(
    media(resolution >= 2x): url(the-font-unhinted.woff2);
    else: url(the-font-hinted.woff2)
  );
}
```

Without `if()` support (or nesting support, see #11940), we have to needlessly repeat the unchanged descriptors:

```css
@media (resolution < 2x) {
  font-family: 'The Font';
  src: url(the-font-hinted.woff2);
}

@media (resolution >= 2x) {
  font-family: 'The Font';
  src: url(the-font-unhinted.woff2);
}
```

This isn’t DRY and is annoying when there are lot of `@font-face` rules.
