### ISSUE TITLE
[css-easing] Allow `steps()` to accept an easing function as the `<step-position>`

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#11970]
Recently Vasilis [asked](https://front-end.social/@vasilis@social.vasilis.nl/114174299342016142):

> Dearest CSS working group, I want to be able to define a transition between the steps in an animation-timing-function. Can you please fix this?

They needed this create the seconds hand of this clock which uses an `ease` between every second it ticks: https://vasilis.nl/clocks/station-clock/01/

As a workaround I [pointed](https://front-end.social/@bramus/114174411047664584) them to creating a bunch of keyframes and setting the `animation-timing-function` per keyframe, which they did, resulting in _a lot_ of code.:

```css
/* 
Very annoying, but this is, for now, the only way to 
transition between steps() in a keyframe animation.
Had to write out every percentage. 
*/
@keyframes ticking {
	0% {
		rotate: 0deg;
		animation-timing-function: ease;
	}
	1.66666666% {
		rotate: 6deg;
		animation-timing-function: ease;
	}
	3.33333333% {
		rotate: 12deg;
		animation-timing-function: ease;
	}
	…
	98.33333333% {
		rotate: 354deg;
		animation-timing-function: ease;
	}
	100% {
		rotate: 360deg;
		animation-timing-function: ease;
	}
}
.seconds {
  animation: ticking 58s linear;
}
```

_(Not sure why they chose `58s`, though)_

If [`steps()`](https://www.w3.org/TR/css-easing-2/#step-easing-function) were to accept another easing function as the `<step-position>`, the code could be simplified to the following:

```css
@keyframes ticking {
  to {
    rotate: 360deg;
  }
}

.seconds {
  animation: ticking 60s steps(60, ease);
}
```

**Comment by bramus** [comment]
> Can't you do it with a really long `linear()` function?

Yes, but then you’d need a generator to generate the contents for `linear()`, resulting in a long and highly unreadable string. In contrast, `steps(60, ease);` is very readable, concise, and clearly conveys what it does.

**Comment by ydaniv** [comment]
@bramus not sure I understand, are they asking to be able to set the keyframe-wide easing once in the `animation-timing-function`? If so then this is already what that does, unlike the new [`animation-easing`](#6982) property we resolved to add.
So not setting `ease` in each keyframe and putting it once in the `animation` shorthand is already equivalent.

**Comment by bramus** [comment]
> are they asking to be able to set the keyframe-wide easing once in the animation-timing-function?

No, they are asking to set the easing between the steps. Like this:

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/fe65d9b8-1cfa-4b9f-aac8-2ca03b31c6d6" />

**Comment by ydaniv** [comment]
Gotcha! Then your proposal sounds fine, however, I wonder if we have any other use-cases beside creating an animated clock?
That aside, this could have been possible today with WAAPI in one line if we had [`iterationComposite`](https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect/iterationComposite) cross-browser: https://jsbin.com/yulefimane/1/edit?css,js,output 😀 🙏 (Firefox only!)

**Comment by birtles** [comment]
> That aside, this could have been possible today with WAAPI in one line if we had [`iterationComposite`](https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect/iterationComposite) cross-browser: https://jsbin.com/yulefimane/1/edit?css,js,output

Ah, yes, I forgot we specified that. I think that's more useful for this case because it allows you to easily have a flat part followed by an ease part which seems more clock-like to me, e.g.

```js
window.target.animate({
  rotate: ['0deg', '0deg', '6deg']
}, {
  duration: 1000,
  iterations: Infinity,
  iterationComposite: 'accumulate',
  easing: 'ease'
});
```

[JSbin](https://jsbin.com/sesewuwida/edit?css,js,output)

I'm not sure how you'd achieve that with the `steps(3, ease)` approach.

**Comment by surahotoke** [comment]
I came up with the following workaround:

```css
@keyframes ticking-steps {
  to {
    rotate: 360deg;
  }
}
@keyframes ticking-ease {
  to {
    rotate: 6deg;
  }
}

.seconds {
  animation: ticking-steps 60s steps(60) infinite;
}
.seconds-smooth {
  animation: ticking-ease 1s ease infinite;
}
```

```html
<div class="seconds"><div class="seconds-smooth"></div></div>
```
