### ISSUE TITLE
Pseudo elements and SVG for form controls

### ISSUE THREAD

**Issue by jpzwarte** [w3c/csswg-drafts#12039]
So as part of the CSS Forms 1 spec, i love that a lot of user-interface things are being exposed. Like `::picker-icon` in `<select>` and `::checkmark` for `<input type=checkbox>`. I'm unclear however how customizable those things actually are in practice.

One common practice for design systems is to provide a custom icon for those experiences, usually in the form of SVGs. Sometimes those icons are also animated, for example the `<path>` of the checkbox when the state changes to `:checked`.

One way today would be to use `background: url("data:image/svg+xml.....");` for the pseudo element. The downside of that is that the SVG is not styleable via CSS. So using this technique, you wouldn't be able to animate it in the checkbox scenario.

Is there an existing issue for this that i'm missing?

**Comment by noamr** [comment]
See also https://front-end.social/@kizu/111564320833361099 (@kizu)

**Comment by noamr** [comment]
I think this issue is bigger than stylable form controls... e.g. being able to pass a template that slots into scroll marker.
It takes the web platform in the direction of CSS-managed markup composition.
It could be a really interesting to pass a template, which gets slotted into a pseudo-element and gets some of its parameters propagate from outside.

It's a big undertaking though :)

**Comment by jpzwarte** [comment]
Here is another example from @argyleink where the fill color of the `<svg>` is hardcoded in a data URI for the CSS `content` value: https://codepen.io/editor/argyleink/pen/019c1f28-bbc2-7bac-ad4a-a7e41d3730f1

What if we start "simple" here and make `currentColor` and CSS custom props available to inline data URI SVGs? Is that doable? Are there reasons why that isn't already possible?

**Comment by kizu** [comment]
@jpzwarte In theory, this is covered by https://drafts.csswg.org/css-link-params-1/, although no browser has implemented that yet.

**Comment by jpzwarte** [comment]
> [@jpzwarte](https://github.com/jpzwarte) In theory, this is covered by https://drafts.csswg.org/css-link-params-1/, although no browser has implemented that yet.

There is no data URI example in there, but i assume it would look something like this?

```css
content: url(
  'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" stroke="env(--stroke, black)" fill="none" viewBox="0 0 24 24"  stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"/></svg>', 
  param(--stroke, var(--some-design-system-color))
);

**Comment by kizu** [comment]
Yes, or via the `link-parameters` property on the pseudo:

> The [link-parameters](https://drafts.csswg.org/css-link-params-1/#propdef-link-parameters) property is one way to set [link parameters](https://drafts.csswg.org/css-link-params-1/#css-link-parameter) on the element itself (if it is an element representing an external resource, such as an HTML [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) or [iframe](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element)), and on all external CSS resources specified on the element (such as background images, etc). Its values are:

Note “on all external CSS resources specified on the element” — the image in the data URI should count as such.

**Comment by jpzwarte** [comment]
> Yes, or via the `link-parameters` property on the pseudo:

Nice, but it says `link-parameters` doesn't inherit, so this wouldn't work, right?

```css
option {
  link-parameters: param(--stroke, var(--some-design-system-color));
  
  &:hover {
    link-parameters: param(--stroke, var(--some-design-system-hover-color));
  }

  &::checkmark {
    content: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" stroke="env(--stroke, black)" fill="none" viewBox="0 0 24 24"  stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"/></svg>');
  }
}
```

You'd have to explicitly set it on `::checkmark`?

```css
option {
  &:hover::checkmark {
    link-parameters: param(--stroke, var(--some-design-system-hover-color));
  }
  
  &::checkmark {
    content: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" stroke="env(--stroke, black)" fill="none" viewBox="0 0 24 24"  stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"/></svg>');
    link-parameters: param(--stroke, var(--some-design-system-color));
  }
}
```

Edited: the above is way too complex i think; just do this:

```css
option {
  --stroke: var(--some-design-system-color);

  &:hover {
    --stroke: var(--some-design-system-hover-color);
  }

  &::checkmark {
    content: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" stroke="env(--stroke, black)" fill="none" viewBox="0 0 24 24"  stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"/></svg>');
    link-parameters: param(--stroke, var(--stroke));
  }
}
```

**Comment by kizu** [comment]
That's a good question! By itself it is not inherited, so unless we'd resolve for it to inherit on pseudo-elements (similar to implicit anchors available on them), yes, it will need to be defined on the pseudo-element itself.

- - - 

Also… thinking about all of that — I am not sure we will be able to pass the `currentColor` specifically… I don't think the spec currently defines the timing of when the parameters are passed:

> (using the [CSS value definition syntax](https://drafts.csswg.org/css-values-4/#css-value-definition-syntax); TODO define an actual parser for it).

`currentColor`'s value is resolved at the used time, and, for example, is not expanded when we use it with `@property` etc. Maybe that will need to be more explicitly defined — and `currentColor` in the linked params might be one of the most common use cases (for icons, etc.). cc @tabatkins (probably, could be a separate issue specifically about this aspect of linked params?)

**Comment by andyearnshaw** [comment]
I came here to suggest that base form control icons be represented internally as SVG elements so that you could, essentially customise the path. For example, for select components:

```css
::picker-icon {
  d: path("M6 9L12 15L18 9"); /* chevron angled downwards */
}

::checkmark {
  d: path("M20 6L9 17L4 12"); /* traditional checkmark */
}
```

The spec would probably have to define the viewbox for each icon.  While this is not as flexible as the template suggestion, it's incredibly simple. The paths can also be animated. For instance, you could linearly draw the checkmark of a checkbox as it is clicked, or flip a picker icon when the select picker is opened.
