### ISSUE TITLE
[css-overflow] What is the expected behavior of scrollable overflow in case of non-rectangular descendant area due to transforms?

### ISSUE THREAD

**Issue by stevennovaryo** [w3c/csswg-drafts#12112]
The overflow spec defines how [scrollable overflow area calculated in a recursive way](https://drafts.csswg.org/css-overflow/#scrollable-overflow-region). Basically, the spec would consider the union of children's area for each layer of recursion. In which, could be non-rectangular due to transform. 

On the other hand, implementations uses the smallest bounding rectangle of these union in each layer of recursion for the calculation of a scrollable overflow area. This causes inaccuracy where the scrollable overflow of the element could extend beyond the farthest point of it's descendants if it have nested transforms that results in non-rectangular shapes. As shown by [scrollable overflow of an element with nested rotated descendant example](https://jsfiddle.net/a57m89pj/2/). 

cc: @xiaochengh @Loirooriol

**Comment by Loirooriol** [comment]
<details><summary>Source code of the example</summary>

```css
.container {
  width: 250px;
  height: 250px;
  overflow: scroll;
  background: silver;
  border: solid thick;
}

.element {
  width: 200px;
  height: 200px;
  background: lime;
}

.element-2 {
  width: 200px;
  height: 200px;
  background: aqua;
}
```
```html
<div class="container">
  <div style="transform: rotate(-45deg);" class="element">
    <div style="transform: rotate(45deg);" class="element-2">
    </div>
  </div>
</div>

<div class="container">
  <div style="transform: rotate(30deg) rotate(-15deg);" class="element">
    <div style="transform: rotate(-30deg) rotate(105deg);" class="element-2">
    </div>
  </div>
</div>
```

</details>

![](https://github.com/user-attachments/assets/8b36ecda-11b6-4647-b403-e2a57f8bc5e4)

Also: https://wpt.fyi/results/css/css-overflow/scrollable-overflow-transform-010.tentative.html
