### ISSUE TITLE
[css-overflow] Clarify the contribution of untransformed direct descendant box

### ISSUE THREAD

**Issue by stevennovaryo** [w3c/csswg-drafts#12113]
The current implementations of scrollable overflow seems to be quite quirky and specific in terms of direct descendant contribution. Where it would consider the untransformed box of direct descendant, As shown in this [example](https://jsfiddle.net/8dq6Lvbc/). With the untransformed box of non-direct descendant being omitted, shown by this [example](https://jsfiddle.net/rtykg9bL/). Meanwhile, the scrollable overflow implementations is ignoring the untransformed box in case the box is absolute positioned while the parent element established absolute positioned containing block, shown [here](https://jsfiddle.net/dLstjh1g/). 

This quite particular behavior however, is not specifically defined or mentioned in [scrollable overflow definition](https://drafts.csswg.org/css-overflow/#scrollable-overflow-region). I believe it would be good to have a consistent behavior for this case, maybe omitting the untransformed box since scrollable overflow are supposed to show till the farthest corner of descendant anyway. Or, an additional explanation for these behavior. 

cc: @xiaochengh @Loirooriol

**Comment by Loirooriol** [comment]
I don't trust jsfiddle to keep hosting the examples

<details><summary>Example 1</summary>

```css
.container {
  width: 150px;
  height: 150px;
  overflow: scroll;
  background: silver;
  border: solid thick;
}

.element {
  width: 200px;
  height: 200px;
  background: lime;
}

.element-2 {
  width: 100px;
  height: 100px;
}
```
```html
  <div class="container">
    <div style="transform: translate(-50%, -50%);" class="element">
    </div>
  </div>
```

</details>


<details><summary>Example 2</summary>

```css
.container {
  width: 150px;
  height: 150px;
  overflow: scroll;
  background: silver;
  border: solid thick;
}

.element {
  width: 200px;
  height: 200px;
  background: lime;
}

.element-2 {
  width: 100px;
  height: 100px;
}
```
```html
<div class="container">
  <div style="width: 150px; height: 150px;">
    <div style="transform: translate(-50%, -50%);" class="element">
    </div>
  </div>
</div>
```

</details>

<details><summary>Example 3</summary>

```css
.container {
  width: 150px;
  height: 150px;
  overflow: scroll;
  background: silver;
  border: solid thick;
}

.element {
  width: 200px;
  height: 200px;
  background: lime;
}

.element-2 {
  width: 100px;
  height: 100px;
}
```
```html
  <div class="container" style="position: relative;">
    <div style="transform: translate(-50%, -50%); position: absolute;" class="element">
    </div>
  </div>
```

</details>
