### ISSUE TITLE
[css-forms-1] Does the Basic Appearance UA Stylesheet Define intrinsic sizing?

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#12117]
With the release of [CSS Form Control Styling Level 1](https://drafts.csswg.org/css-forms/), does [Appendix A](https://drafts.csswg.org/css-forms/#basic-appearance-stylesheet) ("Basic Appearance User Agent Stylesheet") define how intrinsic sizing (especially `width: auto` / `height: auto`) should behave for form controls?

Example from the appendix:

```css
select {
  /* Base appearance: select always sizes based on its contents. */
  field-sizing: content !important;
}
```

Per the [spec](https://drafts.csswg.org/css-forms/#valdef-field-sizing-content), `field-sizing: content` tells the UA to size based on content and ignore any default preferred size defined by the host language.

Does this mean `width: auto` for `<select>` effectively behaves like `max-content` or `fit-content`? 

Are these UA styles meant to align with, or establish, a new standard for automatic sizing of form controls?
