### ISSUE TITLE
[css-images-4] Conic Gradient "color wheel" example is backwards

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1222]
Conic-gradient() color-stops are distributed clockwise around the circle, but in Example 17 the example rendering shows them being laid out counter-clockwise.

**Comment by yisibl** [comment]
@LeaVerou 

With the addition of [Hue Interpolation](https://www.w3.org/TR/css-color-4/#hue-interpolation) in css-color-4, it is now possible to use `longer hue` for this example, can we add it to the example as well?

```css
.test {
  background-image: radial-gradient(circle closest-side, #fff, transparent),
    conic-gradient(in hsl longer hue, red, red);
  transform: scaleX(-1);
}
```
