### ISSUE TITLE
Defining how custom-indent results referring to a function should be handled

### ISSUE THREAD

**Issue by Que-tin** [w3c/csswg-drafts#12304]
How should results should be handled that return a custom-indent that might be a reference to another function?

```css
@function --x1() returns <number> {
  result: 2;
}

@function --x2() returns <custom-ident> {
  result: ident("x1");
}

.x {
 /* Will this be possible? */
 --y: --x()();

 /* Or do I need to do this? */
 --y: --x();
 --z: --y();
}
```
