### ISSUE TITLE
[css-conditional-5] `scroll-state(stuck)` will remain applying its `@container` ruleset for elements has left viewport

### ISSUE THREAD

**Issue by n0099** [w3c/csswg-drafts#12302]
https://jsfiddle.net/ebkafjtp/12/
```html
<div class="container">
  <div class="sticky"></div>
  <div class="sticky"></div>
  <div class="sticky"></div>
  <div class="sticky"></div>
  <div class="sticky"></div>
</div>
```
```css
.sticky {
  container-type: scroll-state;
  position: sticky;
  top: 0;
  height: 30vh;
  margin-block: 2rem;
  background: gray;
}
.sticky:nth-child(even) {
  background: darkgray;
}

@container scroll-state(stuck: block-start) {
  *::before {
    content: 'block-start';
  }
}
@container scroll-state(stuck: none) {
  *::before {
    content: 'none';
  }
}
```
When scrolling the viewport to the end, any `.sticky` whose [`getBoundingClientRect().bottom`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) is negative will still have their `::before { content: 'block-start'; }` style that defined in the [`<block-contents>`](https://drafts.csswg.org/css-syntax-3/#typedef-block-contents) of [`@container`](https://drafts.csswg.org/css-conditional-5/#container-rule).
