### ISSUE TITLE
[css-mixins-1] Allow typed custom properties inside custom functions

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#12317]
See: https://github.com/w3c/csswg-drafts/issues/12315

I also found it a bit surprising that there is no way to have local typed custom properties. (except `result`)

```css
@property --x {
  syntax: "<color>";
  inherits: true;
  initial-value: pink;
}

@function --foo() returns <color> {
  --x: rgb(255 0 0);
  
  result: if(
    style(--x: red): green;
    else: black;
  );
}

* {
  background-color: --foo(); /* black */
}
```

----

What was the original motivation to make everything untyped inside custom functions?

Because values are resolved in imaginary child elements nothing leaks out when a function is evaluated.
I can imagine that when the types are preserved it is possible to break custom functions by registering seemingly unrelated properties.

So maybe it should be possible to do local registrations?

**Comment by tabatkins** [comment]
> What was the original motivation to make everything untyped inside custom functions?

To avoid locals inside of functions having to be aware of all properties defined outside, or having to be defensively named to avoid collisions.

It would suck to write a re-usable function that used a local `--foo` variable to hold some intermediate calculation, and have that function straight up fail to work, unpredictably, on certain pages because that page also uses `--foo` for something and registered it with an incompatible type.

Also, arguments establish local variables, and they have a type, which has no need to be consistent with outside registrations either.

**Comment by romainmenke** [comment]
Authors are surprised that typed custom properties do not work as they would expect: https://bsky.app/profile/css-only.dev/post/3lttqh2u7t22q

Would it be possible to allow `@property` definitions inside `@function`?
This still avoid conflicts without limiting capabilities.

```css
@function --foo() returns <color> {
  @property --x {
    syntax: "<color>";
    inherits: true;
    initial-value: pink;
  }

  --x: rgb(255 0 0);
  
  result: if(
    style(--x: red): green;
    else: black;
  );
}
```

**Comment by tabatkins** [comment]
Hm, I see the argument for that. There's behavior you can get from inherited variables that you can't get from local variables, which isn't great. Most of the machinery of the registration isn't really necessary, tho - you honestly only need the syntax, right? Maybe we can just have a more limited syntax allowed in the function.

I keep looking for excuses to revive the `using()` prelude for some reason, lol, but having another "argument list" that just sets up some types for names you'll use in the body makes a lot of sense, I think. That is:

```css
@function --foo() using(--x <color>) returns <color> {
  --x: rgb(255 0 0);
  
  result: if(
    style(--x: red): green;
    else: black;
  );
}
```

That would just affect the set of registrations visible while evaluating the body. I don't think we *need* to allow a "default value" in the `using()`, and honestly that would probably be a bit confusing - I think it would need to be an overriding initial value, instead, which means it would be different from the value in the arguments. Probably better just to disallow, and only let you specify the type; you can supply the "initial value" at the top of the body, like in the example above.
