### ISSUE TITLE
[css-values] Allow `unset` to use `revert` for non-inherited properties, instead of `initial`

### ISSUE THREAD

**Issue by benface** [w3c/csswg-drafts#12341]
This would allow _actually_ resetting all properties to what they were before some arbitrary CSS was applied, e.g. in a subtree:

```css
/* bunch of CSS here */

#vendor-controlled-section {
  &, *, *::before, *::after {
    all: unset; /* all `div`s in this section will be inline! 😱 */
  }
}
```

Two ideas for syntax:

1. Make `unset` a function that accepts which value to use for non-inherited properties; `unset` would default to `unset(initial)` but the above would use `unset(revert)`. Maybe there's even a use case for `unset(revert-layer)`? 🤔
2. Add a `unset-revert` value.
