### ISSUE TITLE
[css-mixins-1] Are @mixin rules valid within other at-rules?

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#12417]
For example, are `@mixin` rules valid within `@container`?

```
@container (...) {
  @mixin --m() {
    /* style rules */
  }
}
```

If yes, we already know that `--m()` isn't defined conditionally based on CQ evaluation (https://drafts.csswg.org/css-conditional-5/#container-rule, last paragraph of chapter), but are the inner _style rules_ affected?

```
div {
  @apply --m();
}
```

In other words, does the above `@apply` rule "remember" that the referenced mixin is enclosed by an `@container`? Any decision we make should hopefully answer the same question about `@layer`, `@starting-style`, etc.

My initial thought is that (for simplicity) we should make `@mixin` invalid within any at-rule except conditional rules with the ["old school" processing model](https://drafts.csswg.org/css-conditional-3/#processing) (i.e. currently `@media` and `@supports`).

**Comment by romainmenke** [comment]
> My initial thought is that (for simplicity) we should make `@mixin` invalid within any at-rule except conditional rules with the "old school" processing model (i.e. currently `@media` and `@supports`).

I somewhat agree with this.

But I think mixin rules should also be valid in `@layer` rules to be able to use cascade layers to resolve name conflicts.

However the inner styles should not be affected by this I think.
I would expect `:root` to have `color` `green` in this example:

```css
@layer early-layer, later-layer;

@layer later-layer {
  @mixin --m() { /* later layer declaration wins */
    color: green;
  }
}

@layer early-layer {
  @mixin --m() {
    color: red;
  }
}

:root {
  color: pink;
}

:root {
  @apply --m(); /* inner styles are unlayered */
}
```

Authors can also layer inner styles by writing:

```css
@layer a {
  @mixin --m() {
    @layer b {
      color: green;
    }
  }
}
```
