### ISSUE TITLE
[css-align][css-flexbox]Can align-content be used in a single-line of flex-containers?

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#1268]
```html
<div class="test"><div>foo</div></div>
```

```css
.test {
  display: flex;
  flex-wrap: wrap;
  border: 1px solid black;
  width: 200px;
  height: 100px;
  align-content: center;
  justify-content: center;
  margin: 30px auto;
}
```
Chrome ignores the `align-content` property, **Firefox, Edge, Safari will not**. 

Which does not seem to be explicitly defined in the specification.

Demo: http://jsbin.com/vuxorikewe/edit?html,css,output

![image](https://cloud.githubusercontent.com/assets/2784308/25266046/43d0a65c-26a2-11e7-9f1c-0d095373dc36.png)
![image](https://cloud.githubusercontent.com/assets/2784308/25266054/5390e2fa-26a2-11e7-949e-d8d315b7c1c6.png)
