### ISSUE TITLE
[css-properties-values-api] Mass property registration

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#13212]
Twitter thread: https://twitter.com/James0x57/status/1467601715067342853

It's rather common to register a number of properties with the same descriptors. E.g. most `<integer>`, `<number>` or `<length>` properties are registered to have an initial value of `0` and most properties are registered to have `inherits: true`. So, the multiple `@property` rules can get quite repetitive. For a particularly egregious example of this, look [here](https://github.com/propjockey/css-conways-game-of-life/blob/main/game-of-life.css#L140).

This proposal is about two things:
## `@property` should be able to define multiple properties with the same descriptors by just comma-separating them.

This is such low hanging fruit, that the MDN and web.dev docs on `@property` [originally included it](https://github.com/mdn/content/issues/5830) even though it was never a thing on the CSS side! 

It should also be pretty easy to do, if it's just a parse time shortcut that is expanded into multiple rules for the CSSOM.

We could even define them to cascade, like so:

```css
@property --number, --scale {
	syntax: "<number>";
	initial-value: 0;
	inherits: true;
}

@property --scale {
	initial-value: 1;
}
```

`CSS.registerProperty()` does not need to change, since if you're in JS-land, you can just loop anyway.

## Authors should be able to register entire namespaces of properties by using a wildcard at the end.

Something like this would help condense the [4000 lines of property registrations here](https://github.com/propjockey/css-conways-game-of-life/blob/main/game-of-life.css#L140) to just one. Admittedly, this is not a realistic example of regular CSS, but I've definitely come across more real cases of duplication that could be eliminated this way.

Another use case is utility registered properties like `--int-*`, `--length-*` etc [see tweet by @propjockey](https://twitter.com/James0x57/status/1467646389148688384).

@tabatkins said [they think it is feasible](https://twitter.com/tabatkins/status/1467686598649073667).

These would also need to be combinable, to deal with potential conflicts:

```css
@property --int-* {
	syntax: "<number>";
	initial-value: 0;
	inherits: true;
}

@property --int-foo-* {
	initial-value: 1;
}

@property --int-foo-bar {
	initial-value: 2;
}
```

Since `<dashed-ident>` does not permit `*`, I suppose we'd need to define a new token, `<dashed-ident-group>` 
`CSS.registerProperty()` could just accept these tokens under `name`, to minimize API changes, or we could do something more fancy on the JS side.

CSSOM wise this cannot really be expanded at parse time, since the set is infinite. Perhaps there should be some read-only boolean for authors to check if this is a group without having to do `rule.name.endsWith("*")`, but that's a minor point.

**Comment by Crissov** [comment]
For at least 4 years now, everybody has agreed the syntax for [`@property`](https://drafts.csswg.org/css-variables-2/#typedef-custom-property-name) should be :
~~~~ css
@property <custom-property-name># {
  <declaration-list>
}
~~~~
but in the current draft it still lacks that `#`.

**Comment by andruud** [comment]
There is another proposal here: https://github.com/w3c/csswg-drafts/issues/7523#issuecomment-1683831209 (based on Tab's post immediately before):

```css
@property {
  syntax: "<length>";
  inherits: false;
  initial-value: 2147483647px;
  --width: initial; /* 2147483647px */
  --height: initial; /* 2147483647px */
  --depth: 0px;
}
```

And/or we could imagine that a hypothetical `initial()` function is allowed here, to be able to express an initial value in terms of other initial values:

```css
@property {
  syntax: "<length>";
  inherits: false;
  --one: 1px;
  --two: 2px;
  --width: initial(--one);
  --height: initial(--two);
  --foo: calc(initial(--one) + initial(--two));
}
```

That would require a novel concept of "computing" an _initial_ value, but that should be possible as long as everything is [computationally independent](https://drafts.css-houdini.org/css-properties-values-api-1/#computationally-independent) otherwise.

---

Mass registration with wildcards: so ... `@property --int-*` is basically something like a "selector" that "matches" custom property names on that form? I'm not sure if it's wise to bake that much (potentially expensive) complexity into the the computed value process. Hopefully we can consider other ways to solve the use-cases this would be needed for. For example, custom functions/`if()` could help for some of them?

**Comment by LeaVerou** [comment]
> Mass registration with wildcards: so ... `@property --int-*` is basically something like a "selector" that "matches" custom property names on that form? I'm not sure if it's wise to bake that much (potentially expensive) complexity into the the computed value process. Hopefully we can consider other ways to solve the use-cases this would be needed for. For example, custom functions/`if()` could help for some of them?

I do think we should introduce features that eliminate the need for the **hundreds** of custom properties currently needed by design systems, and yes custom functions and `if()` will help tremendously, but I don't think we'd ever get it down to such small numbers where mass-registration won't be desirable. And there is a nice decoupling in being able to write 

```css
@property --foo-color-* {
	syntax: "<color>";
	initial-value: transparent;
	inherits: true;
}
```

rather than having to list every color design token in a centralized place.

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle

> append to decls all the [custom properties](https://drafts.csswg.org/css-variables-1/#custom-property) whose [computed value](https://drafts.csswg.org/css-cascade-5/#computed-value) for obj is not the [guaranteed-invalid value](https://drafts.csswg.org/css-variables-2/#guaranteed-invalid-value).

How do you conciliate this with mass registration? With `--foo-color-*`, there would be an infinite amount of such properties.

**Comment by andruud** [comment]
We'd have to say that `@property --foo-color-*` doesn't actually count as those (infinitely many) properties existing, but instead just affects the computed value process for the actually-specified custom properties that match.

**Comment by Loirooriol** [comment]
I don't get it, what makes one of these infinitely many properties exist for real? Being used in `var()`?

**Comment by andruud** [comment]
The same thing that makes an unregistered property exist for real: specifying it somewhere. E.g. for `#foo { --thing: 1; }`, `--thing` shows up in the gCS enumeration on `<div id=foo>`, but the infinite amount of unregistered custom properties that _could_ have been specified do not.

**Comment by Loirooriol** [comment]
> The same thing that makes an unregistered property exist for real

It's not the same thing, because for unregistered, the logic is that the value is not the guaranteed-invalid value. E.g. this is false:

```html
<!DOCTYPE html>
<style>:root { --foo-bar: initial }</style>
<script>
// This is false, the value is the guaranteed-invalid value
document.documentElement.textContent =
  [...getComputedStyle(document.documentElement)].includes("--foo-bar");
</script>
```

For mass registered properties whose initial value is not the guaranteed-invalid value, the above doesn't work. So instead of checking the computed style, we need to check the cascade. And then this would be true?

```html
<!DOCTYPE html>
<style>
@property --foo-* { syntax: "<number>"; initial-value: 1; inherits: true }
:root { --foo-bar: initial }
</style>
<script>
// This is true, the property is specified
document.documentElement.textContent =
  [...getComputedStyle(document.documentElement)].includes("--foo-bar");
</script>
```

And what about inheritance? Does the property count as specified if it inherits from an ancestor where it's actually specified?

And what about `revert` & friends, do they count as specifying, or can they undo the specification of the property?

**Comment by LeaVerou** [comment]
Hit this once more when trying to use CSS for icons. I have an `icons.css` with a bunch of declarations like:

```css
:root {
	--icon-check: url("icons/check.svg");
	--icon-play: url("icons/play.svg");
	--icon-undo: url("icons/undo.svg");
	--icon-redo: url("icons/redo.svg");
	--icon-lock: url("icons/lock.svg");
	--icon-lock-open: url("icons/lock-open.svg");
	--icon-share: url("icons/share.svg");
	/* … dozens more … */
}
```

Without `@property` this is very fragile: used from stylesheets not adjacent to `icons.css`, the icons are broken, since without registration, the `url()`s are resolved relative to the callsite.

However, it would be extremely verbose to add `@property` for each of them, even with a defaulted `inherits`:

```css
@property --icon-check {
  syntax: '<image>';
  initial-value: url("icons/check.svg");
}

@property --icon-play {
  syntax: '<image>';
  initial-value: url("icons/play.svg");
}

@property --icon-undo {
  syntax: '<image>';
  initial-value: url("icons/undo.svg");
}

@property --icon-redo {
  syntax: '<image>';
  initial-value: url("icons/redo.svg");
}

@property --icon-lock {
  syntax: '<image>';
  initial-value: url("icons/lock.svg");
}

@property --icon-lock-open {
  syntax: '<image>';
  initial-value: url("icons/lock-open.svg");
}

@property --icon-share {
  syntax: '<image>';
  initial-value: url("icons/share.svg");
}

/* ... dozens more ... */
```

The `#` syntax would actively *degrade* the code. Yes, it would be shorter, but now adding an icon would require editing two separate places:

```css
:root {
	--icon-check: url("icons/check.svg");
	--icon-play: url("icons/play.svg");
	--icon-undo: url("icons/undo.svg");
	--icon-redo: url("icons/redo.svg");
	--icon-lock: url("icons/lock.svg");
	--icon-lock-open: url("icons/lock-open.svg");
	--icon-share: url("icons/share.svg");
	/* … dozens more … */
}

@property 
	--icon-check,
	--icon-play,
	--icon-undo,
	--icon-redo,
	--icon-lock,
	--icon-lock-open,
	--icon-share,
	/* … dozens more … */ {
  syntax: '<image>';
}
```

The shorter syntax that @tabatkins has been mentioning would help, but is still noisy and error prone (easy to define a new icon and forget it):

```css
:root {
	--icon-check <image>: url("icons/check.svg");
	--icon-play <image>: url("icons/play.svg");
	--icon-undo <image>: url("icons/undo.svg");
	--icon-redo <image>: url("icons/redo.svg");
	--icon-lock <image>: url("icons/lock.svg");
	--icon-lock-open <image>: url("icons/lock-open.svg");
	--icon-share <image>: url("icons/share.svg");
	/* … dozens more … */
}
```

The North star syntax that truly expresses author intent and has the highest signal to noise would be:

```css
:root {
	--icon-check: url("icons/check.svg");
	--icon-play: url("icons/play.svg");
	--icon-undo: url("icons/undo.svg");
	--icon-redo: url("icons/redo.svg");
	--icon-lock: url("icons/lock.svg");
	--icon-lock-open: url("icons/lock-open.svg");
	--icon-share: url("icons/share.svg");
	/* … dozens more … */
}

@property --icon-* {
  syntax: '<image>';
}
```

**Comment by LeaVerou** [comment]
Alright, since most of this discussion had centered around wildcards, and wildcards are significantly harder, I split out the much simpler comma expansion to #14225 and ported all relevant comments there (please post if I missed yours, or post and delete your comment here if there were no reactions to it in this thread) so we can track the two separately. This also allows me to put this issue under #14224.

I also edited the OP with:
- Framing and use cases to be explicitly distinct from #14225 
- Cut rule cascading from the proposal. Only one rule wins (the more specific one) with source order as the tie-breaker.
- Added proposed spec changes
- Fleshed out the proposed CSSOM changes (= no changes needed for an MVP)

**Comment by Loirooriol** [comment]
> The `#` syntax would actively degrade the code. Yes, it would be shorter, but now adding an icon would require editing two separate places

A solution for this was proposed in https://github.com/w3c/csswg-drafts/issues/7523#issuecomment-1683049214:

```css
@property {
	syntax: '<image>';
	--icon-check: url("icons/check.svg");
	--icon-play: url("icons/play.svg");
	--icon-undo: url("icons/undo.svg");
	--icon-redo: url("icons/redo.svg");
	--icon-lock: url("icons/lock.svg");
	--icon-lock-open: url("icons/lock-open.svg");
	--icon-share: url("icons/share.svg");
	/* … dozens more … */
}
```

You ["found this incredibly confusing to understand"](https://github.com/w3c/csswg-drafts/issues/7523#issuecomment-3609532747), but it avoids the problems of mass registration by prefix, so I prefer it.

**Comment by LeaVerou** [comment]
For that in particular, there's a more architecturally coherent syntax, though it would require repeating the type:

```css
@property 
	--icon-check <image>: url("icons/check.svg"),
	--icon-play <image>: url("icons/play.svg"),
	--icon-undo <image>: url("icons/undo.svg"),
	--icon-redo <image>: url("icons/redo.svg"),
	--icon-lock <image>: url("icons/lock.svg"),
	--icon-lock-open <image>: url("icons/lock-open.svg"),
	/* … dozens more … */
	--icon-share <image>: url("icons/share.svg");
```

Though this resolves verbosity and repetition, it does not resolve coupling. Though once we have the shorthand declaration syntax, perhaps that (together) will.

> the problems of mass registration by prefix, so I prefer it.

Which problems specifically are you referring to?

**Comment by Loirooriol** [comment]
> Which problems specifically are you referring to?

Mostly https://github.com/w3c/csswg-drafts/issues/13212#issuecomment-3646870627 and https://github.com/w3c/csswg-drafts/issues/13212#issuecomment-3646870695.

Also, you already added it to the top post, the conflict resolution challenge. Your proposal matches what I would expect, but it's like an extra thing that needs to be decided.

**Comment by LeaVerou** [comment]
> It's not the same thing, because for unregistered, the logic is that the value is not the guaranteed-invalid value.

We resolved in another thread to make `initial-value` optional, and default to the guaranteed-invalid value, wouldn't that create the same issue for regular registered properties? (I'm not 100% sure I see the issue you're seeing, so this may be completely off)

> Also, you already added it to the top post, the conflict resolution challenge. Your proposal matches what I would expect, but it's like an extra thing that needs to be decided.

Having to make design decisions is not a "problem", it's a normal part of language design. It becomes a problem when there is no clear best option, so consensus is hard and everything we pick will surprise a good chunk of users. So far, there is no evidence that this is the case here.

**Comment by Loirooriol** [comment]
> wouldn't that create the same issue for regular registered properties?

No. Let me try to explain the problem again:

```html
<!DOCTYPE html>
<style>
@property --foo-bar { syntax: "<number>"; initial-value: 1; inherits: true }
</style>
<script>
// This is true, because the computed value isn't the guaranteed-invalid value (it's 1).
document.documentElement.textContent =
  [...getComputedStyle(document.documentElement)].includes("--foo-bar");
</script>
```

The `--foo-bar` property gets included in `getComputedStyle()`. Presumably, this means that with ...

```css
@property --foo-* { syntax: "<number>"; initial-value: 1; inherits: true }
```

... `getComputedStyle()` should include all possible properties starting with `--foo-`. But there are infinitely many, so it's not possible.

I think Anders was saying that it could instead check whether the property gets assigned a value, but that raises various questions:
 - Would this imply changing the current behavior (risking web compatibility), or be restricted to properties mass registered with a prefix (inconsistency)?
 - What is the exact meaning of being assigned a value, specially with respect to resetting/inheritance (explicit or implicit) and cascade rollbacks?

> Having to make design decisions is not a "problem", it's a normal part of language design

My point is that if one approach raises lots of non-obvious design questions, and another approach doesn't because it's simpler, then the later is probably preferable.
