### ISSUE TITLE
[css-grid-1] Flex like control over grid items

### ISSUE THREAD

**Issue by lassediercks** [w3c/csswg-drafts#1344]
I'm referring to [the grid-column](https://drafts.csswg.org/css-grid/#typedef-grid-row-start-grid-line) shorthand. 

-----

I tried to implement a grid where the children adapt to the size of the container.

At one point I expected a grid item to behave similar to what we know from the  [the flex-grow](https://www.w3.org/TR/css-flexbox-1/#propdef-flex-grow) property.

Test case: https://codepen.io/lassediercks/pen/XRZbBo

Above 935px the grid looks fine,
Belove 935px I expect the `.aside` div to flow to the next line

---- 

The purpose of this issue is a proposal to add a behaviour similar to flex: 

When our container looks like this

```css
.container{
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
}
```
and a grid-item like this

```css
.item{
   grid-column-flex: 2;
}
```

We can expect `.item` to have the width of  `2*minmax(250px, 1fr)`

**Comment by lassediercks** [comment]
As this is the first issue in this repository, please let me know if I should provide additional information to elaborate the proposal

**Comment by mrego** [comment]
You can use `grid-column: span 2;` for that. Isn't that enough?

BTW, `flex-grow` from Flexbox is somehow similar to `fr` in Grid. So things like `flex: 2;` could be similar to a column with `2fr`.

**Comment by lassediercks** [comment]
Thanks for the comment @mrego 

As `grid-column: span 2;` is a absolute it would not solve the case what happens when auto-fill would be 2.

What I believe is, that a `grid-column-flex` property can [achieve this grid](http://codepen.io/lassediercks/pen/aWqVmb?editors=1100) without media queries



> BTW, flex-grow from Flexbox is somehow similar to fr

Totally, and if I could assign `fr` to a item, that would do the trick. 

```css
.item{
   grid-column: 2fr;
}
```
