### ISSUE TITLE
[css-page-4] Page margin box for watermarks and overlays

### ISSUE THREAD

**Issue by dauwhe** [w3c/csswg-drafts#1393]
Mike Day of PrinceXML [suggested](http://www.princexml.com/forum/topic/3665/wrapping-text-in-page) that a page margin box which represents the entire page body would be quite useful for watermarks or other page overlays.

**Comment by dauwhe** [comment]
Prince has now implemented a prince-overlay page region:

```css
@page {
  @prince-overlay {
    content: "WATERMARK";
    font-size: 300%;
    transform: rotate(-30deg)
  }
}
```

**Comment by frivoal** [comment]
Should that be a magically always on top thing, regardless of what the actual content of the page does in terms of z-indexing, 3d transforming, outlines, and so on?

**Comment by dauwhe** [comment]
I don't think so. We often set watermarks underneath some layers. But author control would be useful.

**Comment by faceless2** [comment]
We've had this functionality in our Report Generator for years, and it's popular - mostly for stamping "confidential" or "draft" on things.

If there were two layers - "underlay" or "background" (behind any content but above the page background), and "overlay" (on top of all content)- that would cover the two obvious cases, and implementing both is no harder than implementing one. I'm not sure any other form of interleaving with document content would be possible (injecting things into layers containing transforms and z-index?) or desirable.

The underlay option would effectively be creating another background layer, above any background on the @page (which includes those propagated from the root or HTML body).
```css
@page {
    @underlay {
         content: counter(page);
         font-size: 80vh;
         text-align: center;
    }
}
```
