### ISSUE TITLE
[Cascade / Pseudo-elements / Values / Fragmentation] currentColor when fragments have differents colors

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1510]
[CSS Color](https://drafts.csswg.org/css-color/#currentcolor-color) says

> The keyword `currentcolor` represents value of the color property on the same element.

But what if different fragments of that element have different colors? This is possible with `::first-line`.

<details> 
  <summary>Example: <a href="https://jsfiddle.net/ehzknab5/2/">https://jsfiddle.net/ehzknab5/2/</a></summary>

```html
<div><span>Lorem ipsum<br />dolor amet.</span></div>
<div><span>Lorem ipsum.</span></div>
```

```css
div {
  color: red;
}
div::first-line {
  color: green;
}
br {
  line-height: 0;
}
span {
  box-decoration-break: clone;
  -webkit-box-decoration-break: clone;
  line-height: 50px;
  background-image: linear-gradient(currentcolor, currentcolor);
  background-color: currentColor;
  background-size: 100% 75%;
  background-repeat: no-repeat;
  border: 5px solid currentColor;
  outline: 5px solid currentColor;
  box-shadow: 111px 0 5px currentColor;
  text-shadow: 222px 0 2px currentColor;
  filter: drop-shadow(333px 0 0 currentColor);
}
```
</details>

<br />

Firefox:

![firefox](https://user-images.githubusercontent.com/7477678/26946962-4c4de726-4c91-11e7-8a69-f28028a875ef.png)

Chrome:

![chrome](https://user-images.githubusercontent.com/7477678/26946319-20fbb384-4c8f-11e7-82cb-cdec1124d2dc.png)

Edge:

![edge](https://user-images.githubusercontent.com/7477678/26946320-20feafc6-4c8f-11e7-9541-b62d5d6c64c8.png)
