### ISSUE TITLE
[selectors] pseudo selector to match forms ValidityState

### ISSUE THREAD

**Issue by jimmywarting** [w3c/csswg-drafts#1525]
## The Problem
When I did put a pattern to one of my form elment, it yields a tooltip saying "Enter a correct pattern"
The browser don't do a good job at displaying the correct pattern to use. So i need a way to inform them how the field should be written (look like)

```html
<input 
  type="text"
  name="username"
  minlength="2"
  maxlength="20"
  required
  pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}$"
/>
```

## The solution
I would want it to behave a little like angular´s ngMessage, see [demo](https://docs.angularjs.org/api/ngMessages/directive/ngMessages#example)

Say you got custom errors like this:
```html
<input ...>
<div class="required">Username is required</div>
<div class="minlength">Username is too short</div>
<div class="maxlength">Username is too long</div>
<div class="pattern">Use only letters and numbers</div>
```

Now to style the right error message green or red, show or hide. I would want to use the same properties that exist on the constraints object `input.validity` (ValidityState)

```js
ValidityState {
  badInput, patternMismatch, rangeOverflow, rangeUnderflow
  stepMismatch, tooLong, tooShort, typeMismatch, valueMissing
}
```

```css
input:valueMissing ~ .required {display: block}
input:tooShort ~ .minlength {display: block}
input:tooLong ~ .maxlength {display: block}
input:patternMismatch ~ .pattern {display: block}
```

**Comment by SebastianZ** [comment]
This is covered by the [`:invalid` pseudo-class](https://drafts.csswg.org/selectors/#validity-pseudos).

Sebastian

**Comment by jimmywarting** [comment]
the `:invalid` is to general.

**Comment by SebastianZ** [comment]
I see. And you're right, there doesn't seem to be more fine grained matching of invalidity except the [`:out-of-range` pseudo-class](https://drafts.csswg.org/selectors/#out-of-range-pseudo).

Note that CSS uses hyphen-separated syntax, not camel case. So, your proposal should rather look like this:

```css
input:value-missing ~ .required { display: block; }
input:too-short ~ .minlength { display: block; }
input:too-long ~ .maxlength { display: block; }
input:pattern-mismatch ~ .pattern { display: block; }
```

Another way would be to allow parameters for the `:invalid` pseudo-class. That would group the different error types. I.e. this could then look like:

```css
input:invalid(value-missing) ~ .required { display: block; }
input:invalid(too-short) ~ .minlength { display: block; }
input:invalid(too-long) ~ .maxlength { display: block; }
input:invalid(pattern-mismatch) ~ .pattern { display: block; }
input:invalid(out-of-range) ~ .outofrange { display: block; }
```

which would allow to match different types of errors by allowing to provide multiple keywords:

```css
input:invalid(too-short, too-long) ~ .invalidlength { display: block; }
```

Furthermore, for empty inputs there is already issue #1283. So empty inputs requiring a value could then also be matched via `input:required:empty`. Though an explicit way to check whether a required field is missing the value is probably nicer and more consistent to the other proposed pseudo-classes.

Sebastian
