### ISSUE TITLE
[css-cascade] What happens when you animate the all property?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#1566]
Right now it doesn't work in any browser. Is that a bug? Should we spec it that way? (just curious)

https://wptest.center/#/hku8b7
```css
div {
	color: red;
	animation: x 3s infinite alternate;
}
@keyframes x {
	to {
		all: initial !important; /*color:black*/
		font-weight: bold;
		background: yellow;
	}
}
```
