### ISSUE TITLE
[css-selectors] :style() - detecting css tags

### ISSUE THREAD

**Issue by Nokel81** [w3c/csswg-drafts#1675]
It is sometimes quite useful to style based on style. This selector would be able to match styles of a given element.

Example:
`div:style(display: flex) { }`
Would match all `div`s that are flex boxes. Choosing by display type seems to me to be the most useful but I have generalized it to be able to be used for other selections

**Comment by FremyCompany** [comment]
This is unfortunately a class of problems that cannot be solved reasonably in web browsers.

Take for instance a look at issue #1675

**Comment by astearns** [comment]
@FremyCompany I expect you meant to link to some other issue

**Comment by FremyCompany** [comment]
Ahahah yes, sorry :)

#1656

**Comment by Nokel81** [comment]
You could disallow any properties that were used for selection.

Allowed:
```css
div:style(display: flex) {
    background-color: grey;
}
```

NotAllowed (Ignored):
```css
div:style(display: flex) {
    display: grid;
}
```
