### ISSUE TITLE
[css-ui]Spec for cursor during selection?

### ISSUE THREAD

**Issue by EiraGe** [w3c/csswg-drafts#1691]
Is there spec about cursor change during selection (Like over link)? @frivoal 
This seems cannot achievable by UA stylesheet.

**Comment by frivoal** [comment]
You can do it with
```css
:any-link {
  cursor: pointer;
}
```
or, if you are in a browser that does not support `:any-link`, with:
```css
:link, :visited {
  cursor: pointer;
}
```
