### ISSUE TITLE
Please add "tab-index" to CSS specification

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#1748]
The needed specification:
`tab-index: <numeric-signed> | none | inherit | unset; `
If -1 or lower, the element is focusable by mouse/touch but not TAB key.
If 0, the element has default tab order and is focusable by mouse/touch.
If greater than 0, the number precise order in tab queue due to ascending values.
if "none" the element is not focusable by keyboard and not focusable via touch/mouse. 

Reason:
The CSS including floating, position absolute, fixed and relative can change the visual order of elements, The developer shall have a tool to set appropriate TAB order for all elements. Additionally if any "modal" dialog "window" will be shown via CSS (it is possible!), here shall be possibility to disable tab-index (via "-1" value) in the background without changes in markup (HTML). 

If it is needed, I can send my private (commercial) solutions for "modal" dialog "windows" that are using only HTML5 and CSS without any scripts. It is real requirement. 

On the Stack Overflow you also can find questions how to disable element via CSS or how to change tabindex by CSS only. 

BTW. Opera from 11.5 to 12 implemented this style as nav-index partially. Thus the name may also be: nav-index instead of tab-index. 

Redirected from html thread: https://github.com/whatwg/html/issues/2953

**Comment by Nadya678** [comment]
Default value:
```
*
{
   tab-index: none;
}
input, textarea, a, button /* ... and other focusable by default */
{
   tab-index: 0;
}
[tabindex]
{
   tab-index: attr( tabindex );
}
```

**Comment by frivoal** [comment]
I agree that there is a need for controling the tabing order. As you said, layout can change the visual order of things. Often, it is still better to keep the tab order in the logical document order, but sometimes it is useful to reorder.

Since it depends on layout, I agree it should be done in css.

However, I don't think `tab-index` / `nav-index` is the right solution: the index is global to the page, so you need to be aware of all elements on the page to pick your number correctly, which is a huge pain. Its's been proposed before, and was removed as people (including browsers vendors) did not like that solution.

But that doesn't mean we don't need a solution. We do.

An alternative has been discussed, but not yet specified: `nav-next` and `nav-pre`. They would work with the same syntax as `nav-up`, `nav-down`, `nav-left`, and `nav-right` (see https://drafts.csswg.org/css-ui-4/#nav-dir).

This also allows you to reorder elements for tab navigation, but instead of needing to figure out a global order in your page, you can simply change the order locally. Specifying this is in my todo list.

It is used differently than `tab-index` / `nav-index` so it may take some time to get used to, but I hope that ends up being more usable and useful.

I understand it may be a little hard to evaluate without a full specification, but if you understand the idea, I'd appreciate your feedback about whether this seems like it would solve your use case, or whether you think it would have issues.

**Comment by Nadya678** [comment]
Browsers correctly recognize tab-index="100" for many elements. They are tabbed then in the order of tags (after all other) elements. But tab-index can be also defined like "z-index" (similar behaviour) but then... the default value cannot be coded as CSS (like above) - local mode. 

The tab-index is supported by all browsers identically except of firefox for input[type="radio"] if all are unchecked. Firefox tabs via all unchecked radio's, other browsers tabs only via first of group. 

Thus this behaviour is the easiest to implement. 
Ascending order - I used this term on purpose. We can treat [1, 2, 4, 8, 100, 105] as ascending and [1, 2, 2, 2, 3, 4, 5, 5, 5] also. Maybe "not descending order" will be more correct phrase?

My description can be updated by other users. I poorly speak english. 

Nav-pre, nav-next (if there will be identifiers) can make infinite loop and trigger developers to "id-itis" ("id"-like div-itis/class-itis).  

BTW. I tkink, the tab-index will by used mainly for elements with set "tabindex" property and form controls. In this purpose, here is a little elements for styling and developer for each skin (layout) can define it if it is possible. 

If other solution is better, it also can be implemented instead this, but Opera (Presto, before WebKit) has implemented this algorithm (except "none"). Currently tab order in many layouts is chaotic and there is possible to access controls that should by inaccessible. It is more needed than pointer-events. Disabling of elements (for mouse and touch only) can be reached via negative z-index and additional layer (via ::after or ::before) on other element. 

Does new-pre/next is able to disable any element from tab-queue?

**Comment by jihyerish** [comment]
I think `nav-pre`/`nav-next` is better design than `nav-index`.

For example, there are button elements like:
```html
<button id="b1">Button 1</button>
<button id="b2">Button 2</button>
<button id="b3">Button 3</button>
<button id="b4">Button 4</button>
<button id="b5">Button 5</button>
```
if the tabing order is specified with [nav-index](https://www.w3.org/TR/2012/WD-css3-ui-20120117/#nav-index0), it will be: 
```css
button {
    position: absolute;
}
button#b1 {
    top: 20%; left: 25%;
    nav-index: 1;
}
button#b2 {
    top: 30%; left: 0%;
    nav-index: 2;
}
button#b3 {
    top: 50%; left: 40%;
    nav-index: 3;
}
button#b4 {
    top: 60%; left: 25%;
    nav-index: 4;
}
button#b5 {
    top: 70%; left: 20%;
    nav-index: 5;
}
```
otherwise, the same result using `nav-pre` & `nav-next` is: 
```css
button {
    position: absolute;
}
button#b1 {
    top: 20%; left: 25%;
    nav-next: #b2;
}
button#b2 {
    top: 30%; left: 0%;
    nav-prev: #b1;
    nav-next: #b3;
}
button#b3 {
    top: 50%; left: 40%;
    nav-prev: #b2;
    nav-next: #b4;
}
button#b4 {
    top: 60%; left: 25%;
    nav-prev: #b3;
    nav-next: #b5;
}
button#b5 {
    top: 70%; left: 20%;
    nav-prev: #b4;
}
```
If I want to add a new button element(`#new`) and make it have a tab order between the button `#b2` and the button `#b3`, I have to modify the tab order of all the next button element after the button `#new` when using 'nav-index'.  
But when using `nav-pre` & `nav-next`, I need to modify the tab order the very previous and  next button of the button `#new`. This way is easier to use.

> Regarding nav-up, nav-right, nav-down, nav-left - it is good idea for table DATA layouts (like online emulation of MS Excel) but... it generates id-itis. All elements need to have "id". Is there possibility to avoid of it (too many id's)?

I think we can just give the direction to find the previous or the next element to `nav-pre` or `nav-next`. So the previous or the next element will be the closest element in the direction.
For example, the value type can be [ray(
)](https://www.w3.org/TR/motion-1/#offset-path-ray) that specifies the straight line with an angle starting from the element. 
`nav-next: ray(45%)` means the next element is the closest element which is at 45 degree angle from the current element.

**Comment by SebastianZ** [comment]
@jihyerish Your example can be handled without defining any order, as the default order is how the elements appear in the DOM.

So, a better example is when you want to toggle through them in a different order. E.g. let's say we want the order to be `#b1`, `#b3`, `#b5`, `#b2`, `#b4`, then the CSS would look like this:

```css
button#b1 {
  nav-index: 1;
}
button#b2 {
  nav-index: 4;
}
button#b3 {
  nav-index: 2;
}
button#b4 {
  nav-index: 5;
}
button#b5 {
  nav-index: 3;
}
```

vs.

```css
button#b1 {
  nav-next: #b3;
}
button#b2 {
  nav-pre: #b5;
  nav-next: #b4;
}
button#b3 {
  nav-pre: #b1;
  nav-next: #b5;
}
button#b4 {
  nav-pre: #b2;
}
button#b5 {
  nav-pre: #b3;
  nav-next: #b2;
}
```

> If I want to add a new button element(#new) and make it have a tab order between the button #b2 and the button #b3, I have to modify the tab order of all the next button element after the button #new when using 'nav-index'.

That's probably the biggest disadvantage of having an absolute index property. One big advantage is that it corresponds to the `tabindex` HTML attribute.

> But when using nav-pre & nav-next, I need to modify the tab order the very previous and next button of the button #new. This way is easier to use.

As it probably doesn't make sense to specify two different navigation paths for forward and backward, I think only `nav-next` is needed. Applied to the example above this would then be:

```css
button#b1 {
  nav-next: #b3;
}
button#b2 {
  nav-next: #b4;
}
button#b3 {
  nav-next: #b5;
}
button#b5 {
  nav-next: #b2;
}
```

And the backward navigation is automatically inferred from the forward navigation.

>> Regarding nav-up, nav-right, nav-down, nav-left - it is good idea for table DATA layouts (like online emulation of MS Excel) but... it generates id-itis. All elements need to have "id". Is there possibility to avoid of it (too many id's)?
>
> I think we can just give the direction to find the previous or the next element to nav-pre or nav-next. So the previous or the next element will be the closest element in the direction.
For example, the value type can be ray() that specifies the straight line with an angle starting from the element.
nav-next: ray(45%) means that the next element is the closest element which is at 45 degree angle from the current element.

In my opinion, navigation should initially have specified that way, i.e. regarding the visual placement of the element for the default navigation order.

Your idea sounds quite interesting, though I'm not sure whether that's feasible. It requires people to calculate the angle between the elements to get the right order. What if there's no element in that direction?

In regard of my previous sentence, what about introducing a property that allows to specify a visual navigation order? E.g.:

```css
nav-order: strutural | visual;
```

With `visual` just doing The Right Thing™ regarding writing mode.

Having said that, this might be introduced additionally to any explicit way to set a navigation index.

Sebastian
