### ISSUE TITLE
[mediaqueries-5] Example for `inverted-colors` seems to be a no-op

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#1756]
The example:

```css
@media (inverted-colors) {
  img { filter: invert(100%); }
  * { text-shadow: none; box-shadow: none; }
}
```

Source: https://drafts.csswg.org/mediaqueries-5/#inverted

***

If I understand correctly, the purpose of the second style rule is to revert all the text and box shadows that are used on the page. However, due to the low specificity of the `*` selector, this revert will never apply. For example:

```css
h1 {
  text-shadow: 1px 1px 0 gray;
}

* {
  text-shadow: none;
}
```

Here, the second rule is a no-op. If its purpose is to revert the first rule, then `!important` is needed, I think.

**Comment by frivoal** [comment]
Nice catch, thanks. Fixed now.

**Comment by simevidas** [comment]
@frivoal I think, you missed one. It should be:

```css
* {
  text-shadow: none !important;
  box-shadow: none !important;
}
```
