### ISSUE TITLE
[css-ui] Add a property controlling the navigation order

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#1764]
As explained in https://github.com/w3c/csswg-drafts/issues/1748#issuecomment-324283133, the tab order is currently defined by the [element order within the DOM](https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation).

If elements are placed in a different visual order, e.g. via `display: flex; flex-direction:row-reverse;`, then the order may not make sense.

Therefore, there should be a property that allows you to control the general navigation order within a container to focus the elements in visual order, like

```css
nav-order: strutural | visual;
```

where `structural` is the default value (behavior the same as defined in the HTML spec.), while `visual` creates a default navigation order following the visual placement of the ancestor elements considering the writing mode, i.e. for LTR languages the order would be from left to right, for RTL languages from right to left.

Sebastian

**Comment by Crissov** [comment]
There are mixed types that make sense, too, and I think they could be achieved easily with this proposed property by exploiting the cascade appropriately. 

However, in many documents you encounter different structural hierarchic levels of navigation and it would be awesome if this property or a companion could control that as well. Imagine a simple textual document where the user can navigate from heading to heading: sometimes it makes sense to cycle through all headings of the current level and sometimes it makes sense to just go to the next heading whichever its level.

```` css
section {nav-order: structural shallow;} /* h1:first-of-type -> h1:nth-of-type(...) -> h1:last-of-type -> h1:first-of-type ... */
section :not(h1):focus {nav-order: structural deep;} /* does that make sense? */

form {nav-order: structural deep;} /* form>fieldset -> fieldset>label>input -> ... -> form>fieldset ... */
````

**Comment by Loirooriol** [comment]
How is the visual order defined for abspos elements? Would it use inset properties or something?

**Comment by Nadya678** [comment]
Not only absolute positioning. How is the "visual" algorithm for... fixed positioning elements. This bug also has "ray()" proposition.

**Comment by jihyerish** [comment]
Having the `visual` value is useful, but some cases must be considered when defining the visual order. 
For example, like below:

```css
button {
    position: absolute;
    nav-order: visual;
}
button#b1 {
    top: 60px;
    width: 80px;
    height: 80px;
}
button#b2 {
    top: 10px; left: 100px;
    width: 80px;
    height: 40px;
}
button#b3 {
    top: 70px; left: 120px;
    width: 70px;
    height: 40px;
}
```

which object would be the next order after `#b1`?

**Comment by jihyerish** [comment]
For defining the visual order, the value could be like: 

```css
nav-order: strutural | row | row-reverse | column | column-reverse
```
`row`, `row-reverse`, `column`, `column-reverse` are also used in [flex-direction](https://www.w3.org/TR/css-flexbox-1/#propdef-flex-direction).
Those can be combined well with the writing mode, as defined [here](https://www.w3.org/TR/css-flexbox-1/#axis-mapping).

**Comment by SebastianZ** [comment]
Regarding absolutely positioned elements, the order still depends on their actual visual position within the document. So, regarding your example, in an LTR context the order would be `#b2`, `#b1`, `#b3`.
But note, the `nav-order` is **expected to be set on the container**, not the items.

For fixed positioned or sticky elements I can imagine different options:

1. Visual order
2. Structural order
3. First in order
4. Last in order 

As a user I'd probably still expect to access them in visual order. To be clear, I define the visual order as the initial placement of the elements within the document before scrolling.
So, e.g. having a fixed header with a search field and login fields and scrolling down the page would focus those fields before other elements further down the document.

I'm not sure whether there's a need for allowing to change the navigation direction via the Flexbox keywords, because the elements may not be aligned in rows or columns, as your example shows. Especially `row-reverse` and `column-reverse` don't make sense in this context, in my opinion.
But I may just miss the use case here.

Sebastian

**Comment by SebastianZ** [comment]
The idea having `shallow` and `deep` keywords sounds interesting, though the `nav-order` property is not meant to define, which elements are focusable. It just defines the default navigation order for the focusable elements.

This is why I split this idea from issue #1748.

Sebastian

**Comment by jihyerish** [comment]
I wonder "visual" value can cover all the factors which affect the visual order.
The factors would be: 
- Absolute positioning
- Fixed positioning
- Sticky positioning
- Float positioning
- Flexbox layout
`flex-direction: row | row-reverse | column | column-reverse`
`order: < number >`
- Grid layout
- Writing mode (text can be focusable with 'tabindex')

Also, the navigation order is affected by the value of 'tabindex' and it isn't always the same with the document order nor visual order.
The `strutural` value considers the order by 'tabindex' attribute?

**Comment by SebastianZ** [comment]
> I think `visual` value would be nice, but wonder it can cover all the factors which affect the visual order.
> The factors would be:
> 
> * Absolute positioning
> * Fixed positioning
> * Sticky positioning
> * Float positioning
> * Flexbox layout
>    `flex-direction: row | row-reverse | column | column-reverse`
>    `order: < number >`
> * Grid layout
> * [writing-mode](https://drafts.csswg.org/css-writing-modes-3/#block-flow) (text can be focusable with 'tabindex')

Thank you for pointing this out again! As I [wrote earlier](https://github.com/w3c/csswg-drafts/issues/1764#issuecomment-326274118), absolute, fixed, sticky and float positioning can easily be handled regarding the visual order. It may also apply to Flexbox, Grid Layout and the writing mode, though that needs to be discussed.

Could be that it needs to be renamed to `logical`, or `logical` needs to be introduced as a third option, so it can be defined to follow the most expected order.

> Also, the navigation order is affected by the value of 'tabindex' and it isn't always the same with the document order nor visual order.
> The `structural` value considers the order by 'tabindex' attribute?

The `nav-order` property only defines the **default** navigation order. It can be overwritten for individual elements via the `tabindex` attribute, the `nav-index` property suggested in #1748, or other properties like the `nav-up`/`nav-right`/`nav-down`/`nav-left` properties [defined in CSS UI 4](https://drafts.csswg.org/css-ui-4/#nav-dir).

Short example:

```html
<form id="myform">
  <input id="firstname"/>
  <input id="lastname"/>
  <input id="dateofbirth" type="date"/>
  <input id="city"/>
</form>
```

```css
#myform {
  display: flex;
  flex-direction: row-reverse;
  nav-order: visual;
}
```

This would result in the order to be `#city`, `#dateofbirth`, `#lastname`, `#firstname` for LTR writing modes.

```css
#myform {
  display: flex;
  nav-order: visual;
}

#firstname { order: 2; }
#lastname { order: 4; }
#dateofbirth { order: 1; }
#city { order: 3; }
```

⇒ `#dateofbirth`, `#firstname`, `#city`, `#lastname` (as that's the visual order).

Sebastian

**Comment by jihyerish** [comment]
> Short example:

Nice example! How about for the Grid layout?
For example, there is a sample like this:

```html
<div id="grid">
  <div id="section1">
    <button id="btn1">Button</button>
    <button id="btn2">Button</button>
  </div>
  <div id="section2">
    <button id="btn3">Button</button>
    <button id="btn4">Button</button>
    </button>
  </div>
  <div id="section3">
    <button id="btn5">Button</button>
    <button id="btn6">Button</button>
</div>

```
```css
#grid {
  display: grid;
  grid-gap: 20px;
  grid-template-columns: 200px 200px;
  grid-template-rows: 200px 200px;
}

#section1 {
  grid-column: 1 / 3;
}

#section2 {
  grid-column: 2;
 grid-row: 2;
}

#section3 {
  grid-column: 1 ;
  grid-row: 2;
}
```
The DOM order (structural order) is `#btn1`, `#btn2`, `#btn3`, `#btn4`, `#btn5`, `#btn6` and it is the default tab order. You can see how it works[ here](https://jihyerish.github.io/focus-grid/).
Is it right that if `nav-order: visual` is given to `#grid`, then the tab order is changed to `#btn1`, `#btn2`, `#btn5`, `#btn3`, `#btn6`, `#btn4`?
