### ISSUE TITLE
[css-ui-4] none value for nav-up, nav-right, nav-down, nav-left properties

### ISSUE THREAD

**Issue by jihyerish** [w3c/csswg-drafts#1822]
It would be nice to add `none` value for disabling the directional navigation.
 
The directional focus navigation properties, `nav-up`, `nav-right`, `nav-down`, `nav-left` can be used for the responsive grid layout.
In this case, the specified directional navigation needs to be changed, or be disabled.
 
For example, here is a grid layout like this in a wide screen:
![image](https://user-images.githubusercontent.com/6636090/30529289-ef5b44f6-9c76-11e7-972f-6e56dd5edb38.png)

and it will change in the mobile as:
 
![image](https://user-images.githubusercontent.com/6636090/30529290-f0fba4f4-9c76-11e7-88b1-d84d5dc65076.png)

`#content` is specified as:
```css
#content {
  nav-right: #menu;
  nav-up: #header;
  nav-down: #footer;
}
 
@media only screen and (max-width: 750px) {
  #content {
    nav-up: #menu;
    nav-down: #footer;
  }
}
```
 
But, in the mobile, it won't have the focus navigation to the right. 
If `#menu` is given to `nav-right`, it may be an unintentional navigation.
The directional focus navigation would be changed to disable the right-side focus navigation:
```css
#content {
  nav-right: #menu;
  nav-up: #header;
  nav-down: #footer;
}
 
@media only screen and (max-width: 750px) {
  #content {
    nav-right: none;
    nav-up: #menu;
    nav-down: #footer;
  }
}
```
