### ISSUE TITLE
[css-values] Function to retrieve index of element among siblings, or counter on element as integer

### ISSUE THREAD

**Issue by Nokel81** [w3c/csswg-drafts#1869]
Currently you can write the following with the `:nth-child` or similar style selectors
```css
.foobar>*:nth-child(2n) {
    background-color: lime;
}
```

Which means that every second child has a background colour of lime. However you cannot do something like the following:

```css
.foobar {
    display: grid;
    grid-template-columns: 100px 1fr;
}
.foobar>*:nth-child(2n) {
    grid-column: 1/2;
    grid-row: n;
}
.foobar>*:nth-child(2n+1) {
    grid-column: 2/3;
    grid-row: n;
}
```

I think that this would be very useful and would make working with grids quite a bit more easy

**Comment by tabatkins** [comment]
What would happen in:

```
.foo > :nth-child(n) > :nth-child(2n) { grid-row: n; }
```

?

**Comment by Nokel81** [comment]
The second one would overwrite the first value. A way around this would be to allow other letters besides n

**Comment by Loirooriol** [comment]
I think allowing [`counter()`](https://drafts.csswg.org/css-lists/#counter-functions) to return an integer would be a better way to address this kind of problems.

```css
.foobar {
  counter-reset: n;
}
.foobar > * {
  counter-increment: n;
  grid-row: counter(n integer);
}
```

**Comment by Nokel81** [comment]
Having not known of counters before this, that is cool. Now, yes I believe that that is a much better way of addressing this problem

**Comment by tabatkins** [comment]
An integer-returning `counter()` is definitely one way to address this. We could possibly also go with a more direct `sibling-index()` function that just returns your index in among your siblings, so you don't have to set up a counter explicitly. I can definitely see some uses for this.

If you want the index of an ancestor element to use in a further descendent, you just need to (a) register a custom property to have a `<number>` type, and (b) set the property using `sibling-index()` on that parent element. Then you can use `var()` on the descendant to fetch the value.  (You need to register the prop to get CSS to evaluate the function at the place you originally used it; an unregistered var will just preserve the function itself and resolve it on the descendant instead.)

**Comment by Loirooriol** [comment]
If a specific `sibling-index()` function is added, I guess it could also accept an argument to be consistent with the <code>of <i>S</i></code> syntax of `:nth-child()`. For example, <code>sibling-index(<i>S</i>)</code> would return the (1-based) index of the current element among its inclusive siblings that match the selector list *S*. The problem is if the element does not match *S*, then maybe return 0.

**Comment by Nokel81** [comment]
The idea of a selector as well is cool but another way to get the parent's sibling count would be `sibling-index(1p)` for the first parent

**Comment by jakearchibald** [comment]
This, along with a way to get the number of children in an element, would be really nice for staggered animations.

```css
.parent {
  --parent-children-count: children-count();
}
.parent .anim {
  /* Stagger from start to end */
  animation-delay: calc(sibling-index() * 100ms);
  /* Stagger from end to start */
  animation-delay: calc(var((--parent-children-count) - sibling-index()) * 100ms);
}
```

(@Nokel81 maybe the above shows that you don't need a special way to get values from the parent)
