### ISSUE TITLE
[css-tables] Setting order of rendering borders with border-collapse: collapse

### ISSUE THREAD

**Issue by ahtohbi4** [w3c/csswg-drafts#1870]
Currently, if you want to highlight any cell of a table with `border-collapse: collapse` by `border-color` there will get only two borders in needed color.

https://jsfiddle.net/ahtohbi4/vpkst1rf/

But if you could specify an order of rendering borders (e. g. `border-order`), we could get all borders of the highlighted cell.

```css
.highlighted-cell {
    border-order: 1;
}
```

What do you think about it?

**Comment by Loirooriol** [comment]
I don't think it's worth adding a new property which only works for collapsed tables. You can use outlines instead of borders:

```css
table {
  border-spacing: 3px;
}
th, td {
  outline: 3px solid #ccc;
}
.highlighted-cell {
  outline-color: #f30;
  position: relative;
}
```

https://jsfiddle.net/vpkst1rf/1/
