### ISSUE TITLE
[css-contain] Do scoped counters create new counters?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1887]
From [Style Containment](https://drafts.csswg.org/css-contain/#containment-style),

> For example, if `counter-increment` is scoped to an element, the first use of it within the subtree acts as if the named counter were set to 0 at the scoping element, regardless of whether the counter had been used outside the scoping element. Any increments made within the subtree have no effect on counters of the same name outside the scoping element.

But it's not much clear if a scoped `counter-increment` [creates a new counter](https://drafts.csswg.org/css-lists/#create-a-new-counter) or not.

That is, what is the expected output of

```html
<div></div>
```
```css
div {
  contain: style;
  counter-increment: n;
}
div::before {
  counter-increment: n 2;
  content: counters(n, '.');
}
```

Is it `1.2` or just `2`?
