### ISSUE TITLE
[html] Change default <sup> and <sub> styling?

### ISSUE THREAD

**Issue by domenic** [w3c/csswg-drafts#1888]
HTML [currently specifies](https://html.spec.whatwg.org/#phrasing-content-3) the following default styles for `sup` and `sub`:

```css
sub { vertical-align: sub; }
sup { vertical-align: super; }
sub, sup { line-height: normal; font-size: smaller; }
```

[In an article on web typography I just read](https://alistapart.com/article/web-typography-numerals#section3), it was pointed out that a better default styling would be

```css
sub { font-variant-position: sub; }
sup { font-variant-position: sup; }
```

Is this a change we could consider making? I thought the right people to discuss this with would be the CSSWG, thus I am here.

(One thing that might kill this idea: if this only works on fonts with a sub/sup variant built in, then it seems like it wouldn't be a good default. I wasn't clear from reading the article whether that was the case; it says "That will work fine for browsers that support OpenType", but what about on non-OpenType fonts in browsers that do support OpenType?)

**Comment by tabatkins** [comment]
Per [the spec](https://drafts.csswg.org/css-fonts/#propdef-font-variant-position), if the font doesn't support it, the UA *must* synthesize appropriately sized/aligned glyphs instead. It's not as good as native support (see the example in the spec) but it's basically equivalent to the current "size it smaller, shift it up/down" styling.

I think the CSSWG would be broadly supportive of this; compat concerns are my only doubt, but they're likely small. I can bring it up on the CSSWG call tomorrow.

**Comment by domenic** [comment]
Hooray! I take it from the Agenda+ tag this will be discussed on an upcoming call? I'm happy to write the HTML spec change and web platform tests for this if it gets agreement from implementers in the CSSWG.

**Comment by frivoal** [comment]
While that is indeed better typography, and I would be happy to switch to that if we could, I don't think this is OK in terms of compat (and semantics) because the possibility of nested sub/sup. While these are not overly common it does exist, and this style change is would induce a rendering with apparently different semantics.

Consider:
```html
2<sup>2<sup>2</sup></sup> = 16
```
This correctly, even if the typography isn't great looks like 2^2^2 = 16 with the legacy styling, but would look like 2^22=16 with the proposed change, which is wrong.

I think we can strike a good balance between good typography and good compat by combining the two, using the proposed approach for the first level, and the original one for nesting:

```css
sub { font-variant-position: sub; }
sup { font-variant-position: super; }

:matches(sub, sup) :matches(sub, sup) {  font-size: smaller; }
/* Not using :matches() on the parent in the following 2 rules is intentional,
   it would shift too much. */
sub sub { vertical-align: sub; }
sup sup { vertical-align: super; }
```

The result is better in the non nested case, and not obviously better or worse in the case of nested subs or nested sups the nested case. It does arguably become somewhat worse when instead of nesting multiple sub or multiple sup, we nest sub in sup or vice versa, but it remains understandable, and that's a pretty rare.
