### ISSUE TITLE
[css-sizing] max-width: 100% while also using width: min-content on container

### ISSUE THREAD

**Issue by o-t-w** [w3c/csswg-drafts#1927]
* please tag the issue title with the spec's shortname, like `[css-foo]`
* please link to the spec section you're talking about, or at least the spec

Using min-content to get text to wrap to the same size as an image is very helpful. However, most users also need to make sure that on small screens/mobile there is no horizontal scrolling and that the image isn't overflowing, which would normally be achieved with max-width: 100%. 
These two things do not seem to be compatible with one another. Setting max-width: 100% on the image causes min-content to stop working. Is there a solution to this?

**Comment by Loirooriol** [comment]
You can try something like https://jsfiddle.net/sm4tecns/
```css
.container {
  width: max-content;
}
.container, img {
  max-width: 100%;
}
p {
  width: 0;
  min-width: 100%;
}
```
