### ISSUE TITLE
Real sites using the `line-height-step` property

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1942]
In Paris F2F, @jetvillegas requested that he wants to see real sites using the `line-height-step` property to prove that this property is what authors want.

Several Japanese companies started creating pages in response to the request. This issue keeps track of their progress.

/cc @frivoal @FremyCompany @litherum @fantasai @astearns @dbaron @eaenet

**Comment by kojiishi** [comment]
A web developer blog:
https://blog.jxck.io/

He even wrote an article from his experience.
https://blog.jxck.io/entries/2017-10-09/css-rhythmic-sizing.html

**Comment by kojiishi** [comment]
A subscription service for web front end professional just applied the `line-height-step` to their articles.
Example: https://app.codegrid.net/entry/z-index-1

**Comment by kojiishi** [comment]
As far as I know, 5 more companies are working on, but they will not make their pages live before TPAC unfortunately.

So far the feedback is very positive. All web engineer done so far could apply it to their pages within 2-3 hours.

**Comment by kojiishi** [comment]
[A Japanese article](http://yuheiy.hatenablog.com/entry/2017/04/02/210214) saying he wants the `line-height-step` but since it's still not available, he simulated it in Sass.

**Comment by kojiishi** [comment]
[My Japanese article](https://html5experts.jp/kojii/24718/) is up. Hopefully [Google Translate](https://translate.google.com/translate?sl=ja&tl=en&js=y&prev=_t&hl=ja&ie=UTF-8&u=https%3A%2F%2Fhtml5experts.jp%2Fkojii%2F24718%2F&edit-text=) or [Bing Translate](https://www.microsofttranslator.com/bv.aspx?from=&to=en&a=https%3A%2F%2Fhtml5experts.jp%2Fkojii%2F24718%2F) can do good translation.

**Comment by kojiishi** [comment]
Two more sites are now live as the support from [KADOKAWA Corporation](https://en.wikipedia.org/wiki/Kadokawa_Corporation), one of the largest media company in Japan:

http://ascii.jp/elem/000/001/588/1588140/?topnew=1
http://weekly.ascii.jp/elem/000/000/407/407547/

These are very popular news sites.

**Comment by FremyCompany** [comment]
@kojiishi Could you include screenshots showing how the experience is improved on these sites, and how much code was written to achieve these improvements?

**Comment by kojiishi** [comment]
@FremyCompany here's screenshots of https://blog.jxck.io/ , the left is off, the right is on.

![line-height-step-jxck io-compare](https://user-images.githubusercontent.com/1274377/33320893-0ea70c80-d487-11e7-8634-e9c54b6ffc4c.png)

and copying the CSS below:
```css
@supports (line-height-step: 1px) {
  article {
    line-height: 1.5;
    --grid: 1.5em;
    line-height-step: var(--grid);
  }

  article h1,
  article h2,
  article h3,
  article h4,
  article h5,
  article h6 {
    display: inline-block;
    width: 100%;
    line-height-step: 0;
    line-height: 1.2;
    margin-bottom: 0;
  }

  article p {
    margin-top: var(--grid);
    margin-bottom: var(--grid);
  }

  article pre,
  article table {
    line-height-step: 0;
    line-height: normal;
  }
}
```
