### ISSUE TITLE
[css-images] [css-gcpm] Overloaded definitions of element()

### ISSUE THREAD

**Issue by kosek** [w3c/csswg-drafts#1981]
Hi,

I have noticed that the following two modules define element() function/notation in the completely different way:

https://www.w3.org/TR/css-images-4/#element-notation
https://www.w3.org/TR/css-gcpm-3/#funcdef-element

I see that css-images define element() for use in properties that can reference image whereas css-gcpm currently uses element() for content property. But using same function name for different purposes and with different function arguments is very confusing for CSS authors.

Each function should be named differently or their behaviour should be unified.

Jirka

**Comment by SebastianZ** [comment]
This name conflict is already filed as [issue 5 in CSS Images 4](https://drafts.csswg.org/css-images-4/#issue-1449f72e).

Sebastian

**Comment by SebastianZ** [comment]
So far I see four different solutions for this conflict:

## 1. Define running elements in HTML
Instead of CSS, [running elements](https://drafts.csswg.org/css-gcpm/#running-elements) could be defined within HTML, e.g. via a `<running>` element, as they have some associated semantic.

Doing so would allow to style them without the need for the `running()` and `element()` functions currently defined in the CSS GCPM Module.

Example:
```html
<running position="top-center">
  <h1>My awesome title</h1>
  <h2>With a great subtitle</h2>
</running>
```

```css
@page {
  @top-center { color: #808080; }
}
```

## 2. Rename the `element()` function
If defining the element outside of CSS is not an option, another solution would be to simply rename the `element()` function defined in the CSS GCPM Module. It could even be renamed to `running()`, so definition and usage would be consistent.

Example:
```css
@page {
  @top { content: running(header); }
}

h1 { position: running(header); color: #808080; }
```

## 3. Let one definition of `element()` serve both use cases
Only define `element()` once, e.g. just let it take `<id-selector>`s. This would make the `running()` function redundant, because the element would be identified by the selector instead of a custom identifier.

Example:
```css
@page {
  @top-center { content: element(#header); color: #808080; }
}
```

## 4. Define the element within the margin at-rule instead via `content`
Instead of defining the contents of the page margins via the `content` property they could be defined as value for the margin at-rule.

Examples:
```css
@page {
  @top-center #header { color: #808080; }
}
```

```css
@page {
  @top-center "My awesome title" { color: #808080; }
}
```

Sebastian
