### ISSUE TITLE
[cssom] Need to specify serialization of CSS grouping rules

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1985]
Specifically, `@media` and `@supports` rules at the moment.

For an `@media` rule like
```css
@media screen { div { color: white; } }
```
Gecko and Blink serialize it as
```css
@media screen {
  div { color: white; }
}
```
and Edge serializes it as
```css
@media screen {
	div { color: white; }
}
```

The serialization of CSS declaration block has been specified, but serialization of a CSS rule list has not.

I think the way Gecko and Blink do this makes sense for common cases, so we probably should spec that behavior.

(Note that in Firefox 57 backed by Stylo, the serialization is different, and I'm working on fixing it.)
