### ISSUE TITLE
[css-table] Please add table-span

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2014]
No equivalent of rowspan and colspan attribute.

I propose `table-span` or with value `<number>/<number>`

For example: `table-span: 2/3` will specify: two columns and three rows. Attribute active only if disaplay:table-cell.

default value:   `table-span: 1/1`

**Comment by Loirooriol** [comment]
I would love this functionality, but I think there should be an independent property for each value.

CSS Multi-column introduces [`column-span`](https://drafts.csswg.org/css-multicol/#column-span), its syntax could be extended to accept integers, and behave like HTML's `colspan` in table cells. An analogous `row-span` property could be added, this one just for table cells.

The proposed `table-span` could be a shorthand property of `column-span` and `row-span`.

**Comment by Crissov** [comment]
I agree that there should be features in a future level of the CSS Tables module that can replicate the effects of `colspan` and `rowspan` in HTML, but I believe it should work differently to honor the CSS model and enable extended use cases.

Authors should be able to specify the spatial directions a table cell 1. may, 2. should or 3. must not merge with adjacent cells.

``` css
/*
  | #a | #b |
  | #c | #d |
*/
td#a {span-right: merge;}
td#b {span-left: merge;}

td#c {span-right: merge;}
td#d {span-left: none;/* or `avoid` */}

td#a {span-bottom: auto;}
td#c {span-top: auto;}

td#b {span-bottom: merge;}
td#d {span-top: auto;}
```

In this example, cells _a_, _b_ and _d_ would be merged in a complex, non-rectangular shape that would be impossible to achieve with HTML attributes.
