### ISSUE TITLE
[css2] Browsers disagree on margin collapsing when element’s height > content

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#2171]
```html
<h1>Foo</h1>

<p>Bar</p>
```

```css
html,
body {
  margin: 0;
  padding: 0;
  min-height: 100vh;
}

h1 {
  margin-top: 0;
}
```
Live demo: https://codepen.io/simevidas/pen/XVzaPz?editors=1100

![gif](https://user-images.githubusercontent.com/716405/34641652-8b9fd002-f307-11e7-960e-f65ddc2c1e78.gif)

In Chrome, Safari, and Edge, the `<p>` element’s bottom margin collapses with `<body>`, which causes the `<html>` element to expand (to contain `<body>`’s newly-acquired margin) beyond `100vh`, which in turn causes the scroll bar to appear.

In Firefox there is no scroll bar.

Who is right? If `<body>`’s height is set to a value that is larger than its contents, should margin collapsing happen to begin with?
