### ISSUE TITLE
[css-variables] [selectors] Should custom properties work for :visited?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2263]
Should the following test-case be brown or yellow?

```css
<!doctype html>
<style>
  a {
    --foo: brown;
  }

  :visited {
    --foo: yellow;
    color: var(--foo);
  }
</style>
<a href="">Which color?</a>
```

Right now Gecko is yellow, blink / webkit are brown.
