### ISSUE TITLE
[css-cascade] !default declarations proposal

### ISSUE THREAD

**Issue by CyberAP** [w3c/csswg-drafts#2272]
`!default` declarations, opposite to `!important` declarations, could set a default property value, if it has not been set yet, or if another `!default` declaration is more specific. User agent styles should be overridden with `!default` (of course excluding ones with `!important`).

Consider this example:

```html
<body class="default-theme new-theme">
  <button>Style me!</button>
</body>
```

```css
.new-theme button {
  border: thin solid black;
}

button {
  border: 1px dotted grey !default;
}

.default-theme button {
  border: none !default;
}
```

The button would have a thin solid black border in result. Having the `!default` declaration possible would make it so much easier to do theming or reset CSS.

**Comment by Loirooriol** [comment]
I don't like `!important` very much, and this would be a similar hack. And I don't think it's necessary, because you should be able to achieve a similar behavior by using selectors with 0 specificity (#1170), e.g.

```css
:is(.default-theme button) {
  border: none; /* default */
}
```
