### ISSUE TITLE
[css-values] Trigonometric functions

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#2331]
I keep stumbling on use cases that need trigonometric functions to be solved, and I always have to resort to JS or a preprocessor for them, which is a pain. Basically almost any time you need to match two things and angles are involved.

Sadly I couldn't find most of my use cases, but here are two: 

- https://codepen.io/leaverou/pen/JpyZMO - cos, atan (via JS)
- [play.csssecrets.io/folded-corner-realistic](http://play.csssecrets.io/folded-corner-realistic) — sin, cos (precomputed)

Also the following use sqrt (precomputed), but would need trigonometry in the general case :

- [play.csssecrets.io/inner-rounding](http://play.csssecrets.io/inner-rounding)
- [play.csssecrets.io/diamond-images](http://play.csssecrets.io/diamond-images)
- [play.csssecrets.io/bevel-corners](http://play.csssecrets.io/bevel-corners)
- [play.csssecrets.io/folded-corner](http://play.csssecrets.io/folded-corner)

(credits: @MeFoDy for collecting these from my book)

What do you think? Can we make it happen?

**Comment by thebabydino** [comment]
My primary use case is for syncing rotation angles and scale factors or translation distances when I animate multiple elements such that corners/ edges match throughout the animation.

In [this demo](https://codepen.io/thebabydino/pen/JNZGwE/), I need to sync the rotation angle of the bright yellow squares and the post-skew scale factor of the orange squares. This is done by doing the trigonometric computations in the JS and then setting the values to the custom properties used in the transform.

A way to do it all from the CSS would be immensely useful.

I can try to fake it with different timing functions for rotation angles and scale factors or translation distances as I did in [this demo](https://codepen.io/thebabydino/pen/ybExWm/), but that's just hardcoding the cubic-bezier() for every case.

**Comment by Crissov** [comment]
Adding these would require a solution to enter π other than `0.5turn` etc. #309

**Comment by LeaVerou** [comment]
> Adding these would require a solution to enter π other than 0.5turn etc. #309

Um, why? (Yes, I did read the issue you linked to)

**Comment by MeFoDy** [comment]
Some awesome use cases in [presentation](http://askd.rocks/pres/css/) by @askd:
<details><summary>Triangle</summary>

```css
/* http://askd.rocks/pres/css/#triangle */
.triangle {
  position: relative;
  width: var(--w);
  height: var(--h);
  overflow: hidden;
}
.triangle::before {
  --a: arctan(var(--w) / var(--h));
  content: '';
  position: absolute;
  left: 100%;
  width: 100%;
  height: 100% / cos(var(--a));
  background: #000;
  transform-origin: 0 0;
  transform: rotate(var(--a));
}
```

</details>
<details><summary>Parallelogram</summary>

```css
/* http://askd.rocks/pres/css/#parallelogram1 */
.parallelogram {
  --w: 400;
  --h: 200;
  position: relative;
  width: calc(1px * var(--w));
  height: calc(1px * var(--h));;
}
.parallelogram::before {
  --angle: arcsin(var(--h) / var(--w));
  content: '';
  position: absolute;
  width: calc(100% - 100% * var(--h) / var(--w) * tan(var(--angle)));
  height: 100%;
  transform-origin: 0 100%;
  transform: skew(calc(0 - var(--angle)));
  background: #000;
}
```
</details>

<details><summary>Diagonal background animation inside the button</summary>

```css
/* http://askd.rocks/pres/css/#example1 */
.button {
  --h: 4em;
  height: var(--h);
  padding: 0 calc(var(--h) * tan(32deg));
  font-size: 40px;
  line-height: var(--h);
  overflow: hidden;
  text-align: left;
}
```

</details>
