### ISSUE TITLE
[css-contain] Scoping of the content property unclear.

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#2483]
As discussed in a side conversation in #1887, the description of how the `content` property is scoped for the purpose of style containment is unclear:
* ` content` is "scoped (for the purpose of open-quote/etc values)". "etc" is unclear
*  `content` but then content can read counter values from ancestors. So it doesn't really act as the root.

**Comment by Loirooriol** [comment]
Clarify what exactly is included in 'etc' and also add some example, e.g.

```html
<div><span></span></div>
```
```css
div {
  quotes: "«" "»" "<" ">";
}
div::before, span::before {
  content: open-quote;
}
div::after {
  content: close-quote;
}
span {
  contain: style;
}
```

If I understand properly, it should produce `««»`.

**Comment by frivoal** [comment]
I agree. To better describe that effect, I suspect changing the spec from:

> Giving an element style containment has the following effect:
> 
> 1.    The counter-increment, counter-set, and content (for the purpose of open-quote/etc values) properties must be scoped to the element’s sub-tree.
>
> [...]
>
> When scoped, the counter-set and counter-increment create a new counter.

to

> Giving an element style containment has the following effect:
> 
>  1. The `counter-increment` and `counter-set` properties must be scoped to the element’s sub-tree, and create a new counter.
> 2. The effects of the `content` property's `open-quote`, `close-quote`, `no-open-quote` and `no-close-quote` must be scoped to the element’s sub-tree: the depth of quote nesting in the subtree starts at 0 regardless of its value outside the subtree, and changes to the depth of quote nesting by these values inside the subtree do not affect the depth of quote nesting outside the subtree.

**Comment by Loirooriol** [comment]
OK! Also consider this generalization of the example in the spec:

```html
<div></div>
```
```css
div {
  contain: style;
  counter-increment: n;
}
div::before, div::after {
  content: counters(n, '.') ", ";
}
div::after {
  counter-increment: n 2;
}
```

When `content` refers to a counter which does not exist, a new counter is created (#2348).

So what happens if you use `counter()` or `counters()` inside a scoped subtree, and the counter does not exist in the subtree, but does exist in some ancestor?

I think creating a new counter seems more consistent with scoped `counter-increment` and `counter-set`. But since this is a read-only operation, it may not be necessary.

So should the example produce `1.0, 1.2,` or `1, 1.2,`? Chrome renders `0, 2,`.
