### ISSUE TITLE
[css-variables] Fallback lists for color properties

### ISSUE THREAD

**Issue by henrikhelmers** [w3c/csswg-drafts#2618]
https://drafts.csswg.org/css-color/
https://drafts.csswg.org/css-backgrounds/#background-color
https://drafts.csswg.org/css-backgrounds/#border-color
https://www.w3.org/TR/fill-stroke-3/#fill-color
https://www.w3.org/TR/fill-stroke-3/#stroke-color

With the addition of CSS variables I often end up in situations where a color is not available. The variables are generated with JavaScript. To inform CSS that the color variable is available there I am adding class names.

If CSS colors could be specified with a fallback the classname juggling could be avoided and code would be more precise.

**New functionality:**
```
.bg {
  background-color: var(--customBackground), hotpink;
}

```

**Current situation:**
```
.bg {
  background-color: hotpink;
}
.hasCustomBackground .bg {
  background-color: var(--customBackground);
}
```

In addition to the CSS above, there is also some extra Javascript needed to handle the classnames. The code example above is very short, in practice there are often many lines (or even pages) separating the two background color declarations, making it much easier to make mistakes.

I am unsure how this could be added to background-image gradient or box-shadow syntax without complicating it.

**Comment by jonjohnjohnson** [comment]
I believe the fallback feature in the variables spec already solves your use case?
https://drafts.csswg.org/css-variables-1/#example-abd63bac

```css
/* In the component’s style: */
.component .header {
  color: var(--header-color, blue);
}
.component .text {
  color: var(--text-color, black);
}

/* In the larger application’s style: */
.component {
  --text-color: #080;
  /* header-color isn’t set,
     and so remains blue,
     the fallback value */
}
```
If this covers your request, I'm guessing you could close the issue. If not, you might want to elaborate on what's missing for your use case(s).
