### ISSUE TITLE
[css-logical] Logical properties should be animatable like the physical ones

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2751]
I don't see why this shouldn't be possible:

```css
#element {
  animation: size 1s infinite alternate;
}
@keyframes size {
  from { inline-size: 100px }
  to { inline-size: 200px }
}
```

I expect it to animate just like if I used `width`. But the [spec](https://drafts.csswg.org/css-logical/#dimension-properties) says

> Animation type: discrete

On Chrome it's effectively discrete, on Firefox it doesn't animate at all. https://jsfiddle.net/45e6okrm/

**Comment by birtles** [comment]
From memory, we began implementing this in Firefox but never finished it. It's complicated by the fact that you can also animate the `writing-mode` etc. so that part-way through the animation the mapping for the properties changes, e.g.

```css
#element {
  margin: 50px 100px;
  animation: yer 5s;
}
@keyframes yer {
  to { margin-inline-start: 200px; writing-mode: vertical-lr; }
}
```

As a result you can't just do the mapping to physical properties when you set up the animation. Instead you need to re-evaluate the mapping whenever the _animated_ value of the `writing-mode`, `direction` etc. change.
