### ISSUE TITLE
[css-variables][css-cascade] When are variables computed?

### ISSUE THREAD

**Issue by chharvey** [w3c/csswg-drafts#2793]
I’m a bit confused by [“`var()` functions are substituted at computed-value time”](https://drafts.csswg.org/css-variables/#substitute-a-var) and how it relates to inheritance.

```css
div {
  --color-accent: lime;
  --color-text: var(--color-base);
  --color-bg: var(--color-accent);
}
figure.theme-american {
  --color-base: red;
  --color-accent: blue;
}
figure.theme-irish {
  --color-base: green;
  --color-accent: orange;
}
p {
  /* isn’t --color-text: var(--color-base); inherited here? */
  /* isn’t --color-bg: var(--color-accent); inherited here? */
  color: var(--color-text);
  background-color: var(--color-bg);
}
```
```html
<div>
  <figure class="theme-american">
    <p>My text should be red, and my background should be blue.</p>
    <!-- They’re not. The text is black (inherited) and the background is lime. -->
  </figure>
</div>
```

[**CodePen**](https://codepen.io/chharvey/pen/PaOaBX)

I thought all custom properties inherit, so wouldn’t the paragraph inherit the `--color-text` and `--color-bg` properties from the div? Since it also inherits the `--color-base` and `--color-accent` from the figure, shouldn’t the color be red and the background-color be blue?

Sources:
- https://drafts.csswg.org/css-cascade/#value-stages
- https://drafts.csswg.org/css-variables/#substitute-a-var
