### ISSUE TITLE
[filters] Proposal: color-filter

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#2875]
`color-filter` is a new inherited property that modifies color values used when rendering. It's syntax is similar to the `filter` property, and defines a transform function that is applied to a color.

Example:

```css
.foo {
  color: blue;
  color-filter: invert();
}
```

This would apply a channel invert to all the colors in properties matching `.foo`. In this case the text color would render as an orangey-yellow.

The set of filters available are the same as the current `filter` property, with the exclusion of those that move pixels (i.e. drop-shadow and blur).

Notes:

- Efficient because it only applies to color values at rendering time.
- Very convenient way to do a "dark mode" version of your site.
- Applies to color values, including those in gradients.
- Leaves images and emoji untouched.
- No nasty side effects of `filter`
  - No new stacking context
  - Because it is inherited, descendants can change the value

**Comment by AmeliaBR** [comment]
>  all the colors in properties 

This seems like a dangerously vague generalization.

Also, is there any use-case other than `invert` where you'd want to apply the same filter to all CSS painting, but not to embedded media?

**Comment by tabatkins** [comment]
> This seems like a dangerously vague generalization.

Eh, I suspect it's okay to just literally state that every single `<color>` in properties on the element gets the filter applied.

> Also, is there any use-case other than invert where you'd want to apply the same filter to all CSS painting, but not to embedded media?

Yeah, this is my question too. A few other filters could make sense here, like `sepia()`, but I'm not sure you'd want to sepia the `<color>`s but not the images and emoji on the element.

**Comment by AmeliaBR** [comment]
One option might be to make sure that the color filters are available as modifiers within the color modification functions, whenever they are spec'd again.

An author could then integrate that with variables, for something like:

```css
main {
  color: filter-color(var(--text-color), var(--global-color-filter));
  background: filter-color(var(--bg-color), var(--global-color-filter));
}

:root.dark {
  --global-color-filter: invert(100%);
}
```

Much more verbose, but also much more flexible, so the effect can be targetted exactly as the author intends.
