### ISSUE TITLE
[css-nesting]The parent selector should not be placed inside the subselector

### ISSUE THREAD

**Issue by wangmeijian** [w3c/csswg-drafts#2909]
About [The Nesting At-Rule: @nest](https://tabatkins.github.io/specs/css-nesting/#at-ruledef-nest)
```css
.foo {
  color: red;
  @nest .parent & {
    color: blue;
  }
}
/* equivalent to
   .foo { color: red; }
   .parent .foo { color: blue; }
 */
```
if .parent have three child selectors ".foo",".foo2",".foo3"，I must write "@nest .parent &"  in every child selectors，this is very tedious

**Comment by tabatkins** [comment]
Yes? That is indeed what you must do. What do you think it should look like instead.

**Comment by tabatkins** [comment]
I'm not sure I understand. That seems like ordinary nesting, which you can do with just:

```
.parent {
  & .foo { color: red; }
  & .foo2 { color: yellow; }
  & .foo3 { color: blue; }
}
```

The only reason you'd need to use `@nest` is if you wanted to put the `.parent`-based styling inside of the foo/foo2/foo3 blocks, like:

```
.foo {
  ...
  @nest .parent & { color: red; }
}
.foo2 {
  ...
  @nest .parent & { color: yellow; }
}
.foo3 {
  ...
  @nest .parent & { color: blue; }
}
```

If that's the style you want, to keep all of the `.foo` styles together and separate from the `.foo2` or `.foo3` styles, then yes, you'd have to write that `.parent &` selector a few times.

But your proposal doesn't seem to do anything about that, so I'm not sure I understand what you're trying to propose.

**Comment by matthew-dean** [comment]
@tabatkins 

With your proposal, can someone write:
```less
.foo {
  @nest .parent & {
    & .foo1 { color: red; }
    & .foo2 { color: yellow; }
    & .foo3 { color: blue; }
  }
}
```
Just curious.

**Comment by tabatkins** [comment]
Yeah, sure.

**Comment by flavi1** [comment]
(Not sure if i post it in the good place. And sorry for my poor english)

It maybe less powerfull than your proposal.
I just discovered the "nest" proposal.
And i probably don't have all optimisation in mind too.
But i trust it could be more simple and easy to maintain if we just have something like that (at least in a first time).
(idea from https://github.com/flavi1/lcss)

Example
=======

Just transform this :
```
@(#parent1) {
  @(.sub1.myClass > span, .sub2.active) {
    body { color: #888; }
    @media print {
      body { color: #333; }
    }
  }
  @(.sub3) {
    code { color: red; }
  }
  code { color: blue; }
}

@(#parent) {
  .sous-style {
    display: none;
  }
}
```

To this :

```
#parent1 .sub1.myClass > span body, #parent1  .sub2.active body {
 color: #888; 
}

@media print {
#parent1 .sub1.myClass > span body, #parent1  .sub2.active body {
 color: #333; 
}


}

#parent1 .sub3 code {
 color: red; 
}

#parent1 code {
 color: blue; 
}

#parent .sous-style {
    display: none;
}

```

Think about playing with 
* css files importations "@import" 
* default variables value  "var(--my-var, defalut_val)"
* and assignement in a highter level "--my-var: assigned_val;"
And imagine all you can do with it...

https://github.com/flavi1/lcss

**Comment by tabatkins** [comment]
> ```css
> @(body aside.left, body aside.right ) {
>   . {      /* point should mean "current selector full path itself" */
>     color:red;
>   }
>   span.my-sub-span {
>     color red
>   }
> }
> ```

You can already write this in my proposal as:

```css
body aside.left, body aside.right {
  & {
    color: red;
  }
  & span.my-sub-span {
    color: red;
  }
}
```

Your second example can also be written in my proposal just fine. (I'm not going to show it rewritten, because it's long and doesn't demonstrate anything new, just more nesting.)  The only exception is that `@media` can't be nested into style rules yet, but that's a separate proposal.
