### ISSUE TITLE
[css-grid] `auto-fit` behaves like `auto-fill` if an element spans all columns or rows

### ISSUE THREAD

**Issue by pmccloghrylaing** [w3c/csswg-drafts#2956]
Spec: https://www.w3.org/TR/css-grid-1/#auto-repeat
Codepen: https://codepen.io/pmccloghrylaing/full/PBJNKG/

There doesn't appear to be a way to create `auto-fit` columns/rows in combination with an element spanning all of those columns/rows. The linked codepen is for a pure CSS tabs layout where I have attempted to use `auto-fit`.

From what I've read of the spec I'm gathering that because an element spans all columns, each column has an "in-flow grid item" so none of the columns collapse. If that's the case maybe it would be worth providing a way to remove a grid item from those calculations?

**Comment by tabatkins** [comment]
There is, kinda - if you make the element `position:absolute`, you can still use the grid-positioning properties to set it up into a particular grid area, then use `top:0`/etc to make it fill the whole grid area.  It's not counted as a grid item then. However, *because* it's not a grid item, it's also not considered when the grid layout algorithm runs, so CSS won't ensure that the tracks it crosses are large enough to fit its content.

It's not completely clear to me from your example what you were actually wanting, tho - was it that you wanted the tabs to completely fill their row, so with two tabs each was 50% of the screen, etc?

**Comment by pmccloghrylaing** [comment]
I didn't realise `position: absolute` behaved like that inside a grid, that's really helpful and solves the problem of stopping a grid item from affecting the layout. The 50% tabs is exactly what I was aiming for with that solution.

**Comment by jefferyto** [comment]
I believe I have a use-case for this. I have:

* A grid with a variable/unknown number of items
* Items have a box shadow that extend outside of the item box (box shadows of adjacent items overlap each other in the gutters)
* Want to implement a "collapsed" state where only the first two rows of items are visible

I'd like to do this using a third row as spacing, to push down hidden items and also hide their box shadow:

```css
.grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));
}

.grid.collapsed {
    grid-template-rows: auto auto 50px;
    grid-auto-rows: 0;
    margin-bottom: -50px;
    overflow: hidden;
}

.grid.collapsed::before {
    content: "";
    grid-column: 1 / -1;
    grid-row: 3;
}
```

When there are enough items to fill the first row, there are no issues (and `auto-fit` doesn't come into play). When there are not enough items to fill the first row, the `::before` pseudo-element spanning all columns causes `auto-fit` to behave like `auto-fill`, leaving a gap at the end of the row.

(I'd also be interested in any alternative ways to implement this collapsed state.)
