### ISSUE TITLE
[selectors4] ":scope" inside ":matches"-like funktions?

### ISSUE THREAD

**Issue by nuxodin** [w3c/csswg-drafts#3108]
Wouldn't it be useful in ":maches"-like functions to have a reference to the current scope?  

:matches https://www.w3.org/TR/selectors-4/#matches-pseudo  
:scope https://www.w3.org/TR/selectors-4/#scope-pseudo  

Instead of this:
```css
button.superTheme,
.superTheme button {
    color:white;
    background:black;
}
```
one could write:
```css
button:matches(.superTheme .superTheme :scope)
```

I hope I'm not writing completely stupid stuff. :)
