### ISSUE TITLE
[css-box-3] Should margin-trim apply to flex or grid containers?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3255]
Like it says on the tin. Also, which axes should it apply to? http://drafts.csswg.org/css-box-4/#margin-trim

Options are: Block axis only / Main axis only / Cross axis only / Both / Neither

**Comment by ExE-Boss** [comment]
I believe it should.

**Comment by letrastudio** [comment]
*Just some thoughts, no real conclusion :)*

My instinct is that it should apply. My main gripe with Grid is precisely how poorly it works as a progressive enhancement over elements that use margin collapsing. It can be very hard to wrangle the margins when they are not set on direct children.

My first thought was that it should apply to both axes. That way `margin-trim: all` could always be used to get a clean slate when using `gap` for spacing.

But thinking about it as simply a solution for dealing with margin collapsing in grid/flex contexts, It might make more sense to just apply it to the block axis, since margin collapsing only works in that direction.

But then wouldn't this:

```css
.grid {
  display: grid;
  margin-trim: all;
}
```

achieve the same result as:

```css
.grid {
  display: grid;
}

.grid > * {
  margin-block-start: 0;
  margin-block-end: 0;
  margin-trim: all;
}
```

So maybe `margin-trim` doesn't really *need* to apply to grid or flex containers, as it wouldn't solve any unsolvable problem 🤷‍♂️

Anyway, hope this lends some perspective, because I'd really love to see `margin-trim` implemented.
