### ISSUE TITLE
[css-backgrounds-4] Background origin for x and y axes

### ISSUE THREAD

**Issue by CyberAP** [w3c/csswg-drafts#3312]
It would be useful to have `background-origin-x` and `background-origin-y` properties, similarly to `background-position-x` and `background-position-y`.

Consider this example:

```html
<input class="with-icon">
```

```css
input
{
  padding: 20px;
}

/* old way */
.with-icon
{
  padding-left: 40px; /* icon will be placed within this left padding */
  background: no-repeat 14px 50%/auto 60% url('image.svg'); /* icon size has magic numbers */
}

/* new way */
.with-icon
{
  padding-left: 40px;
  background: no-repeat 14px 50%/auto contain url('image.svg'); /* icon size is relative to content area of the input */
  background-origin-y: content-box;
}
```

We can't use simply `background-origin` here, because the background position of the icon would we within the content boundaries of the input, and thus would require to have negative numbers.
