### ISSUE TITLE
[css-text-decor-3] text-underline-position usage in Default UA Stylesheet doesn't match its syntax

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#3441]
The syntax of `text-underline-position` is `auto | [ under || [ left | right ] ]` which means `auto` should never be combined with other values.

However, in  Appendix B: Default UA Stylesheet, we have
```css
:root:lang(ja), [lang|=ja],
:root:lang(mn), [lang|=mn],
:root:lang(ko), [lang|=ko] { text-underline-position: auto right; }
:root:lang(zh), [lang|=zh] { text-underline-position: auto left;  }
```
which doesn't match the syntax above.

One of them should be updated.
