### ISSUE TITLE
[css-env][css-conditional] Need an approach to check whether an environment variable is supported

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#3576]
Websites need to detect whether an environment variable is support in order to have special rules applied on it. It seems there is currently no way to do that.

Natively authors would just use something like
```css
@supports (padding-top: env(safe-area-inset-top)) { ... }
```
for the detection, but the only thing it checks is that `env` is supported. If you replace `safe-area-inset-top` with something else like `x`, all implementations nowadays would still happily accept it. This is problematic for future extensions.

I'm not sure whether #3285 would solve this (and breaks things like `env(x)` in `@supports`). If not, we probably need to either special-case the behavior of `env` in `@supports`, or introduce a function for it.

**Comment by emilio** [comment]
So I thought that was the purpose for the fallback value in `env()`? But maybe there's a use-case for detecting a particular environment variable?

Ideally you'd use `env(my-var, 10px)` or such.

**Comment by upsuper** [comment]
Yeah, probably fallback is enough... I need to think more about possible usecases.

**Comment by upsuper** [comment]
Okay... I cannot think of any usecase. Authors may want to specify different style when certain env is available, but conceptually I think what they would actually want would be to make the page responsive to different value of the env, which should be done with media queries, and in that case, fallback should be enough.

**Comment by fantasai** [comment]
Unlike variables, the set of supported environment variables isn't open-ended, though. Seems legit to ask about support.

**Comment by bramus** [comment]
I ran into this when trying to feature detect support for the new `safe-area-max-inset-bottom` envvar introduced in #11019.

The following check _([live demo](https://codepen.io/bramus/pen/VYwaxqW/4f856abd0eee483e5044919803848ad2))_ always passes in all browsers, because parsers support the syntax:

```css
body {
	background: red;
	@supports (x: env(safe-area-max-inset-bottom)) {
		background: green;
	}
}
```

A workaround that I found, is to default to a an unreachable value and then use a style query to check the result ([live demo](https://codepen.io/bramus/pen/pvoyVGX/2867dffa407bcc51bb33582989a89ccd)):

```css
@property --safe-area-max-inset-bottom-support {
	syntax: "<length>";
	inherits: true;
	initial-value: 0px;
}

:root {
	--safe-area-max-inset-bottom-support: env(safe-area-max-inset-bottom, -1px); /* When supported the value returned will be 0px or greater */
	--safe-area-max-inset-bottom: max(0px, var(--safe-area-max-inset-bottom-support));
}

body {
	background: green;
	@container style(--safe-area-max-inset-bottom-support: -1px) {
		background: red;
	}
}
```

This however only works in browser that support style queries, which currently excludes Firefox.

A proper solution would be needed.

---

I suggest to extend `<supports-feature>` with a `<supports-env-fn>`, like so:

```
<supports-feature> = <supports-selector-fn> | <supports-env-fn> | <supports-decl>
<supports-selector-fn> = selector( <complex-selector> )
<supports-env-fn> = env( <custom-ident> )
```

When the passed in `<custom-ident>` is one of the supported Environment Variables, the result is `true`. Otherwise it is `false`.

Example usage:

```
@supports env(safe-area-max-inset-bottom) { … }
```

WDYT @fantasai?
