### ISSUE TITLE
[css-env][mediaqueries] Support comparing value of environment variable

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#3578]
It can be useful to be able to compare value of environment variable with some fixed number, just like testing width and height. Potential usecases like one may want to use a different background image when the safe inset is different, or want some width to be aligned to certain grid lines.

We may also use this mechanism combined with custom environment variable to replace the "Script-based Custom Media Queries" mentioned in mediaqueries-5?

**Comment by UtterDonkey** [comment]
Any updates on this?

**Comment by bramus** [comment]
You can achieve this with style queries:

```css
:root {
	--size: env(safe-area-inset-bottom, -1px);
}

@container style(--size: 0px) {
	body {
		background: blue;
	}
}
```

Or using the upcoming `if()`:

```css
body {
	background: if(
		style(--size: 0px): green;
		else: initial;
	);
}
```

The one thing that is missing though, is range comparisons in style queries, for which I have filed https://github.com/w3c/csswg-drafts/issues/11759
