### ISSUE TITLE
[css-grid] What if base sizes of both auto/min-content and max-content minimums are being handled?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3621]
From https://drafts.csswg.org/css-grid/#algo-spanning-items,

> For intrinsic minimums: First increase the base size of tracks with an intrinsic min track sizing function by distributing extra space as needed to accommodate these items’ minimum contributions.

But then https://drafts.csswg.org/css-grid/#extra-space says

> If space remains after all tracks are frozen, unfreeze and continue to distribute space to the item-incurred increase of…
> - when handling base sizes of tracks with min-content or auto minimums: [...]
> - when handling base sizes of tracks with max-content minimums: [...]

What if the item spans a track with a `min-content` or `auto` minimum, and another with `max-content`, and the base sizes of both tracks are being simultaneously handled because both are intrinsic? To which tracks do you distribute space? The union of both cases? The intersection (all affected tracks if empty)? Something else?

**Comment by Loirooriol** [comment]
Firefox, Chromium and Edge are not interoperable: https://jsfiddle.net/mafd8s3o/
```css
.grid {
  display: grid;
  grid-template-columns: 200px 300px;
  grid-template-rows: max-content fit-content(0);
}
.foo {
  background: yellow;
}
.bar {
  background: cyan;
}
.baz {
  grid-area: 1 / 2 / 3 / 3;
  background: magenta;
  height: 300px;
}
```
```html
<div class="grid">
  <div class="foo">foo</div>
  <div class="bar">bar</div>
  <div class="baz">baz</div>
</div>
```
 - Firefox distributes the 300px of `.baz` equally among both rows.
 - Chromium distributes them only to the 2nd row because the 1st one doesn't have an `auto` or `min-content` min track sizing function.
 - Edge  distributes them only to the 1st row.
