### ISSUE TITLE
[css-fonts] Clarify how the computed font-size is determined for size keyword

### ISSUE THREAD

**Issue by fred-wang** [w3c/csswg-drafts#3906]
cc @emilio @rwlbuis @bkardell @bfgeek 

Spec: https://drafts.csswg.org/css-fonts-4/#font-size-prop

For example Emilio gave me this example:

      <div style="font-family: serif">Serif <div style="font-family: monospace">mono</div></div>

The first div has size 16px and the second 13px in all browsers. font-size on them is the default "medium" value. Compare with:

      <div style="font-size: 16px"><div style="font-family: serif">Serif <div style="font-family: monospace">mono</div></div></div>

Currently, the spec suggests some scale factors but maybe it should make clear that the computed font-size is determined from the computed font-family, lang, user preferences etc

**Comment by fred-wang** [comment]
(Note: This is blocking #3746 ; we need to decide how the computed font-size is calculated if in addition one of these inner divs have a script level change.)

**Comment by litherum** [comment]
WebKit [has](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/page/Settings.yaml#L71):

```yaml
defaultFontSize:
  type: int
  initial: 16
  onChange: setNeedsRecalcStyleInAllFrames
defaultFixedFontSize:
  type: int
  initial: 13
  onChange: setNeedsRecalcStyleInAllFrames
```

and [also](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/graphics/FontCascadeDescription.h#L75):

```C++
bool useFixedDefaultSize() const { return familyCount() == 1 && firstFamily() == monospaceFamily; }
```
