### ISSUE TITLE
[css4-fonts] Support 1 @font-face (1 file) providing both normal and italic font-styles

### ISSUE THREAD

**Issue by davelab6** [w3c/csswg-drafts#3908]
@nyshadhr9 pointed out today that this doesn't work as expected:

```html
<html>
  </head>
    <style>
      @font-face {
        font-family: 'Sample VF';
        font-weight: 400;
        font-style: normal;
        src: url("VfItalSlnt-Regular.ttf") format('truetype');
      }
      @font-face {
        font-family: 'Sample VF';
        font-weight: 400;
        font-style: italic;
        src: url("VfItalSlnt-Regular.ttf") format('truetype');
      }
      p1 {
        font-family: 'Sample VF', display;
        font-style: normal;
      }
      p2 {
        font-family: 'Sample VF', display;
        font-style: italic;
      }
    </style>
  </head>

<body>
  <p1>hello world</p1><br>
  <p2>hello world</p2>
</body>
</html>
```

![Screen Shot 2019-05-10 at 9 53 27 AM](https://user-images.githubusercontent.com/261579/57532357-79fc7980-7309-11e9-8fed-ff4fddb06c1b.png)

[VfItalSlnt-Regular.zip](https://github.com/w3c/csswg-drafts/files/3166802/VfItalSlnt-Regular.zip)

Perhaps rather than duplicating the `@font-face`, this should be possible:

```css
      @font-face {
        font-family: 'Sample VF';
        font-weight: 400;
        font-style: normal italic;
        src: url("VfItalSlnt-Regular.ttf") format('truetype');
      }
```
