### ISSUE TITLE
[css-fonts-4] How are duplicate "feature value blocks" treated in @font-feature-values?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3947]
If you have a single @font-feature-values rule with a duplicate "feature value block", are those blocks cascaded together or last-wins?

```css
@font-feature-values foo {
  @swash { pretty: 1; }
  @swash { cool: 2; }
}
```

Does the above let me do `font-feature-alternates: swash(pretty);` *and* `font-feature-alternates: swash(cool);`, or just `cool`?

Same question between rules, too:

```css
@font-feature-values foo {
  @swash { pretty: 1; }
}
@font-feature-values foo {
  @swash { cool: 2; }
}
```

------------

In both of these cases, I presume that they cascade together; in other words, the only duplication we look out for is in the (family, feature, name) whole tuples, at which point last-wins.
