### ISSUE TITLE
[css-transforms] Zero value in perspective() function

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#413]
Please see the discussion in the mailing list [1](https://lists.w3.org/Archives/Public/www-style/2016Apr/0059.html), [2](https://lists.w3.org/Archives/Public/www-style/2016Apr/0131.html), and also whatwg/compat#48.

In the current spec, zero is invalid for `perspective()` function and `perspective` property, which, according to Tab, violates CSS's rule of limited range. The spec should be changed to something like

> specify that there's a UA-defined minimum perspective length, and anything below that length (but not negative) is clamped to it.

**Comment by upsuper** [comment]
cc @tabatkins @smfr @grorg

**Comment by upsuper** [comment]
Note that, this change leads to interoperability issue in Firefox as shown in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1316236). Imgur uses `perspective(0)` in an animation, which leads to some rendering weirdness.

They do something like:
```css
@keyframes flipin {
  from { transform: perspective(500px) translate(-50%, 0) rotateX(-90deg) rotateY(0); }
  to { transform: perspective(0) translate(-50%, 115%) rotateX(0) rotateY(0); }
}
```

Browsers agree on the same weirdness if the value in `perspective` function is changed to `1px`. What I don't quite understand is how Blink handles this case. If I understand the spec correctly, even if it handles `perspective(0)` itself like infinite, there should still be intermediate value inserted between `500px` and `0`. Probably Blink consistently handles `0` as infinite everywhere? (But how can an infinite value be animatable?)
