### ISSUE TITLE
[css-flexbox] flex-shrink: hide

### ISSUE THREAD

**Issue by Netmosfera** [w3c/csswg-drafts#4199]
Rather than shrinking the element, CSS would just hide it.

For example a `<button>` normally containing a label and a icon, might hide the label if the `<button>` gets too small.

```
<button>
    <img src="icon.png" alt="">
    <span>Label</span>
</button>
```

```
button { display: flex; flex-direction: row; }
button > img { flex: 0 0 auto; }
button > span { flex: 1 hide auto; }
```

Thank you.

**Comment by nxtman123** [comment]
I think this is a great idea. I also think developers might want to decide in what order elements are hidden.

There could be, in addition to `flex-shrink` a new `flex-hide: [number]`.

```html
<button>
    <img src="icon.png" alt="">
    <span class="label">Label</span>
    <span class="count">3</span>
</button>
```

```css
button { display: flex; flex-direction: row; }
button > img { flex: 0 0 auto; }
.label { flex-grow: 1; flex-hide: 2; }
.count { flex-hide: 1; }
```

I don't know if the numbers should go up or down, i.e. Priority 1 stays on screen vs. No. 1 is hidden first (like this example).
