### ISSUE TITLE
[css-lists] Should list-item counter reset rule be in a UA stylesheet?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4244]
Or should it be browser-engine magic like the increment?

The TLDR is this. Gecko implements the counter reset as suggested in the appendix:

https://drafts.csswg.org/css-lists/#ua-stylesheet

Which is something like:

```css
/* Set up ol and ul so that they scope the list-item counter */
ol, ul {
  counter-reset: list-item;
}
```

So the issue with doing it at the UA stylesheet level is that pages can override it.

We've received two reports of broken lists, the first of them is fixed, the second of them is from today. So arguably not a lot of breakage, but still worth discussing, I think.

 * https://bugzilla.mozilla.org/show_bug.cgi?id=1576802
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1545746

cc @MatsPalmgren @tabatkins
