### ISSUE TITLE
[css-sizing-4] Scrollbars when intrinsic-width is > width?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4415]
What should happen with scrollbars in `overflow:auto; intrinsic-width: 200px; width: 100px;`?  

If the element was filled with 200px worth of child content, it would definitely create scrollbars. I believe intrinsic-width should do the same.

As an added bonus, this helps with some infinite-scroller cases that currently use a tall dummy element to make the scrollbar look right.

**Comment by tabatkins** [comment]
@frivoal Does anything need to be done in Overflow to make this happen? I'm unclear if overflowing happens automatically as a result of intrinsic sizes, or from something more explicit that's essentially the same thing.

**Comment by AmeliaBR** [comment]
If the `intrinsic-*` properties are intended to replace the intrinsic size from the child content in the layout calculations, then yes, it should definitely trigger scrollbars if it is larger than the box size for the parent.

But that brings up the question: Do we, in general, have a good definition of how intrinsic/extrinsic sizing, the box model, and scroll overflow work? Because if not, this would be a good time to define it.

**Comment by frivoal** [comment]
TL;DR: If you want to cause/avoid scrollbars, you need to change the actual size of then content so that it does/doesn't stick out, not the size of the (potentially) scrolling element.

----

If you have an image with 200px intrinsic width, and you set its width to 100px, then it doesn't overflow 100px anymore. By that logic, `intrinsic-width: 200px` on something that has `width: 100px` wouldn't cause overflow either: intrinsic size is what you use when you need a size but don't have a [specified/computed] one (yet). If you are given an explicit size, the intrinsic one doesn't matter, and if nothing actually sticks out, then you don't overflow.

That's consistent with the point of view of the css-overflow spec (emphasis mine):
> CSS uses the term overflow to describe the **contents** of a box that extend outside one of that box’s edges (i.e., its content edge, padding edge, border edge, or margin edge).

However, it gets more interesting/complicated when you consider the min-content size. In most layout modes, the initial value of `min-width` resolves to 0, but if you're in flexbox or grid, or if you manually set it to `min-width: min-content`, then we would force the content to adopt its assigned intrinsic width, (which is possibly larger than its natural one).

If a parent/container has overflow:auto and is limited to 100px, then we'll overflow an show scrollbars.

But you were asking about the element itself having scrollbars or not, not a container. I think if we don't do/say anything special, the above logic says that it would not. It would just be the size you gave it, and the overflowing or not would depend on the actual size of the element's **content**. And since fiddling with the element's intrinsic size doesn't do anything to the element's **content**, I think that behavior is reasonable.

A while back, @Loirooriol proposed a `::contents` pseudo element (https://github.com/w3c/csswg-drafts/issues/2406). If we had that, you could opt into the behavior you seem to want. Instead of:
```css
div {
   intrinsic-width: 200px;
   /* and maybe "min-width: min-content;" */
   width: 100px;
   overflow:auto;
}
```
you'd do
```css
div::contents {
   display: block; /*the default is display: contents; */
   intrinsic-width: 200px;
   min-width: min-content;
}
div {
   width: 100px;
   overflow:auto;
}
```

I suppose we could define something analogous to that to happen automatically for non replaced elements when you assign an `intrinsic-width`, but I think I the behavior I've described above falls out more naturally of what we already have, and that to enable the scrollbar-is-desired case,  we should give @Loirooriol 's proposal serious thoughts, because there are quite a few situations, like this one, where having this sort of general purpose magic would save us from inventing lots of special purpose magic.

I think this way of looking at it works even better if consider the other direction: assigning a smaller than natural intrinsic width a non replaced element.
```html
<div>123456789</div>
```
```css
div {
    font-family: monospace;
    intrinsic-width: 2ch;
   /* and maybe "max-width: max-content;" */
    width: 4ch;
    overflow: auto;
}
```
I don't really see what logic would cause the content to honor the intrinsic size and by fitting, causing the absence of scrollbar in that case. However, you could do something like that:
```css
div {
    font-family: monospace;
    width: 4ch;
    overflow: auto;
}
div::contents {
    display: block;
    intrinsic-width: 2ch;
    max-width: max-content;
    overflow: hidden; /* or ''overflow-wrap: break-words'',
                         or " contain: strict",
                         or some other thing to force the content
                         to actually stay within the requested max-size. */
}  
```
