### ISSUE TITLE
[css-mediaqueries] expose user left/right hand preference

### ISSUE THREAD

**Issue by nico3333fr** [w3c/csswg-drafts#4443]
Usually, an app/website design will place main CTAs at a place that can be reached easily on a smartphone using the thumb. Usually on the bottom right, however, this could be problematic for left-handed people.

![image](https://user-images.githubusercontent.com/2578321/67388069-4c924800-f598-11e9-9796-414dcfd61868.png)

![image](https://user-images.githubusercontent.com/2578321/67388114-5e73eb00-f598-11e9-9e81-3925a69fee45.png)

## Idea

It would be nice to have the possiblity to adapt websites/apps depending on left/right handed user preference `@media prefers-hand: right/left/no-preference (default)`, which would allow to easily customize interfaces.

## Example

```css
.mySuperCTA {
  position: fixed;
  right: 0;
  bottom: 0;
}

@media prefers-hand: right {
  .mySuperCTA {
    right: auto;
    left: 0;
  }
}
```

## Ressources

- https://www.smashingmagazine.com/2018/02/comprehensive-guide-to-mobile-app-design/ (also source for images)
