### ISSUE TITLE
[css-grid] Allow auto-placement to use areas

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#4457]
```css
.my-grid {
  display: grid;
  grid:
    'a b'
    'c c'
    'd d';
}
```

This above declares a simple grid.

```html
<div class="my-grid">
  <div>…</div>
  <div>…</div>
  <div>…</div>
  <div>…</div>
</div>
```

The above will auto place elements into cells of a 2x3 grid. But I'd like a way to make auto-place them into grid areas, to avoid having to write this:

```css
.my-grid > :nth-child(1) {
  grid-area: a;
}
.my-grid > :nth-child(2) {
  grid-area: b;
}
.my-grid > :nth-child(3) {
  grid-area: c;
}
.my-grid > :nth-child(4) {
  grid-area: d;
}
```

Could there be an additional value to `grid-auto-flow` that indicates that items should be flowed into areas?
