### ISSUE TITLE
[css-color] Generic Transform Function for RGB Color Spaces

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4488]
All predefined color spaces are RGB. In [prose](https://drafts.csswg.org/css-color/#predefined) and [sample code](https://drafts.csswg.org/css-color/#color-conversion-code), their transfer function into linear-light components is described quite differently, although it could be stated in a single formula with up to four parameters specific to the color space (of which only gamma γ is frequently mentioned). Can we use this abstraction – or a similar one – in the spec and leave optimization up to implementers? 

```` js
c = (C < β × δ)
  ? C ÷ δ
  : ((C − 1) ÷ α + 1) ^ γ
  ;
C = (c > β)
  ? α × c ^ γ⁻¹ − α + 1;
  : c × δ
  ;
````

| Color Space | α = _a_ + 1 | β = _K₀_/φ | γ | δ = φ |
| --- | --- | --- | --- | --- |
| Rec. 2020 | ~1.099297 | ~0.018054 | 2.4 = 12/5 | 4.5 = 9/2 |
| sRGB, P3 | 1.055 | 0.0031308 | 2.4 = 12/5 | 12.92 = 323/25 |
| ProPhoto, ROMM | 1 | 0.001953 | 1.8 = 9/5 | 16 |
| Adobe 1998 | 1 | 0 | 563/256 ≈ 2.2  | (1) |

**Comment by Crissov** [comment]
These parameters could even become descriptors in `@color-profile`, but that would be worthy of a dedicated issue.

```` css
@color-profile "rec-2020" {
  composition: rgb	0.708	0.292, 0.17	0.797,	0.131	0.046;
  white-point: D65;
  linearization: 2.4 0.018054 1.099297 4.5; /* [γ = 2 [β = 0 [α = 1 [δ = 1]]]] */
}
@color-profile "sRGB" {
  composition: rgb 0.64	0.33,	0.30	0.60,	0.15	0.06;
  white-point: D65;
  linearization: 2.4 0.0031308 1.055 12.92;
}
@color-profile "Pro-Photo" { /* ROMM */
  composition: rgb	0.7347	0.2653,	0.1596	0.8404,	0.0366	0.0001;
  white-point: D50;
  linearization: 1.8 0.001953 1 16;
}
@color-profile "A98-RGB" { /* Adobe 1998 */
  composition: rgb 0.64 0.33, 0.21 0.71, 0.15 0.06;
  white-point: D65;
  linearization: calc(563/256);
}
````
