### ISSUE TITLE
[css-lists] A way to control the gap between the marker and the text

### ISSUE THREAD

**Issue by benface** [w3c/csswg-drafts#4571]
I might be missing something obvious, but I couldn't find a way to specify the gap between a list item's marker and its text after 15 minutes of Googling (or at least one that didn't involve a hack such as wrapping the text with a `<span style="position: relative; left: -5px;">`). I actually see that there used to be a `marker-offset` property but it's been removed. Is something else coming, or is there a reason why this is missing?

**Comment by Loirooriol** [comment]
I guess there's the possibility of
```css
::marker {
  content: counter(list-item) "     ";
}
```

where you choose the number of spaces depending on the desired gap.

For more precision, maybe you can use a tabulator and control its size with `tab-size`. Currently it doesn't apply to ::marker, but you may have luck inheriting it:
```css
.list-item { tab-size: 10px }
::marker { content: counter(list-item) "\9 " }
```

If `margin` is added to the list of properties supported in ::marker, I guess you will be able to use that.
