### ISSUE TITLE
Anchor Link 

### ISSUE THREAD

**Issue by analuciabolico** [w3c/csswg-drafts#4672]
have difference between mouse arrows when **anchor link** hover with `_blank`  and normal

**Comment by emilio** [comment]
How is this different from:

```css
a[target="_blank"]:hover {
    cursor: /* whatever you want */;
}
```
