### ISSUE TITLE
[css-color-5] color-contrast() needs resolution logic if 2 or more have the same contrast

### ISSUE THREAD

**Issue by argyleink** [w3c/csswg-drafts#4732]
Spec draft
https://drafts.csswg.org/css-color-5/#colorcontrast

**Example**
```css
foo {
  --bg: hsl(200 50% 80%);
  --purple-in-hsl: hsl(300 100% 25%);
  color: color-contrast(var(--bg) hsl(200 83% 23%), purple, var(--purple-in-hsl));
}
```
verify contrast scores: [[hsl(200 83% 23%)](https://contrast-ratio.com/#hsl%28200%2083%25%2023%25%29-on-hsl%28200%2C50%25%2C80%25%29), [purple](https://contrast-ratio.com/#purple-on-hsl%28200%2C50%25%2C80%25%29), [var(--purple-in-hsl)](https://contrast-ratio.com/#hsl%28300%20100%25%2025%25%29-on-hsl%28200%2C50%25%2C80%25%29)]

Given `purple`, `hsl(200 83% 23%)`, & `hsl(300 100% 25%)` all have the same contrast with `--bg`, which wins? First match, cascade, your idea?
