### ISSUE TITLE
[css-page] [css-variables-2] Allow use of css-variables in page contexts

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#4761]
Propagating an old idea of Shinyu Murakami from the mailing list to Github issues, because I think it's the gem of a great idea. I want to make sure it's available as a starting point for discussion.

The intended goal is to allow some page-based variation of fragments, of the type commonly requested in print workflows, eg:
* switching from single column to two column after the first page
* changing border-radius values depending on whether the page was left or right
-----

Hello,

I would like to propose another approach: Use [CSS Variables](http://www.w3.org/TR/css-variables-1) with @page :left/:right.

An example:

```css
  @page :left {
    var-foo: 2em 0.5em 0.5em 2em;
  }
  @page :right {
    var-foo: 0.5em 2em 2em 0.5em;
  }
```
```html
  div {
    border-radius: var(foo);
  }
```
The problem here is that the `var(foo)` cannot refer the custom property 'var-foo' value set in the @page context according to the current spec.
We need to allow this usage, or to define another notation to refer the custom property values set in the @page context, e.g.:
```html
  div {
    border-radius: from-page-context(var-foo);
  }
```
Here the from-page-context() function retrieves the property value that the argument matches the property name, which can be custom (var-*) or normal properties, e.g.:
```css
  @page :left {
    color: blue;
    var-foo: 2em 0.5em 0.5em 2em;
  }
  @page :right {
    color: green;
    var-foo: 0.5em 2em 2em 0.5em;
  }
```
```html
  div {
    color: from-page-context(color);
    border-radius: from-page-context(var-foo);
  }
```
The concept of the from-page-context() function is similar to the `from-page-master-region()` function defined in the [XSL-FO](http://www.w3.org/TR/xsl/), although this XSL-FO's function only accepts very limited properties, and no custom properties, for now.

Regards,

Shinyu Murakami
Antenna House

**Comment by faceless2** [comment]
The reason I like this is it can be done by extending an existing, well understood part of CSS to offer a great deal of new functionality with no new syntax, and virtually no learning curve.

Simply insert the page context as an ancestor for variable inheritance after the root element. This wouldn't work for everything, of course - most obviously you couldn't expect `page: var(--page)` to inherit from the @page rule, but there are plenty of others you would consider excluding from using the page-context for inheritance (display, break-before, position spring to mind).

However, for a suitably limited list of properties, it offers great things:

```css
:root {
    --cols: 2;
}
@page :first {
    --cols: 1;
}
div {
    column-count: var(--cols);
}
```
```css
page :left {
    --radius-right: 50%;
    --radius-left: 0;
}
page :right  {
    --radius-left: 50%;
    --radius-right: 0;
}
.box {
    border-top-left-radius: --radius-left;
    border-bottom-left-radius: --radius-left;
    border-top-right-radius: --radius-right;
    border-bottom-right-radius: --radius-right;
}
```
