### ISSUE TITLE
[css-multicol] Extend 'column-width' to take multiple <length> values to support varying column sizes?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4896]
It seems like it would fairly easy to extend the [column-width](https://drafts.csswg.org/css-multicol/#cw) property to support multiple values, like so: `auto | <length [0,∞]>+`. Has this been discussed before? Would it be a useful feature?

## Example
```css
  .columns {
    column-width: 300px 200px 100px;
    column-rule: 3px solid;
    column-fill: auto;
    height: 200px;
  }

  .columns > * {
    display: block;
    background: lightgrey;
    border: 2px dotted;
  }
```
would render something like this:

![image](https://user-images.githubusercontent.com/4010828/77361332-60142b80-6d4f-11ea-8057-1c45b3a58b68.png)
