### ISSUE TITLE
[css-values][css-images] Allow trailing comma in gradient functions (and probably others)

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#4968]
Trailing comma can be visual pleasing with certain code styles, for example, this code piece from MDN:
```css
body {
  background: linear-gradient(to right, 
     red 20%, orange 20% 40%, yellow 40% 60%, green 60% 80%, blue 80%);
}
```
can be written as
```css
body {
  background: linear-gradient(
    to right,
    red 20%,
    orange 20% 40%,
    yellow 40% 60%,
    green 60% 80%,
    blue 80%,
  );
}
```
which may look better for some people.

This is currently invalid as trailing comma is not allowed.

It would probably be great if trailing comma is always accepted, like in many programming languages.

**Comment by AmeliaBR** [comment]
If we make this change, could we extend it to all comma-separated lists, not just gradient functions?  E.g., background layers and such. Anything that uses the `<item>#` syntax.

**Comment by upsuper** [comment]
I agree that it may be better to extend it to all comma-separated lists, thus I marked it css-values as well. It may make most of the sense for gradient functions, but it's indeed better with more consistency.

**Comment by Loirooriol** [comment]
> If we make this change, could we extend it to all comma-separated lists

Maybe for all functions, but the `,;` looks a bit odd for me in 

```css
background-image: url("image.png"),;
```

Though maybe some people would like this style in order to avoid touching the previous line when inserting some item at the end:

```css
background-image:
  url("image1.png"),
  url("image2.png"),
;
```

Anyways, doing this for all [`#`](https://drafts.csswg.org/css-values/#mult-comma) can have some strange implications for more general syntaxes.

For example, the syntax of [`background`](https://drafts.csswg.org/css-backgrounds/#background) is `<bg-layer># , <final-bg-layer>`. So if we just allow a trailing comma after `<bg-layer>#`, then this would still be invalid:

```css
background:
  url("image.png"),
  yellow,
;
```

but this would be valid:


```css
background: url("image.png"),, yellow;
```

So instead of tying this to `#` lists, maybe the rule should be that `)` and `;` can be preceded by an optional comma or something like that.

**Comment by tabatkins** [comment]
Yes, the point of allowing `,;` is for when you break across lines; it means you can reorder the lines or add/remove lines without having to touch *other* lines. This improves both editability and diffability.

> Anyways, doing this for all # can have some strange implications for more general syntaxes.

We would indeed need to still manually apply trailing-comma in some properties,
but `url("image.png"),,yellow` would continue to be invalid due to the comma-elision rules if we did this.

Something like: `#` allows an optional trailing comma (but subject to elision rules, no doubled commas), and any function or property that contains a `#` or a literal `,` in its grammar allows an optional trailing comma at the end of its grammar.

**Comment by Loirooriol** [comment]
> `url("image.png"),,yellow` would continue to be invalid due to the comma-elision rules

This doesn't seem clear to me. There is no omitted item between the commas, so the conditions in https://drafts.csswg.org/css-values/#comb-comma don't seem to apply.

> Something like: # allows an optional trailing comma

But why? Wouldn't allowing it at the end of a function or property value be enough?

Allowing a comma after `#` seems problematic if you have a grammar like `<ident># <ident>?`. If the value is `a, b, c`, does it mean that `a, b, c` is the `<ident>#` list and the final `<ident>?` is omitted? Or is `a, b` the `<ident>#` list, `,` the optional comma, and `c` the final `<ident>?`, i.e. a synonym of `a, b c`?

**Comment by AmeliaBR** [comment]
>  if you have a grammar like `<ident># <ident>?`.

That's definitely something that needs to be defined explicitly. To use a real-world example: a `background: url(image.png), blue` is different from `background: url(image.png) blue` with respect to other background-list properties that override the declaration. For backwards compatibility, the comma always has to be meaningful in this case.

The optional comma should only be allowed either at the end of a value or at the end of a function parameter list.

**Comment by tabatkins** [comment]
@AmeliaBR Ah, I didn't see your last comment before the call, and thus misunderstood your comment during the call. You're right, `background` is indeed ambiguous if we allow a trailing comma after the `#` term.

Since Oriol and Emilio both expressed preference for just allowing it at end of a function/property, and I don't think it negatively affects any existing property or function, I'm happy to switch to that.

So, that still leaves us with two possibilities, afaict.

1. Property or function grammars that contain either a top-level `,` combinator or `#` multiplier allow an optional final comma at the end of their value.
2. All properties and functions allow a trailing final comma that is stripped from their value by the Syntax parser.

If I understood them correctly, Emilio preferred handling this at the lowest level possible, to minimize the chance of someone forgetting to implement it, so they'd prefer (2).  I think I'm okay with that. I first thought it was kinda weird to allow something like `content: attr(foo,);`, but then realized that if attr() had an optional comma-separated argument (which it *does* now in Values 4), that would be valid and fine; it's not great to have the validity of this change over time, so it's better to allow it all the time up-front.

This does allow oddities like `color: blue,;`, but heck, maybe someday we will make `color` comma-separated. And disallowing things that look weird but nobody will actually do isn't very important; we're not protecting anyone from anything. The gain in overall conceptual simplicity, since it would be addressed at the parser level, seems like a great win too.

So, when we pick this up (at the f2f I guess?) I propose that we accept (2), and I make edits to Syntax to make all functions and properties accept a final trailing comma, which is removed during parsing.

Specifically, I'd add a penultimate step to <https://drafts.csswg.org/css-syntax/#consume-a-declaration> dropping a single comma token, and add a similar bit dropping trailing ws and commas from the function value in <https://drafts.csswg.org/css-syntax/#consume-function>.

**Comment by mirisuzanne** [comment]
Sass doesn't have an easy way to track popularity of a feature, but it looks like we've supported trailing commas in many places since 3013, and basically everywhere since 2016. I'll dig deeper and see if I can find any exceptions, but I haven't found any yet. I can also try to survey use, if that's helpful.

Trailing commas on a single item are used internally to signify that the item should be treated as a `list` type, and we remove remove trailing commas when compiling to CSS. We do the same with trailing commas on a property:

```scss
$sass: item,; // -> a comma-separated list of one
.test { content:  $sass,; } // -> content: item;
```

I've most often seen it used in Sass list & map variables, though I often use it for gradients as well. My sense is that use in multi-line sass lists and maps is the norm rather than the exception. There was clamor in 2016 to allow it even more places than we did originally. But I also think people "trust" it more where the code is clearly a Sass-defined syntax (lists & maps), and are less likely to know we also support it in general CSS syntax (backgrounds, css functions, etc).

For a quick sample, this Sass:

```scss
body {
  background:
    linear-gradient(
      to right,
      red 20%,
      orange 20% 40%,
      yellow 40% 60%,
      green 60% 80%,
      blue 80%,
    ),
    linear-gradient(to top, black, transparent),
  ;
  width: clamp(0, 100%, 30em,),;
}
```

compiles to valid CSS without any trailing commas:

```css
body {
  background: linear-gradient(to right, red 20%, orange 20% 40%, yellow 40% 60%, green 60% 80%, blue 80%), linear-gradient(to top, black, transparent);
  width: clamp(0, 100%, 30em);
}
```

**Comment by mirisuzanne** [comment]
We also support it where the number of accepted arguments is clear:

```scss
// example function accepts a single argument
@function example(
  $arg
) {
  @return $arg;
}

.test {
  error: example(a, b); // two arguments -> error
  valid: example(a,); // one with trailing comma -> `a`
}
```
