### ISSUE TITLE
[css-fonts] Should all new generic family names win over @font-face names?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#5001]
According to:
https://drafts.csswg.org/css-fonts-4/#family-name-syntax
The unquoted generic font-family names should not match @font-face nor existing font names.

As we add more generic families, and we changed the definition not to require to resolve to existing fonts, I wonder we may want to revisit this criteria too.

As the number of generic family increases, we'll increase the risk of snippets like this to behave differently by browsers:
```css
@font-face { family-name: fangsong; ... }
html { font-family: fangsong; }
```
then browsers that supports `fangsong` generic family will ignore this `@font-face`.

In Blink, we apply this rule to `system-ui`, but haven't done so to other generic families yet.

**Comment by svgeesus** [comment]
A similar issue in CSS Color was dealt with by making the author-supplied identifiers be dashed idents. I don't thinks we can do that here though, because the weight of existing usage is too great.  So yes, if we constantly make new generics then there is a risk that they clash with previously-ok  user supplied names. The only wiggle room we have is the use of quoting:

```css
@font-face { font-family: "serif"; ...}
html { font-family: "serif", serif }
```

This will use the webfont called "serif" and then as fallback the generic font family `serif`.
