### ISSUE TITLE
[css-transitions]/[css-animations] Proposal: Allow velocity values for transition-duration and animation-duration

### ISSUE THREAD

**Issue by SetTrend** [w3c/csswg-drafts#5091]
Transitions and animations look weird on sibling elements having different sizes.

This is particularly true when, for example, one menu strip only contains a few items while the neighbour menu strip contains many.

See [this JSFiddle](https://jsfiddle.net/hjtyx3ng/1/) for a sample application: The same transition is applied to both menu items, but comparing the left transition to the right it's a rabbit versus a turtle.

That's why I'd like to propose to allow for providing transition and animation duration values in terms of velocity (i.e. length/time).

For instance, valid property values could be:

```css
transition-duration: 1em/185ms;
transition-duration: 2px/100ms;
animation-duration: 5em/1s;
```

**Comment by Loirooriol** [comment]
You seem to assume that only lengths can be interpolated non-discretely. But you can also interpolate `<number>`, `<percentage>`, `<frequency>`, or even repeatable lists:

```css
#grid {
  display: grid;
  animation: anim 1s;
}
@keyframes anim {
  from { grid-template-columns: 0px 100px }
  to { grid-template-columns: 200px 50px }
}
```

the 1st track changes with an average velocity of `200px/1s`, while for the 2nd track it's `-50px/1s`.
How does this fit into your proposal?

**Comment by SetTrend** [comment]
Good question ...

I would suppose my proposal to apply to length values only. "Where applicable" would most closely describe it.

It's similar to `inset properties` being ignored when [`position: static`](https://www.w3.org/TR/css-position-3/#valdef-position-static).

**Comment by Loirooriol** [comment]
But even with just lengths,

```css
#element {
  animation: anim 100px/1s;
}
@keyframes anim {
  from { width: 0px; height: 0px }
  to { width: 100px; height: 200px }
}
```

`width` wants to increase 100px with a speed of 100px/1s, so it wants the animation to last 1s.
`height` wants to increase 200px with a speed of 100px/1s, so it wants the animation to last 2s.

Then, either one of them wins (which one?) or I guess it's converted to something like

```css
#element {
  animation: anim 2s;
}
@keyframes anim {
  0% { width: 0px; height: 0px }
  50% { width: 100px }
  100% { height: 200px }
}
```
