### ISSUE TITLE
[css-grid] Should grid-template-areas accept empty strings?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#5110]
```js
CSS.supports("grid-template-areas", `""`)
CSS.supports("grid-template-areas", `"" ""`)
```

They are both `true` in Firefox and `false` in Chromium and old Edge. Looking at https://drafts.csswg.org/css-grid/#propdef-grid-template-areas,

 - There is no trash token.
 - All strings have the same number of columns (0).
 - There's in no non-rectangular named grid area (since there's no named grid area).

So it seems valid per the spec. But also pretty pointless, so possibly it was not deliberate. Given that neither Chromium nor old Edge support that, should we really allow it?

**Comment by Loirooriol** [comment]
I guess the utility of this is something like

```css
#grid {
  display: inline-grid;
  grid-auto-columns: 50px 100px;
  grid-auto-rows: 50px 100px;
  grid-template-areas: "";
  border: solid;
}
```

and if the grid is empty, you get a 50px tall and 0px wide grid. If you used `grid-template-areas: "."` you would get a 50x50 square. If you used `grid-template-rows: 50px` then you would have to reorder `grid-auto-rows: 100px 50px` in case there are two items, but this would also affect leading implicit tracks. Maybe `grid-template-rows: 50px repeat(auto-fit, 100px)` could be an alternative?

Anyways I don't know why somebody would want to do this, and allowing it for rows but not for columns is not much consistent either.
