### ISSUE TITLE
table-row baseline alignment with empty cells

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#5148]
See https://codepen.io/gsnedders/pen/VweZobe, which has the following:

```css
table {
  display: inline-table;
}
td {
  vertical-align: baseline;
  outline: 3px solid blue;
}
td:first-child, div {
  width: 100px;
  height: 100px;
}
```

```html
xxx
<table>
  <tr>
    <td>
    <td>Cell 2
</table>
yyy
```

Note that if you add `<div></div>` to the first table-cell the rendering significantly changes in both Gecko, Blink, WebKit, and Presto.

With the `div` I get the behaviour I expect; without it I cannot justify the behaviour from either CSS2 or CSS Table 3.

Per spec, I'd expect the row baseline to be at the bottom of the cell in both cases: the row's baseline is set by the lowest cell baseline, and in both cases that should be the first cell, in both cases it should be the bottom edge of the content box.
