### ISSUE TITLE
[css-fonts-4] [varfont] @font-face descriptors should accept ranges

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#521]
[Migrated](https://github.com/w3c/csswg-drafts/issues/498#issuecomment-248194701) on behalf of @AmeliaBR

Would there be a value in allowing the font-face descriptors (e.g., font-weight, font-stretch) to take two values, defining the range available from the file?

If you use range descriptors, then the non-variable fallbacks no longer match the descriptors, and would need separate font-face rules.  However, I'm pretty sure that still works with `@font-face` as currently defined, just need to watch the ordering:

```css
@font-face { /* fallback normal weight face */
font-family: BodyText;
font-weight: normal;
src: url(something) format(woff);
}
@font-face { /* fallback bold weight face */
font-family: BodyText;
font-weight: bold;
src: url(something-bold) format(woff);
}
@font-face { /* variable weight font */
font-family: BodyText;
font-weight: 200/700; /* min and max weights */
src: url(something-variable) format(woff2-variations);
}
```
So user agents that recognize the range descriptor and variable-font format would download the final file, others would download one or all of the backups (depending on which weights are required).

EDIT: I initially had the range descriptor using comma to separate the values.  But it would probably be best to reserve commas for a list of distinct values (not a range).  So, for example, if a user agent supported OpenType collection files (multiple distinct faces in one file), that could be `font-weight: 300, 500, 800`, while a variable-weight font with a continuous range would be `font-weight: 200/800`.

**Comment by litherum** [comment]
[Migrated](https://github.com/w3c/csswg-drafts/issues/498#issuecomment-248200644) on behalf of @nattokirai:

> Would there be a value in allowing the font-face descriptors (e.g.,
> font-weight, font-stretch) to take two values, defining the range
> available from the file?

Yes, that's another possibility and others have suggested this for `@font-face` font descriptor values. It would make the font matching algorithm a bit more complex and I was hoping to avoid making it any more complex than it already is.

My hunch is that with variable fonts we don't need to make the font descriptor syntax more complex. Once all user agents support variable fonts the set of `@font-face` rules will boil down to one or two rules per family. All the variations will be defined within the font itself. The `@font-face` would just look something like:

```css
@font-face {
  font-family: BodyText;
  src: url(something-variable);
  /* no need to define additional descriptors for a variable font */
}
```

**Comment by litherum** [comment]
If we do go with a range solution, I recommend using syntax similar to unicode-range (so it would use hyphens).

**Comment by litherum** [comment]
[Migrated](https://github.com/w3c/csswg-drafts/issues/498#issuecomment-248222408) on behalf of @nattokirai:

Jonathan Kew has also suggested using ranges in `@font-face` rules:

```css
/* For legacy UAs that don't support variation fonts,
   load individual faces. */
@font-face {
  font-family: BodyText;
  src: url(fonts/BodyText-Regular.otf) format("opentype");
}
@font-face {
  font-family: BodyText;
  font-weight: bold;
  src: url(fonts/BodyText-Bold.otf) format("opentype");
}
@font-face {
  font-family: BodyText;
  font-style: italic;
  src: url(fonts/BodyText-Italic.otf) format("opentype");
}
@font-face {
  font-family: BodyText;
  font-style: italic;
  font-weight: bold;
  src: url(fonts/BodyText-BoldItalic.otf) format("opentype");
}

/* For UAs with variation support: the style and weight descriptors
   cover a range, which means this will override all the preceding
   rules that fall within the ranges. UAs that don't recognize the
   "opentype-variation" support will not load anything here, so will
   fall back to the individual faces above. */
@font-face {
  font-family: BodyText;
  font-style: normal, italic;
  font-weight: 1-1000;
  src: url(fonts/BodyText-Var.otf) format("opentype-variation");
}
```

So `font-stretch` would use a percentage range? `50-150%`? Hmmm.
