### ISSUE TITLE
[css-mediaqueries] inner `@media` rules.

### ISSUE THREAD

**Issue by Zambonifofex** [w3c/csswg-drafts#531]
Consider:

```CSS
foo
{
    color: red;
    @media screen
    {
        background-color: blue;
    }
}
```

This syntax is good because:

1. It’s DRY (what if `foo` was a really long selector?)
2. It interacts well with [nesting](https://tabatkins.github.io/specs/css-nesting/).
3. Not only it interacts well with [custom property sets](https://tabatkins.github.io/specs/css-apply-rule/), but it allows people to do things that would otherwise be impossible. Consider:

```CSS
:root
{
    --button:
    {
        color: red;
        @media screen
        {
            background-color: blue;
        }
    };
}
```

**Comment by LeaVerou** [comment]
Note that this is one of the things preprocessors do and authors use a lot.

**Comment by frivoal** [comment]
I think this would be useful, and the error handling of CSS Syntax should allow this evolution. An unknown `@media ` in the middle of a rule set will simply get ignored, but will not confuse the parser, and traditional property declarations before or after the `@media` rule will continue to apply just fine.

I also don't think it poses any significant implementability challenge to make parsers support this, although I could be wrong about that.

LTL;DR: LGTM.

**Comment by LeaVerou** [comment]
I don't see why it shouldn't be implementable either, since all use cases I've seen (including the one in the first post) are just syntactic sugar over what can already be done).

**Comment by Zambonifofex** [comment]
@LeaVerou

Well, the first one might be “just syntactic sugar”, but the second one isn’t possible today, as far as I’m aware.

**Comment by LeaVerou** [comment]
Isn't it basically this?

```css
:root
{
	--button: {
		color: red;
	}
}

@media screen {
	:root {
		--button: {
			background-color: blue;
		}
	}
}
```

(Then you use with `@apply`)
