### ISSUE TITLE
[css-apply-rule] Variables in @apply should resolve based on calling context, not defining context

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#532]
For example, in the following code ([live demo - works in Chrome with flag](http://dabblet.com/gist/2ad78e799dd967dc75fd8eb8c2130694))

``` css
:root {
    --foo: orange;
    --bg: {
        background: var(--foo);
    }
}

body {
    --foo: green;
    @apply --bg;
}
```

`<body>` should be green, not orange. That will allow parameterization of `@apply` mixins, which is what authors really want (and already do with preprocessors, bloating the CSS size as it spits out different code for each call). If it's just about copying a bunch of declarations, they can always preprocess that. It's also surprising, given that in every other case variables resolve based on current element.

**Comment by LeaVerou** [comment]
CC @tabatkins

**Comment by tabatkins** [comment]
This has nothing to do with `@apply`, it's just the normal behavior of custom properties.  As far as CSS is concerned, you have:

```css
:root {
  --foo: meaningless-stuff;
  --bg: meaningless-stuff var(--foo) meaningless-stuff;
}
```

It sees the var(), and substitutes it as normal. The fact that you later are subbing in --bg via an @apply rule rather than a var() is meaningless.

That said, plan for a later version of Custom Properties is to have a var() option that causes it to be substituted at time of use (when it's used in something other than an untyped custom property), which will achieve what you're looking for.

**Comment by mildred** [comment]
What is preventing from treating custom properties enclosed with `{` and `}` a spacial way:

```css
:root {
  --bar: bar;
  --foo: var(--bar);
  --baz: { anything with var(--variable) inside };
}
```

Where `--foo` would equal to `bar` and `--baz` would equal to `anything with var(--variable) inside` (variable not interpolated).

Then, later on, `@apply --baz` would be able to interpolate `var(--variable)`.
