### ISSUE TITLE
[css-position-3] Single auto value of offset properties for absolutely positioned elements should not be zero

### ISSUE THREAD

**Issue by zjopy** [w3c/csswg-drafts#5327]
The [spec](https://drafts.csswg.org/css-position-3/#abspos-insets) reads for absolutely positioned elements

> If only one inset property in a given axis is auto, it is set to zero.

This would imply, that if the size in the same axis is not specified (i.e. `auto`), then the element would be resized, since now both sides are set to non-`auto` values.

For example, I'd expect the following box to be full width instead of `max-content` wide.

```html
<div class="abs">Hello World</div>
```

```css
.abs {
  position: absolute;
  background-color: lightgrey;
  left: 0;
  /* right: 0; */
}
```

Since this is not the case, I expect this formulation is a bug.
