### ISSUE TITLE
[css-flexbox-1] flex-basis can not be smaller than min-content

### ISSUE THREAD

**Issue by zjopy** [w3c/csswg-drafts#5367]
I can't find this behavior specified anywhere in the current [spec](https://drafts.csswg.org/css-flexbox/#valdef-flex-flex-basis). But all current versions of the major browsers (Chrome 84, Firefox 78, Safari 13) set the lower bound of `flex-basis` to `min-content`. This makes `flex-basis` behave different from `width`/`height`, since you can't create overflow by making the box smaller than its contents.

Is this a bug in the implementations or in the spec?

On the first glance it seems like a bug in the implementation, since there is no lower bound mentioned in the spec and it would be of little use, since the keyword `min-content` was made for exactly that.

But the implementation suddenly seems reasonable, given that the shorthand `flex` resets `flex-basis` to zero when omitted, which would make little sense if zero were not equivalent to `min-content`, although this is similarly nowhere specified.

> When omitted from the flex shorthand, its specified value is 0.

If the spec had instead defined the "reset value" of `flex-basis` in the `flex` shorthand as `min-content`, then a lower bound of `min-content` in `flex-basis` would reasonably be a bug in the implementation.

A minimal working example.

```html
<div class="container">
  <div class="mincontent">Lorem ipsum</div>
  <div class="smallerflexbasis">Lorem ipsum</div>
  <div class="smallerwidth">Lorem ipsum</div>
</div>
```

```css
.container {
  display: flex;
}

.container div {
  background-color: lightgrey;
  border: 1px solid black;
  margin: 0 10px;
  /* disable any flexible sizing */
  flex-grow: 0;
  flex-shrink: 0;
}

.mincontent {
  width: min-content;
}

.smallerflexbasis {
  flex-basis: 3ex;
}

.smallerwidth {
  width: 3ex;
}
```
