### ISSUE TITLE
[css-values] Re-adding min() and max()?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#544]
Perhaps now that Values 3 has gone to CR it's time to reconsider adding `min()` and `max()` back into Values 4?

Authors are doing extremely [weird](http://blog.typekit.com/2016/08/17/flexible-typography-with-css-locks) [hacks](http://fvsch.com/code/css-locks/) with `calc()` to emulate them in `font-size` and `line-height`, which they call "CSS locks". If you google _CSS locks_ you will see how widespread these hacks are becoming, indicating a clear author need.

Furthermore, as CSS variables become more widely used, the need for `min()` and `max()` will become even greater. I recall some of the issues that [made us drop them 6 years ago](https://lists.w3.org/Archives/Public/www-style/2010Sep/0233.html) can now be solved with the _invalid at computed value time_ concept that Variables introduced.

**Comment by Crissov** [comment]
So, for “locks”,

``` css
selector {
  property: /* $min_value ≤ */ $fallback_value /* ≤ $max_value = $min_value + $max_increment */;
}
@media (min-width: $min_vw) and (max-width: $max_vw) {
  selector {
    property: calc( $min_value + $max_increment *   (100vw - $min_vw) 
                //*                               ———————————————————  */
                                                  ($max_vw - $min_vw)  );
  }
}
@media (max-width: $min_vw) {
  selector {
    property: calc( $min_value + 0 );
  }
}
@media (min-width: $max_vw) {
  selector {
    property: calc( $min_value + $max_increment /* = $max_value */ );
  }
}
```

would become

``` css
selector {
  property: /* $min_value ≤ */ $fallback_value /* ≤ $max_value = $min_value + $max_increment */;
  property: calc( $min_value + $max_increment * min(  (100vw - $min_vw) 
              //*                                   ———————————————————     */
                                                    ($max_vw - $min_vw), 1) );
}
```

right?

I wonder if authors would also find good use for `mid()`dle/`avg()`, `med()`ian, `mod()`e etc.

**Comment by MadeByMike** [comment]
I proposed a map() function that allows for min and max sizes as well as easing and interpolation of more than just length units: https://github.com/w3c/csswg-drafts/issues/581

I think this would be a much more versatile approach, especially with things like variable type, where min() and max() might not work.

**Comment by MadeByMike** [comment]
People have shared with me examples of how `min()` and `max()` functions in CSS might work in addition to a `map()` function. So to clarify, I don't think it needs to be one or the other.

Since calc() allow some `min` and `max` functionality (although not with whole numbers) It might be useful to consider other implementations of `min` and `max` including returning the min and max value of a set e.g. `max(14px, 1em, 1rem, 3vw)`.

**Comment by LeaVerou** [comment]
It's generally good API design practice to have shortcuts for commonly needed things, otherwise you end up with clunky, verbose APIs that are a pain to use for anything. I will not discuss whether what you're proposing is a good idea or not here, partly because I haven't thought about it much. However, even if it is, using `map()` to specify the min of two values results in extremely weird and convoluted code. Power is good, as long as it stays out of your way when you don't need it.

**Comment by Crissov** [comment]
I wonder whether `min()` and `max()` would be the best notation, however, especially if these operations were only available within `calc()`. I know it’s unusual and incompatible with programming languages (which need logic operators and, unlike CSS, have a boolean data type), but maybe `<` and `>` could be used as operators instead.

``` CSS
{
width: min(100px 10em 10vw);
width: min(100px, 10em, 10vw);
width: calc(min(100px 10em 10vw));
width: calc(min(100px, 10em, 10vw));
width: calc(100px < 10em < 10vw);

height: max(100px 10em 10vw);
height: max(100px, 10em, 10vw);
height: calc(max(100px 10em 10vw));
height: calc(max(100px, 10em, 10vw));
height: calc(100px > 10em > 10vw);
}
```
