### ISSUE TITLE
[cssom-view] [css-overflow] Document.scrollingElement doesn't reflect viewport propagation correctly in presence of overflow: clip

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5601]
https://drafts.csswg.org/cssom-view/#dom-document-scrollingelement disagrees with https://drafts.csswg.org/css-overflow/#overflow-propagation in what makes the root scrollable, and they shouldn't.

In particular, for this case:

```css
<style>
  :root {
    overflow: clip;
  }
  body {
    overflow: scroll;
  }
</style>
```

Per css-overflow, the viewport style comes from `:root`, not from the `<body>`. But `document.scrollingElement`, which in quirks mode is intended to return the `<body>` if it propagates the scroll styles from the viewport, disagrees and says that `document.scrollingElement` should be `document.body`.

I think this is wrong and that `cssom-view` should be fixed (or overflow propagation should be changed to match `cssom-view`...)
