### ISSUE TITLE
[css-values] meta() – Access Document Metadata

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#575]
* [V&U: Functional Notations](https://drafts.csswg.org/css-values/#functional-notations)
* [whatwg/html#1868: “Single source theme-color values”](https://github.com/whatwg/html/issues/1868#issuecomment-251920081)

Like local element attributes with `attr()`, it would sometimes be handy to be able to access document-wide meta data, e.g. with HTML:

``` html
<meta name="theme-color" content="#F00B42">
```
``` css
h1 {color: meta("theme-color" color, red;)}
h2 {background: meta("theme-color" color, red;)}
```
