### ISSUE TITLE
[css-cascade] What is the appropriate syntax for appending to nested layers?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#5791]
The draft Cascade 5 specification allows [nesting cascade layers](https://drafts.csswg.org/css-cascade-5/#nested-layers), and appending styles to nested layers using a dot (`.` period/full-stop/`U+002E`) character:

```css
@layer framework {
	@layer default {
		p { margin-block: 0.75em; }
	}

	@layer theme {
		p { color: #222; }
	}
}

/* These styles will be added to the theme layer inside the framework layer */
@layer framework.theme {
	blockquote { color: rebeccapurple; }
}
```

It might also work to use a space, or some other character in place of the dot.

**Comment by fantasai** [comment]
While I *like* the dot notation because it's commonly used in programming languages, I think it might make sense within the context of CSS to use a space:
- it matches how we write descendant selectors, which is the closest concept we have.
- it doesn't match how we write class selectors, which are a flat concept, not a nested one

**Comment by tabatkins** [comment]
On the other hand, staying away from the Selectors analogy might be a *good* thing? In particular, this *shouldn't* match the descendant combinator, but rather the child combinator. So instead leaning on the programming-language `.` actually feels a little better to me.

(And I don't want to use `>` and admit the possibility of a descendant combinator as well; that seems unnecessary.)

**Comment by frivoal** [comment]
Just thinking out loud, considering separators that haven't been mentioned yet:
* another typical css separator is the comma, but it implies a flat list, not a hierarchy
* a rarer css separator is the slash. In the context of css, it doesn't imply a hierarchy either, but in file paths or URLs is does

Overall, I think I'd still go with the space, not because it matches selectors, but because it's the simplest thing used all over the pace in CSS as a separator. The period feels a bit foreign. But I wouldn't push back much if people insisted that we should go with that.

**Comment by mirisuzanne** [comment]
Worth noting that this syntax can also be used inside a (currently comma-separated) list of layers. To show a few of those options:

```css
@layer framework.default, framework.theme;
@layer framework default, framework theme;
@layer framework / default, framework / theme;
```

Or in the block syntax:

```css
@layer framework.theme {
	blockquote { color: rebeccapurple; }
}

@layer framework theme {
	blockquote { color: rebeccapurple; }
}

@layer framework / theme {
	blockquote { color: rebeccapurple; }
}
```

I think the space works well in both cases, and adding punctuation feels unnecessary.
