### ISSUE TITLE
[selectors] add ::transition (styles applied during transition)

### ISSUE THREAD

**Issue by yairEO** [w3c/csswg-drafts#5823]
# `::transition`

I would like to suggest creating such a useful selector, for styling elements **only** during transition (not *animation*).

### Block the user from toggling a thing during transition 
```css
.elm::transition{ pointer-events:none }  
```

### Hide specific children during transition
```css
.elm::transition > .foo{ display:none }  
```

----

It will also open the door to some interesting effects:

### Every time `.elm` is transitioned, apply a filter
```css
.elm::transition{ filter:blur(2px) }  
```
