### ISSUE TITLE
Does nested @layer syntax work for declaring layer order?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5849]
[nested cascade layer](https://drafts.csswg.org/css-cascade-5/#nested-layers) let you do this:

```css
@layer out {
  @layer in1 {
    p { color: blue; }
  }
  @layer in2 {
    p { color: red; }
  }
}
@layer out.in2 {
  h1 { color: pink; }
}
```
Does the period notation also affect layer ordering? In other words, If I changed the above example to
```css
@layer out.in2 {
  h1 { color: pink; }
}
@layer out {
  @layer in1 {
    p { color: blue; }
  }
  @layer in2 {
    p { color: red; }
  }
}
```
does that now mean that `in2` is ordered before `in1` rather than after? I suppose it does, as
```css
@layer out.in2 {
  h1 { color: pink; }
}
```
is just syntatic sugar for
```css
@layer out {
  @layer in2 {
    h1 { color: pink; }
  }
}
```
but it might be worth making it explicit.
