### ISSUE TITLE
[css-cascade] Provide an attribute for assigning a <link> to a cascade layer

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#5853]
This was raised on #4969, related to the [Cascade level 5 spec](https://drafts.csswg.org/css-cascade-5/).

We've defined a syntax for cascade layers to be declared as code-blocks or url imports:

```css
@layer reset url(remedy.css); 

@layer reset {
  audio[controls] { display: block; }
}
```

If we're allowing authors to import entire stylesheets into a layer, it seems appropriate to make that available on `<link>` and `<style>` tags as well. For performance reasons, those are more likely to be used - rather than chaining imports. I'm proposing a `layer` attribute:

```html
<link rel="stylesheet" href="remedy.css" layer="reset">

<style layer="reset">
  audio[controls] { display: block; }
</style>
```

**Comment by frivoal** [comment]
I suspect that's not going to work, as existing user agents would just ignore the layer attribute, and assign all those styles to the default layer instead, so that's not going to be forward compatible.

For `<style>`, I'm not so sure it's critical: if we can find a nice syntax that's forward compatible, then great, but otherwise, it's just syntactic sugar: if you can do
```css
<style layer="reset">
  audio[controls] { display: block; }
</style>
```
you can also do
```css
<style>
@layer reset {
  audio[controls] { display: block; }
}
</style>
```

For `<link>` it's more useful though, as you may be trying to load into a particular layer a stylesheet that you cannot modify.
