### ISSUE TITLE
[css-conditional] [css-contain] `cw` and `ch` units

### ISSUE THREAD

**Issue by una** [w3c/csswg-drafts#5888]
Viewport-relative units (such as `vh` and `vw`) are commonly used among UI design for sizing and spacing of elements.

With the new container queries spec, authors will want to use such units as container-height (`ch`) and container-width (`cw`) for container-based sizing.

An example is using `cw` units in `srcset` similarly to how one would use `vw` units in `srcset`. Percentages would not work in that instance, as the value needs to be absolute or relative length.

**Comment by dbaron** [comment]
The [`ch` unit](https://drafts.csswg.org/css-values-3/#ch) already exists with a different meaning (short for "character"), so this will at least need a different name.

**Comment by jimmyfrasche** [comment]
`ew` and `eh`

**Comment by nigelmegitt** [comment]
`rw` and `rh` would match the identically named [`<length>`](https://www.w3.org/TR/ttml2/#style-value-length) units in TTML2, in the case that the container is the _root container region_, which makes sense e.g. for playing captions over a video container, where it is normal to render text at a height proportional the height of the video.

**Comment by una** [comment]
@nigelmegitt I like the idea of using "root" in the name here. Potentially also "root container width" (`rcw`) and "root container height" (`rch`) to specify container from root. I also like `rw` and `rh`

**Comment by chrishtr** [comment]
@mirisuzanne

**Comment by mirisuzanne** [comment]
Yeah, I'm totally in favor of this, and think it would be very useful. My understanding was that container-relative units would have an additional performance cost with every use, making them likely too expensive. I would love to find out that I mis-understood.

There has been some previous discussion of this in [other container query threads](https://github.com/WICG/container-queries/issues/12#issuecomment-525520959).

**Comment by lilles** [comment]
Container units would be as costly as vh/vw for @media query changes, I suppose. Blink marks computed styles for an element with a flag saying that it relies on viewport units and such elements have styles recomputed when the viewport size changes. Same should work for container units/queries.

**Comment by fantasai** [comment]
Note, we use 'r' as a prefix currently for the root element e.g. in `rem` and `rlh` so probably should avoid that as a prefix here.

**Comment by astearns** [comment]
I got ahead of the bot:

<una> Also should consider 4 names for height/width and inline/block
<dlibby> RESOLVED: add new units to express container dimensions

**Comment by matthew-dean** [comment]
Yeah, I think [I came up](https://github.com/WICG/container-queries/issues/12) with `aw` / `ah` / `ai` / `ab` (for allocated width, height, inline-axis, block-axis), but could also be: `qw` / `qh` / `qi` / `qb`? (For queried units?)

**Comment by matthew-dean** [comment]
Also relevant: https://github.com/WICG/container-queries/issues/12#issuecomment-587186810

> https://github.com/WICG/container-queries/issues/12#issuecomment-587186810

So whatever the "prefix", should have [x]min and [x]max to correspond with viewport units?

**Comment by fantasai** [comment]
Important comment from @dholbert in those minutes: need to consider what happens when the element and container writing modes don't match.

**Comment by LoganDark** [comment]
cx and cy

**Comment by davewallace** [comment]
`bw` for box width, `bh` for box height 📦

**Comment by Martinspire** [comment]
What if not CO was the shorthand, but CT instead? So CTW (container width) and CTH (container height) instead of COW and COH? In the past I've seen many projects using containers and ct to prefix stuff instead of co. It prevents making words that don't make sense (like cow) and still is similar enough to container...

**Comment by mirisuzanne** [comment]
> Important comment from @dholbert in those minutes: need to consider what happens when the element and container writing modes don't match.

Since `vi` and `vb` resolve based on the root element’s writing mode, I expect we would use the container writing mode here. That has the advantage of ensuring that the containment axis and unit axis always match: when the container has inline containment, the inline units match the contained dimension.

**Comment by mirisuzanne** [comment]
Beyond the naming question (which should be considered in tandem with bikeshedding a [new container property](https://github.com/w3c/csswg-drafts/issues/6174)), there's a bigger question about how these units work.

1. if there is no ancestor container
2. if the nearest ancestor container does not have the appropriate dimension contained (eg a block-dimension unit in an inline-container)

For normal `@container` queries, we've concluded that: 

1. the query [fails when no container is available](https://github.com/w3c/csswg-drafts/issues/6178)
2. the query fails when the queried container has improper containment (This hasn't been discussed officially, but the alternative isn't viable to begin with. Browsers would have to parse each query condition before knowing what container to resolve against, and conditions could either resolve against different containers, or impact the meaning of other conditions)

But relative units don't usually "fail" in the same way as query-blocks. My immediate instinct is that they would:

1. Resolve against the viewport, if no container is present
2. Resolve based on the nearest _relevant_ container

But that could have some unexpected behavior: 

1. the viewport is likely much larger than any expected layout containers
2. inline and block units could resolve against different containers in confusing ways

Maybe that's workable for authors, but it feels very fragile and unpredictable. Would we need some way to provide a more customizable fallback value in the "failed query" situations? Either by allowing them to "fail" and fallback on a previous value:

```css
p {
  padding: 1em;
  padding: 10cw; /* ignored if no width-query is possible */
}
```

Or using some function fallback logic?

```css
p {
  /* container(<container-relative-value>, <fallback value>) */
  padding: container(calc(1em + 1w), 1em);
}
```

I'm not sure either of those is quite right. Just trying to think through the options here.

(The `cw` and `w` units above represent a container width unit, but are not actual unit name proposals. I know that `cw` will not work.)

**Comment by matthew-dean** [comment]
@mirisuzanne I would think that if they don't apply, they simply don't apply (are not valid), and similar to other CSS behavior, would be as if the entire property were not declared. So your first option `ignored if no width-query is possible` seems the most intuitive / consistent with CSS.

**Comment by mirisuzanne** [comment]
Well, both my example fallbacks are based on existing CSS mechanisms. One is used for parse-time issues like invalid syntax, while the other is used for computed-value-time issues like invalid custom properties.

Looking back through the transcript, it seems like we plan resolve these units at computed value time, which means we're in custom-property (invalid-at-computed-value-time/IACVT) territory. So, having suggested it, I now think we _can't_ use the parse-time fallback, even if we wanted to? So that complicates things a bit more.

I think ideally we might want:
- A decent default that ensures we always get _some_ value, even if it's not ideal in all cases (are there better options than viewport?)
- Some way to provide an IACVT fallback, to override that default

**Comment by lilles** [comment]
As you mentioned, this won't work since the first declaration will be dropped at parse time as long as the 'cw' unit is supported at all:

```css
p {
  padding: 1em;
  padding: 10cw; /* ignored if no width-query is possible */
}
```

If you resolve against 0 or the viewport dimensions, could one use calc with the existing min()/max() functions, or would that bee too hard to do predictably because you cannot predict if the fallback will be narrower or wider than a working container?

**Comment by andruud** [comment]
For that kind of fallback, just make it possible to query for a given container type?

```CSS
p { padding: 1em; }

@container (inline-size) {
   p { padding: 10cw; }
}
```

> custom-property territory

I don't think we're _automatically_ in custom-property territory here, we should first try to be in `em`-territory (which is also resolved computed value time).

**Comment by dvdherron** [comment]
a suggestion for units I don't think I've seen yet: `qw`,` qh` ( query-width, query-height? )

**Comment by una** [comment]
I like `qw` and `qh` to not clash with `ch` (more than `rcw` and `rch`)

**Comment by mirisuzanne** [comment]
Just to flesh that out into the six value we need: 

- `qw`: 1/100th of the container `width`
- `qh`:  1/100th of the container `height`
- `qi`:  1/100th of the container `inline-size`
- `qb`:  1/100th of the container `block-size`
- `qmin`:  the smaller of `qb` and `qh`
- `qmax`:  the larger of `qb` and `qh`

(the only potential confusion here might be with the [`Q` unit](https://drafts.csswg.org/css-values-4/#Q)?)

In each case, the value can only be resolved inside a container of the appropriate [type](https://drafts.csswg.org/css-contain-3/#container-type). As an initial draft, I'm proposing that unresolved container-units default to zero. Any other fallback seems dangerous and unpredictable. Zero may seem dangerous, but I think it can work well in practice. Consider these uses, assuming there is no container:

```css
.examples {
  font-size: calc(1em + 0.2qmin); /* 1em */
  font-size: clamp(1em, 5qw, 3em); /* 1em */
  font-size: clamp(1em, max(5qw, 3vw), 3em); /* clamp(1em, 3vw, 3em) */
  padding: max(2qh, 1em) max(2qw, 1em); /* 1em 1em */
}
```

And, as mentioned by @andruud above, we can ensure they resolve by specifying them inside the appropriate @container queries. (I'll start with this as the draft spec, and we can revisit before publishing)

**Comment by matthew-dean** [comment]
> (the only potential confusion here might be with the Q unit?)

That.... is a very unusual unit. I would petition to have that one (`Q`) removed before that proposal exits draft status, personally, partly for its unusualness, partly because I don't see the need, and partly because of this proposal.

**Comment by Crissov** [comment]
`q` could have been called `qmm` to make it more transparent for people unfamiliar with it, but for those that are actually using it, `q` is the appropriate symbol they are used to. (Some might say `kyu` would have been fine as well.) 
It’s been in CSS for a while now and is not going to be changed.

**Comment by mirisuzanne** [comment]
> For that kind of fallback, just make it possible to query for a given container type?
> 
> ```css
> p { padding: 1em; }
> 
> @container (inline-size) {
>    p { padding: 10cw; }
> }
> ```

@andruud This ensures that that there is a proper container for the unit, but it doesn't ensure it's the _nearest ancestor_ container referenced by the unit. We would still need to say that units evaluate against the nearest container _of the appropriate type_. And that puts us back in a situation where units could evaluate against multiple containers:

```html
<div style="container: size;>
  <div style="container: block-size;>
    <div style="container: inline-size;>
      <div style="container: style;>
        <p>how do container units evaluate on this paragraph?</p>
      </div>
    </div>
  </div>
</div>
```

Which container is used for the various units?

```css
p {
  /*  style (nearest)? block-size (of-type)? */
  margin: 1qb;

  /*  style (nearest)? inline-size (of-type)? */
  padding: 1qi;

  /*  style (nearest)? size (of-type)? or inline-size & block-size, individually per axis? */
  font-size: 1qmax;
}
</style>
```

**Comment by andruud** [comment]
That's a different question, but OK, how about making the units evaluate against the [selected container](https://drafts.csswg.org/css-contain-3/#container-rule) (see "container selection process") for the container-query/element pair?

```CSS
/* (Syntax borrowed from https://github.com/w3c/csswg-drafts/issues/6393). */
@container type(inline-size) {
   p { padding: 1qi; }
}
```
Here `qi` evaluates against whatever is the current selected container is for the matched element. This way authors have full flexibility.

Otherwise, if there is no enclosing `@container` rule, it evaluates against the nearest container (no mercy).

Worse ideas:

- A function which can be used to select the container explicitly? `calc(1 * qi(<selection>))` (beautiful).
- Custom units and an API to define them?

**Comment by mirisuzanne** [comment]
@andruud lol, _no mercy_.

If I were to do something like this now, without container queries, I would likely set eg `--qi` and `--qb` custom properties on each container with inline or block containment respectively, using JS. Then I would inherit them, and determine the other units from there: 

```css
[data-container~="inline-size"],
[data-container~="size"] {
  --qi: <set via JS>;
}

[data-container~="block-size"],
[data-container~="size"] {
  --qb: <set via JS>;
}

[data-container] * {
  --qmin: min(var(--qi, 0), var(--qb, 0));
  --qmax: max(var(--qi, 0), var(--qb, 0));
}
```

When I think of it that way - it doesn't bother me that the two dimensions might come from different containers. I feel like each unit represents the best info we have about the given axis. So that's making me lean towards doing unit container selection for each axis individually, as though `qi` represents `@container type(inline-size)` and `qb` represents `@container type(block-size)`, and the other units are derived from those.

Then we only need the (merciless) fallback when there is no container in the requested dimension.

**Comment by andruud** [comment]
(Great, you already have a solution! :P)

While not impossible to have different units do their own "implicit container selection", it sounds like a mess to me. And of course it will add much-unneeded paper cuts to performance.

 - What if the unit exists inside an at-container rule which selects some higher-up named container? Having multiple interpretations of the what the selected container is in the same context is what seems like a mess.

```CSS
@container foo (...) {
   p { padding: 2qi; } /* Still resolves against nearest container with inline-size?! */
}
```
 - Is it a commonly needed to use qmax/min with different containers for each axis? If not, perhaps your way is actually good enough if CSSified?

```CSS
@property --qi {
  syntax: "<length>";
  initial-value: 0px;
  inherits: false;
}

@property --qb {
  syntax: "<length>";
  initial-value: 0px;
  inherits: false;
}

@container somelevel {
  p { --qi: 2qi; }
}

@container anotherlevel {
  p { --qb: 2qb; }
}

p { padding: max(var(--qi), var(--qb)); }
```
But I can see how that's a _bit_ verbose if it's a common thing.
