### ISSUE TITLE
[css-contain-3] What container features can be queried?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#5989]
This relates to #5796, adding Container Queries to Contain Level 3.

Since container queries resolve against a contained ancestor element, rather than _the viewport_, we've discussed the ability to use actual/computed font sizes when resolving container dimensions in font-relative units:

```css
html { font-size: 24px; contain: size layout; }

/* resolves against browser default font size - often 16px  */
@media (width > 30em) { /* applies above 480px viewport */ }

/* resolves against container font size - in this case 24px  */
@container (width > 30em) { /* applies above 720px container */ }
```

Would we be able to query other computed values on the container? A few quick examples:

```css
/* custom properties */
@container (var(--color-mode) = dark) {
  a { color: plum; }
}

/* background-color */
@container (background-color = black) {
  h2 { color: white; }
}

/* background-color */
@container (font-style = italic) {
  em { font-style: normal; }
}
```

Some of the use-cases here might overlap with #5624. 

If they are possible, would these queries require the same size/layout/style containment that we need for dimensional queries?

**Comment by matthew-dean** [comment]
It's a fascinating idea. I think to do this, though, you'd have to define what values mean in terms of equality, less than, greater than, etc. As in, say an author did this:
```css
@container (font-weight >= normal) {
// ...
}
```
Is that valid? If so, are we converting `normal` to its numerical value? I mean, it seems intuitive that you would, but I think such conversions for the purposes of queries would have to describe those behaviors. I'm not sure the spec is specific enough for types in order to clearly communicate to vendors what `>` `<` `=` should automatically mean for every single CSS property as it might be compared to every possible value. Or what should happen to the entire query for a type mismatch. Although I've been wrong before lol.

My instinct would be to limit it to layout (height / width), get container queries implemented and everyone used to them, with the knowledge that the types of queries will likely be expanded / further defined in the future.

**Comment by ausi** [comment]
In the container query polyfill I created a while ago, querying other properties is possible too ([demo](https://ausi.github.io/cq-prolyfill/demo/)).

From what I learned, the number of useful properties to query against seems to be quite limited.

> If they are possible, would these queries require the same size/layout/style containment that we need for dimensional queries?

I think containment is only required for properties relating to layout/dimensions. But which parent should get selected as the “container” should be defined on a per property basis. For `background-color` the first ancestor that has a non-transparent background should probably be the “container”. Inherited properties can use the direct parent as the “container”.

I also think it would make sense to limit it to layout at first. Or at least to a limited set of properties that are supported like `background-color`, `color`, `font-size` and `text-align`.

**Comment by andruud** [comment]
Querying standard properties (background-color etc) might introduce too much complexity (not sure), but custom properties seems doable. I guess we can use `@property` to define what <, <=, (etc) means.

**Comment by mirisuzanne** [comment]
I'd want to be real careful about changing the meaning of a "container" based on what is queried. Assuming we keep that definition of an "ancestor with containment", maybe the question is "what else might be useful to query about those existing container elements?"

**Comment by argyleink** [comment]
if more than properties and values can be queried, it'd be amazing to have things like `:stuck`, `:overflow`, `:snapped`, `:on-screen`, `:wrapping`, `:ellipsing`, etc. these are more like browser internal states or do they fit the question?

**Comment by mirisuzanne** [comment]
@argyleink That's an interesting idea. I feel like it would need some clarifying syntax - since the default is a computed value comparison, and this is something new… Maybe like:

```css
@container state(stuck) { … }
@container (min-width: 30em) and not state(overflow) { … }
```

**Comment by argyleink** [comment]
I like that, sure reads nice

```css
@container state(stuck) {
  nav {
    --box-shadow-y-distance: 15px;
  }
}
```

```css
@container state(in-view) {
  section {
    animation: reveal .5 ease forwards;
  }
}
```
