### ISSUE TITLE
[css-contain] Is it possible to apply containment inside @container?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6177]
Is this allowed, or does it lead to cyclic dependencies?

```css
.parent, .child { contain: layout inline-size; }

@container (inline-size > 30em) {
  .child { contain: initial; }
  .grandchild { /* which container is queried? */ }  
}
```
