### ISSUE TITLE
[selectors][mediaqueries] :media() pseudo-class as a shortcut for media queries

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#6247]
Authors often need to duplicate rules across media queries and selectors. For example, this kind of thing is common:

```css
@media (prefers-color-scheme: dark) {
	:root {
		/* dark mode rules */
	}
}

:root.dark {
	/* duplicated dark mode rules */
}
```

To my knowledge, there is no way to reduce this duplication currently, even if we take CSS nesting into account.

Also, often media queries only contain a single rule, and could benefit from a more concise syntax.

With this proposal, the code above would be written as:

```css
:root:is(.dark, :media(prefers-color-scheme: dark)) {
	/* dark mode rules */
}
```

Any `:media()` pseudos within a selector would desugar as media queries, joined with `and` and prepended with `not` accordingly (e.g. `:media(foo):not(:media(bar))` should desugar to `@media (foo) not (bar) {...}`).

**Comment by tabatkins** [comment]
I definitely agree with this functionality. Having some tests appear in an MQ vs others appearing in a selector means we have to do some awkward nesting and reduplication. This is also the motivation behind a generic conditional rule that combines @media and @supports (the [@when proposal](https://tabatkins.github.io/specs/css-when-else/) that I need to revive).

With that background, perhaps we should make the pseudo-class name more generic, so that it can handle support queries as well?

**Comment by LeaVerou** [comment]
> With that background, perhaps we should make the pseudo-class name more generic, so that it can handle support queries as well?

Agreed, I was wondering about it when I opened the issue, but decided against it as I thought it would complicate the syntax too much. But if you also think so, let's do that.

**Comment by argyleink** [comment]
I ran into this last week and after asking Tab about it, have found myself here!

Here's a reduced case https://codepen.io/argyleink/pen/OJpmEWE where I would hope to eliminate the duplication between light and dark

**Comment by bkimmel** [comment]
I love this idea. I kinda wish media queries just worked this way in the first place.

**Comment by mirisuzanne** [comment]
We discussed this as an approach to container queries, and it's probably good to consider them as part of this conversation. If the only syntax is selector-based, it makes larger changes (impacting multiple selectors) more repetitive – though nesting could help that problem:

```css
.card:container(width > 30em) {
  & .card-image { … }
  & .card-content { … }
  & .card-footer { … }
}
``` 

With container queries specifically, this also introduces a different way to solve the "named container" problem – but it can be kinda confusing as well. Right now we always have the selector-target query its nearest container:

```css
/* body and card are both containers */
body, .card { contain: inline-size style layout;

@container (width > 30em) {
  .card { /* card queries the size of body */ }
  .card .content { /* content queries the size of card */ }
}

.card:container(width > 30em) .content {
  /* card queries the size of body, in order to update content */
}
```

I don't see it as a universally better solution than the at-rule syntax, but I do think it can provide some interesting trade-offs. Interested to see where this conversation goes.

**Comment by andruud** [comment]
Adding `:container` probably exceeds acceptable complexity limits. It makes invalidation much more annoying, since we would need to figure out if a given selector _would have matched_ without `:container` pseudos, and in order do that correctly we would probably need to evaluate any non-matching selector with `:container` _twice_, which I'd rather not do.

Also, you know Emilio won't accept that it makes Element.matches depend on _layout_.

Also _also_, it's not compatible with other CSS things, e.g.:

```
body {
  width: 40em;
  contain: inline-size style layout;
}

body:has(.card:container(width > 30em)) {
  width: 20em;
}
```

**Comment by romainmenke** [comment]
Might be more interesting to leverage `@scope` as mentioned n the examples.
https://drafts.csswg.org/css-cascade-6/#scoped-styles

```css
@scope (.light-scheme) {
  a { color: darkmagenta; }
}

@scope (.dark-scheme) {
  a { color: plum; }
}
```

With `when` it could become :

```css
@when media(prefers-color-scheme: dark) or scope(.dark) {
  /* styles */
}
```

------

I do think it will have some weird side-effects to mix conditional at-rules and selectors:

```css
@when media(prefers-color-scheme: dark) {
  @layer foo {
    /* this is fine */
  }
}
```

```css
.dark {
  @layer foo {
    /* this is not fine */
  }
}
```

```css
@when media(prefers-color-scheme: dark) or scope(.dark) {
  @layer foo {
    /* ?? */
  }
}
```

Same is true for other syntax proposals.

```css
:root {
  @media (prefers-color-scheme: dark),
  &.dark {
    @layer foo {
      /* ?? */
    }
  }
}
```

**Comment by tabatkins** [comment]
Putting selectors into MQs/etc has the wrong semantics; the selector isn't a query with a truth result, it's actually selecting elements, a completely independent action from the conditional itself.  `:media()` has the correct semantics.

**Comment by jakearchibald** [comment]
> `:media()` has the correct semantics.

Well, not really. Pseudo-classes are query something about the element, whereas `:media()` is querying the viewport. It's a bit of a hack that it's classed to the element.

Fwiw, that's why I suggested:

```css
:root {
  @media (prefers-color-scheme: dark),
  &.dark {
    /* dark mode rules */
  }
}
```

It's saying "this block of styles applies when this media query matches, or where this selector matches". It isn't putting MQs into element classes, nor is it putting selectors into MQs.

**Comment by tabatkins** [comment]
> Pseudo-classes are query something about the element, 

My point is that the *semantics* of a pseudo-class (any selector, really) is "filter the currently-matched set of elements according to condition X". The fact that `:media()`'s condition isn't element-specific doesn't change this, it just makes it feel a little funny. (We could always define that the pseudo-class only matches on the root element, to make it feel more "global", but I think that would make things unnecessarily annoying in practice.)

Conditional rules, on the other hand, either match or not, and activate or deactivate the rules inside of them. They haven't previously had any effect on the set of matched elements. Obviously we could add this, changing their pattern of behavior, but it would be a fairly significant change. We could no longer imagine conditional rules as "turning off" rules, but rather as a type of selector in itself that filters the set of matched elements.

(Also a nit: putting selector syntax nakedly into MQ syntax would be a no-go; the grammar is too wide and would force us to be very careful evolving both selectors and MQs in the future. But a `selector()` function would work.)

**Comment by jonathantneal** [comment]
> Pseudo-classes are query something about the element, whereas `:media()` is querying the viewport.

I think context _is_ something about the element. A similar API would be `:has()`.

Here is a hypothetical example of context by target class or media query:
```css
:root:is(.dark, :when(media(prefers-color-scheme: dark))) {
	/* dark mode rules */
}
```

Here is a hypothetical example of context by target class or style query:
```css
:root:is(.dark, :when(style(--mode: dark))) {
	/* dark mode rules */
}
```

**Comment by NickGard** [comment]
Getting back to the problem of code duplication, could we do something similar to SASS's mixin? 

Instead of setting a Custom Property flag and using container queries to style, you could add a block of code to a ruleset.
```css
/* With flag */
.dark { --mode: dark; }
@media(prefers-color-scheme: dark) { --mode: dark; }

@container(style(--mode: dark)) {
  /* rules */
}

/* With mixin */
@mixin dark-mode {
  /* rules and nested rules that will map to the selector that includes the mixin */
}

.dark { @includes dark-mode }
@media(prefers-color-scheme: dark) {
  @includes dark-mode 
}
```
It doesn't have to be as full-featured as SASS's mixin, just the code reuse and dynamic scoping would be enough.

**Comment by brandonmcconnell** [comment]
Would this pseudo-class counterpart to the `@media` at-rule work directly on selectors or only inside `:is()` and `:not()`? I'd guess both, but I only see examples within other pseudo-class rules on this thread.

Assuming this applies to all applicable at-rules, this might also solve the issue/proposal I opened today in #10356.

This way, `@starting-style` rules can be applied inline with other selector-based rules to avoid redundancy. One of the spec's authors, @dbaron, also spoke into the discussion and voiced a similar sentiment.
> I agree that we ended up with a solution that requires a bunch of repetition that I'm not happy about.

Having a way to use these at-rules inline as pseudos would be amazing.

I initially preferred the syntax proposed by @jakearchibald (above) and by @jothsa in #8840, but that would also impose some limitations. In the case of `@starting-style`, this would still not allow the at-rule to mix with selector logic in the ways necessary to remove redundancy.

However, with a pseudo-class rule counterpart available, much of the redundancy in this example:
```css
dialog {
  transform: translateY(-50%);
  &, &::backdrop {
    transition: all 0.25s ease-out allow-discrete;
    opacity: 0;
  }
  &[open] {
    transform: translateY(0);
    &, &::backdrop {
      opacity: 1;
    }
  }
  @starting-style {
    &[open] {
      transform: translateY(-50%);
      &, &::backdrop {
        opacity: 0;
      }
    }
  }
}
```

…can be consolidated, leaving us with this:
```css
dialog {
  &, &[open]:starting-style {
    transform: translateY(-50%);
    &, &::backdrop {
      transition: all 0.25s ease-out allow-discrete;
      opacity: 0;
    }
  }
  &[open] {
    transform: translateY(0);
    &, &::backdrop {
      opacity: 1;
    }
  }
}
```

I think @jonathantneal's suggestion of introducing a `:when` pseudo for this could also work well, as long as `starting-style` would be valid within `@when()` rules `:when()` wouldn't pose a significant risk of confusion (between `:where()` and `:when()`).

If we did want a way to match the query syntax exactly, we could consider `:matches(@media(…))`, but I think that might be a step backward with the more flexible `@when` on the horizon.

---

It might help to organize a comprehensive list of all at-rules that could benefit from a pseudo-class counterpart like this.
* `@when`
* `@media`
* `@supports`
* `@starting-style`
* any others?

Or should we introduce only one new pseudo-class, `:when()` which can be used to test for any of these and others?

**Comment by trusktr** [comment]
If this comes out, please make sure it intuitively works with the `color-scheme:` property.

This currently does not work as intuitively expected based on CSS nesting:

```css
foo {
  color-scheme: only light;
}

bar {
  color: black

  @media (prefers-color-scheme: dark) {
    color: white;
  }
}
```
```html
This text is white in dark mode, or black in light mode.

<foo>
  <bar>
    I expected this text to always be black (light mode) because of the color-scheme override in foo (only light) forcing light mode for the subtree in foo
  </bar>
</foo>
```

This does not work: although `foo` has `color-scheme` set to `only light`, the media query nested inside of `bar` will still be triggered by the OS-level setting, instead of the nearest ancestor's `color-scheme` mode.

Here is a CodePen example showing the issue:

https://codepen.io/trusktr/pen/wBKJZRz

It makes intuitive sense for `color-scheme` to override the OS-level mode anywhere in the tree, especially for nested `@media`.

This already works fine for the `light-dark()` function, so a workaround for code that is made with `@media` that wishes to introduce app-specific light/dark settings is to port from media queries to `light-dark()` for all values. An alternative is to use JavaScript to place a `data-theme="dark"` attribute on `html` and use `[data-theme='dark']` or `:host-context([data-theme='dark'])` selectors (including nesting) instead of `@media`, making it possible to write `data-theme` attributes on particular sub trees rather than using `color-scheme`.
