### ISSUE TITLE
[css-env] border radius

### ISSUE THREAD

**Issue by mantou132** [w3c/csswg-drafts#6259]
In some operating systems (such as macOS), the browser has a rounded corner of the border. When the page content sets the border, need to adapt this rounded corner

# Proposal

Add `safe-border-top-left-radius`, `safe-border-top-right-radius`, `safe-border-bottom-right-radius`, `safe-border-bottom-left-radius`  environment variables.

# Example

```css
body {
  border: 10px solid red;
  border-bottom-left-radius: env(safe-border-bottom-left-radius, 0);
  border-bottom-right-radius: env(safe-border-bottom-right-radius, 0);
}
```

current case:
<img width="797" alt="Screen Shot 2021-05-01 at 10 25 56 PM" src="https://user-images.githubusercontent.com/3841872/116788471-59242480-aadc-11eb-86d9-f287bf7a71ba.png">
