### ISSUE TITLE
Prevent layout jumps on changing overflow hidden to scroll

### ISSUE THREAD

**Issue by amir2mi** [w3c/csswg-drafts#6262]
This is an obvious one but let me dissect it.

First of all look at the Slack.com sidebar scrollbar, it is pretty great and natural, something that can be done on the web when you know hacks and do some tricks:
![CSS: Prevent layout jumps on changing overflow hidden to scroll](https://s19.picofile.com/file/8432450618/true_gif.gif)

Now see the version of browser pure scrollbar that I have made with that:
![CSS: Prevent layout jumps on changing overflow hidden to scroll](https://s19.picofile.com/file/8432446118/false_gif.gif)

Here is the simple code of this behavior:
```css
.sidebar{
     overflow: hidden;
}

.sidebar:focus-within,
.sidebar:hover{
     overflow: auto;
}
```

So when the scrollbar is displayed it is part of its wrapper and adds its width, which causes unwanted layout jumps and shifts other parts.
In contrast, when a modal wants to be shown body **overflow** should be **hidden** to prevent the user from scrolling, and here we have another layout jumping again and it is disgusting; there are [hacks for this](https://codepen.io/amirmp3/pen/rNjEbzj) but it is not enough, to be honest.

I wish if we had a feature in CSS to optimize these situations like this:
```css
.sidebar{
     scrollbar-place: beside | over;

     // beside as default
     // 'over' means it does not have any effect on neighbors something like [position: absolute] for elements.
}
```

In my dreams, I think about pure web scrollbars like native operating system smart scrollbars:
![Windows 10 scrollbar in css](https://s18.picofile.com/file/8432448468/windows_dreamy_scrollbar.gif)

I searched about it but it seems there is no native way to handle this situation if there is let me know.
