### ISSUE TITLE
[css-images] Consider making -webkit-image-set a parse-time alias to image-set

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6285]
Per the discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1709415 it seems `-webkit-image-set` may be used enough on the wild that supporting it as a parse-time alias would be a low effort compat win.

If my reading of the WebKit code is right, WebKit supports the prefixed version with an slightly stricter syntax, but they serialize to the modern syntax. I think it'd be good if they just supported the same syntax, since the modern syntax is an extension of the webkit one, and it's less maintenance.

cc @smfr.

**Comment by foolip** [comment]
An alias would be great if it's web compatible. Is the prefixed form more limited in what syntax it accepts? If so, if (almost) all allowed syntax for the unprefixed form work with the prefixed one, then this should be pretty safe.

Or is it the other way around?

**Comment by emilio** [comment]
Yeah, prefixed syntax is more limited, and a strict subset of the modern one.

**Comment by foolip** [comment]
That's great! I guess the only risk then is use of the prefixed variant that's currently rejected but would start working and have an unintended effect. It's not super common but not a theoretical problem. This could be answered with httparchive or use counters probably.

**Comment by emilio** [comment]
@tabatkins fyi tests for this are in https://github.com/web-platform-tests/wpt/commit/6ea104531e81351cfe53751813fa6a2dd471a528

**Comment by tabatkins** [comment]
Oh nice, thanks!

**Comment by yisibl** [comment]
I found that the implementation of -webkit-image-set() in Firefox is completely a standard image-set() mapping, and some new syntaxes are not supported in WebKit/Blink. This seems to be confusing. Does Firefox need to fully follow the existing syntax in WebKit/Blink?

e.g.

```css
.foo {
  background: -webkit-image-set('../img/image-1x.jpg' 1x, '../img/image-2x.jpg' 2x) /* WebKit/Blink invalid */
  background: -webkit-image-set('../img/image-1x.jpg' 1x, linear-gradient(black, white) 2x) /* WebKit/Blink invalid */
  background-image: -webkit-image-set('../img/image-1x.jpg' 1dppx, '../img/image-2x.jpg' 2dppx); /* WebKit/Blink invalid */
}
```
