### ISSUE TITLE
[css-fonts-4] @font-family src: should accept a specifier which lists font requirements

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#633]
When discussing the format() specifier with regards to font variations, we came across diverging behavior between different browsers.

There are two possible mechanisms (that I know of) for fallback:

``` css
@font-face {
    ...
    src: url("file-novariations.otf") format("opentype");
    src: url("file-variations.otf") format("opentype", "variations");
}
```

and 

``` css
@font-face {
    ...
    src: url("file-variations.otf") format("opentype", "variations"), url("file-novariations.otf") format("opentype");
}
```

Currently, with either of the above examples, Edge and Firefox would download the variation font even when though those browsers don't (currently) understand variations.

The spec states:

> The format hint contains a comma-separated list of format strings that denote well-known font formats. Conformant user agents must skip downloading a font resource if the format hints indicate only unsupported or unknown font formats.

This seems to imply that the format() identifier will be used if any of the arguments are known. Instead, in order to support modern and future font behaviors, web authors should be able to list the requirements that the browser needs to understand in order to use a font.

This could either be changing how format() works, adding a new specifier, or something completely different.

**Comment by svgeesus** [comment]
So something like
src: url("file-variations.otf") format("opentype") requires("variations");

**Comment by litherum** [comment]
I expect something similar would be needed for fonts using the "SVG " OpenType table.

**Comment by svgeesus** [comment]
Yes (same for "COLR"), if the stylesheet author didn't want to just use the default fallback.

**Comment by tabatkins** [comment]
> This seems to imply that the format() identifier will be used if any of the arguments are known.

This is because the purpose of multiple strings in format() is to supply multiple (usually OS-specific) names for the same format (yay real-world compat), not list multiple features that the font requires support for.

Rather than minting a new function, as Chris suggests, we could just expand the grammar for format(), like:

```
format() = format( [ <format-string> | requires <feature-name> ]# )

src: url("file-variations.otf") format("opentype", requires variations);
```

**Comment by svgeesus** [comment]
I prefer the new function, rather than overloading the format specifier. The font/* top level type includes a field for the css @font-face format string, fone for each or each media type. (Indeed, the whole reason we have a format string is because there were no MIME types for fonts, and adding them was strongly resisted at the time). Overloading it with the requires stuff is awkward, a separate function seems cleaner.

**Comment by PeterCon** [comment]
What about defining new values that add additional specificity: "opentype-variation", "opentype-colr", etc.?

**Comment by jfkthame** [comment]
> What about defining new values that add additional specificity: "opentype-variation", "opentype-colr", etc.?

The "etc." there worries me.... the number of features/capabilities/requirements that we might want to expose (e.g. variations, COLR glyphs, SVG glyphs, CBDT glyphs, etc) combined with the variety of packaging formats (opentype, woff, woff2, ...) leads to a lot of possible values if we define a unique new value for each combination.

One possible approach, I suppose, would be to define a microsyntax used _within_ the format hint string, e.g. splitting it into tokens on comma or some such character (even hyphen would be possible, I guess, though IMO comma reads better):

    src: url("file-colr-var.otf") format("opentype,colr,variations"),
         url("file-svg-var.otf") format("opentype,svg,variations"),
         url("file-var.otf") format("opentype,variations"),
         url("file-colr.otf") format("opentype,colr"),
         url("file-svg.otf") format("opentype,svg"),
         url("file-fallback.otf") format("opentype");

Existing UAs will drop sources with the new-style format hints, avoiding the problem with the `format("opentype", "variations")` version.

The UA would split the format hint into fragments and use the source only if it supports _all_ the individual requirements listed in its format.

**Comment by PeterCon** [comment]
> The "etc." there worries me.... leads to a lot of possible values if we define a unique new value for each combination.

Your concern with combinatorial multiplication is valid. I like your alternative.

**Comment by behdad** [comment]
> The UA would split the format hint into fragments and use the source only if it supports all the individual requirements listed in its format.

I had something like this in mind as well.  Ie. more like BCP 47 language tags that need to be broken down and understood.  Also, the current option in format() that multiple values can be passed can be used to pass the grandfathered existing keywords for older clients.  Eg. format("ot-cff", "opentype").  Where opentype is the old tag and "ot-cff" new one.

**Comment by AmeliaBR** [comment]
I was thinking of this issue this week, and thinking that it would be best to build on the OpenType concept of named "tables" for each feature.

So, if a browser should only download a font if it knows what to do with a CPAL (color palette) table, say that. If a browser should only download the font if it knows how to use an FVAR (font variations) table, say that.  If the browser should download the font if it knows how to use _both_ a CPAL table _and_ an FVAR table, say that.

This therefore avoids any new debates on naming things, about what a "color" font is or isn't and so on, while keeping it easily open-ended to new features added to OpenType.

As for the syntax, I think it would be best to follow the MIME type with parameters format, which is currently used to specify charsets for text-based files, and codecs for video and audio package formats (see the [MIME-sniff spec](https://mimesniff.spec.whatwg.org/#parameters), or [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.1) for the full spec).

I know the `format()` strings aren't proper MIME type strings to start with (because they don't include the initial `font/` part), but might as well follow it as best we can from there on.

So something like:

```css
@font-face {
  font-family: heading-font;
  src: url(fancy-font.woff2) format("woff2;tables=COLR,FVAR"),
        url(fallback-font.woff2) format("woff2"),
        url(fallback-fallback-font.woff) format("woff"),
        url(how-old-is-your-browser-font.ttf) format("ttf");
}

Of course, you wouldn't need to specify _every_ OpenType table in the format string; only the essential ones that you want the browser to consider as a feature support test.

**Comment by AmeliaBR** [comment]
Addendum:

It looks like MIME type parameters are supposed to be part of a MIME type registration, and [`font/otf`](https://www.iana.org/assignments/media-types/font/otf) already has an "outline" parameter to distinguish TTF, CFP, and SVG outlines.  But you'd need to contact someone named @svgeesus to get parameters added to the WOFF & WOFF2 registrations.

**Comment by svgeesus** [comment]
> So, if a browser should only download a font if it knows what to do with a CPAL (color palette) table, say that. 
Suppose an implementation can handle `COLR`+`CPAL` but not `SVG `+`CPAL`? OK in that case there is still a single table name that can be used, but sometimes it really is the case of certain combinations of tables or certain parts of tables (`OS/2` springs to mind) or certain versions of tables (the many versions of `CMAP` for example).

> I know the format() strings aren't proper MIME type strings to start with (because they don't include the initial font/ part), 

I initially planned to use MIME types there, but given _significant_ resistance to the idea of a font/* top level type we went with the 'format' string as a temporary workaround. Temporary meaning two decades or so.

> It looks like MIME type parameters are supposed to be part of a MIME type registration,

Yes in general, and yes for the specifics of the font/* top level type. See the registration procedure in [RFC 8081](https://tools.ietf.org/html/rfc8081).

However, putting files on a web server is significantly complicated if parameters need to be set; and then we also need to deal with legacy and mis-configured servers. Part of the goal of RFC 8081 was to align specifications with actual widely deployed practice.

In my experience, content negotiation of that sort is easier and more likely to work if client driven. So I would rather see a new `features()` string in the stylesheet than a complex  parameter-based addendum to Media Types.

```css
@font-face {
  font-family: heading-font;
  src: url(fancy-font.woff2) format("woff2") features("CPAL,FVAR"),
        url(fallback-font.woff2) format("woff2"),
        url(fallback-fallback-font.woff) format("woff"),
        url(how-old-is-your-browser-font.ttf) format("ttf");
}
```

**Comment by AmeliaBR** [comment]
>  I would rather see a new `features()` string in the stylesheet

That definitely looks nicer to read. And my main comment was about re-using OpenType table names, anyway, the rest was mostly musings.

One limitation, though: by adding a separate `features` parameter, instead of overloading `format()`, wouldn't we break the syntax for existing browsers?  So you'd actually need to write (for the near-future, anyway):


```css
@font-face {
  font-family: heading-font;
          /* fallback stack for browsers that don't know features() */
  src: url(fallback-font.woff2) format("woff2"), 
        url(fallback-fallback-font.woff) format("woff"),
        url(how-old-is-your-browser-font.ttf) format("ttf");
  src: url(fancy-font.woff2) format("woff2") features("CPAL,FVAR"),
           /* fallback for browsers that understand features(), but don't support these features */
        url(fallback-font.woff2) format("woff2"); /* assume woff2 support in this case */
}
```

Which is sub-optimal, but no worse than oodles of other similar fallback redundancies in modern stylesheets.
