### ISSUE TITLE
[css-nesting] Meaning of using multiple &

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#6336]
```css
div {
  @nest & > & {
    color: blue;
  }
}
```

What's the meaning of this? Does it match all `div` element which are a child of another `div` element, just like

```css
div > div { color: blue }
```

Or does it only match the `div` elements which are a child of themselves (i.e. match nothing)?

**Comment by Loirooriol** [comment]
OK, I missed this example from the spec:

```css
.foo {
  color: blue;
  & .bar & .baz & .qux { color: red; }
}
/* equivalent to
   .foo { color: blue; }
   .foo .bar .foo .baz .foo .qux { color: red; }
 */
```
