### ISSUE TITLE
[css-flexbox] new flex wrap value that changes the flex direction

### ISSUE THREAD

**Issue by manuelmeister** [w3c/csswg-drafts#6366]
I couldn't find a way to style parent & child, so that it behaves like Version 1 & 3 depending on the content: 

![wrap](https://user-images.githubusercontent.com/3001985/121332544-42ad8c00-c918-11eb-8b65-dafebcac814c.png)

The content is unknown, could be "A", "B" & "C" or "A", "B" & "VERYLONG", … could be more than 3 elements. This eliminates media width queries.

I thought of something like this:
```css
body {
  max-width: 200px;
}

container {
  display: inline-flex;
  flex-direction: row;
  flex-wrap: flip-flex-direction;
}
```

**Comment by Loirooriol** [comment]
So if the items don't fit into the row, it changes into column direction. But what if they don't fit into the column either? Do they wrap into a 2nd column?

**Comment by manuelmeister** [comment]
> Do they wrap into a 2nd column?

I don't think so. It would only change the flex direction from `row` to `column` and from `column` to `row`. There would only be two possible new values for `flex-wrap`: `direction` and `direction-reverse`.

Further behavior would probably be too complicated.

**Comment by mgrsskls** [comment]
I have a (for me) very common use case for that as well: I often have a horizontal navigation in a footer with an undefined amount if links in there. What I usually want then is that as soon as the first link does not fit into the row anymore, I want the navigation to become a column.

Using `flex-wrap: wrap` would be ideal for me here, but instead of wrapping only the element that does not fit, I want all elements to wrap. I had initially thought of something like `flex-wrap: wrap all`.

**Comment by devongovett** [comment]
Would be amazing to be able to do this in pure CSS. Our [Button Group](https://spectrum.adobe.com/page/button-group/#Behaviors) component in Spectrum swaps orientation from horizontal to vertical when space is limited, and we currently have to implement this with some tricky JavaScript. However this has the downside that the initial layout is potentially incorrect on page load before the JS has executed. I agree with the previous commenters that an extension of `flex-wrap` seems like the simplest solution.

**Comment by devongovett** [comment]
Related: https://ishadeed.com/article/flex-wrap-detect/. This proposes a `:wrap` pseudo-class to detect when a flex container wraps. Not sure if that's possible for similar reasons as `:stuck`, but it has some good examples of the kinds of problems that often need to be solved. There are numerous stack overflow questions about this as well.

**Comment by Loirooriol** [comment]
Yes `:wrap` is circular:

```css
.flexbox:wrap {
  flex-wrap: nowrap;
}
```

**Comment by spartanatreyu** [comment]
Some developers are getting around the lack of flex-wrap detection using the _albatross hack_ (pictured here):

![Image](https://github.com/user-attachments/assets/af05e58d-fed1-4fc8-a15d-b4d58da2b854)

Here's the initial post describing the _first albatross hack_ and the problem it solves: https://heydonworks.com/article/the-flexbox-holy-albatross/

Here's the follow-up post showing the _simplified albatross hack_: <https://heydonworks.com/article/the-flexbox-holy-albatross-reincarnated/>

And here's a separate post breaking down the _albatross hack_, how it works, extending it, and it's limitations: <https://snook.ca/archives/html_and_css/understanding-the-flexbox-albatross>

If the circular issue can be resolved, a `:wrap` pseudo-class / `flex-wrap: wrap all` extension / container state wrap query or other similar solution would remove the need for the albatross hack and it's limitations.

**Comment by jamiebuilds** [comment]
This can somewhat be achieved today with `scroll-state()` container queries with the caveat that once it switches direction it can't switch back

Demo: https://codepen.io/jamiebuilds/pen/JoRoYXx?editors=1100

```html
<div class="container">
  <div class="flex">
    <div class="item">Item 1</div>
    <div class="item">Item 2</div>
    <div class="item">Item 3</div>
  </div>
</div>
```

```css
.container {
  container-type: scroll-state;
  overflow-x: hidden;
}

.flex {
  display: flex;
  gap: 5px;
  
  /* not scrollable */
  @container scroll-state(scrollable: none) {
    .item {
      min-width: fit-content;
    }
  }

  /* scrollable */
  @container not scroll-state(scrollable: none) {
    flex-direction: column;
    /* fix for cycles: make scrollable state "sticky" */
    width: calc(100% + 1px);
  }
}

.item {
  flex-grow: 1;
  background: dodgerblue;
}
```

**Comment by kizu** [comment]
I noticed that I never shared my “solution” for this from my [“Position-Driven Styles”](https://kizu.dev/position-driven-styles/#flex-wrap-detection) article — with it, it is possible to do via scroll-driven animations, in both directions (but, now testing it — in Safari it is a bit buggy; will need to debug and fill a bug)

**Comment by jamiebuilds** [comment]
@kizu Thank you for sharing this, it was super enlightening! And I found a way to merge your [tabs](https://kizu.dev/position-driven-styles/#tabs) approach with mine:

Instead of splitting up the first item and the rest, it wraps around your flex container and uses an extra element to force the scroll container to overflow when your items would need to start wrapping.

Demo: https://codepen.io/jamiebuilds/pen/gbwbrwq?editors=1100

```html
<div class="flex-wrap-detector-container">
  <div class="flex-wrap-detector-overflower"></div>
  <div class="flex-wrap-detector-contents">
    <div class="flex">
      <div class="item">Item 1</div>
      <div class="item">Item 2</div>
      <div class="item">Really really long item 3</div>
    </div>
  </div>
</div>
```

```css
.flex-wrap-detector-container {
  container-type: scroll-state;
  display: flex;
  flex-wrap: wrap;
  overflow-x: hidden;
}

/* extra element to force the scroll container to overflow when items wrap */
.flex-wrap-detector-overflower {
  position: relative;
  flex-grow: 1;
  
  &::after {
    content: "";
    display: block;
    position: absolute;
    right: -1px;
    width: 1px;
    height: 1px;
  }
}

/* The contents should grow rather than the overflower when they are in the same row */
.flex-wrap-detector-contents {
  flex-grow: 9999;
}

.flex {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.item {
  flex-grow: 1;
  background: dodgerblue;
  
  /* when scrollable */
  @container not scroll-state(scrollable: none) {
    width: 100%;
  }
}
```
