### ISSUE TITLE
[css-backgrounds] border-radius with a circular edge

### ISSUE THREAD

**Issue by jonathantneal** [w3c/csswg-drafts#6467]
Is there, or could there be a more semantic way to describe a border radius as being round rather than some current conventions?

From [TailwindCSS](https://github.com/tailwindlabs/tailwindcss/blob/v2.2.4/stubs/defaultConfig.stub.js#L150):

```css
.rounded-full {
  border-radius: 9999px;
}
```

From an [accepted StackOverflow answer](https://github.com/tailwindlabs/tailwindcss/blob/v2.2.4/stubs/defaultConfig.stub.js#L150):

```css
#rect {
  border-radius: 100000000000000px;
}
```

Other examples include `9999em` or `100vmax`.

Perhaps we could introduce a keyword, like `round`?

```css
.rounded-full {
  border-radius: round;
}
```

```css
#rect {
  border-radius: round;
}
```

**Comment by nickfla1-mxm** [comment]
Just a minor note:

> From an [accepted StackOverflow answer](https://github.com/tailwindlabs/tailwindcss/blob/v2.2.4/stubs/defaultConfig.stub.js#L150):

Points to the wrong url (same as Tailwind).

**Comment by argyleink** [comment]
YES

**Comment by Loirooriol** [comment]
Maybe `calc(1px / 0)` or `calc(infinity * 1px)` look less arbitrary than `100000000000000px`?

**Comment by argyleink** [comment]
could use `border-radius: 1e5px` too

**Comment by jonathantneal** [comment]
Thank you, @nickfla1-mxm! The link has now been updated.

**Comment by anthonyrivas** [comment]
As much as I would love to see this, is there any concern that the term round or something similar could be confusing? Perhaps something more like "max" would be more descriptive? 

Generally any radius is making a corner round to some degree, but "max" may better indicate that it is meant to be fully rounded?

**Comment by yisibl** [comment]
This has indeed troubled developers for many years, and using `999px` or `9999px` is too hack.

**Comment by jonathantneal** [comment]
While I don’t want the request for a semantic value to get confused with bikeshedding a specific keyword solution, I hope it will be helpful to share something I’ve learned. Having reviewed the specification for `corner-shape` in [css-backgrounds-4](https://drafts.csswg.org/css-backgrounds-4/#corner-shaping), I now think `border-radius` would need a keyword that somehow describes the radii without describing its _shape_.

Here is an example of using `border-radius` and `corner-shape` from the current specification:

```css
a {
  border-radius: .3em .8em .8em .3em / .3em 50% 50% .3em;
  corner-shape: round angle angle round;
  padding: .5em 1em .5em .5em;
}
```

I think it would be confusing to write `border-radius: round; corner-shape: angle`. Therefore, a better term might be something like `fill`, `quarter`, etc.

**Comment by fantasai** [comment]
Why is `border-radius: 100%` not good enough for you?

**Comment by yisibl** [comment]
While Chrome and Safari already implement the `infinity` keyword, a separate `border-radius: round` might help optimize browser performance. And it's easier for developers to understand.

`calc(1px / 0)` or `calc(infinity * 1px)` still looks like a hack.

![image](https://user-images.githubusercontent.com/2784308/145769251-85c440a5-8ccf-4491-95c4-883a12eaf0b9.png)

**Comment by simevidas** [comment]
Since a circular border is a the result of a radius that is as large as possible, maybe the optimal keyword for this would be one that describes exactly that.

```css
{
  border-radius: maximum;
}
```
