### ISSUE TITLE
[css-flexbox] placeholder pseudo-element fails to be flex item

### ISSUE THREAD

**Issue by vwkd** [w3c/csswg-drafts#6536]
I couldn't find anything in the spec related to why Flexbox doesn't apply to the `::placeholder` pseudo-element of `<input>` and `<textarea>` elements.

Yet in none of Chrome, Firefox and Safari I could get it to align using the Flexbox alignment properties. Meanwhile, `::before` and `::after` pseudo-elements align just fine using Flexbox.

I'm opening this issue to clarify if this is a browser bug that happens to be present in all browsers, or if I'm missing something in the Flexbox spec.

---

Example:

```css
textarea {
  height: 10rem;
  display: flex;
  /* should align placeholder center center */
  align-items: center;
  justify-content: center;
}

input {
  height: 10rem;
  display: flex;
  /* should align placeholder top center */
  align-items: flex-start;
  justify-content: center;
}
```

```html
<textarea placeholder="Some text"></textarea>

<input placeholder="Some text" />
```
