### ISSUE TITLE
[css-scroll-animations] Rethinking declarative syntax for scroll-linked animations

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6674]
### Overview ###

@mirisuzanne and I reviewed the [Scroll-linked Animations ED](https://drafts.csswg.org/scroll-animations-1/) this week. We have some concerns (which are at a high level similar to Robert O'Callahan's concerns with the initial proposals for “[CSS Snap Points](https://www.w3.org/TR/2015/WD-css-snappoints-1-20150326/)” that became the current [CSS Scroll Snap Module](https://www.w3.org/TR/css-scroll-snap-1/)):

- The model seems to rely a lot on explicit offsets, rather than on element positions. Typically the reason for using offsets is to align with elements.
- There is functionality to use element-based offsets, but these rely on ID selectors, which are not particularly portable across pages and makes it impossible for styles to be re-used in multiple places on the same page.

We'd like to propose a replacement of the declarative syntax in this module that addresses these problems. Note: This is part of our [larger proposal](https://wiki.csswg.org/ideas/timelines) rethinking various features for animation timelines and interpolation and how to fit them all together.

Our suggestion splits scroll-linked animation timelines into two types: those linked to the scroll timeline as a whole, and those linked to the portion of it in which a particular element participates.

### Animations linked to scroll progress as timeline ###

These are animations whose timeline goes from 0% to 100% based on the scroll position of an ancestor scroll container.

#### animation-timeline: scroll() ####

The idea is to use an inline functional notation to identify the timeline using the `animation-timeline` property, expanding the property's syntax as follows:

```
animation-timeline: auto | scroll(<scroll-direction>? <scroller>?);
<scroll-direction> = block | inline | vertical | horizontal
<scroller> = root | nearest | <container-name>
```
* `auto` is the initial value of `animation-timeline`, and behaves as animations have always done, triggering on application of the animation and lasting for the specified duration and delay.
* `nearest` references the nearest ancestor scroll container
* `root` references the main viewport scroller
* `<container-name>` references the `container-name` property: it filters the lookup to the nearest scroll container with the given `container-name`. (See css-contain-3.)
* The default direction is `block`; the default scroll container lookup is `nearest`

#### animation-timeline: NAME ####

Alternately, some scroll-timeline properties could be defined, which when applied to a scroll container would allow naming its timeline for a more indirect but reusable approach.

```
scroll-timeline-name: <custom-ident>#;
scroll-timeline-direction: <scroll-direction>#;
scroll-timeline: [<scroll-direction>? <custom-ident>]#;
```

Such named scroll timelines would be referenceable by name from the `animation-timeline` property.

```
animation-timeline: auto | <timeline-name>
```

### Animations linked to view progress as timeline

Often animations are desired to start and end while a particular element is in view within the scroller. This timeline is essentially a snippet of the scroller's complete timeline, with 0% and 100% pinned to the moment the element comes into view and the moment it leaves view.

```
view-timeline-name: <custom-ident>
view-timeline-inset:  [ auto | <length-percentage> ]{1,4}
view-timeline-fit:  [ cover | contain | <percentage> ]
```

* `view-timeline-name` - Specifies a name for this element's in-view timeline, so that it can be referenced by descendant and sibling elements as their animation-timeline.
* `view-timeline-inset` - Specifies an inset (positive) or outset (negative) adjustment of the scrollport when considering whether the element is in view. auto indicates to use the value of scroll-padding. Initial value is zero. Percentages are with reference to the scrollport.
* `view-timeline-fit` - Specifies whether the in-view timeline is measured from the moment any part of the box comes into view until all parts leave it (cover/0%) or whether it is measured from the moment all parts of the box come into view until any part leaves it (contain/100%). Initial value is 0% (cover).

### Scope of Scroll-linked Timelines ###

The scope of a scroll-linked timeline (which elements can call it by name via animation-timeline) is defined as:

* its descendants
* its siblings (and their descendants)

This basically means its scope is attached to its parent, but the parent can't use it. In case of multiple timelines with the same name being in scope, the timeline associated with its nearest ancestor wins.

(It might also be useful to allow the scope to expand outside this parent, giving ancestors and far cousins access to the timeline across the document. In all cases the timeline reached via the closest ancestor should win in case of conflict. But this kind of global scoping from descendant elements might be difficult to implement.)

**Comment by bramus** [comment]
Having tinkered with Scroll-Linked Animations quite a lot _(See [here](https://brm.us/scroll-linked-animations-pt1), [here](https://brm.us/scroll-linked-animations-pt2), [here](https://brm.us/scroll-linked-animations-pt3), [here](https://codepen.io/tag/scroll-timeline))_ I'd like to add some counterweight to the premise of this proposal:

---

> The model seems to rely a lot on explicit offsets, rather than on element positions. Typically the reason for using offsets is to align with elements.

 I only found myself in need of explicit offsets is some typical yet always very simple situations:

- Scroll for `100vh` (e.g. cover page)
- Scroll from top to bottom of the entire document (e.g. progress bar)

In all other cases I found myself grabbing to element-based offsets, as they're more dynamic.

Additionally, when absolute offsets are needed they are mostly built using relative units _(instead of absolute units)_, which also keeps them somewhat dynamic.

_(I know: the first linked to article uses them a lot but that's because of the structure of the two articles: only in the second article the concept of element-based offsets is introduced. If I were to rewrite some examples from the first article (such as the image gallery) I'd use element-based offsets for it, as such an implementation would adapt itself to the number of slides/images)_

---

> There is functionality to use element-based offsets, but these rely on ID selectors, which are not particularly portable across pages and makes it impossible for styles to be re-used in multiple places on the same page.

To me, the root cause here is the fact that `selector()` only works with ID selectors. If it were to behave like `document.querySelector` it'd open up lots more possibilities. When also supporting `&` ([from CSS nesting](https://drafts.csswg.org/css-nesting/#nest-selector)) it'd even allow one to point to _“self”_, allowing re-use of created scroll-timelines.

This shortcoming of `selector()` — which was [one of the first things that I documented about it](https://www.bram.us/2021/02/23/the-future-of-css-scroll-linked-animations-part-1/#note--selector) — is being discussed in https://github.com/w3c/csswg-drafts/issues/5884 and by extension https://github.com/w3c/csswg-drafts/issues/5811

**Comment by mirisuzanne** [comment]
The need for a `selector()` function at all stands out to me as an issue — even if it had the ability to select multiple elements. We already have a syntax for attaching properties to selectors (it's the core of the language), so why not use it here? Both scroll-containers and scrolled elements can be selected already, and could establish their timelines in the cascade, using normal CSS syntax. (This is the same reason I pushed against container-queries using a selector syntax, even one without the ID limitation).

**Comment by bramus** [comment]
Thanks for your feedback @mirisuzanne. It's great to see how you approach this from CSS up, whereas the spec as it stands right now was clearly written from a JS-first stance, and then translated to CSS.

If you don't mind, I'm gonna keep on asking questions here, to fully grasp how this adjusted proposal would work in practice.

---

> The need for a `selector()` function at all stands out to me as an issue

I see that `animation-timeline: scroll(…)` accepts a `container-name` which identifies a container. To me it feels kinda the same, but simply shifted: you still need an identifier. Here in the form of a container-name, instead of an id _(or any selector if it were to behave like `document.querySelector`)_ with `selector()`.

However, I do see a reduced number of identifiers with this:

```css
main { /* Identifier 1 */
  container-type: size;
  container-name: page-layout; /* Identifier 2 */
}

.foo {
  animation-timeline: scroll(block, page-layout); /* Identifier 2, again */
}
```

vs.

```css
main { /* Identifier 1 */
  container-type: size;
  container-name: page-layout; /* Identifier 2 */
}

@scroll-timeline my-timeline {  /* Identifier 3 */
  source: selector(main);  /* Identifier 1, again */
  direction: block;
}

.foo {
  animation-timeline: my-timeline; /* Identifier 3, again */
}
```

That's one identifier less, so I guess that's a win there :)

On the other hand: when using a `scroll-timeline-name` — when the animated element is not a child of the scroll container — you'd also have three identifiers again:

```css
main { /* Identifier 1 */
  container-type: size;
  container-name: page-layout; /* Identifier 2 */
  scroll-timeline-direction: block;
  scroll-timeline-name: main-scroller: /* Identifier 3 */
}

.foo {
  animation-timeline: scroller; /* Identifier 3, again */
}
```

As a sidenote: in the snippet above it feels weird to have three identifiers linked to one and the same element. Should more future additions to CSS also require a name, the list of properties with a set name would keep on growing.

Winging back to `selector()` _(sorry, couldn't resist 😅)_:

```css
main {
  container-type: size;
  scroll-timeline-direction: block;
}

@container selector(main) (block-size > 12em) {
  /* … */
}

.foo {
  animation-timeline: selector(main);
}

Feels much neater, no? _(See this as an addendum/alternative syntax, not a replacement for giving names via the `*-name` properties)_

---

> We already have a syntax for attaching properties to selectors (it's the core of the language)

Of course, and we should embrace that where possible.

While working with scroll-timeline _(the current version)_ I often found myself targeting three things. Some using a selector, others using `selector()`:

1. The scroll-container _(using `selector()`)_
1. The element(s) used in element-based offsets _(using `selector()`)_
1. The element that need to be animated. _(using a selector)_

See for example https://codepen.io/bramus/pen/QWGbOBQ which sports a horizontal scrolling section. The code targets:

1. The viewport scroller as the scroll-container
1. The `#sectionPin` as the element-based offset
1. The `.pin-wrap` as the element that needs to be animated

With the adjustments, I guess this be the correct way to do it:

1. Declare `view-timeline-name: sectionpin` on `#sectionPin` so that it's the tracked element _(inside the main viewport scroller)_.
1. Declare `animation-timeline: sectionpin` on `.pin-wrap` so that it animates while `#sectionPin` is visible inside its scroller.

That's correct?

---

> `view-timeline-name` - Specifies a name for this element's in-view timeline, so that it can be referenced by descendant and sibling elements as their animation-timeline.

For the code example referenced above that does seem to work out _(if my understanding is correct there)_ but for a typical ScrollSpy it would not. See a reduced https://codepen.io/bramus/pen/3d544d1a7866478fae98ef39cf4f9b7f demo where the navigation `<nav>` positioned underneath the slider `#s` is not a descendant of the slider `#s` itself.

```html
  <div>
      <ul id="s">
         <li id="s1">Slide 1</li>
         <li id="s2">Slide 2</li>
         <li id="s3">Slide 3</li>
         <li id="s4">Slide 4</li>
      </ul>
   </div>
   
   <nav>
      <a href="#s1" id="d1">Go to Slide 1</a>
      <a href="#s2" id="d2">Go to Slide 2</a>
      <a href="#s3" id="d3">Go to Slide 3</a>
      <a href="#s4" id="d4">Go to Slide 4</a>
   </nav>
```

For example: as `#s2` slides into its parent `#s`, the nav element `#d2` is animated. With the scope limitation mentioned, declaring  `view-timeline-name: s2` on `#s2` will only make that timeline available for descendants/siblings of `#s2`.

This would be something I'd miss to be honest.

---

> Often animations are desired to start and end while a particular element is in view within the scroller.

Often it is also required to perform an animation as an element slides into the scroller, or slides out of it — e.g. not only while it is in view.  See https://codepen.io/bramus/pen/oNYEgEQ for example where elements are animated as the enter/exit the scroller.

How would this be covered in this proposal?

I guess it has to do with the `view-timeline-inset` property that's being mentioned. However, it explicitly states that _“Percentages are with reference to the scrollport.”_, which makes this one not usable for this use-case.

The `view-timeline-fit` also doesn't seem to work out as — at least that's how I interpreted it — it either allows you to animate from the moment an edge touches the scrollport _(”from the moment any part of the box comes into view”)_ or when the targetted element is entirely visible _(contained)_ inside the scrollport _("from the moment all parts of the box come into view")_

Or would one need a combination of both these properties?

Put differently: is it possible to target these 4 typical timelines?

- `#element` is intersecting scrollport, even for the tiniest bit: _(`view-timeline-fit: cover` I guess?)_
- `#element` is in between scrollport edges: _(`view-timeline-fit: contain` I guess?)_
- `#element` is entering from bottom into scrollport: _(?)_
- `#element` is exiting at top from scrollport: _(?)_

Must say I kinda liked the re-use of the threshold concept _(from `IntersectionObserver`)_ in the current proposal which allows you to do this. If there's no way to do this in the adjusted proposal yet, perhaps `view-timeline-inset` could be extended to also accept a `<number>` that resembles the threshold?

---

> Specifies whether the in-view timeline is measured from the moment any part of the box comes into view until all parts leave it (cover/0%) or whether it is measured from the moment all parts of the box come into view until any part leaves it (contain/100%). Initial value is 100% (cover).

Is it possible that there's a typo there and that the very last words should be “… 100% (**contain**).”?

**Comment by fantasai** [comment]
@bramus Responding to a few of your comments...

> when the animated element is not a child of the scroll container — you'd also have three identifiers again

Not quite, the scroll() function looks up to the nearest scroll container ancestor, it doesn't have to be the parent.

> With the adjustments, I guess this be the correct way to do it [...]

Yes. Looking at your example, maybe we should have a way for an element to grab the nearest ancestor view-timeline, same as we do for the nearest ancestor scroll-timeline?

> where the navigation <nav> positioned underneath the slider #s is not a descendant of the slider #s itself

This seems like it ought to be a transitions demo rather than an animations demo, to be honest! Though I'm not sure how we can capture the state there to make it transition... a problem for another day, I guess.

We could make the view timelines global to the page, but we'd probably want to make sure that multiple view timelines that have the same name are prioritized by proximity (similar to how counters work).

> Often it is also required to perform an animation as an element slides into the scroller, or slides out of it — e.g. not only while it is in view.

Interesting! We should definitely make that easily possible somehow. Have to think about that...

> Is it possible that there's a typo there and that the very last words should be “… 100% (contain).”?

Good catch. Should be 0% (cover). But we're open to arguments in favor of a different default. :)

**Comment by andruud** [comment]
> JS-first stance, and then translated to CSS

I support this rethink (I never liked `selector()` either), but if the CSS approach can't be expressed in terms of reasonable primitives shared with the JS API, this is going to be hard to both spec and implement.

BTW, what happens if we access `Animation.timeline` on a CSS-created scroll-linked animation? Will we create new interfaces separate from the current `ScrollTimeline` interface? (E.g. `ViewTimeline`).

> view timelines global to the page

> might be difficult to implement 

On the one hand, this is Weird and New (boo!). On the other hand, the mode of operation for scroll-linked animations is to base the timeline state on layout information from the previous frame. Assuming we're sticking with that, global/broad names seem possible.

**Comment by flackr** [comment]
@andruud I think that we would change the JS interface as well to have ViewTimeline and ScrollTimeline as separate timeline types that can be constructed with arguments that roughly match the CSS syntax, except allowing specifying any element as the target as the JS API allows with ScrollTimeline today.

**Comment by bramus** [comment]
As pointed out by @andruud and @flackr above I also think it's preferable to keep the JS and CSS interfaces tied to each other. Right now this is the case: if you know how one works you also know the other, as they share the same concept/approach.

---

@fantasai Regarding those "element slides into view"-animations.

Note that it can also be about a portion of that element, e.g. "only start when a quarter into view" or "be finished when 75% in view". I've done so in https://www.bram.us/2021/03/04/the-future-of-css-scroll-linked-animations-part-2/#demos--revealing-images for example where the animation runs from 50% into view to 100% into view.

Above that several animations can be attached to several phases of a timeline. See https://www.bram.us/2021/03/04/the-future-of-css-scroll-linked-animations-part-2/#demos--contact-list-revisited for example, where there are different enter and exit animations on the same element.

💡 To implement this it looks like a good idea to me to have one shared `view-timeline` for an element, and then be able to tap into parts of that `view-timeline` (e.g. the enter and exit phases) to hook animations on.

I'm thinking of two new properties here:

- `animation-timeline-phase` to define which part of the `view-timeline` you want attach your animation on.
  - Values are `enter`, `exit` and `auto` (= for the entirety of the `view-timeline`, with respect to `view-timeline-fit`)
- `animation-timeline-thresholds` to define the element-based thresholds for running the animations.
  - As an author you can opt to set two thresholds, e.g. `25% 80%`.
    - Both percentages indicate _"how much percent of the element should be in view"_. 
    - The first one is the start threshold _(e.g. how much percentage does the element need to be in view before the animation can start)_
    - The second one is the end threshold _(e.g. when the element in that much percentage in view the animation must be finished)_.
  - Default value is `auto`.
    - For `enter` phases that translates to `0% 100%` _(i.e. from element not in view and touching start edge to element entirely in view)_.
    - For `exit` phases that translates to `100% 0%` _(i.e. from element entirely in view and touch end edge to element entirely out of view)_.

The adjusted syntax for the https://www.bram.us/2021/03/04/the-future-of-css-scroll-linked-animations-part-2/#demos--contact-list-revisited example would then become:

```css
@keyframes animate-in {
   …
}

@keyframes animate-out {
   …
}

ul {
  overflow-y: scroll;
}

li {
  view-timeline: li-in-ul;
  view-timeline-fit: cover;
}

li > * {
  animation:
    animate-in 1s linear forwards,
    animate-out 1s linear forwards;
  animation-timeline: 
    li-in-ul, 
    li-in-ul;
  animation-timeline-phase: 
    enter,
    exit;
  animation-timeline-thresholds:
    25% 100%, 
    100% 25%;
}
```

In this example:

- The `animate-in` animation would run during the `enter` phase of the `li-in-ul` timeline. The animation will start when the watch element (the `li`) is 25% in view at the start edge and be finished when the watched element is entirely in view.
- The `animate-out` animation would run during the `exit` phase of the `li-in-ul` timeline. The animation will start when the watch element (the `li`) is 100% in view at the exit edge (e.g. about to leave) and be finished when the watched element is 75% out of view.

🤔 Braintwist: If these new properties would exist, is `view-timeline-fit: cover;` still feasible as we're basically delegating that responsibility to `animation-timeline-phase`? `animation-timeline-phase` could in that case be extended to accept the values `cover` and `contain`, deprecating `view-timeline-fit`.

🤔 Braintwist on the braintwist: Say`animation-timeline-phase` would be extended as suggested in the braintwist above and a user wants to do something like "run the animation from the moment the element is entering the scrollport until it is halfway in the scrollport", then the `enter`/`exit`/`cover`/`contain` keywords won't do. 

In that case I'm sliding back to a syntax using an edge and a percentage, which is awfully similar to [`<element-offset>` from the current proposal](https://drafts.csswg.org/scroll-animations-1/#typedef-element-offset):

```css
animation-timeline: some-element-in-a-scroll-container;
animation-timeline-phase-start: end 0%; /* Start animation when the watched element is sitting at the end edge, with 0% in view*/
animation-timeline-phase-end: 50%; /* Have animation be finished by the time the watched element is in the middle of the scroll-container*/
```

To combine these in the `animation-timeline-phase` shorthand a separator other than `,` would be needed.

Thinking of `/` right now (e.g. `animation-timeline-phase: end 0% / 50%;`) as using a space (e.g. `animation-timeline-phase: end 0% 50%;`) makes it somewhat weird: the first percentage is a threshold but the second percentage is a progression of the `view-timeline`.

_(Apologies for freewheeling here. My mind is playing ping-pong with itself when it comes to Scroll-Linked Animations 😅)_

---

Looking a bit broader, I think it's advised to also keep Scroll-Triggered Animations in mind while figuring out the syntax for Scroll-Linked Animations, so that we don't hit a wall when they are being considered. I'm seeing options with something like `animation-timeline-type: trigger` here, also being to leverage the proposed `animation-timeline-phase` if need be.
