### ISSUE TITLE
[css-animations] Add keyframe selectors for the animationstart and animationend events

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#6687]
Spec: https://drafts.csswg.org/css-animations/#keyframes

Maybe it would be a good idea to add `start` and `end` keyframe selectors that would represent the `animationstart` and `animationend` events. That would enable code like this:

```css
@keyframes fadeOut {
  to { opacity: 0 }
  end { display: none }
}
```

It seems that, currently, authors have to apply `display: none` via JavaScript.

***

[Related Twitter discussion](https://twitter.com/_developit/status/1412452250065252361)
