### ISSUE TITLE
Allow to write css class inside an other class (like less)

### ISSUE THREAD

**Issue by YglesEyes** [w3c/csswg-drafts#6713]
Hi all,
I open an issue on this subject because I didn't find it but perhaps I missed it...

It should be nice if we can write CSS class inside an other class like LESS manage it.

### For example:

``` css
#card {
  background: red;
}
#card.disable {
  background: grey;
  color: black;
}
``` 
### become:

``` css
#card {
  background: red;

  .disable {
    background: grey;
    color: black;
  }
}
```
