### ISSUE TITLE
[css-cascade] `revert-layer` keyword in keyframes

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#6749]
If there's a `revert-layer` in a keyframe, which layer does it revert to? Should it be the layer below where the keyframe is defined?

For example:
```css
@layer first {
  #target { font-size: 200px; }
}

@layer second {
  @keyframes anim {
    from { font-size: 100px }
    to { font-size: revert-layer }
  }
}

#target { animation: anim 5s; }
```

Since the keyframes are defined in layer `second`, should keyframe `to` revert to layer `first`, and therefore animates `font-size` from `100px` to `200px`?

This looks like the most reasonable behavior to me, but I'd like to make sure it's the correct one. And we probably need a note in the spec since this isn't completely trivial.
