### ISSUE TITLE
[css-contain-3] @container syntax in the specification doesn't allow example cases mentioned therein

### ISSUE THREAD

**Issue by RolandHeinze** [w3c/csswg-drafts#6820]
In the [CSS Containment Module Level 3 Specification](https://drafts.csswg.org/css-contain-3/#container-rule) the syntax for the `@container` rule does not allow simple container queries like
```css
@container (block-size > 12em) {
  .card { margin-block: 2em; }
}
```
The `<container-query>` production rule only allows the use of `size()` such that we get `@container size(block-size > 12 em) { ... }`. Therefore, either the examples in the specification need an update or the syntax definition of `@container` needs to be extended.
