### ISSUE TITLE
[css-properties-values-api] Multiple names in `@property` rule

### ISSUE THREAD

**Issue by valtlai** [w3c/csswg-drafts#6912]
Spec: https://drafts.css-houdini.org/css-properties-values-api-1/#at-property-rule

Allowing multiple custom property names in the `@property` rule would simplify, or make more DRY, cases where multiple very similar properties are defined:

```
@property <custom-property-name># {
  <declaration-list>
}
```

For example, the following (where `--x`, `--y`, and `--z` represent some coordinates):

```css
@property --x {
  syntax: '<number>';
  inherits: false;
  initial-value: 0;
}

@property --y {
  syntax: '<number>';
  inherits: false;
  initial-value: 0;
}

@property --z {
  syntax: '<number>';
  inherits: false;
  initial-value: 0;
}
```

could be rewritten into:

```css
@property --x, --y, --z {
  syntax: '<number>';
  inherits: false;
  initial-value: 0;
}
```
