### ISSUE TITLE
[mediaqueries-5] Unclear if @custom-media must precede usage

### ISSUE THREAD

**Issue by devongovett** [w3c/csswg-drafts#6956]
Reading through https://drafts.csswg.org/mediaqueries-5/#custom-mq it is unclear to me whether a `@custom-media` must be defined before it is is used, or if something like this is valid:

```css
@media (--modern) and (width > 1024px) {
  .a { color: green; }
}

@custom-media --modern (color), (hover);
```

Basically: does the substitution happen at parse time or at evaluation time?
