### ISSUE TITLE
[css-nesting]: Confusion around __ example.

### ISSUE THREAD

**Issue by dj2** [w3c/csswg-drafts#6993]
In https://www.w3.org/TR/css-nesting-1/ in [section 2.1 Direct Nesting](https://www.w3.org/TR/css-nesting-1/#direct) the following example is given:

```scss
.foo {
  color: blue;
  &__bar { color: red; }
}
/* In CSS, this is instead equivalent to
   .foo { color: blue; }
   __bar.foo { color: red; }
*/
```

The output of `__bar.foo` doesn't seem to match up with other examples. In other examples the parent selector appears in the same position as the `&` symbol. Is it correct that the `.foo` appears on the left of `__bar` and, if so, are there other cases where the selector flips sides?

Would this also mean that:

```scss
.foo {
  &h1 {color: red; }
} 
```
becomes `h1.foo {color:red;}` ?
