### ISSUE TITLE
[css-position] Absolutely positioned elements' position root should be its parent

### ISSUE THREAD

**Issue by NagayamaToshiaki** [w3c/csswg-drafts#7000]
Current specification is not intuitive. When you want some element to be absolutely positioned, you need to find where you want to root the position and make it relatively positioned.
https://drafts.csswg.org/css-position/#position-property

In most cases, the position root of an element is its parent element. Why isn't it a default?
If I designed CSS, I would make position root its parent by default, and position root should be declared if you desire somewhere else to be a position root from the absolutely positioned element.

The code would be like this:

```css
.absolutely-positioned-element {
    position: absolute;
    top: 10em;
    left: 50%;
    transform: translateX(-50%);
    position-root: body>main;
}
```
