### ISSUE TITLE
Page Visibility hook

### ISSUE THREAD

**Issue by argyleink** [w3c/csswg-drafts#7028]
**Problem**:
[Page Visibility](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) - JavaScript can know when a page has gone into the background, or a tab has lost focus, etc.

**Proposal**:
CSS get's a way to manage it too

```css
@media (document-visibility: hidden) {
  .ui-controls {
    --saturation: 0; /* dim out controls */
  }

  * {
    animation-play-state: paused;
  }

  .sensitive-content {
    filter: blur(10px);
  }
}
```
