### ISSUE TITLE
[css-content] Should content property work with non-string variables?

### ISSUE THREAD

**Issue by dauwhe** [w3c/csswg-drafts#703]
On [Twitter](https://twitter.com/wesbos/status/796749692075986944) there was a request for CSS variables to be used with the content property:

```css
label:before {
content: var(--spacing);
}
```

This works only if the variable is a string. 

Are there good use cases for this? There was some skepticism on the Twitter thread.
