### ISSUE TITLE
[css-pseudo] [css-highlight-api] support for pseudo-elements?

### ISSUE THREAD

**Issue by adam-lynch** [w3c/csswg-drafts#7118]
It's not clear to me if the following would be supported:

```css
:root::highlight(example-highlight)::after {
    content: 'test';
}
```
