### ISSUE TITLE
[css-pseudo] [css-highlight-api] styling of highlight descendants

### ISSUE THREAD

**Issue by adam-lynch** [w3c/csswg-drafts#7120]
It isn't clear to me if this is supported and if it is, what it does;

```css
a {
  color: red;
}

:root::highlight(example) a {
  color: black;
  background-color:yellow;
}
```

1. I'd like to be able to style elements contained in highlights.
2. Imagine the highlight starts at the beginning of a paragraph and ends halfway-through an anchor within the paragraph. What I'd like to happen here is that the first half of the anchor is black (text colour) and the second half is red.
