### ISSUE TITLE
[css-variables] Example 5 choice of language

### ISSUE THREAD

**Issue by aphillips** [w3c/csswg-drafts#7131]
(See Example 5)
https://www.w3.org/TR/css-variables-1/#defining-variables

> A real-world example of [custom property](https://www.w3.org/TR/css-variables-1/#custom-property) usage is easily separating out strings from where they’re used, to aid in maintenance of internationalization:
```
:root,
:root:lang(en) {--external-link: "external link";}
:root:lang(de) {--external-link: "externer Link";}

a[href^="http"]::after {content: " (" var(--external-link) ")"}
```
> The variable declarations can even be kept in a separate file, to make maintaining the translations simpler.

The choice of German here isn't perhaps immediately illustrative. Choosing a language (such as French or Japanese) whose translation is more visually distinct might help understanding. Several reviewers noted that they thought the German looked like a typo.

**Comment by svgeesus** [comment]
Does someone have a good Japanese translation of "external link" in Japanese? @frivoal perhaps

**Comment by svgeesus** [comment]
I admit that I first read this as "link" vs. "Link" myself.

**Comment by svgeesus** [comment]
Example is now

```css
		:root,
		:root:lang(en) {--external-link: "external link";}
		:root:lang(el) {--external-link: "εξωτερικός σύνδεσμος";}

		a[href^="http"]::after {content: " (" var(--external-link) ")"}
```

**Comment by svgeesus** [comment]
Additional example added

```css
	--fijord: red;
	--fĳord: green;
	--ﬁjord: blue;

	.test {
		background-color: var(--fijord);
	}
```
