### ISSUE TITLE
Rendering of style and script elements (white-space: pre)

### ISSUE THREAD

**Issue by nuxodin** [w3c/csswg-drafts#7167]
Although script and style elements are not displayed by default, it would make sense to display spaces if you want to display the elements anyway.

This document specifies the rendering of "flow content".
https://www.w3.org/TR/2021/NOTE-html53-20210128/rendering.html#non-replaced-elements-flow-content

I recommend the following change:
```css
- listing, plaintext, pre, xmp {
+ listing, plaintext, pre, xmp, script, style {
    font-family: monospace; white-space: pre;
  }
```

I don't know exactly what this would mean for backwards compatibility, but I think it would be a tolerable change.
