### ISSUE TITLE
[css-fonts-4] Enable font-palette:dark by default in dark mode

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#7276]
Because `font-palette: dark` doesn't have any effect on non-color fonts, we should probably set it by default in the user style sheet:

```CSS
@media (prefers-color-scheme: light) {
    :root {
        font-palette: light;
    }
}
@media (prefers-color-scheme: dark) {
    :root {
        font-palette: dark;
    }
}
```

This will probably decrease the probability that people render black-on-black color fonts by accident.
