### ISSUE TITLE
[css-fonts] font-size Descriptor for ex Unit

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#731]
There currently is no `font-size` [descriptor](https://drafts.csswg.org/css-fonts-4/#font-prop-desc) for use in `@font-face`. I propose it be added to manually specify the x-height and hence determine a non-fallback size (i.e. 0.5em) of the `ex` unit, which would be more useful and intuitive than the `font-size-adjust` property. If `cap` was added as a unit for the height of capital letters #660, this descriptor should also be able to set it. I think it makes most sense to only allow percentages of `1em`.

```css
@font-face {
  font-family: foo; src: url(foo.woff); 
  font-size: 45% 90%;
}
.foo {
  font-family: foo; 
  font-size: 20px;
  padding: 1ex /* = 0.45em = 9px */ 1cap /* = 0.9em = 18px */;
}
```
