### ISSUE TITLE
[css-color-6] color-contrast() should allow specifying multiple contrast algorithms that need to be satisfied

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#7357]
Assuming we can specify the contrast algorithm at all (see https://github.com/w3c/csswg-drafts/issues/7356), we should be able to specify *multiple* of them as a safeguard for algorithm bugs, as well as to satisfy legal constraints.

E.g. we know that [WCAG 2.1 contrast is severely broken](https://www.cedc.tools/article.html), yet it is legally mandated that websites pass it. Once we have a better contrast algorithm, we may want `color-contrast()` to find us a color pair that **both** satisfies WCAG 2.1, **as well as** the new improved algorithm.

Syntax could just be a space-separated list of contrast algorithms.

*(Issue filed following breakout discussions between @svgeesus, @fantasai, @argyleink and myself)*

**Comment by argyleink** [comment]
`color-contrast(white vs yellow, blue to wcag3(AA) hct(40) wcag2(AA))` is starting to be a mouthful, but could be mitigated with custom properties and supports queries. 

```css
@supports (color: color-contrast(#F00 vs #00F, #0F0 to wcag3(AA))) {
  :root {
    --target-ratio: wcag3(AA);
  }
}

.custom-label {
  background: var(--some-bg);
  color: color-contrast(var(--some-bg) vs #111, #eee to var(--target-ratio, wcag2(AA)));
}
```
