### ISSUE TITLE
[css-images-4] [css-color-5] - [color-interpolation-method] should allow custom idents

### ISSUE THREAD

**Issue by argyleink** [w3c/csswg-drafts#7377]
Given Color 5 allows loading of [custom color profiles](https://www.w3.org/TR/css-color-5/#at-profile), those loaded spaces should be available to use in [CSS Images 4 with gradients](https://drafts.csswg.org/css-images-4/#linear-gradients) like:

```css
@color-profile --myspace {
  src: url(https://myspace.colors/imaginary-path.icc);
}

.card {
  color: color(--myspace 200 50 50);
  background: linear-gradient(to bottom right in --myspace, 
    color(--myspace 200 50 50), 
    color(--myspace 100 50 50)
  );
}

or even

.card {
  background: linear-gradient(in --myspace, lime, blue);
}
```
