### ISSUE TITLE
[css-grid] More granular auto placement from grid container element

### ISSUE THREAD

**Issue by jacobp100** [w3c/csswg-drafts#7399]
https://www.w3.org/TR/css-grid-1/#track-sizing-algorithm

In a many cases, you can rely on the default placement of the grid to do what you want. However, in the cases that it isn’t, you currently have to define `grid-area` (or other) on the children elements, which seems like a lot of extra ceremony.

Firstly, it would be nice if `grid-auto-flow` could be extended to allow named grid areas before `row`/`column` to populate these areas first.

```css
grid: "a b c" auto / auto auto auto;
grid-auto-flow: b c a;
```

And this should also work on the `grid` property itself.

```css
grid: "a b c" auto / auto auto auto b c a;
```

Presumably, if any children had explicit grid areas, they would be excluded from the auto placement. It’s probably an edge case anyway.

Secondly, it would be nice to add `{row,column}-reverse` to `grid-auto-flow`, to match `flex-direction` - where it will fill items in from the end rather than the start

```css
grid-auto-flow: row-reverse;
```

**Comment by fantasai** [comment]
Could've sworn we had an issue on adding row-reverse and column-reverse, but I can't find it... but yes, we should definitely add it.

As for the named area thing, can you explain a bit more what you're wanting and why?

**Comment by jacobp100** [comment]
The naming thing really just makes it easier to create a layout template without the need to add classes/styles to each individual child. Currently, some grids work automatically to place their content - but as soon as you add empty cells, it no longer works. Picture this:-

```css
.modal {
  grid:
    "heading heading heading" auto
    ".       .       .      " 8px
    "body    body    body   " auto
    ".       .       .      " 12px
    "cancel  .       confirm" auto /
     1fr     4px     1fr
}
```

It's very cumbersome to manually place each child - and makes the layout much less usable
