### ISSUE TITLE
[css-nesting-1] Declaration occuring after an invalid nested rule

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7501]
> Declarations occuring after a nested rule are invalid and ignored.

https://drafts.csswg.org/css-nesting-1/#mixing

Does this mean that a declaration occuring after an invalid nested rule is valid? For example:

```css
ul {
  @invalid;
  padding-inline-start: 1em;
}
```

If so, I suggest:

> Declarations occuring after a **valid** nested rule are invalid and ignored.

Related: https://github.com/w3c/csswg-drafts/issues/7286
