### ISSUE TITLE
[css-cascade] New syntax for making an entire layer important

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#7535]
I have some user styles (Stylus extension) that I’m enforcing on a website. For example:

```css
.sticky-header {
  position: static !important;
}

.video-popup {
  display: none !important;
}
```

Instead of writing `!important` in every declaration, I would prefer if I could just put my styles inside an important layer:

```css
@layer stylus-extension !important {
  .sticky-header 
     position: static;
  }

  .video-popup {
    display: none;
  }
}
```
