### ISSUE TITLE
[css-!] Abbreviated form of `!important`, to simply `!`

### ISSUE THREAD

**Issue by mangelozzi** [w3c/csswg-drafts#7538]
When working with CSS utility frameworks, they tend to have all their rules ending with `!important`.
A significant chunk of the generated output is just `!important`.

What if `!` had the same meaning as `!important` so that these two lines did the same thing:

```css
.foo{color:red!important}
.foo{color:red!}
```

I can't see any tokenizing issues with this proposal, but others may explain why its not possible. I suspect people will say it will be gzipped away when sent from the server to the client, however it might be unneccessary verbosity for developers writing/diff'ing sourcecode. It is a feature I would really appreciate, and maybe others would to.

PS: Here's what it looks like next to an exclamation mark:
```css
.foo{color:red!;background:blue!}
```
