### ISSUE TITLE
usability-tip

### ISSUE THREAD

**Issue by pandasoli** [w3c/csswg-drafts#7568]
I do everything not to use CSS, I prefer to use [SASS](https://sass-lang.com/documentation/style-rules/parent-selector) or things like that, where chains are possible, it would be nice to have this as a standard.

It will be cool if CSS has chains with the events too. like:
```scss
  .component {
    label {
      color: red;
    }
    
    &hover {
      background-color: blue;
    }
  }
```
