### ISSUE TITLE
Composite properties.

### ISSUE THREAD

**Issue by korenevskiy** [w3c/csswg-drafts#7593]
In CSS, we often use layered properties. Example:

```CSS
box-shadow: 0 0 10px black, 0 0 20px white;
text-shadow: 0 0 10px black, 0 0 20px white;
background: url(cat.png), url(dog.png), linear-gradient(to bottom, red 0%, blue 100%);
transition: opacity 0.5s, height 1s, background-color 2s;
```
I propose composite properties. We are adding a plus sign "+". Example:
```CSS
box-shadow: 0 0 10px black;
box-shadow+: 0 0 20px white;

text-shadow: 0 0 10px black;
text-shadow+: 0 0 20px white;

background: url(cat.png); 
background+: url(dog.png);
background+: linear-gradient(to bottom, red 0%, blue 100%);

transition: opacity 0.5s;
transition+: height 1s;
transition+: background-color 2s;
```
This will allow you to structure styles by meaning.

```CSS
button{
/* Transition Width */
	width: 50px;
	transition: width 0.5s;
/* Transition box-shadow */
	box-shadow: 0 0 10px black;
	transition+: box-shadow 0.5s;
/* Transition background-color */
	background-color: red; 
	transition+: background-color 1s;
}
```

You can consider the syntax with a plus sign "+" at the very end .
```CSS
button{
	transition: width 0.5s;
	transition: box-shadow 0.5s +;
	transition: background-color 1s +;
}
```

Optionally, you can consider specifying the order of the member after the plus sign "+" 
```CSS
button{
	transition: width 0.5s;
	transition: background-color 1s +2;
	transition: box-shadow 0.5s +1;
}
```
This is the equivalent of
```CSS
button{
	transition: width 0.5s, box-shadow 0.5s, background-color 1s;
}
```
