### ISSUE TITLE
[css-values] hem: font-relative unit, relative to host element font-size

### ISSUE THREAD

**Issue by jonathandewitt-dev** [w3c/csswg-drafts#7613]
For better CSS encapsulation using Shadow DOM, it would be nice to enable relative sizing without coupling styles to the HTML structure.

## The `em` Problem:
`2em` at the browser default `16px` becomes `32px`.  Children of that element now interpret `1em` as `32px`.  This makes it very difficult to keep track of sizes going down the tree, and it tightly couples the styles to the HTML structure.  It would be better to have a common base size shared between all elements.

## The `rem` Problem:
`1rem` is always relative to the document root, and not the shadow root. This means the component's scale can't be adjusted unless a global change is made. It would be preferable to instead provide a base size for each component, independently from the document root.

## The Proposed `hem` Solution:
`1hem` could be equivalent to the component's `:host` element font-size.
```html
<x-calendar></x-calendar>
```
```css
x-calendar {
  --size: 0.5rem; /* by default, this will be 8px */
}
```
```css
/* inside x-calendar's Shadow DOM */
:host {
  font-size: var(--size);
}
.calendar-wrapper {
  width: 50hem; /* this will be 400px, as 1hem is equal to 0.5rem (8px) as defined above. */
}
```

## Alternative:
If it makes more sense to do so, we could perhaps consider allowing styles on the shadow root via `:root`, and just use `rem` as we usually would.

### Link to the spec:
https://www.w3.org/TR/css-values/#font-relative-lengths

**Comment by jonathandewitt-dev** [comment]
I wonder if this would have any crossover impact on the spec for Shadow DOM also.

**Comment by Que-tin** [comment]
While reading and thinking about this, I wonder if there would be a use case for something like `cem` (Container em) in the future. Could be useful if you are creating design systems at scale, which's components are being used across multiple different website with different layouts and behaviour.

**Comment by jonathandewitt-dev** [comment]
> I wonder if there is a good amount of use cases for something like cem (Container em)

In the Light DOM? Interesting thought, how would you determine which element was a container in that context? Maybe something like
```html
<div container>
```

**Comment by tabatkins** [comment]
Hm, I believe something like this would work today?

```css
@property --hem {
  syntax: "<length>";
  initial: 1em;
  inherits: true;
}
:host {
  --hem: 1em;
}
.in-the-shadow {
  font-size: calc(2 * var(--hem));
}
```

When the property is registered like this, it'll process its value using standard computed-value rules, so the `1em` will turn into a px length based on the font-size of the element it's set on (the host element, here).

And once [Variables 2's custom units](https://drafts.csswg.org/css-variables-2/#variable-units) are in, it can be used directly as a unit, like `font-size: 2--hem;`.
