### ISSUE TITLE
[css-animations-2][web-animations-2] API For specifying phase linked offsets in keyframes

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#7637]
In #7044 we [resolved](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1175722383) to add phase linked offsets to the animations APIs. We discussed a simple CSS syntax such as the following:

```css
@keyframes fade-in-out-animation {
  enter 0% { opacity: 0; }
  enter 100% { opacity: 1; }
  exit 0% { opacity: 1; }
  exit 100% { opacity: 0; }
}
```

We didn't talk about a syntax for the web-animations API, however #7589 touches on an API for the similar `delay` and `endDelay` properties so we should probably do the same here. Concretely this means whichever format we choose for #7589 (i.e. String or Object), that could be specified for `offset` in the [Keyframe dictionary](https://drafts.csswg.org/web-animations-1/#processing-a-keyframes-argument:~:text=WebIDL%2Dlike%20definition%3A-,dictionary%20Keyframe,-%7B%0A%20%20%20%20//%20...%20property%2Dvalue%20pairs) and should likely be returned by [getKeyframes](https://drafts.csswg.org/web-animations-1/#dom-keyframeeffect-getkeyframes).
