### ISSUE TITLE
[css-highlight-api] Should pseudo-classes work with Custom Highlights

### ISSUE THREAD

**Issue by luisjuansp** [w3c/csswg-drafts#7647]
Combining pseudo-elements and pseudo-classes is already being spec'd in [Selectors Level 4 (csswg.org)](https://drafts.csswg.org/selectors/#pseudo-element-states:~:text=3.6.3.%20Pseudo%2Dclassing%20Pseudo%2Delements). Custom highlights could benefit from being able to be matched with certain pseudo-classes, specifically user action classes such as :hover.

**Comment by zhangenming** [comment]
i need it
```css
article::highlight(a) { color: blue;background: #fff; transition: background 0.3s ease-in-out } 
article::highlight(a):hover { color: #fff;background: blue;}
```
