### ISSUE TITLE
[css-images] simplify the syntax of `image-set()`

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#7662]
https://drafts.csswg.org/css-images-4/#image-set-notation

```
image-set() = image-set( <image-set-option># )
<image-set-option> = [ <image> | <string> ]
                     [ <resolution> || type(<string>) ]

<image> = <url> | <image()> | <image-set()> | <cross-fade()> | <element()> | <gradient>
```

Here it is allowed to nest image-set() within image-set(), I don't know what the actual scenario of this is, do we need such a complex image adaptation?

This behavior is currently implemented in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1698133):

cc @emilio 

```css
body {
  background-image: image-set(
    image-set(
      image-set(
        image-set(
          linear-gradient(green, green) 1x
        )
      )
    )

    , linear-gradient(red, red) 1x
  );
}
```
