### ISSUE TITLE
[css-fonts] Multiple @font-face multiple src declarations

### ISSUE THREAD

**Issue by hamishwillee** [w3c/csswg-drafts#7753]
CSS Fonts Module Level 4, [Editor’s Draft](https://www.w3.org/standards/types#ED), 15 September 2022

Says in [`@font-face` rule](https://w3c.github.io/csswg-drafts/css-fonts-4/#font-face-rule):

> .... When a given descriptor occurs multiple times in a given @font-face rule, only the last descriptor declaration is used and all prior declarations for that descriptor are ignored.

Then [example 22](https://w3c.github.io/csswg-drafts/css-fonts-4/#ex-incremental) shows where we have multiple src descriptors, allowing fallback:

```css
@font-face {
  font-family: "MyIncrementallyLoadedWebFont";
  src: url("FallbackURLForBrowsersWhichDontSupportIncrementalLoading.woff2") format("woff2");
  src: url("MyIncrementallyLoadedWebFont.otf") format(opentype)  tech(incremental);
}
```

My assumption is that multple `src` descriptors are allowed if valid. If so perhaps the initial sentence could reflect this. Not sure how - maybe something like

> .... When a given descriptor occurs multiple times in a given @font-face rule, only the last _actionable_ descriptor declaration is used and all prior declarations for that descriptor are ignored.
