### ISSUE TITLE
[css-animations] Clarify whether `<keyframes-name>` supports the empty string

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#7762]
The spec allows `<string>` here https://github.com/w3c/csswg-drafts/issues/118#issuecomment-227655060, but does not further clarify whether empty strings(`""` or `" "`) are allowed. 

@ewilligers Says: 
> Also, do we want to ban the empty string '""' ?
> https://github.com/w3c/csswg-drafts/issues/2435#issuecomment-445630241

- From the CSS author's point of view, empty strings seem to be meaningless.
- For current implementations across browsers, this has significant compatibility issues.

## `@keyframes "" {}`

> If the browser supports it, the page background color will be green.

```css
@-webkit-keyframes "" {
    to {
        background: green
    }
}

@-moz-keyframes "" {
    to {
        background: green
    }
}

body {
    background: red;
    -webkit-animation: "" 0s ease 1 forwards;
    -moz-animation: "" 0s ease 1 forwards;
}
```

- ` -webkit-` (Chrome) ✅
- `-webkit-`(Safari) ❌
- `-moz-`(Firefox) ❌
- without prefix(both) ❌ [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1554737)

## `@keyframes " " {}`

```css
@-webkit-keyframes " " {
    to {
        background: green
    }
}

@-moz-keyframes " " {
    to {
        background: green
    }
}

body {
    background: red;
    -webkit-animation: " " 0s ease 1 forwards;
    -moz-animation: " " 0s ease 1 forwards;
}
```

- ` -webkit-` (Chrome) ✅
- `-webkit-`(Safari) ✅
- `-moz-`(Firefox) ✅
