### ISSUE TITLE
[css-sizing] Fix and clarify examples 6 and 7

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7867]
https://w3c.github.io/csswg-drafts/css-sizing-4/#cis-scrollbars

Example 6 just has this code:

```css
div {
  width: max-content;
  contain-intrinsic-size: 100px 100px;
  overflow: auto;
}
```

> The element ends up being 100px wide and 100px tall: [`contain-intrinsic-size`](https://w3c.github.io/csswg-drafts/css-sizing-4/#propdef-contain-intrinsic-size) provides the max-content width, and also the height.

This only happens when there is size containment. I think the code should have `contain: size`. Same in example 7.

> If the element then ended up with content that was 150px tall, it would show a vertical scrollbar

Why would it show a vertical scrollbar? There is no `height` nor `max-height`, so I'm assuming the initial values, which allow the element to grow big enough for the 150px.
