### ISSUE TITLE
[scoping] Direct parent of a :host-context()

### ISSUE THREAD

**Issue by Zefling** [w3c/csswg-drafts#7896]
I have a custom element  `<my-elem>` and I would like only the one whose parent with class `row` to be affected:

```css
<style>
  /* ... */
  :host-context(.row >) > div {
    background-color: blue;
  }
</style>
```

```html
<div class=".row">
  <div>
    <my-elem>
      <div>DIV!</div>
      <main>MAIN!</main>
      <aside>ASIDE!</aside>
    </my-elem>
  </div>
<div>
<div class=".row">
  <my-elem>
    <div>DIV!</div>  <!-- Only this element -->
    <main>MAIN!</main>
    <aside>ASIDE!</aside>
  </my-elem>
<div>
<my-elem>
  <div>DIV!</div>
  <main>MAIN!</main>
  <aside>ASIDE!</aside>
</my-elem>
```

This doesn't seem possible, because `>` at the end of the selector is not valid.

There is a reason for this? If so, how can I do without?
