### ISSUE TITLE
[css-nesting-1] Example 4 : selectors starting with an identifier

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#7980]
https://drafts.csswg.org/css-nesting/

> Example 4
> However, starting the nested selector with an identifier (a [type selector](https://drafts.csswg.org/selectors-4/#type-selector), in other words) is invalid:

Does this only apply to the first selector in a list or to each?

invalid :

```css
div {
  color: red;

  input {
    margin: 1em;
  }
}
```

valid/invalid? : 

```css
div {
  color: red;

  :is(input), textarea {
    margin: 1em;
  }

  & input, textarea {
    margin: 1em;
  }
}
```

From a parser perspective only the first in the list is important. But from an author perspective this is less obvious.

If you remove `:is(input)` then you need to modify `textarea` to make it valid again.

_I have no preference here, only need to know what to implement_

**Comment by bradkemper** [comment]
I think that should be valid. No need to have that restriction for anywhere other than the beginning of the rule.

**Comment by romainmenke** [comment]
If authors want to enforce that each selector in the list is unambiguous in case of edits they can use a linter to enforce this style :

```css
div {
  color: red;

  :is(input), :is(textarea) {
    margin: 1em;
  }
}
```

**Comment by cdoublev** [comment]
Aside (sorry)

> If authors want to enforce that each selector in the list is unambiguous in case of edits they can use a linter to enforce this

As a CSS author, I would prefer that a solution be found to remove the restriction on `<identifier>`, rather than having to remember it or to use a linter. Remember to start with `&` or `@nest` (option 1) seems less constraining. As a non-SASS/SCSS author, I also consider option 1 better because nested compound/descendant selectors are explicit.

**Comment by sesse** [comment]
Blink currently allows starting the second one in the list with an identifier, but it _does_ run into an issue we've talked about before (in the context around parser switching), where deleting the first rule suddenly makes the other one invalid. I'm fine with changing this if people want to, but we'd need to what happens to the rule (does only that selector go away and the sub-rule stays, or does it poison the entire parse).

**Comment by romainmenke** [comment]
Do you mean this case :

```css
div {
  color: red;

  :is(input), textarea {
    margin: 1em;
  }
}
```

and then changing `:is(input), textarea` to `textarea` via CSSOM?
