### ISSUE TITLE
[scroll-animations-1] Make view timeline axis values more specific

### ISSUE THREAD

**Issue by scottkellum** [w3c/csswg-drafts#8009]
Regarding [view-timeline-axis](https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-axis), it would be nice to see the values being more specific as to what the axis is relating to. Currently scroll is the only axis, but in the future I could imagine also creating a timeline with container inline size as the axis.

As a result this feels more clear to me:

```css
.element-moving-in-viewport {
  view-timeline-name: foo;
  view-timeline-axis: scroll(block);
  animation: scale both linear;
  animation-delay: enter 0%;
  animation-end-delay: cover 50%;
  animation-timeline: foo;
}
```

as opposed to this:

```css
.element-moving-in-viewport {
  view-timeline-name: foo;
  view-timeline-axis: block;
  animation: scale both linear;
  animation-delay: enter 0%;
  animation-end-delay: cover 50%;
  animation-timeline: foo;
}
```
