### ISSUE TITLE
[css-logical] Allow logical values in CSS gradients

### ISSUE THREAD

**Issue by shadeed** [w3c/csswg-drafts#8015]
An improvement to CSS logical properties would be to allow using the logical values within CSS gradients. One use-case for that is having a gradient from left-to-right for LTR and from right-to-left for RTL languages.

Without CSS logical properties, we need to flip the gradient manually.

```css
.hero {
    background-image: linear-gradient(to right, #000, transparent);
}
```

If we allow using the logical values, it would look like the following.

```css
.hero {
    background-image: linear-gradient(to end, #000, transparent);
}
```

<img width="1142" alt="gradient-start-end" src="https://user-images.githubusercontent.com/8038659/199998997-ac2db2e6-6d33-478d-9f0f-3d1cd96bf46a.png">

@jonathantneal has something about that [here](https://jonneal.dev/logical-gradients-spec/).

Not sure if there any side effects of implementing this feature. Happy to provide more use-cases and demos!
