### ISSUE TITLE
[css-nesting-1] Nesting with `@scope` and `:scope`/`&`

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8019]
```css
/* 1.a */
:scope {
  @scope (.foo) {
    color: pink;
  }
}

/* 1.b */
& {
  @scope (.foo) {
    color: pink;
  }
}

/* 2.a */
@scope (.foo) {
  :scope {
    color: pink;
  }
}

/* 2.b */
@scope (.foo) {
  & {
    color: pink;
  }
}
```

I find these cases really tricky to reason about.
Are these all equivalent or not?

see : https://github.com/w3c/csswg-drafts/issues/5745

The `1.x` examples:
- nested `@scope` rule
- parent selector is `:scope` or `&`, but this is just `:root` in this context
- they don't have a rule with a selector inside `@scope`

The `2.x` examples:
- normal `@scope` rule
- selector is `:scope` or `&`, but `&` is `:scope` in this context

If we change the nesting of rules for `1.x` we get `2.x` but doing this naively changes the meaning of `:scope`. It is no longer equivalent to `:root`.

**Comment by romainmenke** [comment]
```css
/* 1.a */
:scope {
  @scope (.foo) {
    color: pink;
  }
}
```

is this equivalent to :

1. `:scope` is `:root`
2. "resolve" nesting

```css
/* 1.a */
@scope (.foo) {
  :root {
    color: pink;
  }
}
```

or equivalent to :

is this equivalent to :

1. "resolve" nesting
2. `:scope` is `:scope`

```css
/* 1.a */
@scope (.foo) {
  :scope {
    color: pink;
  }
}
```
