### ISSUE TITLE
[css-nesting-1] Should code portability trump coding habits wrt nesting syntax?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#8029]
As a follow-up from #7834, the question of the "same-brace-but-inconsitent-prefixing" (Proposal 3) vs "other-brace-but-consistent-prefixing" (Proposal 4) was left open. Proposal 3 is described in the [current editor draft](https://drafts.csswg.org/css-nesting/). The presentation of Proposal 4 and the related discussion can be found here: https://github.com/w3c/csswg-drafts/issues/7834#issuecomment-1292144760. Proposal 5 can be found here: https://github.com/w3c/csswg-drafts/issues/7970

**The main advantage of Proposal 3**... 
> is that this should be very familiar to anyone who might have used nesting through CSS preprocessors, although the requirement to use `&` or `:is()` in some cases is new as preprocessors don't limit themselves to the more efficient types of parsing which browsers rely on for performance reasons.

**The main advantage of Proposal 4...** 
> is that it provides full interoperability between contexts: you can take any CSS code you have today, wrap it in a block, add a selector prefix, and now you have "nested" the existing code without having to make any change. Similarly, moving from and to CSS Scoping blocks does not require any change at all. Finally, if some code needs to be un-nested (because it is moved to a Web Components CSS file and no longer requires a prefix), this can be done without any change to the CSS.

**The main advantages of Proposal 5...**
> It provides a top-level construct that contains nothing but nested rule. This avoids the need to mix style rules and properties in a single context. It uses nothing but standard CSS syntax and requires no changes to the OM or parsing rules. It's easier to explain and understand.

Apart from the requirement to put the rules in another brace, the syntax between the three proposals looks remakably simliar, as can be seen in the following examples:

<table>
<thead><tr><th>Proposal 3</th><th>Proposal 4</th><th>Proposal 5</th></tr></thead>

<tr><td>

- Is familiar to users of CSS preprocessors.
- Every CSSStyleDeclaration block can now support nested rules

</td><td>

- Code portability between regular stylesheets rules, nested rules, scoped rules, and web component rules.
- Does not put major syntax restrictions on the declaration block.

</td><td>

- Code portability between regular stylesheet rules, nested rules, scoped rules, and web component rules.
- No new syntax, parsing changes or OM changes.
- Avoids potential conflicts of future property or selector syntax exensions.
- Preserves the ability to interleave nested rules without reordering in the OM. 
</td></tr>

<tr><td>

- Rules are invalid if they start with a type selector, requiring them to be rephrased somehow. (Using :is(div), starting with &, etc.)
- This prevents us from changing property syntax to start with an ascii glyph in the future.

</td><td>

- Requires another pair of brackets
- If you are only nesting rules, you still need an empty declaration block ({}), which looks awkward
- Nesting is not secured by default for the others CSSStyleDeclaration context (e.g. inline styles)

</td><td>

- Requires adding an additional block of scope to the parent rule
</td></tr>

<tr><th>Spec example 1</th><th>...</th></tr>

<tr><td>

```css
table.colortable {
  & td {
    text-align:center;
    &.c { text-transform:uppercase }
    &:first-child, &:first-child + td { ... }
  }
  & th {
    text-align:center;
    background:black;
    color:white;
  }
}
```

</td><td>

```css
table.colortable {} {
  td { text-align:center; } {
    &.c { text-transform:uppercase }
    &:first-child, &:first-child + td { ... }
  }
  th {
    text-align:center;
    background:black;
    color:white;
  }
}
```

</td><td>

```css
@nest table.colortable {
  @nest td {
    { text-align:center; }
    &.c { text-transform:uppercase }
    &:first-child, &:first-child + td { ... }
  }
  th {
    text-align:center;
    background:black;
    color:white;
  }
}
```
</td></tr>

<tr><th>Spec example 2</th><th>...</th></tr>

<tr><td>

```css
.foo {
  color: red;
  .bar {
    color: blue;
  }
}
```

</td><td>

```css
.foo { 
  color: red; } 
  { .bar {
    color: blue;
  }
}
```

</td><td>

```css
@nest .foo {
  { color: red; }
  .bar { 
    color: blue; 
  }
}
```
</td></tr>

<tr><th>Spec example 3</th><th>...</th></tr>

<tr><td>

```css
div {
  color: red;

  & input { margin: 1em; }
}
```

</td><td>

```css
div {
  color: red; } {

  input { margin: 1em; }
}
```

</td><td>

```css
@nest div {
  { color: red; }

  input { margin: 1em; }
}
```
</td></tr>

<tr><th>Integration with layers</th><th>...</th></tr>

<tr><td>

```css
@layer base {
  html {
    block-size: 100%;

    @layer base.support {
      & body {
        min-block-size: 100%;
      }
    }
  }
}
```

</td><td>

```css
@layer base {
  html {
    block-size: 100%; } {
    
    @layer base.support {
      body {
        min-block-size: 100%;
      }
    }
  }
}
```

</td><td>

```css
@layer base {
  @nest html {
    { block-size: 100%; }

    @layer base.support {
      body {
        min-block-size: 100%;
      }
    }
  }
}
```
</td></tr>

<tr><th>Integration with scope</th><th>...</th></tr>

<tr><td>

```css
.card {
  inline-size: 40ch;
  aspect-ratio: 3/4;

  @scope (&) to (> header > *) {
    :scope > header {
      border-block-end: 1px solid white;
    }
  }
}
```

</td><td>

```css
.card {
  inline-size: 40ch;
  aspect-ratio: 3/4; } {

  @scope (&) to (> header > *) {
    :scope > header {
      border-block-end: 1px solid white;
    }
  }
}
```

</td><td>

```css
@nest .card {
  {
    inline-size: 40ch;
    aspect-ratio: 3/4;
  }

  @scope (&) to (> header > *) {
    :scope > header {
      border-block-end: 1px solid white;
    }
  }
}
```
</td></tr>

</table>

Regarding the question of nested rules in the style attribute, I would rather have rules contained in a `<style>` element where they can receive the space needed. There is a proposal for this already, for instance:

```html
<article>
    <style>
        :style-root { } {
            h1 { color: purple; }
        }
    </style>
    <h1>Title</h1>
    ....
</article>
```

Otherwise, we can also put them in another attribute named cssRules="..." which contains the content of the second (rule) block.

Anything I missed in the discussion?

**Comment by romainmenke** [comment]
> is that it provides full interoperability between contexts: you can take any CSS code you have today, wrap it in a block, add a selector prefix, and now you have "nested" the existing code without having to make any change.

I am confused by this statement.
It says that you do not need to make any change while outlining the changes you need to make.

-------

`} {`

I don't think any authors will like writing this at the end of a declaration.
- if you want to add one more declaration you need to move `} {` to the next one.
- if you re-order declarations the block breaks.
- if you copy/paste that line it will need to be changed.

In general I also find that typing `} {` in that order is awkward.
People will get used to it, but it is uncommon today.

**Comment by FremyCompany** [comment]
> > is that it provides full interoperability between contexts: you can take any CSS code you have today, wrap it in a block, add a selector prefix, and now you have "nested" the existing code without having to make any change.
> 
> I am confused by this statement. It says that you do not need to make any change while outlining the changes you need to make.

I think @argyleink was confused by that statement, too.

Here is an example of HTML/CSS you might find today: (I just took it from the table spec)
```html
<ul class="table">
  <li><b>One</b><i>1</i></li>
  <li><b>Two</b><i>2</i></li>
  <li><b>Three</b><i>3</i></li>
</ul>
<style>
  ul.table { display: table; }
  ul.table > li { display: table-row; }
  ul.table > li > * { display: table-cell; }
</style>
```

Let's say that you inherit that code, and realise that it's not such a good idea to use the "table" class that way in your entire codebase, and you want to limit to a section of your site that contains the articles from the legacy system.

You can take the CSS code, prepend `:where(article.legacy) {} {`, indent the entire list of rules, then close the brace with `}`.

```css
:where(article.legacy) {} {
  ul.table { display: table; }
  ul.table > li { display: table-row; }
  ul.table > li > * { display: table-cell; }
}
```

Now, with the current option, proposal 3, this is not sufficient. You have to go and find all selectors that were starting with an indent, and fix them.

```css
:where(article.legacy) {
  & ul.table { display: table; }
  & ul.table > li { display: table-row; }
  & ul.table > li > * { display: table-cell; }
}
```

This is a manual operation that requires O(n) steps for the author. Each selector needs to be inspected, and then prepended with a '&' symbol if needed. This operation is error-prone and takes time, for something which I expect to be a very common refactoring.

Plus, now, if you want to go back to an independant stylesheet (because, say, you moved to web components and isolated the legacy content there), you have to go back and remove all the `&` symbols since they don't mean anything anymore. If you had used proposal 4 or 5, you would not need to do this.

This is also true if you move from or to `@scope` statements. This is another very likely scenario, given the features work similarly but have different effects on cascade importance.

> I know that writing } { at the end of a declaration is not required but it is placed there to create the visual illusion of nested curly braces (which falls apart with different formatting).

Yeah, that's true. I don't find that other way of writing it that bad, but it does feel less compact. I'd like to note that the examples for the first spec also use artifically-shortened forms though, like `&.c { text-transform:uppercase }` one-liners.

I would also like to point out that with autocompletion these days, you hardly ever write a `}` yourself. They are auto-inserted. The actual workflow when adding nested rules is more likely to be "click after the `}` and type `{` then your rules".
