### ISSUE TITLE
[css-inline-3] Naming Stuff

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8067]
Just a thread for some bikeshedding:

- The `text-edge` property: is this a good name? any better ideas?
- The `leading` value of `text-edge`, should it be `normal`? `half-gap`? something else?
- The `text` value of `text-edge`, is there a more descriptive word we could use?
- The `leading-trim` property: we have an outstanding resolution to rename to `trim-leading`, should we do that or something else?
- The `inline-sizing` property: see https://github.com/w3c/csswg-drafts/issues/5189

**Comment by jantimon** [comment]
+1 for renaming the `leading` value to `normal`

that way it would be easier to memorise the value of the normal css behaviour.
it would also match with the initial value of `text-edges` and similar font properties:

```css
leading-trim: normal;
text-edge: normal;
line-height: normal;
...
```

**Comment by oly-wan-kenobi** [comment]
+1 for the value `normal`

totally agree with @jantimon it fits in much better with the existing values.

**Comment by michaeltaranto** [comment]
A suggestion for an alternative to `text-edge` could be `text-box-sizing`. This would align it with existing terminology used by other properties, e.g. `box-sizing`. 

Example in context:
```css
.paragraph {
  font-size: 1em;
  text-box-sizing: cap;
}
```

**Comment by jantimon** [comment]
+1 for the `text-box` suggestion by @michaeltaranto.
Imho the consistency in terminology brings clarity and simplifies comprehension.

Here are some more examples:

**default**:

```css
.paragraph {
  text-box-sizing: normal;
  text-box-trim: normal;
}
```

**cap** ✂️:

![image](https://user-images.githubusercontent.com/4113649/217504359-2a53117b-fca9-4aab-8e34-8195b4eb6aa1.png)

```css
.paragraph {
  text-box-sizing: cap;
  text-box-trim: both;
}
```

**cap alphabetic** ✂️:

![text-box-sizing: cap alphabetic](https://user-images.githubusercontent.com/4113649/217506411-f9c06764-366d-4e67-b9c1-4465b1ffad86.png)

```css
.paragraph {
  text-box-sizing: cap alphabetic;
  text-box-trim: both;
}
```
