### ISSUE TITLE
[css-nesting-1] are declarations allowed in a nested `@layer` rule

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8082]
@argyleink These examples all follow the same basic pattern:

```
- style rule
  - at-rule
    - style rule
      - declarations
```

```css
.foo {
  @layer a-layer {
    .bar {
      color: red;
    }
  }
}
```

But can we also do this?

```
- style rule
  - at-rule
    - declarations
```

```css
.foo {
  @layer a-layer {
    color: red;
  }
}
```

Also unclear if the wording from section 2.2 is still correct now that `@layer` and `@scope` are allowed. Should this be changed to be less specific than conditional rules. (afaik `@layer` isn't a conditional rule)
Or do need a new section for at-rules that aren't conditional rules?

_Originally posted by @romainmenke in https://github.com/w3c/csswg-drafts/issues/7965#issuecomment-1304608409_
