### ISSUE TITLE
[css-anchor-1] Transitioning when the anchor element with a given name changes

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#8181]
It's pretty obvious that if an element changes from `top: anchor(--foo top);` to `top: anchor(--foo bottom)`, that's a computed-value change that will trigger a transition on 'top'.

But what happens when the value is `top: anchor(--foo top);` the whole time, but you change which element has `anchor-name: --foo;`? @jh3y has an example of this using the popover API, where they change the popover attribute, altering which element is used as the "implicit anchor element" without actually touching the CSS. They'd like the abspos to smoothly transition to its new position.

I think this gets solved appropriately with the exact same solution as #8180 - if the tree-scoped reference is resolved as part of the computed value, then having it change underneath you counts as a computed-value change, thus triggering a transition, *and* the start and end values are (non-textually) distinct, referring to the old and new anchor, so you can meaningfully transition between them.

**Comment by jh3y** [comment]
Yep – Transitioning the inset properties or being able to use those values in calc to generate `transform` values would be super useful. The demo in question is this one 👇 

https://user-images.githubusercontent.com/842246/205658978-489b6590-bbbf-44ee-a1d2-cd369c32db88.mp4

It shows a use case where you might want an element to follow user interaction. Not one I'd throw into production anytime soon 😅 

But it works using `:has()` to update and `--active-anchor` custom property (this did work in ~108).

```css
:root {
  --active-anchor: --email;
  --active-left: anchor(var(--active-anchor) right);
  --active-top: anchor(var(--active-anchor) center);
}

:root:has(.form-group:focus-within) {
  --anchor-scale: 1;
  --anchor-transition: top 0.2s, left 0.2s, transform 0.2s;
}

#password {
  anchor-name: --password;
}

:root:has(#password) {
  --active-anchor: --password;
}
```

A combination of implicit anchor and transition could also be useful in a variety of tooltip/overlay scenarios too. Even those type trigger UI where like on here when you type `#` to get the dropdown (What is the technical name for that pattern? 😅 )
