### ISSUE TITLE
[css-overflow-3] Typo in example 6

### ISSUE THREAD

**Issue by johannesodland** [w3c/csswg-drafts#8190]
https://drafts.csswg.org/css-overflow-3/#example-bf93dfa6

Example 6 in CSS Overflow Module 3 says "truncated to fit within 10 lines"

But then the example is defined as follows: 
```css
li {
  line-clamp: 5 "… (continued on next page)";
}
```

The text should probably say "truncated to fit within 5 lines"?
