### ISSUE TITLE
[css-backgrounds] Add `background-opacity` as an alternative to Relative Color (Color Module Level 5)

### ISSUE THREAD

**Issue by mrleblanc101** [w3c/csswg-drafts#8465]
Currently, it's impossible to change to opacity of a CSS Custom Propriety without:
a) Wacky hacks with Custom Proprieties
b) [Relative Colors from CSS Color Module Level 5](https://bugs.chromium.org/p/chromium/issues/detail?id=1274133#c3) which is unsupported by all browser and pretty complex.
c) Pseudo-elements nesting

Let's say I have this variable on my site.
But somewhere else I need to use this color variable but with opacity:
```css
:root {
  --c-primary: #e2273c;
}
.regular-background {
  background: var(--c-primary);
}
```

#### Option A
I could use an intermediate CSS Cutom Propriety, but it's hacky and it would require me to wrap my var in a rgb function for every use:
```css
:root {
  --c-primary: 226, 39, 60;
}
.regular-background {
  background: rgb(var(--c-primary))
}
.regular-background-with-opacity {
  background:  rgba(var(--c-primary), 0.5);
}
```

#### Option B
Using relative color from CSS Color Module Level 5
```css
:root {
  --c-primary: #e2273c;
}
.regular-background-with-opacity {
  background:  rgb(from var(--c-primary) r g b / 50%);
}
```

#### Option C
```css
:root {
  --c-primary: #e2273c;
}
.regular-background-with-opacity {
  position: relative;
  &::before {
    content: '';
    position: absolute;
    inset: 0;
    background:  var(--c-primary);
    opacity: 0.5
  }
}
```

#### Proposal
```css
:root {
  --c-primary: #e2273c;
}
.regular-background {
  background: var(--c-primary);
  background-opacity: 0.5;
}
```

On the plus side, this could also affect `background-image` which currently require to use Option C and a pseudo-element to change their opacity.
From my very little understanding of how browser engine work, this seem a lot easier to implement than Relative Color and could be implement and shipped much faster.

**Comment by svgeesus** [comment]
Just to comment on one point:

> [Relative Colors from CSS Color Module Level 5](https://bugs.chromium.org/p/chromium/issues/detail?id=1274133#c3) which is unsupported by all browser and pretty complex.

Actually no, [looking at the results](https://wpt.fyi/results/css/css-color/parsing?label=master&label=experimental&aligned&view=subtest&q=relative) Safari has 100% passes (2076 / 2076) on RCS in the WPT tests, Chrome and Firefox are also working on it.

It is also pre-cleared (before CR) as [ready to ship](https://github.com/w3c/csswg-drafts/issues/7978)

Your example shows that RCS is pretty simple although there is no need to use `rgb()` there:

#### Option B
Using relative color from CSS Color Module Level 5
```css
:root {
  --c-primary: #e2273c;
}
.regular-background-with-opacity {
  background:  rgb(from var(--c-primary) r g b / 50%);
}
```
what happens if another stylesheet does 

```css
:root {
  --c-primary: color(display-p3 0 1 0);
}

You may be assuming that the color space used for the declaration and the one used for RCS have to match? If so, rest assured that they do not. Although your example will still work, there will just be rgb values greater than 1 00% or less than 0.

Either way, this seems like a simple and easy way to alter the alpha value. Your example is not demonstrating the complexity you mention, do you have a better example?
