### ISSUE TITLE
why mediaqueries?

### ISSUE THREAD

**Issue by ghost** [w3c/csswg-drafts#8472]
A media query consists of a media type and at least one expression that limits the scope of stylesheets using media features such as width, height, and color. Media queries, added in CSS3, let the presentation of content adapt to a specific range of devices without needing to change the content itself.

```html
<!-- CSS media query by link -->
<link rel="stylesheet" media="(max-width: 800px)" href="example.css" />
```

*or*
```css
/* CSS media query inside stylesheet */
@media (max-width: 600px)
{
  .facet_sidebar
   {
    display: none;
   }
}
```

*why don't we do something like this?*
```css

/* example  1 */
max-width: 600px-600px{
  .facet_sidebar
   {
    display: none;
   }  
}

/* example  2 */
max-width: 300px-500px{
  .facet_sidebar
   {
    display: none;
   }  
}

/* example  2.1 */
max-width: start-end {}

/* example  2.2 */
max-width: [500px, 300px, 200px]{}

/* example 3 */
min-width: [500px, 300px, 200px]{}

/* example 4 */
width: [500px, 300px, 200px]{}

/* example 5 */
max-height: [500px, 300px, 200px]{}

/* example 6 */
height: [500px, 300px, 200px]{ }

/* example 7 */
max-height: start-end {}

/* example 8 */
width: start-end {}

/* example 9 */
height: start-end {}

/* example 10 */
min-width: start-end {}

/* example 11 */
min-height: start-end {}

```

**Comment by Loirooriol** [comment]
Both style rules and your media queries can start with an identifier, which can be quite long, but CSS doesn't have infinite lookahead. You also seem to expect `max-width:start-end {}` to be a media query, but it just looks like a type selector, a pseudo-class, and a style block. See nesting discussions, there is a similar problem.

**Comment by SebastianZ** [comment]
It is also not clear to me what your examples actually mean.

Example 1 and 2: `max-width: 300px-500px` doesn't seem to make sense because `max-width` defines a maximum value. A range syntax only makes sense for features without `min-` or `max-` prefix, e.g. for `width`.

What does the syntax using square brackets mean? I assume you want to combine layout breakpoints. Though how do you imagine the style rule and property definitions to look like?

@Loirooriol outlined the implementation view, though also from an author's perspective the suggested range syntax is hardly distinguishable from a style declaration.

And just as a side note in case you didn't know, media query ranges can be defined via a mathematical syntax nowadays. So your first example could also be written like this:

```css
@media (width <= 600px) {
  .facet_sidebar {
    display: none;
  }
}
```

And ranges can be expressed like this:

```css
@media (300px <= width < 500px) { }
```

And with the [nesting](https://drafts.csswg.org/css-nesting-1/) mentioned by @Loirooriol you'll be able to nest media rules inside style rules. That may then look like this:

```css
.facet_sidebar {
  display: flex;

  @media (width <= 600px) {
    display: none;
  }
}
```

So the questions are: What are your use cases? And what's are the benefits of your syntax in comparison to the existing one?

Sebastian

**Comment by tabatkins** [comment]
For a use-case to be convincing, it needs to show something that is some combination of (a) difficult (or impossible) currently, and (b) commonly worked around by authors. Alternately, a convincing argument that while authors don't *currently* do The Thing (because it's too annoying), they likely *would* do it if we made it easier, and this would improve their experience.

None of what you've demonstrated are use-cases, they're just syntax examples. (And in most of them I can't tell what the syntax is trying to achieve.) Could you explain what you're attempting to do with each of the examples, how you might achieve those today and why that's annoying, and why something like the suggested syntax would make things better?

**Comment by Loirooriol** [comment]
Glancing over your proposal, it seems you want:
 - A way to use variables in `@media`. This can be covered by #2627
 - A way to define lists and extract items from lists. This can be covered by `spread()` from #8391 and `nth-value()` from https://github.com/w3c/csswg-drafts/issues/5009#issuecomment-785524020. I don't think this part seems particularly useful in your case, though.

Your example could then be something like

```css
@custom-env --small 200px;
@custom-env --big 600px;
@media (width <= env(--big)) { /* @media (width <= 600px) {  */
  .menuBar { display: none; }
}
@media (width <= env(--small)) { /* @media (width <= 200px) {  */
  .menuBar { display: none; }
}
```
or
```css
@custom-env --sizes spread(200px; 600px);
@media (width <= nth-value(2; env(--sizes))) { /* @media (width <= 600px) {  */
  .menuBar { display: none; }
}
@media (width <= nth-value(1; env(--sizes))) { /* @media (width <= 200px) {  */
  .menuBar { display: none; }
}
```
