### ISSUE TITLE
[css-logical] Add `size` shorthand? (size, min-size, max-size)

### ISSUE THREAD

**Issue by brianewing** [w3c/csswg-drafts#8492]
Logical Properties and Values Level 1 defines `inline-size` and `block-size`, logical mappings for `width` and `height`.

In stylesheets, we often want to set the same value for both dimensions:

```css
foo-container {
  inline-size: 100%;
  block-size: 100%;
}

cool-widget {
  max-inline-size: 100%;
  max-block-size: 100%;
}

canvas {
  min-width: 0;
  min-height: 0;
}
```

Would the WG consider adding `size` as a shorthand property:

```css
foo-container { size: 100% }
cool-widget { max-size: 100% }
canvas { min-size: 0 }
```

Similar to `inset`, `margin`, `padding`, etc, it could help authors write more expressive stylesheets.

A two-value form would support flow-relative syntax for shorthands: #1282
