### ISSUE TITLE
[css-page-3] Specify how to handle negative page margins

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#8508]
(Related to https://github.com/w3c/csswg-drafts/issues/8335 , but now for margin...)

I don't think the css-page-3 spec ( https://w3c.github.io/csswg-drafts/css-page-3/ ) defines what to do (if anything) with negative `@page { margin: ...} ` values (though I may have overlooked it).

In practice:
* Chromium seems to honor negative `@page` margins, effectively inflating the page content area beyond the bounds of the sheet of paper on the sides that have negative margins.  (So, content gets clipped on those sides, generally.) 
* Firefox clamps negative `@page` margin to 0 (or rather, to the printer's writable page area) with the intent of keeping page content on the sheet. (as of https://bugzilla.mozilla.org/show_bug.cgi?id=1665001 )

**Comment by dholbert** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1679041 which was filed 2 years ago by someone who happened to depend on the Chrome behavior (and the behavior that Firefox used to have before https://bugzilla.mozilla.org/show_bug.cgi?id=1665001 )

**Comment by MurakamiShinyu** [comment]
There are certain uses cases of negative page margins.

- negative page margins are used to prevent unwanted page breaking. This is necessary unless we can use `break-inside: never` (discussed in #3404).

- negative page margins can be used to position images fitting to the bleed edges.
  Example: 

  ```css
  @page  {
    size: A4; /* 210mm 297mm */
    marks: crop;
    bleed: 3mm;
    margin: -3mm;
  }

  img {
    display: block;
    width: 100vw; /* = 216mm */
    height: 100vh; /* = 303mm */
  }
  ```
