### ISSUE TITLE
CSS Media Query for Browser Reader Views

### ISSUE THREAD

**Issue by denk0403** [w3c/csswg-drafts#8546]
Safari and Microsoft Edge both have a Reader Mode (named [Reader View](https://support.apple.com/guide/safari/hide-ads-when-reading-sfri32632/mac) and [Immersive Reader](https://support.microsoft.com/en-gb/topic/use-immersive-reader-in-microsoft-edge-72ac6331-2795-42eb-b3e8-c03503231f32), respectively), which aim to remove ads and other distractions when viewing web articles. These modes seem to enforce their own styles on elements and potentially limit what JavaScript is allowed to execute.

I understand these restrictions are necessary in order to make these modes a more accessible format for users, but it would be nice if there was some standardized way for developers to customize a small set of text-related styles (`color`, `display`, `text-decoration`, etc.). Within these modes, Microsoft Edge changes the page's URL protocol to `"read:"`, and Safari changes it to `"safari-reader:"`, so it's partially detectable with JavaScript via `location.protocol`, but it's still unclear to me what kind of JavaScript is allowed to execute.

Personally, this need came up when, due to my web page's structure, Safari's reader view failed to hide certain UI elements, and I didn't want them to appear in the reader view. This feels like something CSS media queries should be able to override. Media queries already support targeting different media types like `print` and `screen`, so it feels natural to add something like `reader` as a new media type to target these reader modes.

Example:
```css
@media reader {
  p.emphasize { text-decoration: underline; }
  .ad { display: none; }
}
```

Browsers then implementing a reader mode should also offer an option to users to "Disable Page Stylesheets" that fallbacks to default styles in the event that a website tries to abuse the media query such as by hiding the page content.

**Comment by thibaudcolas** [comment]
I’m glad to see this being raised! A similar use case I’d have is to change the color of `img` elements with a `filter` so they are higher-contrast against the background of the page as overridden by the reader mode. This is particularly useful for monochrome images (logos, non-decorative icons). Here’s an example of what those styles tend to look like with other media queries:

```css
@media print {
  .my-img {
    /* This image needs to be on the print, but we don’t care about its color. */
    filter: grayscale(1);
  }
}

@media (forced-colors: active) and (prefers-color-scheme: dark) {
  .my-img {
    /* Increase the contrast between the image and bg in forced colors mode with a dark theme */
    filter: contrast(0);
  }
}
```

It’d be useful to do similar tweaks in reader mode to improve contrast / legibility.
