### ISSUE TITLE
[css-backgrounds-4] Allow repeating `none` in `box-shadow-offset`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8567]
`none, none` is currently valid in [`box-shadow`](https://drafts.csswg.org/css-backgrounds-4/#propdef-box-shadow) but not in [`box-shadow-offset`](https://drafts.csswg.org/css-backgrounds-4/#propdef-box-shadow-offset).

`animation`, `transition`, `scroll-timeline`, `view-timeline`, accept declaring `none` with other values and repeating it in a [coordinating value list](https://drafts.csswg.org/css-values-4/#coordinated-value-list). In #8440, I suggested restricting `none` in these properties, before considering some (contrived) use cases.

```css
.box {
  box-shadow: 0px 0px, black none 1px;
}
.box:hover {
  box-shadow-offset: 1px 1px, 2px 2px;
}
```

Nit: stacking `{1,2}` and `#` does not seem invalid but some spec readers may think `[ <length>{1,2} ]#` is clearer.
