### ISSUE TITLE
[css-color-4] [css-color-5] inconsistent mentions of powerless components in `white`.

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8609]
https://drafts.csswg.org/css-color-4/#specifying-oklab-oklch

> If the lightness of an Oklch color is 0% or 0, or 100% or 1.0, both the hue and chroma components are powerless.

So `white` should be equivalent to `oklch(100% none none)`.

https://drafts.csswg.org/css-color-5/#ex-mix-blue-white

> Example 6
> white is rgb(100% 100% 100%) which is lch(100% 0 none) which is oklch(100% 0 none)
> blue is rgb(0% 0% 100%) which is lch(29.5683% 131.201 301.364) which is oklch(45.201% 0.31321 264.052)

------

Chrome :

`oklch(0.725987 0.15663 323.92)`

<img width="75" alt="Screenshot 2023-03-17 at 22 51 53" src="https://user-images.githubusercontent.com/11521496/226059730-05d0b77d-0631-4581-adf4-d3242f81539e.png">

Safari :

`oklch(0.72600687 0.15660721 177.02602)`

<img width="144" alt="Screenshot 2023-03-17 at 22 52 19" src="https://user-images.githubusercontent.com/11521496/226059761-bf49c741-ce5c-4a55-ba43-0a586f30c502.png">

Specification :

`oklch(72.601% 0.15661 264.052)`

<img width="149" alt="Screenshot 2023-03-17 at 22 57 15" src="https://user-images.githubusercontent.com/11521496/226060264-6cb5886c-c19e-43ba-9b6e-095cbd3e9d5b.png">

What I think it should actually be :

`oklch(72.601% 0.31321 264.052)`

<img width="97" alt="Screenshot 2023-03-17 at 22 57 44" src="https://user-images.githubusercontent.com/11521496/226060326-ad52914b-b681-4f14-a0e3-36a3f064b200.png">

------

I think we are seeing the same implementation issues as in :
- https://github.com/w3c/csswg-drafts/issues/8563
- https://github.com/w3c/csswg-drafts/issues/8602

But this might require different specification and test edits to resolve.

**Comment by facelessuser** [comment]
This is because the OkLCh algorithm does not resolve to a perfect zero (except maybe for black) when a color is achromatic. There are some color spaces that do even worse, but OkLCh is the worse offender in CSS, and it really isn't that bad. 

Compared to LCh though, OkLCh does a worse job and is actually more sensitive to the hue because chroma doesn't get as low as it does with LCh. The ideal hue for OkLCh is somewhere around 90˚ based on the CSS matrices, but using zero ends up being "close enough" and introduces only minimal error, but may slightly impact the round trip.

```py
>>> Color('white').convert('oklch').set('hue', 0).convert('srgb')[:]
[1.000000056645113, 0.9999999632010229, 1.0000001023697391, 1.0]
>>> Color('white').convert('oklch', undef=False).convert('srgb')[:]
[1.0000000000000049, 0.9999999999999981, 0.9999999999999999, 1.0]
>>> Color('white').convert('oklch', undef=False)[:]
[0.9999999935000001, 3.729999997759137e-08, 90.00000025580869, 1.0]
>>> Color('white').convert('oklch')[:]
[0.9999999935000001, 3.729999997759137e-08, nan, 1.0]

```

The CSS spec does mention the powerless when "close to zero" for things like LCh and OkLCh, but yes, it gives no specific directions beyond that. It also doesn't mention this for HSL, so conversions from OkLCh to HSL, could leave you with a color close to achromatic, but not quite in HSL.

> For extremely small values of a and b (near-zero Chroma), although the visual color does not change from being on the neutral axis, small changes to the values can result in the reported hue angle swinging about wildly and being essentially random. In CSS, this means the hue is [powerless](https://www.w3.org/TR/css-color-4/#powerless-color-component), and treated as [missing](https://www.w3.org/TR/css-color-4/#missing-color-component) when converted into LCH or Oklch; in non-CSS contexts, this might be reflected as a missing value, such as NaN.

Calculating some perfect threshold for each cylindrical space that resolves to identify achromatic exactly the same in all spaces when you convert to them may prove difficult as each color space has different levels of accuracy for chroma/saturation equaling zero, and the scaling is a bit different. I'm not sure how much CSS cares about this, at least with the current included color spaces, if most achromatic colors are firmly in the achromatic pocket, it is likely you could pick a threshold tailored to each space that is close enough.

You could eliminate a lot of these achromatic detection differences between spaces by identifying achromatic colors in a common space, like maybe taking the cross product of the color vector against the white point vector in the XYZ D65 color spaces (with some threshold for deviation away from zero). Then "closeness" for achromatic colors would be the same for each space. This would require an XYZ conversion when checking achromatic colors though.

**Comment by romainmenke** [comment]
That is not really what is happening here.
You can get the same result with a white defined in `oklch`

This should be true white in `oklch`:

```css
color-mix(in oklch, oklch(100% 0 0), blue);
```

Browsers just aren't handling powerless/missing components correctly.
But the specification is also inconsistent when referring to these powerless/missing components.

- `css-color-4`: `white` is `oklch(100% none none)`
- `css-color-5`: `white` is `oklch(100% 0 none)`

This is not a math/floating point issue, it is a specification and implementation issue :)

**Comment by facelessuser** [comment]
Ah, well the spec does mention it, just no real specifics :).  If implementations do choose to rely on a hard 0, the previously mentioned issues may arise as well, but I get what you are saying.

**Comment by facelessuser** [comment]
So, I've actually taken a closer look at this. If powerless means that interpolation should treat the components as missing, I think the current CSS spec is heading in a confusing direction. Let's take a look.

Here we create two OkLCh colors `oklch(1 0 none)` and `oklch(1 none none)`. The first matches white yields the results in the CSS spec which I believe was added before the stipulation that 0% and 100% lightness make chroma powerless. The latter matches the powerless suggestions in the spec and also matches @romainmenke's assertion that the proper OkLCh output should be `oklch(72.601% 0.31321 264.052)`. But notices how the powerless hue makes the blue more purple.

<img width="625" alt="Screenshot 2023-03-29 at 11 23 28 AM" src="https://user-images.githubusercontent.com/1055125/228619080-635c71fb-e0ed-4fba-bb04-de30097e1b24.png">

But let's look at the entire interpolation:

<img width="1365" alt="Screenshot 2023-03-29 at 11 26 55 AM" src="https://user-images.githubusercontent.com/1055125/228619507-610db4a6-6fe7-4a40-92c0-fd4d70a70ea9.png">

Oh, no, now we have a huge shift in color. This defeats the whole purpose of using OkLCh! What happens if we use black?

<img width="1355" alt="Screenshot 2023-03-29 at 11 30 57 AM" src="https://user-images.githubusercontent.com/1055125/228620612-1cd60153-58ce-4c23-8dde-0423e57302ad.png">

Just as bad.

So, why do we want chroma as powerless treated as missing for black and white during interpolation?

**Comment by facelessuser** [comment]
I guess I'd make the same argument for forcing `a` and `b` to be powerless (assuming powerless actually means undefined) in Lab color spaces as well.

**Comment by svgeesus** [comment]
Right, clearly for achromatic colors `a` and `b` and `C` are zero or near zero, not undefined. Hue on the other hand is ill conditioned and could swing all over the place from small shifts in `a` and `b`, so it genuinely is powerless.

**Comment by svgeesus** [comment]
[This part](https://drafts.csswg.org/css-color-4/#powerless) is just plain wrong:

> For example, a gray color converted into [lch()](https://drafts.csswg.org/css-color-4/#funcdef-lch) may, due to numerical errors, have an extremely small chroma rather than precisely 0%; this can, at the user agent’s discretion, still treat the hue component as powerless.

Saying that missing components get treated as zero is fine (but assuming that always happens is not fine; in interpolation the missing component is treated as the analogous component in the other color). Saying that zero-valued components are always missing, on the other hand, is just wrong.

**Comment by romainmenke** [comment]
@facelessuser Are you sure there aren't any bugs on your end?
Those results do not match what I am seeing in our implementation.

I don't understand why you would get a hue shift here.

```css
.foo {
	background: linear-gradient(to right, rgb(255, 255, 255) 0%, color(display-p3 0.57766 0.85014 1.67992), color(display-p3 0.51024 0.77327 1.59733), color(display-p3 0.44387 0.69646 1.51535), color(display-p3 0.37854 0.61944 1.43399), color(display-p3 0.31424 0.54177 1.35327), color(display-p3 0.25084 0.4627 1.27319), color(display-p3 0.18808 0.38082 1.19377), color(display-p3 0.12528 0.29307 1.11502), color(display-p3 0.05998 0.19058 1.03695), rgb(0, 0, 255) 100%); /* generated fallback */
	background: linear-gradient(to right in oklch, white 0%, blue 100%); /* original */
}
```

Should look like :

<img width="484" alt="Screenshot 2023-03-29 at 23 29 16" src="https://user-images.githubusercontent.com/11521496/228671996-b6aa1752-5965-4a36-86db-8ecc81833ef0.png">


----

```css
.foo {
	background: linear-gradient(to right, rgb(255, 255, 255) 0%, color(display-p3 0.89543 0.92911 1.00686), color(display-p3 0.79238 0.85738 1.01077), color(display-p3 0.69089 0.78448 1.01198), color(display-p3 0.59093 0.70993 1.01068), color(display-p3 0.49247 0.63302 1.00706), color(display-p3 0.39536 0.55257 1.0013), color(display-p3 0.29925 0.46652 0.99353), color(display-p3 0.20328 0.37049 0.9839), color(display-p3 0.10457 0.25236 0.97254), rgb(0, 0, 255) 100%); /* generated fallback */
	background: linear-gradient(to right in oklch, oklch(100% 0 none) 0%, blue 100%); /* original */
}
```

Should look like :

<img width="490" alt="Screenshot 2023-03-29 at 23 37 21" src="https://user-images.githubusercontent.com/11521496/228673521-76b59bde-e031-49fe-873c-9cce823a0322.png">

----

The second example with `0` chroma is slightly less saturated, but there isn't any difference in hue between these two.

------

It is not unlikely that what I am doing here isn't a good way to verify this part of the specification.

But using the tools I have, to try and illustrate how we've interpreted and implemented the specification.
