### ISSUE TITLE
[css3-selectors][css-pseudo-4] Add Pseudo Element ::around or ::wrap simmilar to ::before / ::after

### ISSUE THREAD

**Issue by inoas** [w3c/csswg-drafts#877]
In essence `display: flex`, `display: grid` and `display: table` + float hacks already give a lot of flexibility on rendering layout. However more often than not authors have to add `div` / `span` just for rendering/presentation purposes.

### Proposal
Add `::around` or `::wrap` pseudo-elements.

### Example Use Case
```css
/* horizontally centered article having a max-width */
article {
  max-width: 500px;
  margin: 0 auto;
}
article.with-background::around, /* fully stretched background if class given */
article.nth(2)::around { /* fully stretched background on every 2nd element */
  display: block;
  width: 100%;
  background: orange;
}
```

Usually these presentional-only boxes would require extra divs in the dom.

```html
<div class="max-width-container">
	<article>
		...
	</article>
</div>
<article>
	...
</article>
```

VS

```html
<article>
	...
</article>
<article>
	...
</article>
```

OR

```html
<article class="with-background">
	...
</article>
```

#### Codepen Examples
Div Wrapper: http://codepen.io/anon/pen/jyWqqE
Pseudo Wrapper: http://codepen.io/anon/pen/JEGKKw
