### ISSUE TITLE
[css-color-5] Examples 11, 20, 24, ... mix deg and number values

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8839]
https://drafts.csswg.org/css-color-5/#example-4889a5cd

```css
html { --base:  oklch(52.6% 0.115 44.6deg) }
.summary {
  background:  oklch(from var(--base) l c  calc(h + 90));
}
```

The calc expression is `calc(44.6deg + 90)` which is not valid as far as I know.

`90` and `90deg` are both valid `<angle>` values but I don't think these can be added in `calc`

----

https://drafts.csswg.org/css-color-5/#example-c4b276dd

```css
--accent:  lightseagreen;
--complement:   hsl(from var(--accent) calc(h + 180) s l);
```

----

https://drafts.csswg.org/css-color-5/#example-fb53cf30

```css
--accent:  lightseagreen;
--complement:   lch(from var(--accent) l c calc(h + 180));
```

----

_there might be more examples_

-----

@svgeesus is the example incorrect or am I overlooking something?
