### ISSUE TITLE
[css-anchor-1] Change `anchor-scroll`'s initial value to `default`

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#8844]
I think it's better if `anchor-scroll`'s initial value is `default`, so that as long as we are using `anchor-default` or implicit anchor, we don't need to explicitly set the value of `anchor-scroll`.

This would allow a very simple the basic usage pattern, where `anchor-scroll` is automatically hooked up:

```css
.anchor { anchor-name: --my-anchor; }
.target {
  position: fixed;
  anchor-default: --my-anchor;
  top: anchor(bottom);
  left: anchor(left);
}
```

Also:
- In my understanding, `anchor-scroll` is a technical side-product to prevent doing relayout on scroll changes
- We might change the name of `anchor-scroll` for issues like #8675

So it's not a very ergonomic design, and if we can avoid it from a use case, avoid it.
