### ISSUE TITLE
[css-view-transitions-2] Media query alternative to cross-document opt-in

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#8868]
In #8048, the proposal is to use a new rule for opting-in to cross-document transitions.
This has a few drawbacks:
- You can't opt-out of the transition based on things in the document, e.g. `body.disable-transitions { @cross-document-transitions: allow; }`
- It's totally different from the way you disable of same-document transitions (`::view-transitions { display: none }`)
- Its limited to opting in/out, it requires extensions or JS to allow, for example, different names for cross-document transition.
- It's a bespoke rule, so we have to define how it interacts with other rules and so forth, and developers have to learn it.

Proposing, instead, to use a media-query:
```css
@media (page-tranistion: incoming | outgoing | any | ...` (we can bikeshed this of course)
```
To accomplish the original requirement of disabling cross-doc transitions by default, the default UA stylesheet can be:
```css
@media (page-transition) { 
  ::view-transition { display: none }
}
```

This separates the condition (is this a page-transition?) with the action (the transition should be animated/skipped) and thus allows for more mixing and matching, e.g:
```css
@media (page-transition) or (prefers-reduce-motion) {
  ::view-transition { display: none }
}

@media (page-transition: outgoing)  {
  body.disallow-outgoing-tranistions {
    ::view-transition { display: none }
  }
}
```

We can also change the transition names based on whether this is a page transition:

```css
#my-element { view-transition-name: some-name }

@media (page-transition) {
   #my-element { view-transition-name: some-other-name }
}
```

We also get the JS API for free [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and [`MediaQueryList/change` event](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/change_event) gives the developer all the JS observability they need. There's no need for a `ViewTransition` object.

Note that to enable this, we would have to clearly define in the lifecycle at which exact points in the navigation/rendering lifecycle the page-transition media is matched, and we would have to enable the `::view-transition` pseudo-element when navigating to a page that can potentially trigger a page transition.

**Comment by bramus** [comment]
In general, I like this at-rule approach. 

A few remarks/questions:

1. What is the lifetime when these at-rules apply? In internal conversations I heard that the incoming one would only be alive at the very first frame _(to actually opt in + optionally set up different transition names)_ and outgoing one only at the very last frame of the page.

2. The nested example seems incorrect. I think it should be this, as `::view-transition` is a pseudo of the root :

    ```css
    @media (page-transition: outgoing)  {
      :root:has(body.disallow-outgoing-transitions)::view-transition {
        display: none;
      }
    }
    ```
    
    However, with `@media (page-transition) { ::view-transition { display: none } }` in the UA, in practice the logic would be flipped around, no? Like this:
    
    
    ```css
    @media (prefers-reduce-motion: no-preference) and (page-transition) {
      ::view-transition { display: block; }
    }
    ```
    
    Or, more selectively:
    
    ```css
    @media (prefers-reduce-motion: no-preference) and (page-transition) {
      :root:has(body.allow-outgoing-transitions)::view-transition {
        display: block;
       }
    }
    ```

3. Would this replace the meta tag opt-in? If not, what happens when both are set with contradicting values? More specifically, what happens if the meta tag opts-in, but the the UA default styles (which is essentially an opt-out) is applied?

4. When the outgoing page does not opt-in but the incoming page does, do we then get a simple fade-in of the root or would all transitions get skipped? Put differently: it’s a double opt-in?

5. With the JS approach, one quickly can set up some classes on the root based on the directionality of the page hierarchy. For example, clicking from an overview page to a detail page should slide all stuff to the left, whereas then clicking the home icon should slide all stuff to the right as you’re going back from that detail page to the overview page.

    Maybe there should be some way to pass this type of info from one page to another, which could then also be taken into account in the MQ on the new page? That way, an author can set up the appropriate vt-names and animations, based on that piece of data. In #8048, you proposed for the page URL to be that piece of data. Is this still considered?
    
    _(Not sure if this is essential to this issue, or could be discussed separately.)_
