### ISSUE TITLE
[cssom]getComputedStyle(element) should return a list of transform functions

### ISSUE THREAD

**Issue by gibbok** [w3c/csswg-drafts#891]
I would like to suggest having `getComputedStyle(element).transform` function returning the actual transform functions and serialized matrix instead serialized matrix only.

Or alternative having a new function returning the actual transform functions.

Example:
https://jsfiddle.net/gibbok/pruyh2ns/

````html
<div id="target"></div>
````
````css
div {
  transform: translate(0, 0) rotate(45deg);
  width: 50px;
  height:100px;
  background-color:red;
}
````
````js
var elem1 = document.getElementById("target");
var style = window.getComputedStyle(elem1, null);
console.log(style.transform);
// now returns matrix(0.707107, 0.707107, -0.707107, 0.707107, 0, 0)
// would be interesting having also the actual transform functions returned as translate(0, 0) rotate(45deg)
````

Related documentation:
https://drafts.csswg.org/css-transforms/#serialization-of-the-computed-value

Related:
https://bugs.chromium.org/p/chromium/issues/detail?id=680111
https://github.com/web-animations/web-animations-js/issues/101
