### ISSUE TITLE
[css-view-transitions-1] Should mix-blend-mode be a part of the ua opacity animation?

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#8924]
This is somewhat related to [ISSUE 4](https://drafts.csswg.org/css-view-transitions/#issue-c760166d) in the spec. We currently specify mix-blend-mode conditionally if we have a crossfade. 

This, however, has unintended and sometimes surprising effects for developers trying to customize old/new animations. @argyleink had an example where the old content did a slide out to the left and new content did a slide in from the left: the overlap between the two contents did not "look right", since the expectation is to see a normal blend mode.

My suggestion is to consider putting mix-blend-mode to be a part of the UA animation instead, maybe something like

```
@keyframes -ua-mix-blend-mode-plus-lighter {
  from { mix-blend-mode: plus-lighter }
  to { mix-blend-mode: plus-lighter }
}
```
and adding that into the animation-name for ua generated css. As an aside, mix-blend-mode is not animatable, but would need to be at least discretely animatable for this to work.

It's a bit of a hack, but I worry that having mix-blend-mode that is added for pairs automatically may cause more developer pain.

Any thoughts?

**Comment by fantasai** [comment]
I think mix-blend-mode should be animatable. I suspect what happened is that the reformatting of ”Animatable” to “Animation type” didn't catch the compositing spec, and it's really _supposed_ to be “discrete”.

**Comment by khushalsagar** [comment]
So the idea here is that if authors override the default animation on old/new images, we want it to automatically override the blending as well? Because use of the blend-mode is tightly coupled with the opacity animation. Adding up the pixels on the 2 images works because they precisely overlap each other and their opacity (based on the fade animation) adds up to 1.

This thought process sounds good but it would be better if this could be setup in a way that this also removes `isolation` from the wrapper. Otherwise we have undue rendering cost that authors will not notice because its not a visual glitch. Can't think of a CSS way to make that happen.

**Comment by vmpstr** [comment]
I also don't know if it's possible to select based on the specified css value of a descendant (I don't think it is?) I think isolation rendering cost in this case should be something that a user-agent can optimize.

Since we'd have a normal blending mode, so there would be no other trigger for compositing, so isolation can also be decomposited. Is that right?

**Comment by khushalsagar** [comment]
That's a good question. `isolation` has to induce a stacking context (since that affects paint order) but doesn't necessarily require us to composite the descendants first if they are all using normal blending. Blending is associated if every element has normal blending.

Blend(A, Blend (B, C)) = Blend(Blend(A,B), C)

Thank you @ccameron-chromium for walking me through the math!

In that case, I'm good with this proposal. Just to summarize:

- The current UA CSS for cross-fading the 2 images is as follows:
    ```css
    @keyframes -ua-view-transition-fade-out {
	to { opacity: 0; }
    }
    @keyframes -ua-view-transition-fade-in {
	from { opacity: 0; }
    }
    :root::view-transition-old(*) {
	animation-name: -ua-view-transition-fade-out;
	mix-blend-mode: plus-lighter;
    }
    :root::view-transition-new(*) {
	animation-name: -ua-view-transition-fade-in;
	mix-blend-mode: plus-lighter;
    }
    :root::view-transition-image-pair(*) {
        isolation: isolate;
    }
    ```

- We want to change it to this instead:
    ```css
    @keyframes -ua-view-transition-fade-out {
	to { opacity: 0; }
    }
    @keyframes -ua-view-transition-fade-in {
	from { opacity: 0; }
    }
    @keyframes -ua-mix-blend-mode-plus-lighter {
      from { mix-blend-mode: plus-lighter }
      to { mix-blend-mode: plus-lighter }
    }
    :root::view-transition-old(*) {
	animation-name: -ua-view-transition-fade-out, -ua-mix-blend-mode-plus-lighter;
	mix-blend-mode: plus-lighter;
    }
    :root::view-transition-new(*) {
	animation-name: -ua-view-transition-fade-in, -ua-mix-blend-mode-plus-lighter;
	mix-blend-mode: plus-lighter;
    }
    :root::view-transition-image-pair(*) {
        isolation: isolate;
    }
    ```
    Because the blending is tightly coupled to the cross-fade. If the author is overriding the cross-fade, the blend mode is just getting in their way.

Open to suggestions to set up this CSS such that `isolation` also gets removed if the author removes the cross-fade animation. But we can optimize the rendering internally assuming none of the elements in the sub-tree have normal blending.
