### ISSUE TITLE
[css-view-transitions-1] Possible perf footgun when styling pseudo-tree based on state

### ISSUE THREAD

**Issue by ydaniv** [w3c/csswg-drafts#8960]
Currently in order to change the style of the generated pseudo-tree based on state of the DOM one has to use a `:has()` selector on the `html` element to capture that state and then chain the pseudo-elements from there to style them.
I have discussed this with @una, @lilles, and @andruud at CSS Day and they said that using a `:has()` on an element so high up the DOM tree may be a big perf issue with rendering possibly taking a few seconds in some cases.

Here is a codepen with a simple example: https://codepen.io/ydaniv/pen/QWJjgQp

Basically it has this:
```html
<main>
  <div id=source></div>
  <div id=target></div>
</main>
```

And styles:
```css
/* This is our source of trouble */
html:has(.switch)::view-transition-group(circle) {
  animation-duration: 1.2s;
}

#source {
  view-transition-name: circle;
 
 .switch & {
    display: none;
  }
}

#target {
  display: none;

  .switch & {
    display: block;
  }
}
```

And the JS for triggering VT is:

```javascript
document.startViewTransition(() => {
    main.classList.toggle('switch');
});
```

My concern is that this may become a common pattern and cause big frustration, probably even more so users than to authors.

It's possible to work around this by lifting all such state up to the `html` element and try to mitigate this with communicating this to authors.
However, I think it's worth trying to find another solution for avoiding it altogetehr.

**Comment by fantasai** [comment]
Are you needing to:

- select based on the new state of the transitioning element in the DOM?
- select based on the old state of the transitioning element in the DOM?
- both?
- select based on a temporary class indicating the type of desired visual transition?
- all of the above?

**Comment by ydaniv** [comment]
My use-case is a simple page transition, and currently just checking a data attribute which holds the type of visual transition to play. Based on the type I change animation properties on both old and new. Could be also on group if I had other animations.
In my use-case it's not temporary, but could definitely change in other scenarios.
So I guess it's all of the above.

I think it boils down to managing transition state in general.
I see 2 options here:

1. It's a "no change", and and agree on the best mechanism for handling state is lifting it up to the `html` element, or maybe even using custom properties on `:root`
2. We define some mechanism for handling that state so that developers are more likely to use it, than to trip on the `:has()` wire

And then I guess we communicate it to developers before it gets messy.

**Comment by khushalsagar** [comment]
A pattern I saw from @jakearchibald which seemed like the easiest/most performant way to do this was using class names on html. When calling startViewTransition, you should know the type of transition. Let's call it type. Add a class corresponding to this type to html for the lifetime of the transition. And then all the CSS is gated on checking whether html has that class.

Script
```js
function doTransition(type, updateCallback) {
   document.documentElement.classList.add(type);
   let transition = document.startViewTransition(updateCallback);
   transition.finished.then(() => {
      document.documentElement.classList.remove(type);
   });
}
```

CSS
```css
:root.type ::view-transition-old(foo) {
   ...
}
```

Would that work?

**Comment by ydaniv** [comment]
Thanks @khushalsagar , I'm already doing that as well.
Of course this could work for all cases, but it still requires components inside the document "touching" DOM elements above them and outside their scope, or at least create some sort of mechanism for exposing this state to the root.

This could be especially problematic for developers of component libraries, where they don't have access to their embedding context, which is also somewhat the case I have at hand, only I'm allowed to play both sides in my case.

**Comment by bramus** [comment]
Would it help if you had any of these available, while being able to read that info in CSS so you can respond to it:

- A way to set a temporary flag/label on the transition
- A way to know which element triggered the transition

**Comment by ydaniv** [comment]
> A way to set a temporary flag/label on the transition

Yes, that would help. The only problem is that for now this may lead authors to add `html:has(...)` for that.

> A way to know which element triggered the transition

Not sure what you mean by that. Talking about SPAs, the transition is triggered via JS and any state at that point can be managed as written above. I'm mostly concerned with handling the declarative state in CSS without causing any potential harm.

**Comment by khushalsagar** [comment]
@ydaniv thanks for clarifying. Do you mind updating the issue title? It doesn't sound like we have a perf issue. It's having to leak information from a component triggering/managing the transition to the embedding context. Also updating the label since this seems like a future feature request but not an issue that needs to be fixed in the current spec.

FWIW, I feel like involving the root (or embedding page) for transitions which span the entire Document makes sense. The whole Document is going to be paused with a layer (view transition stacking context) on top of the whole Document. So a component trying to do it transparently, i.e, avoiding setting state on the documentElement doesn't make sense.

It is a valid question for [scoped transitions](https://github.com/WICG/view-transitions/blob/main/explainer.md#transitions-targeted-to-a-specific-element). But assuming the whole setup (like the view transition stacking context) is scoped to the element which is the root of the transition (and thus the originating element for all pseudos associated with that transition), you could do the class based approach by targeting the element which is the root of that transition. This is conceptually similar to how a transition in an iframe would work.

**Comment by ydaniv** [comment]
Sure @khushalsagar, I generally agree, but the problematic pattern still remains. We might as well resolve on adding a note in MDN (and perhaps web.dev and other places) about avoiding this, and using the other method of setting an attribute on documentElement or a custom property on :root.

**Comment by bramus** [comment]
> We might as well resolve on adding a note in MDN (and perhaps web.dev and other places) about avoiding this

This is covered in https://developer.chrome.com/docs/web-platform/view-transitions/#changing-on-navigation-type, which reads:

> The best way to handle these cases is to set a class name on `<html>`, also known as the document element

**Comment by khushalsagar** [comment]
Thanks for the pointer @bramus. Let me add this to the agenda to make sure the group agrees that this is the most optimal approach. We can add it to the MDN docs as well.

**Comment by jakearchibald** [comment]
This situation will be improved if https://github.com/w3c/csswg-drafts/issues/8683 lands in a way that can also be made available to SPA transitions, which is my recommendation.

**Comment by khushalsagar** [comment]
Assuming we have a parameter passed to `startViewTransition` to provide a transition-name, we’d likely want customization to be supported by adding a parameter in the selectors for ::view-transition pseudo-elements (like `::view-transition-group(foo, transition-name)`). But I don't know if it addresses all use-cases, you won't be able to affect CSS of other DOM elements (like setting `view-transition-name`) using this.

Alternate would be media-query but because there will be support for concurrent transitions eventually, a global concept like media-query does not make sense.

**Comment by bramus** [comment]
I would pass in the parameter to `document.startViewTransition()` using a property bag, as maybe alter some more parameters might be needed:

```js
document.startViewTransition(updateTheDom, {
  type: 'back',
});
```

I like the idea of adding a parameter to the pseudos, but was thinking towards reusing the qualified name syntax for it, as that would not break the existing syntax:

```css
::view-transition-old(*) {
  animation-name: slide-out-to-left;
}
::view-transition-new(*) {
  animation-name: slide-in-from-right;
}

/* Respond to the “back” type of transition, by setting that type as a prefix to the argument */
::view-transition-old(back|*) {
  animation-name: slide-out-to-right;
}
::view-transition-new(back|*) {
  animation-name: slide-in-from-left;
}

```

Or maybe have it as an argument to the `::view-transition` pseudo, where the author would then need to nest the other pseudos:

```css
/* Respond to the “back” type of transition, by setting that type as the name to the enclosing ::view-transition() pseudo */
::view-transition(back) {
  ::view-transition-old(*) {
    animation-name: slide-out-to-right;
  }
  ::view-transition-new(*) {
    animation-name: slide-in-from-left;
  }
}
```

In this last syntax, only the `::view-transition` pseudo accepts a type, the other pseudos need a `view-transition-name` as their argument (or `*`).

One other idea that was floated was to use an at-rule for this, but as @khushalsagar [already mentioned](https://github.com/w3c/csswg-drafts/issues/8960#issuecomment-1602907772) _“Media queries are globally applied on the Document so are not a good fit for scoped transitions.”_ The syntaxes proposed here are not affected by it, as one can prepend the scoping element to the selector, e.g. `:root::view-transition(back)`.

**Comment by vmpstr** [comment]
There's also a possibility of adding a new pseudo class that applies to all elements (including view transition pseudos) that get activated right before the capture element discovery,

something like
```css
::view-transition-old(*):vt(back) {
  ...
}
```
This enables the possibility of having optional view-transition-names on non-view-transition pseudos based on the navigation type:
```css
#foo {
  view-transition-name: foo;
}
#foo:vt(back) {
  view-transition-name: none;
}
```
which is likely desirable as well?

**Comment by khushalsagar** [comment]
The nice thing about pseudo-class is that they work well with scoped transitions. Since we can activate it only for nodes in the sub-tree which can participate in that transition.

Credits to @noamr who's suggestion on https://github.com/w3c/csswg-drafts/issues/8048 gave the pseudo-class idea.

**Comment by ydaniv** [comment]
@bramus 

> I would pass in the parameter to document.startViewTransition() using a property bag, as maybe alter some more parameters might be needed

That could be nice, but how would that translate into the corresponding selectors?

@vmpstr, +1 on the pseudo-classes! Could it also play with the property bag suggestion above?

**Comment by jakearchibald** [comment]
If options are being added to `startViewTransition`, please avoid this issue https://github.com/whatwg/webidl/issues/1191

**Comment by vmpstr** [comment]
> If options are being added to `startViewTransition`, please avoid this issue [whatwg/webidl#1191](https://github.com/whatwg/webidl/issues/1191)

By "please avoid", do you mean we shouldn't add a dictionary as a second parameter to startViewTransition? Looking through the webidl issue, it doesn't _seem_ like a large effort is required to distinguish the two, in which case we can go from "callback" to "callback or dictionary" without breaking existing usage.

Jake, are you by any chance willing to drive the spec changes in webidl?

**Comment by vmpstr** [comment]
> @vmpstr, +1 on the pseudo-classes! Could it also play with the property bag suggestion above?

Yeah, I think it goes nicely with a property bag as well, assuming that we can figure out how to do that without the undesired "second parameter is an opts dict"

**Comment by noamr** [comment]
> > @vmpstr, +1 on the pseudo-classes! Could it also play with the property bag suggestion above?
> 
> 
> 
> Yeah, I think it goes nicely with a property bag as well, assuming that we can figure out how to do that without the undesired "second parameter is an opts dict"

We can use one opts dict Parma, with the done callback being one of the values of the dict (so you pass either a callback or a dict with a callback plus other  opts)

**Comment by jakearchibald** [comment]
@vmpstr I'm not sure how much standards time I get in my current role, if any. I'm still figuring that out. But it seems like it could just be done in the prose https://github.com/whatwg/webidl/issues/1191#issuecomment-1250176883

**Comment by khushalsagar** [comment]
Summarizing the proposal and adding this issue to the agenda.

- When the developer starts a transition, they get to specify an identifier for for the transition.
   ```js
      document.startViewTransition({updateCallback: doDOMUpdate, transition-type: foo});
   ```

- This type can now be used in a pseudo-class with any selector.
   ```css
      #my-element:view-transition-type(foo) {
         view-transition-name: my-element;
      }

      html::view-transition-group(my-element):view-transition-type(foo) {
         animation: none;
      }
   ```
   
   The pseudo-class is activated when startViewTransition is called and de-activated when the `finished` promise for the transition is fired. This pseudo-class could appear before/after other pseudo-classes, specifically the `only-child` pseudo-class. Not sure if we need to disallow combining with any pseudo-class.

**Comment by noamr** [comment]
> Summarizing the proposal and adding this issue to the agenda.
> 
> * When the developer starts a transition, they get to specify an identifier for for the transition.
>   ```js
>      document.startViewTransition({updateCallback: doDOMUpdate, transition-type: foo});
>   ```

Nit: Probably `transitionType`. Though I'd use the word class instead of type, type implies selecting from an enum.

> * This type can now be used in a pseudo-class with any selector.
>   ```css
>      #my-element:view-transition-type(foo) {
>         view-transition-name: my-element;
>      }
>   
>      html::view-transition-group(my-element):view-transition-type(foo) {
>         animation: none;
>      }
>   ```
>      
>     
>   Not sure if we need to disallow combining with any pseudo-class.

Why would we do that? `:view-transitiontype(foo):has(img#hero)` seems fine to me.

**Comment by bramus** [comment]
> `:view-transitiontype(foo):has(img#hero)` seems fine to me.

Then we are back at the issue as originally posted: _“one has to use a `:has()` selector on the `html` element to capture that state and then chain the pseudo-elements from there to style them.”_

**Comment by noamr** [comment]
> > `:view-transitiontype(foo):has(img#hero)` seems fine to me.
> 
> Then we are back at the issue as originally posted: _“one has to use a `:has()` selector on the `html` element to capture that state and then chain the pseudo-elements from there to style them.”_

I used `:has` here only as an example for pseudo-class, can be `:view-transition-type(foo):fullscreen` for that matter.

**Comment by ydaniv** [comment]
Does the `:view-transition-type()` class actually selects anything? As I see it it behaves more like a boolean flag than a selector. Which is fine, but technically it's closer in nature to at-rules than to pseudo-classes.

**Comment by noamr** [comment]
> Does the `:view-transition-type()` class actually selects anything? As I see it it behaves more like a boolean flag than a selector. Which is fine, but technically it's closer in nature to at-rules than to pseudo-classes.

It selects the root element in this case, but when we have element-scoped transition it would select the element whose a view-transition scope.

**Comment by khushalsagar** [comment]
We recently discussed this issue, adding notes below:

- We like the idea of using a pseudo-class because its easily extendible to scoped transitions. The pseudo-class will be activated only on the transition root.
- The type should be one of the params to the `@view-transition` config. This helps authors use the same CSS for same-document vs cross-document transitions. For example, a site might choose between the 2 for the same navigation (@bramus had an example for such a pattern).
- For the MPA case, the type could either be limited to the Document declaring it. In other words, if the old Document declares a type its not carried over to the new Document. Or it does and we deal with the case where the new Document declares a different type.
   
   My preference is to let this be per Document. Much easier to reason about and we don't have any use-case where authors need us to carry it over from the old Document (vs just declaring it themselves in the new Document).
   
   Another option is to let the old Document be the decider but that's bad if the new Document chooses a different transition based on load state (transition to content if cache hit vs a loading screen).
- Does this class activate only on the transition root or all elements which could participate in the transition. @noamr made an excellent argument for only activating it on the transition root.
   
   Authors want namespacing in 2 ways: [transition root, transition type]. If we activate the pseudo-class on every element in the subtree, you can't namespace based on transition root. That'll force authors to express that namespacing in the transition type value instead.

  ```css
     div:active-view-transition(reload) > section {​
     view-transition-name: main-section;
  }
  
     html:active-view-transition(reload) > section {​
     view-transition-name: none;
  }
  ```
   vs
  ```css
     section:active-view-transition(sub-reload) {​
     view-transition-name: main-section;
  }
  
      section:active-view-transition(html-reload) {​
      view-transition-name: none;
  }
  ```
   Its trivial to use the descendant selector on all sub-tree elements so no motivation to activate it on all of them anyway.

**Comment by vmpstr** [comment]
> * The type should be one of the params to the `@view-transition` config. This helps authors use the same CSS for same-document vs cross-document transitions. For example, a site might choose between the 2 for the same navigation (@bramus had an example for such a pattern).

I'd like to clarify a couple of things here:
1. We're talking about MPA transitions, so when you say the type should be reflected in `@view-transition` config, this has no bearing on transitions initiated with `startViewTransition`. If the latter has a type specified in it, which is also a part of this issue, then it affects that transition.
1. The above implies that `@view-transition { type: foo }` has no effect when the transition is initiated with `startViewTransition`. Since both these types will be affecting the same pseudo class activation, we need to be clear about this in the spec. The corollary to this is likely that we won't be able to add a `script` value to the opt-in property, since it would only add confusion about opt-in affecting script. This also aligns with several opinions we've heard comparing this to web animations: CSS can't disable those. 

I'd like to propose a syntax for `startViewTransition`:
* `startViewTransition((UpdateCallback or StartViewTranstionDictionary))` where `UpdateCallback` is the existing syntax, and `StartViewTransitionDictionary` is a dictionary that includes `updateCallback` -- an `UpdateCallback` to use -- and `type` -- a `DOMString` identifying the type of the transition (bikeshedding welcome!). The union should already be distinguishable based on the union type selection algorithm in WebIDL, but I have a PR here to clarify: https://github.com/whatwg/webidl/pull/1353

When the transition starts, the `type` if specified causes the following pseudo-class to be applied to the `:root` element:
* `:view-transition-type(ident)`. This is applied to the `:root` element with the same `ident` as the `type` dictionary value given to the `startViewTransition` call.

Note that I'm explicitly not mentioning `@view-transition` and interaction between two different documents here, but the assumption is that the two approaches work well together

Note that this can be extended to scoped transitions as mentioned above, since the pseudo class can then be applied to the root of the scoped transition, not necessarily `:root`

**Comment by bramus** [comment]
> For example, a site might choose between the 2 for the same navigation (@bramus had an example for such a pattern).

The example is an SPA that – for whatever reason – can decide to do an MPA navigation after all. A typical scenario would be one where a new version of the SPA has been deployed, so that the user ends up on the latest version.

```js
document.addEventListener('a[href="/articles"]').addEventListener('click', async (e) => {
  // Do a regular navigation when a new app version has been detected.
  // Note: the type defined in @view-transition – if any – will be used.
  const serverAppVersion = await getAppVersion();
  if (localAppVersion != serverAppVersion) return true;

  // Fetch new data and build the markup
  const articles = await fetchArticles();
  const articlesFragment = buildArticlesFragment(articles);

  // Do a transition while also setting a type for the CSS the hook onto
  e.preventDefault();
  document.startViewTransition({
    type: 'back-to-articles',
    updateCallback: () => {
      updateContentWith(articlesFragment);
      window.history.pushState({}, '', '/articles'); // Or any other method to update the URL
    }
  });
});
```

With the type available in `document.startViewTransition` _(SPA)_ and in `@view-transition` _(MPA)_, the app can seamlessly switch between SPA/MPA type of navigations without the user even noticing.

**Comment by noamr** [comment]
I wanted to present the 3 ways I think we can go about this. Seems like the discussions are bouncing around between these 3, and we need to choose a strategy. To do this, I'm going to take a use case that's a little above simple, and represents an experience that resembles what early adopters have been doing, and show how this would be implemented using the 3 options.

The use case is as follows:
-  main pages: /home, /list, /cart, /product
- for any of these page transitions: slide from right
- but if using back navigation: slide from left
- (/list|/cart)<->/product: also animate product picture
 - in addition, internal sections in the page can be reordered using a VT animation.

The options on how to qualify a transition are as follows:
1. single-ident transition type
2. A dictionary of parameters
3. Purely navigation-oriented

All the options would have these routes defined:
```css
        @routes {
            --home: urlpattern(/((home/?)?)?*);
            --cart: url(/cart);
            --list: urlpattern(/list\/*);
            --product: urlpattern(/product/:id);
            --main-page: urlpattern(/(home|cart|list)?\/*);
        }
```

## Option 1: single-ident `view-transition-type`

```css
        @navigation --main-page to --main-page {
            view-transition-behavior: trigger;
            view-transition-type: slide-from-right; 
        }

        @navigation back from --main-page to --main-page {
            view-transition-type: slide-from-left; 
        }

        @navigation (--list, --product), (--cart, --product) {
            view-transition-type: slide-from-right-with-product-picture;
        }

        @navigation back (--list, --product), back (--cart, --product) {
            view-transition-type: slide-from-left-with-product-picture;
        }

        html:active-view-transition(slide-from-right),
        html:active-view-transition(slide-from-right-with-product-picture) {
            &::view-transition-group(root) {
                animation-name: slide-from-right;
            }
        }
        html:active-view-transition(slide-from-left),
        html:active-view-transition(slide-from-left-with-product-picture) {
            &::view-transition-group(root) {
                animation-name: slide-from-left;
            }
        }
        html:active-view-transition(slide-from-left-with-product-picture),
        html:active-view-transition(slide-from-right-with-product-picture) {
            #product-picture {
                view-transition-name: product-pic;
            }
        }

        html:active-view-transition(reorder) {
            #section1 { view-transition-name: section1; } 
            #section2 { view-transition-name: section2 } 
            #section3 { view-transition-name: section3; } 
        }

```

```js
        function navigate(newURL, isBack) {
            document.startViewTransition({
                updateCallback: () => do_navigate(newURL, isBack),
                viewTransitionType: ViewTransition.getTypeFromNavigation({
                    oldURL: location.href,
                    newURL,
                    direction: isBack ? "back" : "forward"
                });
            })
        }

        function reorder() {
            document.startViewTransition({
                updateCallback: () => do_reorder(),
                viewTransitionType: "reorder"
            });
        }
```

This feels simple to implement, however it requires a lot of permutations to create idents that cover all the cases.

## Option 2: parameter dictionary

```css
        @navigation --main-page to --main-page {
            view-transition-behavior: trigger;
            --main-page-slide: left; 
        }

        @navigation back from --main-page to --main-page {
            --main-page-slide: right;
        }

        @navigation (cart, product), (list, product) {
            --list-to-product: yes;
        }

        html:active-view-transition(--main-page-slide: left)::view-transition-group(root) {
            animation-name: slide-from-left;
        }
        html:active-view-transition(--main-page-slide: right)::view-transition-group(root) {
            animation-name: slide-from-left;
        }

        htnk:active-view-transition(--list-to-product) {
            #product-picture { 
                view-transition-name: product-pic;
            }
        }

        html:active-view-transition(reorder) {
            #item1 { view-transition-name: item1; } 
            #item2 { view-transition-name: item2; } 
            #item3 { view-transition-name: item3; } 
        }

```

```js
        function navigate(newURL, isBack) {
            document.startViewTransition({
                updateCallback: () => do_navigate(newURL, isBack),
                viewTransitionParams: ViewTransition.getParamsFromNavigation({
                    oldURL: location.href,
                    newURL,
                    direction: isBack ? "back" : "forward"
                });
            })
        }

        function reorder() {
            document.startViewTransition({
                updateCallback: () => do_reorder(),
                viewTransitionType: "reorder"
            });
        }
```

This feels more compact, however adds a level of indirection that might feel verbose for simple cases.
## Option 3: navigation oriented


```css
    @navigation same-origin {
        view-transition-behavior: trigger;
    }

    html {
        :active-view-transition(from --main-page to --main-page) {
            &::view-transition-group(root) {
                animation-name: slide-from-right;
            }
        }
        :active-view-transition(back from --main-page to --main-page) {
            &::view-transition-group(root) {
                animation-name: slide-from-left;
            }
        }
        :is(active-view-transition(--product, --list), active-view-transition(--product, cart)) {
            #product-picture {
                view-transition-name: product-picture;
            }
        }
    }
```

```js
        function navigate(newURL, isBack) {
            document.startViewTransition({
                updateCallback: () => do_navigate(newURL, isBack),
                navigation: {
                    oldURL: location.href,
                    newURL,
                    direction: isBack ? "back" : "forward"
                }
            })
        }

        function reorder() {
            document.documentElement.classList.toggle("reordering", true);
            document.startViewTransition({
                updateCallback(): () => {
                    document.documentElement.classList.toggle("reordering", false);
                }
            });
        }
```

This seems much more compact, however it means that transition types don't work for element-scoped transitions, and also that for transitions that are not URL-based (like reordering in this case) would need to use the "old" mechanism of toggling classes on the root element.

**Comment by noamr** [comment]
... note that the above is not a concrete set of proposals, but rather a choice of direction for classifying transitions:
- by single ident
- by dictionary of parameters
- navigation-based

**Comment by bramus** [comment]
_(This reply quickly turned out to be much longer than I expected it to be. It touches a lot of things at once, as they are all interconnected. Please take your time to read it thoroughly as I think it has potential to form an answer to some of the open VT2 questions.)_

I’m also no longer convinced that a single ident that names the transition would cut it. This would require authors to name each and every possible transition between two pages, in each possible direction. That would be a lot of work and a lot of idents.

I see 3 parameters that determine how a page-like transition should animate:

- The _from_ page
- The _to_ page
- The _direction_

Combining these 3, you gain a lot of flexibility:

- Going _from_ `video-overview` _to_ `video-detail` = Visually slide everything towards the ← side
- Going _from_ `video-detail` _to_ `video-overview` = Visually sllde everything towards the → side

The reason for this third _direction_, is to cater for transitions between to pages of the same type. Think of a paginated list where you are at page 5. Going to page 4 or to 6 is going to the same type page, but in a different _direction_.

- Going _from_ `video-archive` page 5 _to_ `video-archive` page 6 = A `forward` _direction_  = Visually slide everything towards the ← side
- Going _from_ `video-archive` page 5 _to_ `video-archive` page 4 = A `backward` _direction_  = Visually slide everything towards the → side

Note: when moving between two pages of a different type, you don’t really need the direction as you can achieve the reversed direction by flipping _from_ and _to_

---

Instead of setting these three parameters as a bag of parameters – where an author can choose how to name them - I think we should make it structured and give them proper names. The reason for this, is to play nice with the almighty browser back button.

Say you have this:

```js
document.startViewTransition({
  updateCallback: () => {
    updateTheDOM();
    updateTheURL();
  },
  to: `video-detail`,
  from: `video-overview`,
});
```

When the user presses the browser’s back button, it’s now easy very to achieve the opposite transition. Because these arguments are named, the UA can automatically swap the `to` and `from` arguments their values.

That way, pressing the browser’s back button after the snippet from just above, is essentially the same as invoking this:

```js
// Note: this is the code that would get run when pressing the browser’s back button. The UA automatically re-runs the original View Transition with the to and from arguments swapped.
document.startViewTransition({
  updateCallback: () => {
    updateTheDOM();
    updateTheURL();
  },
  to: `video-overview`, // 👈 Swapped value!
  from: `video-detail`, // 👈 Swapped value!
});
```

For transitions where `to` and `from` were the same, it’s a matter of flipping `forward` to `backward` and vice versa when pressing back. Again, it would be the UA that takes care of this when pressing the browser’s back button after having done such a transition.

```js
document.startViewTransition({
  updateCallback: () => {
    updateTheDOM();
    updateTheURL();
  },
  to: `video-archive`,
  from: `video-archive`,
  direction: 'backward', // 👈 When going from page 5 to page 4, you are going back in the pagination.
});
```

If you press the browser’s back button after the snippet above, `backward` would become `forward`.

Upon pressing the browser’s reload button, the direction would be overridden as `reload`. That way, authors can also take that into account to set up their animations.

---

So, what about cross-document Navigation you might wonder? Reusing the `@routes` that was already suggested here it would be a matter of naming the routes.

```css
@routes {
  video-overview: urlpattern('/videos');
  video-detail: urlpattern('/videos/watch/:slug');
  video-archive: urlpattern('/videos/archive(/:page_id)?');
}
```

Nothing else is needed besides this block (🎉). These route names would then automatically be used as the `from` and `to` arguments when doing a cross-document navigation. The `from` value is derived from the current page URL, and the `to` value from the URL that you end up at. When pressing the browser’s back button, the argument values get swapped.

<details>
<summary>Sidetracking here: this does not add a way to set the direction to be used.</summary>

This should be possible with a little bit of JavaScript but ideally it should also be possible from within CSS. I am thinking of a way to configure this direction in the `@view-transitions` at-rule _([the one that configures VTs](https://github.com/w3c/csswg-drafts/issues/8048#issuecomment-1640574446))_.

This would require some sort of pseudo that indicates “hey, this was the element that initiated the cross-document navigation” to hook onto. I’m using `:last-active` here, but the name is definitely up for bikeshedding:

```css
.pagination a.next:last-active {
  @view-transitions {
    direction: forward;
  }
}

.pagination a.previous:last-active {
  @view-transitions {
    direction: backward;
  }
}
```

When clicking a link with the class `.previous` for example, the upcoming cross-document transition’s `direction` would be set to `backward`.

This pseudo would also offer an answer to https://github.com/w3c/csswg-drafts/issues/8209#issuecomment-1693548146, so that you could use it to set some `view-transition-name` on the fly. Two birds, one stone.
</details>

---

With same-document navigations being taken care of by requiring authors to set `to`/`from`/`direction` params when calling `document.startViewTransition`, and cross-document-navigation setting these automatically, responding to such a type of transition happens in the same manner for both: look at the values, irrelevant of what navigation it was.

In CSS this could be an pseudo _(as already suggested in this thread)_ or an at-rule _(as also suggested in this thread)_. Personally I’m leaning towards an at-rule.

_(Note that this at-rule to respond to a VT `@view-transition` – not to be confused with `@view-transitions` which configures VTs.)_

```css
@view-transition (from: video-overview to: video-detail) or (from: video-archive to: video-archive direction: forward) {
  ::view-transition-old(content) {
     animation-name: slide-out-to-left;
  }
  ::view-transition-new(content) {
     animation-name: slide-in-from-right;
  }
}

@view-transition (from: video-detail to: video-overview) or (from: video-archive to: video-archive direction: backward) {
  ::view-transition-old(content) {
     animation-name: slide-out-to-right;
  }
  ::view-transition-new(content) {
     animation-name: slide-in-from-left;
  }
}
```

<details>
<summary>Sidetracking here: maybe there would need to be a way to set some things up on the from and to page?</summary>

Maybe like this?

```css
@view-transition (from: video-overview to: video-detail) {
  @view-transition :from {
    /* Set up some view-transition-names on the from page here, if needed */
  }

  @view-transition :to {
    /* Set up some view-transition-names on the to page here, if needed */
  }
}
```

Or like this?

```css
@route video-overview {
  /* CSS specifically targeting the video-overview route */
}

@route video-detail {
  /* CSS specifically targeting the video-detail route */
}
```

Anyway, this can be tackled later, as authors can add classes/ids/attributes to their pages and respond to that

```css
html[page-type="video-overview"] {
  /* CSS specifically targeting the video-overview route */
}
html[page-type="video-detail"] {
  /* CSS specifically targeting the video-detail route */
}
```
</details>

---

I think this proposal ticks a few boxes:

- Don’t break what has already shipped
- Same animation CSS for MPA / SPA
- Opt-in/opt-out via CSS
- Ability to respond to directionality of links _(e.g. following a link from articles list page 2 to page 3 vs from page 2 to page 1; or when clicking the back button of the browser)_
  - Note that a navigation can go forward but the directionality of the transition should go backward. _(e.g. when following a pagination link from page 2 to page 1)_
- Ability to take originator of the VT into account _(i.e. respond to which link was clicked in the list)_

This forms an answer to:

- https://github.com/w3c/csswg-drafts/issues/8685
- https://github.com/w3c/csswg-drafts/issues/8784
- https://github.com/w3c/csswg-drafts/issues/8683
- https://github.com/w3c/csswg-drafts/issues/8925
- This issue

---

What this proposal does not cover are transitions that are not between two pages, i.e. in-page transitions. Think of a page that reorders a set of elements: it can use a View Transition without a navigation happening. For that case I think it’s perfectly fine to ask of authors to use existing methods such as adding a `className` on the transition root if they want to express some type of directionality. After all, they are already relying on JavaScript to do the reordering.

```js
document.documentElement.classList.add('reordering');

const transition = document.startViewTransition(() =>
  filterAndReorderElements(filter);
);

try {
  await transition.finished;
} finally {
  document.documentElement.classList.remove('reordering');
}
```

```css
html.reordering {
  …
}
```

Alternatively authors can set from to have a value that is not covered by any route, simply to have a hook to hook onto from within their CSS. Admittedly, this is pretty hacky …

```js
document.startViewTransition({
  from: 'reordering',
  updateCallBack: () => { … },
});
```

```css
@view-transition (from: reordering) {
  /* Weird, but it works … */
}
```

---

Congrats on making it this far. Thanks for reading 😊
