### ISSUE TITLE
[css-pseudo-4] Add a pseudo-element to style all highlight pseudo-elements

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#9091]
A proposal I made during the discussion in https://github.com/w3c/csswg-drafts/issues/6641#issuecomment-1642386369 is that, given the model proposed in #6641 for how custom properties work on highlight pseudo-elements, is that we should have a pseudo-element that matches *all* of the highlight pseudo elements.  (This means both the [Higlight Pseudos](https://www.w3.org/TR/css-pseudo-4/#highlight-pseudos) and [Custom Highlight Pseudos](https://www.w3.org/TR/css-highlight-api-1/#styling-highlights).)

This is a slightly new concept because it means that when an implementation resolves the `::selection` pseudo-element (for example), it needs to look at selectors involving `::selection` and also the selectiors involving this new pseudo-element.  Or, to think about it another way, this is sort of like a pseudo-element alias.  That said, I think that still seems like a relatively straightforward feature.

This feature would make it easier for authors who are changing custom properties in a subtree to make sure that those custom properties will work correctly across all the highlight pseudo-elements, without needing to know exactly which highlight pseudo-elements will use the custom properties that they're modifying.

**Comment by dbaron** [comment]
Two possible names for such a pseudo-element might be `::all-highlights` or `::any-highlight`, though I'm sure there are other options.

**Comment by fantasai** [comment]
Naming-wise it should be `::any-highlight` rather than `::all-highlights`, for consistency with `::any-link`.

However, I'm not convinced this is a good idea. It makes sense for custom properties, but as far as non-custom properties go, it's highly unlikely that the author should be styling all the UA-defined highlights (including ones we haven't defined yet) in the same way.

Having `::highlight()` match all custom highlights would make sense, though.

**Comment by LeaVerou** [comment]
As @tabatkins mentioned in https://github.com/w3c/csswg-drafts/issues/6641#issuecomment-1006172908 this is a much broader issue than highlights. The real author need here is to be able to define document-wide custom property values that are available everywhere.

I think instead of introducing more ad-hoc pseudo-elements, we should introduce a pseudo-element or `@rule` that allows this. Or adopt @tabatkins’s proposal and special case the root, paving the cowpaths.

**Comment by tomayac** [comment]
> Having `::highlight()` match all custom highlights would make sense, though.

I just naively and without knowing this wouldn't work tried the above syntax. Then, less confidently, I tried `::highlight(*)`, then I came here. 

My use case is to avoid duplication:

```css
/* Want: */

::highlight() {
  text-decoration-line: underline;
  text-decoration-style: wavy;
}

::highlight(spelling) {  
  text-decoration-color: yellow;
}

…

::highlight(punctuation) {
  text-decoration-color: red;
}
```

Instead, I have to repeat myself:

```css
/* Reality: */

::highlight(spelling) {  
  text-decoration-color: yellow;
  text-decoration-line: underline;
  text-decoration-style: wavy;
}

…

::highlight(punctuation) {
  text-decoration-color: red;
  text-decoration-line: underline;
  text-decoration-style: wavy;
}
```
