### ISSUE TITLE
[css-nesting] Nesting @media inside ::after not working

### ISSUE THREAD

**Issue by mrshoekstra** [w3c/csswg-drafts#9153]
I'm not sure if this is the implementation of Google Chrome or [part of the spec](https://www.w3.org/TR/css-nesting-1/#nest-selector) (bug or feature).
I would like this to work, it seems this should work, but it doesn't:

Preferred (not working)
```css
body {

	@media print {

	}

	@media screen {

		&::after {
			background: red;
			content: '';
			inset: 0;
			position: absolute;
			
			@media (width < 50rem) {
				background: blue;
			}
		}
	}
}
```

Working version with duplicate `@media screen` and `&::after {`
```css
body {

	@media print {

	}

	@media screen {

		&::after {
			background: red;
			content: '';
			inset: 0;
			position: absolute;
		}
	}
	
	@media screen and (width < 50rem) {

		&::after {
			background: blue;
		}
	}
}
```
https://www.w3.org/TR/css-nesting-1/

**Comment by johannesodland** [comment]
I think this is according to the spec. 

When properties are used directly in nested at-rules, they act as if they were nested in a `& { ... }` block. ([#conditionals](https://www.w3.org/TR/css-nesting-1/#conditionals)) However, the `&` nesting selector cannot represent pseudo-elements. ([#nest-selector](https://www.w3.org/TR/css-nesting-1/#nest-selector))

As a result, the rule nested in the media query will be invalid: 

```css 
::before {
  background: red;
  @media (width < 50rem) {
    background: blue;
  }
}

/* equivalent to
  ::before {
    background: red;
    @media (width < 50rem) {
      & {
        background: blue;
      }
    }
  }
*/
```


I agree this can be confusing to authors, but as [Issue 2](https://www.w3.org/TR/css-nesting-1/#issue-62c479a8) the spec say: 

> We’d like to relax this restriction, but need to do so simultaneously for both [:is()](https://www.w3.org/TR/selectors-4/#matches-pseudo) and [&](https://www.w3.org/TR/css-nesting-1/#selectordef-), since they’re intentionally built on the same underlying mechanisms. ([Issue 7433](https://github.com/w3c/csswg-drafts/issues/7433))
