### ISSUE TITLE
[css-anchor-position-1] Should custom property declarations be valid in `@try`?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9198]
I initially asked this in #9150.

@xiaochengh warned that accepting them would break anchor positioning entirely:

```css
.target {
  position: var(--x);
  --x: absolute;
  position-fallback: --fallbacks;
}

@position-fallback --fallbacks {
  @try { --x: static; }
}
```

But I wonder if it would work if custom properties are accepted only if there is one or more declarations of the other accepted properties?

```css

@position-fallback --fallbacks {
  @try { --x: static; } /* invalid, ignored */
  @try { --x: static; width: 100px } /* valid */
}
```

I do not have a strong opinion and I am only interested in disallowing custom properties, because `@try` is the only rule accepting property declarations that do not accept custom properties.
