### ISSUE TITLE
[css-view-transitions-1] Handling changes in aspect ratio for non-replaced elements

### ISSUE THREAD

**Issue by nonphoto** [w3c/csswg-drafts#9202]
[Smooth and simple transitions with the View Transitions API](https://developer.chrome.com/docs/web-platform/view-transitions/#handling-changes-in-aspect-ratio) has a section for [Handling changes in aspect ratio](https://developer.chrome.com/docs/web-platform/view-transitions/#handling-changes-in-aspect-ratio). This approach relies on setting [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) on a transitioning image, a property that only works on replaced elements. No such behavior is possible for non-replaced elements.

Consider the below example (using [Solid](https://www.solidjs.com) for convenience). The only way to visually transition the size of `::view-transition-group(box)` is to set `width` and `height` to `100%`, thus causing a stretch and squash effect while the transition is running.

https://github.com/w3c/csswg-drafts/assets/3441123/7c20ceff-0ff1-47f4-8bf5-83b79e3f04de

index.jsx
```jsx
export default function Home() {
  const [toggleValue, setToggleValue] = createSignal(false);

  function toggle() {
    document
      .startViewTransition(() => {
        setToggleValue((value) => !value);
      })
  }

  return (
    <main onClick={toggle}>
      <Show
        when={toggleValue()}
        fallback={
          <div class="left">
            <div class="inner">#1</div>
          </div>
        }
      >
        <div class="right">
          <div class="inner">#2</div>
        </div>
      </Show>
    </main>
  );
}
```

index.css
```css
::view-transition {
  pointer-events: none;
}

:root {
  view-transition-name: none;
}

main {
  padding: 3rem;
  display: flex;
  perspective: 800px;
  font-size: 2rem;
}

.left,
.right {
  view-transition-name: box;
}

::view-transition-group(box) {
  animation-duration: 1s;
  animation-timing-function: cubic-bezier(0.22, 1, 0.36, 1);
}

::view-transition-old(box),
::view-transition-new(box) {
  overflow: clip;
  width: 100%;
  height: 100%;
}

.left {
  width: 10rem;
  height: 20rem;
  transform: rotateY(30deg);
  background-color: lightskyblue;
}

.right {
  width: 20rem;
  height: 10rem;
  margin-left: auto;
  transform: rotateY(-30deg);
  background-color: lightpink;
}
```

In some cases, it is possible to give a different transition name to the inner content: 

```css
.inner {
  view-transition-name: inner;
}
```

However—because the view transition pulls the element out into a new layer—during the transition the parent and inner elements are actually sibling pseudo elements. This causes the parent and inner elements to become visually "unsynchronized" for examples with rotation and skew transforms like the above.
