### ISSUE TITLE
[css-anchor-position-1] Ability of logical / physical combo positioning

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#9268]
The feature comparison table (see https://github.com/w3c/csswg-drafts/issues/9117) currently says:

Feature | Inset-based (current spec) | Grid-based
-- | -- | --
Logical / physical combo positioning | ❌? | ✅

I assume this is the about `top / start` use case from Apple's earlier [presentation](https://www.icloud.com/keynote/0f5UxcimbeDm24dK6S_Of2YOw#Anchor_positioning_presentation_to_CSSWG):

<img width="1438" alt="Screenshot 2023-08-29 at 4 40 39 PM" src="https://github.com/w3c/csswg-drafts/assets/19384155/bd54ca00-0b75-44f7-95f9-654dfae1f072">

While the current spec has some difficulties to achieve the same, this should no longer be an issue with the `inset-area` that we newly agreed to add (https://github.com/w3c/csswg-drafts/issues/9145#issuecomment-1690207503), and the syntax should be almost identical.

So I think this is no longer an issue, and we can modify that row into double green ticks, with a reference to https://github.com/w3c/csswg-drafts/issues/9145?

@fantasai @jensimmons

---

Note: without `inset-area`, the current spec needs to know the writing mode & direction of the current element and its containing block in advance, so that it knows which inset properties to set.

For example, assuming they have horizontal writing mode and same direction, it is:
```css
.anchor-positioned-element {
  top: anchor(bottom);
  inset-inline-end: anchor(start);
}
```

But if they have different directions:
```css
.anchor-positioned-element {
  top: anchor(bottom);
  inset-inline-start: anchor(start);
}
```

Things can get even more complicated if the writing modes are different.

With `inset-area`, it simply becomes:
```css
.anchor-positioned-element {
  inset-area: top / start;
}
```
