### ISSUE TITLE
[css-view-transitions-2] Syntax & final names for choosing types in navigation-based view-transitions

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#9461]
Now that we have consensus (% bikeshedding) about the opt-in and transition [types](https://drafts.csswg.org/css-view-transitions-2/#ViewTransition-start-with-options), it's time to figure out how they work together.

The initial use-case is to simply be able to set a transition type for cross-document navigations, and also override it based on conditionals (@media, @supports). Once we have semantics to classify a navigation, this would become even more important.

So for example:

```css
@view-transition {
  trigger: navigation;
}

@media (orientation: landscape) {
  trigger: navigation;
  types: slide-from-top reverse; 
}
```

The current name for this is `types`, but there are several suggestions in https://github.com/w3c/csswg-drafts/issues/8960#issuecomment-1722259058, e.g.:
* `active-types`
* `type-list`
* `active-set`
* `scene`
