### ISSUE TITLE
Idea: Properties with Object Values

### ISSUE THREAD

**Issue by AdamSobieski** [w3c/csswg-drafts#9502]
## Introduction

What if the value of a property could be an object?

## Syntax

Let us consider the following syntax with nested curly brackets:

```css
div { prop: { x: 123; y: 456 }; }
```

which intends to communicate that the element:

```xml
<div id="el" class="cls" />
```

would have a style property, `prop`, with a value that would be an object with properties. The expression `prop.x` would be equal to `123` and `prop.y` would be equal to `456`.

## Object Model

With respect to adding this functionality to CSS, we might want to consider the [`CSSStyleDeclaration`](https://drafts.csswg.org/cssom/#cssstyledeclaration) interface which provides the [`getPropertyValue()`](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-getpropertyvalue) method which is specified as returning a [`CSSOMString`](https://webidl.spec.whatwg.org/#idl-DOMString) value rather than an [`object`](https://webidl.spec.whatwg.org/#idl-object) value.

If `getPropertyValue()` returned an `object` value, then something like the following could work:

```js
var element = document.getElementById('el');
var prop = element.style.getPropertyValue('prop');

console.log(prop.x);
console.log(prop.y);
```

## Conclusion

I hope that these ideas are of some interest to the group. What do you think of the capability for properties to have complex objects for their values? Do any other syntax possibilities come to mind with which to express these ideas?

**Comment by romainmenke** [comment]
Hi @AdamSobieski,

It helps if you can provide very concrete examples.
Something that can't be done today or is very hard to do and that would be improved by your proposal.

**Comment by AdamSobieski** [comment]
@romainmenke, thank you. My motivating use case involves a new markup language and corresponding object model that I am working on for interacting with multiple finite-state automata. It is inspired by [SCXML](https://www.w3.org/TR/scxml/) and will support both styling and scripting.

To some HTML-related scenarios, one example of where it might be (or might once have been) convenient to have this expressiveness is the box model:

```css
div {
  margin: { top: 10px; right: 10px; bottom: 10px; left: 10px; };
  border: { top: 1px solid blue; right: 1px solid blue; bottom: 1px solid blue; left: 1px solid blue; };
  padding: { top: 10px; right: 10px; bottom: 10px; left: 10px; };
}
```

Another example involves fonts:

```css
span {
  font: { family: sans serif; size: 12pt; style: normal; weight: bold; };
}
```

Strings and objects are both useful and versatile. I will brainstorm on some more concrete examples.

**Comment by Loirooriol** [comment]
Things like `margin: { top: 10px; right: 10px; bottom: 10px; left: 10px; }` have been proposed in the past and seem useful.

But I don't see the need to keep it as a complex value associated with the shorthand. I would just desugar at parse-time, expanding to `margin-top: top: 10px; margin-right: 10px; margin-bottom: 10px; margin-left: 10px;`

**Comment by tabatkins** [comment]
Right, using {}-blocks just as an alternate syntax for shorthand properties potentially makes sense, tho we'd almost certainly need more justification for it. It's simply not much of a burden to repeat the prefix of the property name a few times. If CSS nested its shorthands more deeply there would be a larger argument, but we rarely go past a single level, and I don't think we ever do more than two.

For expressing JS data directly in CSS, that's much more fraught. JS syntax isn't fully compatible with CSS in several corners. You can use a custom prop for this, if you manually parse/serialize thru JSON.

**Comment by AdamSobieski** [comment]
Brainstorming, there could be a way to use `{}`-blocks for both an alternative syntax for shorthand properties and for providing expressiveness for JS-based objects for property values.

In these regards, three options are presented. Each involves a use of the `-` symbol.

One option would involve appending a `-` to an involved property name:
```css
div {
  animation-: {
    delay: 250ms;
    direction: normal;
    duration: 1s;
    fill-mode: none;
    iteration-count: 1;
    name: kf;
    play-state: paused;
    timeline: auto;
    timing-function: ease-in-out;
  };
}
```
Another option would involve prepending a `-` to involved subproperty names:
```css
div {
  animation: {
    -delay: 250ms;
    -direction: normal;
    -duration: 1s;
    -fill-mode: none;
    -iteration-count: 1;
    -name: kf;
    -play-state: paused;
    -timeline: auto;
    -timing-function: ease-in-out;
  };
}
```
A third option would involve both uses of the `-` symbol:
```css
div {
  animation-: {
    -delay: 250ms;
    -direction: normal;
    -duration: 1s;
    -fill-mode: none;
    -iteration-count: 1;
    -name: kf;
    -play-state: paused;
    -timeline: auto;
    -timing-function: ease-in-out;
  };
}
```
If this third option, we might see cases where a `-` symbol would both prepended and appended to a subproperty name, e.g., `-blend-`:
```css
div {
  animation-: {
    -delay: 250ms;
    -direction: normal;
    -duration: 1s;
    -fill-mode: none;
    -iteration-count: 1;
    -name: kf;
    -play-state: paused;
    -timeline: auto;
    -timing-function: ease-in-out;
    -blend- { -start: normal; -end: normal; };
  };
}
```

In this approach, the absence of any `-` symbol would be for expressing JS-like objects for property values.

The gist is the three possibilities, above, is that, by using `-`, in some manner, to signal the utilization of the alternate CSS syntax for shorthand properties, CSS could additionally support the expressiveness for having JS-based objects as property values.
