### ISSUE TITLE
[css-properties-values-api-1] Figure out what to do with font-relative lengths

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#9517]
Per <https://github.com/w3c/csswg-drafts/issues/8169#issuecomment-1632890687>, there might be a remaining circularity issue if font-relative lengths are used in custom properties with `<length>` type.

**Comment by Loirooriol** [comment]
The problem isn't just for `<length>` type. https://github.com/w3c/css-houdini-drafts/issues/1080

**Comment by fantasai** [comment]
Maybe you need two different `<length>` types: those that can be used in unit-influencing properties like `font-size` and `line-height`, and those that can't.

**Comment by lilles** [comment]
As @Loirooriol points out, this is not just limited to `<length>` values.

Assume `--number` is a registered custom property with the `<number>` syntax:

```css
p {
  --number: calc(10 + 2 * sign(1em - 20px));
  font-size: calc(var(--number) * 2px);
}
```
