### ISSUE TITLE
An extra keyword to disable inheritance?

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#9531]
The blog https://nerdy.dev/ has a transparent retractable sticky nav bar with a few buttons and links on the side. Since the bar is transparent, the website uses the following styles to allow the mouse cursor to go through the “empty” parts of the bar:

```css
.Nav {
  pointer-events: none;
}

.Nav > * {
  pointer-events: auto;
}
```

This works, but I think the code would be more readable and robust if we didn’t have to set and unset `none` in two steps. Imagine if there existed an optional keyword that disabled inheritance for a declaration.

```css
.Nav {
  pointer-events: none no-inherit;
}
```

Does something like this exist?
