### ISSUE TITLE
[css-animations-2] Declarative syntax for GroupEffects

### ISSUE THREAD

**Issue by ydaniv** [w3c/csswg-drafts#9554]
This is a proposal for a declarative syntax of [Web Animations 2's GroupEffects](https://www.w3.org/TR/web-animations-2/#group-effect). The behavior of these suggested properties is already defined in Web Animations 2, and here I only suggest how to align it with CSS Animations.
This follows a proposal in a [comment on a previous issue](https://github.com/w3c/csswg-drafts/issues/8534#issuecomment-1752044866).

## Description:

Add a new property, name to be bike-shedded, like `group-effect`, to declare a group effect that can be later referenced in another new property, like `animation-group`, that takes a list of idents to add an animation to a group, and optionally an integer for the position in the group.

The `group-effect` can be just specified on a parent, which all `animation-group`'s just seek upwards on the tree.
The `group-effect` property can be a shorthand of all properties: `name`, `parent`, and rest of timing properties.
`name` can be a dashed/custom-ident.

An example usage could be something along the lines of:

```css
@keyframes slide { ... }
@keyframes blink { ... }

#container {
  group-effect-TBB: --gorup-1 sequence 2.5s 0.5s linear 2;
}

#target {
  animation:
    slide 1s ease-out both,
    blink 1.5s ease-in-out infinite;
  animation-group: --group-1 1, --group-1 2;
}
```

Once the common parent with the `group-effect` is matched, that animation becomes active and starts its progress, and then the same goes for its children accordingly.

`group-effect` will be a shorthand of the following longhands:
* `group-effect-name`: `<dashed-ident>` - name of the group
* `group-effect-parent`: `<dashed-ident>` - optional name of the parent group
* Rest of [Effect Timing Options](https://www.w3.org/TR/web-animations-1/#dictdef-effecttiming)(+)
* A new longhand `group-effect-align`(++), explained below 👇 

### New property `group-effect-align`

This property will control synchronization of child effects inside the group.  The name of course is TBB.
It behaves same as [described here](https://www.w3.org/TR/web-animations-2/#sequence-effects), with the addition of splitting the parallel behavior of "GroupEffect" to `start` and `end`, which aligns the child effects to either start or end together respectively.
It has the following possible values:
* `start`: align all effects to start simultaneously.
* `end`: align all effects to end simultaneously.
* `sequence`: align each subsequent effect's start to the end of its preceding effect.
* `sequence-reverse`: same as `sequence` but with descending order, so each effect's start is aligned to its succeeding effect.

(+) Need to discuss adding `iterationStart` and `endDelay` to the syntax.
(++) Aligning `group-effect-align` with current spec of `GroupEffect` and `SequenceEffect` in Web Animations 2 will be discussed in a separate.

-------------

### `animation-group`

```
animation-group-name: <dashed-ident>
animation-group-ordinal: <number>

animation-group: [<animation-group-name> <animation-group-ordinal>?]#
```

### `group-effect`

```
group-effect-name: <dashed-ident>
group-effect-parent: <dashed-ident>

group-effect-duration: ... // all effect timing options are 

group-effect-align: start | end | sequence | sequence-reverse

group-effect: [ <group-effect-name> [ / <group-effect-parent>]? [<group-effect-align> || ...]? ]# // ... for rest of timing properties
```

I probably did some syntax mistakes, but I think the gist of it is clear.

**Comment by birtles** [comment]
Looks good! Thanks for doing this! There are two areas I'm particularly interested in.

**1. `animation-group-ordinal`**

I'm curious to know more about how you see `animation-group-ordinal` working and if there are steps we should take to make it more ergonomic.

I think the [`order`](https://developer.mozilla.org/docs/Web/CSS/order) property is a useful precedent for this sort of property. However it's a bit different because for layout _normally_ the source order and the layout order match so you only need to specify `order` occasionally.

It's probably less common for source order and _temporal_ order to match, however? _Sometimes_ they will match (e.g. when you're animating a list in or out), and sometimes the order of animations in the `animation-name` property could provide the correct group ordering, but when you're animating the elements of a screen layout, for example, neither the source order not the `animation-name` order is likely to provide a suitable group ordering and the `animation-group-ordinal` property will be needed.

I guess we need some example content to play with to see what makes most sense? We might discover that a relative ordering could be helpful, e.g. `before <animation-name>`?

**2. Bottom-up vs top-down**

Forgive me if you've covered this elsewhere, but I'm curious if there was a particular reason for taking a bottom-up approach vs a top-down one such as defining the group children via an `@` rule instead?

I think what you have is probably the more CSS-y way to go, but from an authoring point of view, I imagine it might be simpler to define all the children at once like you would do in JS, e.g.

```css
.curtain {
  animation: slide-open 1s;
  animation-ref: --curtain;
}

.character {
  animation: fade-in 1s --character;
}

@animation-group intro {
  /* Group delay... build the suspense */
  animation-delay: 1s;
  /* Specify child animations or groups */
  animation-group-items: --curtain, --character;
}
```

Just an idea for comparison. Apart from being easier to reason about from an authoring point of view, one advantage is it provides an unambiguous order for children. I'm sure there are plenty of disadvantages, however.

**Comment by birtles** [comment]
> In cases 2 and 3, however, you could have a single effect (or a single group effect) and a large number of elements with that effect. So naming the effect doesn't provide much benefit here, but rather opting-in to a group is more straight forward.

I think this (along with the view/scroll-timeline precedent) is a really good reason for taking the bottom-up approach. It does feel more CSS-y too.

Your point about activation is really important too.

Supposing we can add a top-down approach later, I think that would be fine to consider a the needs arises and pursue the bottom-up approach initially.

**Comment by ydaniv** [comment]
> Supposing we can add a top-down approach later, I think that would be fine to consider a the needs arises and pursue the bottom-up approach initially.

Yep, that's one option, although case 1 is something I really, and quite commonly, need today for stuff I'm working on. Basically it's something any animation library could benefit from.
Perhaps it's something that can more easily be done first via WAAPI, and later we can solve the declarative form.

**Comment by birtles** [comment]
@ydaniv Thanks for working on this. That looks promising. I'm having a little trouble remembering how all the parts fit together so perhaps we could work it out in the context of a specific application of case (4).

For example, suppose we have:

```html
<dialog>
  <div class="popup">
    <h1>Popup heading</h1>
    <ul>
      <li>List item 1
      <li>List item 2
      <li>List item 3
    </ul>
  </div>
</dialog>
```

Then suppose we want to implement the following animation when the `dialog:modal` selector matches:

1. Does an opacity fade on the `dialog::backdrop` pseudo element
2. Simultaneously instantly animates `.popup`'s `translate` property to `-100%` or somesuch so that it is initially offscreen (i.e. vertically off the top of the screen)
3. Slightly before the opacity fade ends, starts to animate `.popup`'s `translate` property to `none`.
4. After `.popup` arrives at its resting place, does an opacity fade on `h1` and each of the `li` elements in turn, i.e. "Popup heading", then "List item 1", then "List item 2" etc.. The fade animations should slightly overlap and ideally the amount of overlap should steadily increase so that the start of "List item 2" and "List item 3" is nearly the same.

I wonder how we could express that so that it retains the benefits of group effects like being able to pause/seek the whole animation and adjust the duration globally?

**Comment by ydaniv** [comment]
Great, that's good test, although in your example there's no case of multiple animations on the same element. So it's a case 4 but not really requiring the `@groupeffect` part.

There's a fade on the `::backdrop`, a slide on the `.popup`, and the fade on different parts of the contents.
If I try to translate this example into code it should like as below:

```css
@keyframes slide {
  from {
    translate: -100%;
  }
}

@keyframes fade {
  from {
    opacity: 0;
  }
}


dialog {
  group-effect:
    --showModal 2s sequence,
    --showContent / --showModal 2 1s start calc(200ms * log(effect-index() + 1));
  
  &::backdrop {
    animation: fade 0.5s ease-out;
    animation-group: --showModal 0;
  }
  
  .popup {
    animation: slide 0.6s -0.1s ease-out;
    animation-group: --showModal 1;
  }
  
  h1 {
    animation: fade 0.2s;
    animation-group: --showContent 0;
  }

  li {
    animation: fade 0.2s;
    animation-group: --showContent calc(sibling-index() + 1);
  }
}
```

### Some highlights

This part:
```css
 group-effect:
    --showModal 2s sequence,
```

Groups the entire timeline.

While the second GroupEffect here:
```css
    --showContent / --showModal 2 1s start calc(200ms * log(effect-index() + 1));
```

Groups together the effects on the content. Specifically this part `/ showModal 2` stands for some syntax that should say that the parent group of `--showContent` is `--showModal` and its ordinal in that group is `2`.

Notice I also used negative `delay` to slightly overlap the face of the `::backdrop` and the slide of `.popup` as requeted, here:
```css
animation: slide 0.6s -0.1s ease-out;
```

I guess if we wanted to test case 4 with also multiple animations on a single element, let's assume the fade and slide effects are both on the `dialog` itself. Then it would look like the following:

```css
@groupeffect --showModal {
  fade {
    duration: 0.5s;
    easing: ease-out;
  }

  slide {
    duration: 0.6s;
    delay: -0.1s;
    easing: ease-in;
  }
}

dialog {
  group-effect:
    --showModal 2s sequence,
    --showContent / --showModal 2 1s start calc(200ms * log(effect-index() + 1));
 
  ... 
}
```

And with the assumption above that we define the effects defined inside `--showModal` get ordinals that start from `0`.
