### ISSUE TITLE
[css-properties-values-api] Allow scoped @property rules

### ISSUE THREAD

**Issue by Que-tin** [w3c/csswg-drafts#9580]
There currently is no way to define `@property`-Rules on a non global level. When people want to leverage the `syntax` especially in combination with `|` this will be handy e.g.:

```css
.card {
  @property --size {
    syntax: "default | big";
    inherits: false;
    initial-value: default;
  }
}

.button {
  @property --size {
    syntax: "small | default";
    inherits: false;
    initial-value: default;
  }
}
```

The current implementation would lead to all custom properties being globally scoped and therefore the need of unique names e.g:

```css
@property --card-size {
  syntax: "default | big";
  inherits: false;
  initial-value: default;
}

@property --button-size {
  syntax: "small | default";
  inherits: false;
  initial-value: default;
}
```

This can quickly get out of hand and become chaotic. This feature will become even more useful when Style Queries grow in adoption.
