### ISSUE TITLE
[css-color-adjust] Allow authors do define custom `color-scheme` values.

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#9660]
In #7561 we resolved on adding `light-dark()` so that authors can easily use a color based on whether the `light` or `dark` color scheme is being used. Authors are generally in favor of this addition but some of the feedback I got is asking **why is this limited to light and dark only**?

Reason for this, is that this is the current reality we live in: the possible values for `color-scheme` today are only `light` or `dark` (or `normal`). `<custom-ident>`s are allowed as values but these are ignored, as [per spec](https://drafts.csswg.org/css-color-adjust/#color-scheme-prop):

> `<custom-ident>` values are meaningless, and exist only for future compatibility, so that future added color schemes do not invalidate the `color-scheme` declaration in legacy user agents. User agents must not interpret any `<custom-ident>` values as having a meaning; any additional recognized color schemes must be explicitly added to this property’s grammar.

_(Hereby a thank you to the person who suggested to put that in; very future friendly!)_

Looking at #7561, `light-dark()` isn’t the end goal of that feature. The end goal is [something like `schemed-value()`](https://github.com/w3c/csswg-drafts/issues/7561#issuecomment-1644625985): allow authors to get a value based on a passed in `color-scheme` – any `color-scheme`.

To unblock that issue forward, a first step would be to allow authors to define custom `color-scheme` values. These defined values could then then be used in side `color-scheme` and the `prefers-color-scheme` Media Feature.

---

Classic use-cases are coding color schemes, or application theming such as Slack or VS Code offer:

![image](https://github.com/w3c/csswg-drafts/assets/213073/56ab5123-d6e7-4f8a-8a7e-0b9f211eb66b)

![image](https://github.com/w3c/csswg-drafts/assets/213073/5d8339c0-7683-4d63-8996-b1295e077dd7)

**Comment by lukewarlow** [comment]
![273219103-02c9b371-5427-4573-b214-0963be3a349b](https://github.com/w3c/csswg-drafts/assets/32498324/acfe48e5-a60a-4b33-af65-be9de8e4ffca)

GitHub is a good example where color schemes are tied to a light or dark base.

**Comment by lukewarlow** [comment]
> I think custom light and dark themes should be separate versions.

They would be distinct custom colour schemes but without tying them to either light or dark how does the browser decide how to style native UI using them?

**Comment by matthewp** [comment]
@lukewarlow I don't think themes are tied to base light / dark. When I think about this issue I always think about Kindle which has light, dark, sepia, and green themes. In particular the green theme doesn't seem to be either a "light" or "dark" base. Testing out their web app, they have a light theme for their UI chrome, but it would work equally well with dark UI chrome.

That's a scenario where I'd probably have configurable color schemes on the `body` and then on the `.book` or whatever, set the green theme.

**Comment by tabatkins** [comment]
Hm, we should be clearer on the exact use-case here. The only effect of color-scheme is to change the system color keywords; if you're changing all of the colors to your own chosen set of colors, you can just use your own color custom properties instead.

But it does seem like there are two reasonable arguments to make here:

1. While you *can* use your own colors, you then have to manually set all the existing system color usages to instead use your color variables. And you have to keep that up to date as we add more controls, or more system colors. Letting you set the system colors directly means you can skip a big block of selectors setting those colors.
2. The Web Preference API can potentially persist this.

Especially if #2 comes to pass, this does seem pretty useful.

Design-wise, hm, we'll need to make sure that it's compatible with us adding more system color keywords in the future. I propose we require you to specify a "base" color-scheme (one of the already-defined ones; no particular need to do a full inheritance chain here), and then you can override any or all of the color keywords; any you don't override get taken from the base. So, like:

```
@color-scheme --solarized-dark {
  base-scheme: dark;
  CanvasColor: #002b36;
  CanvasText: #93a1a1;
  AccentColor: #6c71c4;
}
html {
  color-scheme: --solarized-dark;
}
```

This would override the "main" colors (text and background) used by everything (page background, inputs, etc), but take any remaining colors from the standard `dark` scheme.

**Comment by lukewarlow** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/system-color

**Comment by matthewp** [comment]
Ok, thanks, I think I understand the `@color-scheme` at rule now. How does this affect the proposed `schemed-value()` function?

**Comment by lukewarlow** [comment]
Ahh yeah like how it works for stuff like the only keyword that was added. Yeah right that makes sense.

**Comment by Loirooriol** [comment]
Restricting to dashed idents can be simpler, but it could also be like `@counter-style` that allows overriding most of the predefined ones.

**Comment by nt1m** [comment]
I would favor dashed idents, over a `@counter-style` design, it would be good if custom color schemes did not conflict with future new built-in color-schemes (if any).

**Comment by tabatkins** [comment]
I cannot tell what your first example is trying to do. Can you elaborate on the actual behavior you expect?

**Comment by lukewarlow** [comment]
For the same reason that you'd want to override system colours for custom themes would you not also want to be able to do this for the built in light and dark?

Might people just use a custom colour scheme even if they only have 1 dark theme specifically so they can more easily style native UI?

**Comment by bramus** [comment]
> ([#](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1839357671)) Not sure if this is what Bramus had in mind lol.

Originally I thought of only defining custom `color-scheme` values and then being able to respond to that [^1], as also shown in your example:

```css
@color-scheme --ancestry, --arc, --arc-grey;

:root {
  --color-link: schemed-value(
    --ancestry yellow,
    --arc red,
    --arc-grey lime
  )
}

a { color: var(--color-link) }
```

_(Ideally your example should also include `light` and `dark`)_

This feels like a good approach to pull some one-offs, but that is to be discussed in #7561.

---

What Luke and Tab are suggesting[^2] [^3], is to use a `@color-scheme` where authors can define their values for the system colors, with the ability to extend from an already existing scheme (via the `base` descriptor).

I hadn’t originally considered this, but this also makes sense, as it makes things a lot easier. With only these system colors, you can already change the entire site’s appearance.

---

I don’t think these should exclude each other. Combined, I see authors use it like this:

```css
/* Define --solarized-dark custom color-scheme, based on dark */
@color-scheme --solarized-dark {
  base-scheme: dark;
  CanvasColor: …;
  …
}

/* This page supports all of these color-scheme values */
html {
  color-scheme: --solarized-dark light dark;
}

/* Light Mode colors */
:root {
  --link-color: blue;
}
/* Dark Mode colors */
@media (prefers-color-scheme: dark) {
  :root {
    --link-color: pink;
  }
}
/* Custom --solarized-dark colors */
@media (prefers-color-scheme: --solarized-dark) {
  :root {
    --link-color: yellow;
  }
}

/* Ideal usage: use the custom prop that already responds to the chosen color-scheme */
a {
  color: var(--link-color);
}

/* Use schemed-value() for one-offs, i.e. for values that are not stored in a custom property that respond to color-scheme */
a.special {
  text-decoration-color: schemed-value(--solarized-dark red, light pink, dark lime);
}
```

[^1]: https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1833875432
[^2]: https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1833903340
[^3]: https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1834713634

**Comment by lukewarlow** [comment]
> I don’t think these should exclude each other. Combined, I see authors use it like this:

Yeah I completely agree.
Without Web Preferences you'd have to just do "color-scheme: --solarized-dark;" and swap it out when they change their mind. Kinda like how you have to currently if you provide a site user preference.

The `prefers-color-scheme` bit would also be relying on Web preferences API to know which of the color scheme is currently active.

**Comment by tabatkins** [comment]
> I don’t think these should exclude each other.

Oh, they were never intended to. A color scheme is a color scheme, if we have `schemed-color()` then yeah you can refer to a custom scheme in there.

What I still don't actually understand, tho, is what your original example is intending to do. I don't see anything activating a color scheme, nor any definition of what those three custom color schemes are. Are they intended to be literally meaningless outside of their ability to trigger `schemed-color()`? That's not workable - the color scheme defines the system colors, so we still need to know *at minimum* which built-in scheme to use for them (aka the `@color-scheme --foo { base-scheme: light; }` part of my proposal). And then letting you override those colors is just an obvious extension.

I might be missing something obvious about how you're intending that first example to behave, tho.

**Comment by bramus** [comment]
> ([#](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1841452919)) What I still don't actually understand, tho, is what your original example is intending to do. I don't see anything activating a color scheme, nor any definition of what those three custom color schemes are.

Activation: 
- Web Preferences API, where you set this on `:root`
- Author setting `color-scheme: --solarized-dark` on an element.

> ([#](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1841452919)) Are they intended to be literally meaningless outside of their ability to trigger schemed-color()?

No. I like what you proposed [here](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1834713634), in which an author can define a new color scheme and set the system colors. The minimum required descriptors are only the `base-scheme`, the maximum required descriptors are the minimum + all system colors

```css
/* Bare minimum custom color scheme */
@color-scheme --custom-minimum {
  base-scheme: dark;
}

/* Fully fledged custom color scheme */
@color-scheme --solarized-dark {
  base-scheme: dark;
  AccentColor: …;
  AccentColorText: …;
  ActiveText: …;
  ButtonBorder: …;
  ButtonFace: …;
  ButtonText: …;
  Canvas: …;
  CanvasText: …;
  Field: …;
  FieldText: …;
  GrayText: …;
  Highlight: …;
  HighlightText: …;
  LinkText: …;
  Mark: …;
  MarkText: …;
  VisitedText: …;
}
```

I see where [my reply](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1839810219) could be misinterpreted as the first code snippet echos what I initially had in mind … but that initial thought has evolved as this thread grew. The second example in [that comment](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1839810219) has the full picture, and incorporates your proposal _(as also detailed in the code snippet in this comment)_ … I think we’re thinking the same on this?

**Comment by bramus** [comment]
> ([#](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1841452919)) What I still don't actually understand, tho, is what your original example is intending to do. I don't see anything activating a color scheme, nor any definition of what those three custom color schemes are.

Activation: 
- Web Preferences API, where you set this on `:root`
- Author setting `color-scheme: --solarized-dark` on an element.

> ([#](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1841452919)) Are they intended to be literally meaningless outside of their ability to trigger schemed-color()?

No. I like what you proposed [here](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1834713634), in which an author can define a new color scheme and set the system colors. The minimum required descriptors are only the `base-scheme`, the maximum required descriptors are the minimum + all system colors

```css
/* Bare minimum custom color scheme */
@color-scheme --custom-minimum {
  base-scheme: dark;
}

/* Fully fledged custom color scheme */
@color-scheme --solarized-dark {
  base-scheme: dark;
  AccentColor: …;
  AccentColorText: …;
  ActiveText: …;
  ButtonBorder: …;
  ButtonFace: …;
  ButtonText: …;
  Canvas: …;
  CanvasText: …;
  Field: …;
  FieldText: …;
  GrayText: …;
  Highlight: …;
  HighlightText: …;
  LinkText: …;
  Mark: …;
  MarkText: …;
  VisitedText: …;
}
```

I see where [my reply](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1839810219) could be misinterpreted as the first code snippet echos what I initially had in mind … but that initial thought has evolved as this thread grew. The second example in [that comment](https://github.com/w3c/csswg-drafts/issues/9660#issuecomment-1839810219) has the full picture, and incorporates your proposal _(as also detailed in the code snippet in this comment)_ … I think we’re thinking the same on this?

**Comment by tabatkins** [comment]
Okay, then yeah, we're on the same page. ^_^

**Comment by matthewp** [comment]
@bramus but `color-scheme` does not activate a color scheme, it specifies what color schemes an element supports. Are you suggesting changing the meaning of this property?

**Comment by lukewarlow** [comment]
@matthewp Providing a single value to the `color-scheme` property *does* activate the chosen colour scheme. Because there's only 1 supported by the element.

The used colour scheme will be the singular value. Only when the element supports multiple is there some decision to be made on which one to use (based on user preference).

**Comment by matthewp** [comment]
@lukewarlow is this a new behavior being proposed? I don't see this happening currently, see for ex. https://codepen.io/matthewp/pen/RwvveQd

**Comment by lukewarlow** [comment]
`data:text/html,<input style="color-scheme: dark"><input style="color-scheme: light"><input style="color-scheme: light dark">` is a good demonstration.

The reason for your example appearing to not work is because of how color works. It's default value is CanvasText on html but then it inherits. So changing canvas text within the context of the section doesn't change how the CSS value is computed. If you add "color: CanvasText; background-color: Canvas;" to your example you'll see it works.

**Comment by matthewp** [comment]
@lukewarlow Thanks again. I have very rarely seen the system colors used in CSS. I'm guessing probably because they cannot be changed. It seems like this new feature might cause people to use them more (or, maybe it's more correct to say, allow them to be used as defaults). I could see that, even for light and dark schemes, you would define a custom `--dark` and `--light`, then modify the system colors, set the scheme on the root, and you've essentially done most of the work and only need to tweak from there. Very exciting.

**Comment by bramus** [comment]
Summarizing the issue, the current proposal is to allow authors to register custom color schemes through an at-rule. It requires at minimum a `base-scheme` that is used as the basis for the new scheme.

Inside the definition, all System Colors can then be specified. When one is omitted, the one from the `base-scheme` is used.

```css
@color-scheme --solarized-dark {
  base-scheme: dark;
  AccentColor: …;
  AccentColorText: …;
  …
}
```

Custom color schemes can then be used as a value in the `color-scheme` property, which was [future-proofed to accept `<custom-ident>`s](https://drafts.csswg.org/css-color-adjust/#color-scheme-prop:~:text=%3Ccustom%2Dident%3E%20values%20are%20meaningless%2C%20and%20exist%20only%20for%20future%20compatibility%2C%20so%20that%20future%20added%20color%20schemes%20do%20not%20invalidate%20the%20color%2Dscheme%20declaration%20in%20legacy%20user%20agents)

```css
html {
  color-scheme: --solarized-dark;
}
```

The [Web Preferences API](https://wicg.github.io/web-preferences-api/) would allow switching to a custom theme through a preference if multiple are defined. That would also enable the use of a custom color scheme in `prefers-color-scheme` Media Query Conditions.

The addition of custom color schemes opens up the door to [`schemed-value()`](https://github.com/w3c/csswg-drafts/issues/7561#issuecomment-1644625985) in the future.
