### ISSUE TITLE
[css-variables-2] Allow CSS variable to store transforms

### ISSUE THREAD

**Issue by tolmasky** [w3c/csswg-drafts#9791]
I searched the bugs for whether this was already suggested and didn't find anything, so apologies if this has already been covered. I'm just looking to be able to store transforms in CSS variables. One use case is to make "modular animations" significantly easier to implement with transforms. For example:

```css
@keyframes transform-animation-4-steps
{
    0% { transform: var(--transform-0); }
    25% { transform: var(--transform-25); }
    50% { transform: var(--transform-50); }
    100% { transform:var(--transform-100); }
}

.something
{
    --transform-0: translate(20px, 10px);
    --transform-25: translate(200px, 10px);
    --transform-50: translate(10px, 1000px);
    --transform-100: translate(99px, 9px);

    animation: 1s ease-in-out transform-animation-4-steps;
}
```

Currently the best you can do is something far less reusable and much more verbose:

```css
@keyframes transform-animation-4-steps
{
    0% { transform: translate(var(--x-0), var(--y-0)); }
    25% { transform: translate(var(--x-25), var(--y-25));}
    50% { transform: translate(var(--x-50), var(--y-50)); }
    100% { transform: translate(var(--x-100), var(--y-100));}
}
```
