### ISSUE TITLE
[css-ruby-1] "zh-Hanb" or "zh-Hant", which is correct for 30% font-size rule?

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/csswg-drafts#9873]
https://drafts.csswg.org/css-ruby/#default-ua-ruby

```css
rtc:lang(zh-TW), :not(rtc) > rt:lang(zh-TW),
rtc:lang(zh-Hanb), :not(rtc) > rt:lang(zh-Hanb), {
  font-size: 30%; }               /* bopomofo */
```

I think the "zh-Hanb" means Chenese with bopomofo script, but I found the following descriptin in the "Changes since the 2 December 2021 WD":

> - Added `zh-Hant` to rule applying [font-size: 30%](https://drafts.csswg.org/css-fonts-5/#descdef-font-face-font-size) to [ruby annotations](https://drafts.csswg.org/css-ruby/#ruby-annotation-box) in HTML.

"zh-Hanb" or "zh-Hant", which is correct?
