### ISSUE TITLE
[css-backgrounds] Clothoid Corners for `border-radius`

### ISSUE THREAD

**Issue by petamoriken** [w3c/csswg-drafts#9876]
original: https://note.com/onopko/n/n9358eb1262eb

Some UIs, like the native iOS UI, are cornered using a clothoid curve. I believe that supporting this in CSS will increase expressiveness and interoperability.

```css
.box {
    border-radius: clothoid(3em);
}
```

https://drafts.csswg.org/css-backgrounds/#border-radius
