### ISSUE TITLE
[css-values-5] toggle() should be a psuedo-class instead similar to :nth-child()

### ISSUE THREAD

**Issue by miragecraft** [w3c/csswg-drafts#9899]
A few days ago I ran into the problem of styling nested elements and was informed via Twitter that there's already a `toggle()` function in the [draft stage](https://drafts.csswg.org/css-values-5/#toggle-notation).

However upon a closer look I'm not sure solving the problem of styling nested elements via a function is the ideal solution as I feel a psuedo-class in the veins of `:nth-child()` selector is much more useful, such as `:nth-descendant()`.

There are several disadvantage with the `toggle()` function compared to a hypothetical `:nth-descendant()` pseudo-class:

1. Must toggle on a per-property basis, so in case of multiple properties you must use multiple `toggle()` function and manually sync them up, it gets especially convoluted and verbose if you need to repeat the same value multiple times.
2. Toggling on a per-property basis also mean you can't logically group multiple values belonging to a single "toggle state" together, they must be intermixed with other toggle states making everything difficult to read.
3. Forced to manually declare the sequence of values, instead of using the already existing logic we have for `:nth-child()` selector with its `even`, `odd` and `An+B` syntax.
4. No way to toggle based on parent element's nesting level, such as `blockquote:nth-descendant(even) .titlebar {background:blue}`. To do this with `toggle()` function you'd need to toggle a variable in the parent and then use said variable in the child element, adding undue complexity. 

The above is why I believe `toggle()` should not be a function at all, but a pseudo-class instead.

**Comment by Loirooriol** [comment]
You seem to want the selector variant of the `tree-depth()` function from https://github.com/w3c/csswg-drafts/issues/4559#issuecomment-562374563.
`toggle()` seems something entirely different.

**Comment by miragecraft** [comment]
> You seem to want the selector variant of the `tree-depth()` function from [#4559 (comment)](https://github.com/w3c/csswg-drafts/issues/4559#issuecomment-562374563). `toggle()` seems something entirely different.

Kind of, I think it's better to describe it as a depth version of `:nth-child()` selector (pseudo-class) with all the syntactical sugar associated with it, including the `of` keyword which allow you skip levels.

I'd argue it's not something entirely different because it's trying to solve the same problem but with worse ergonomics and limited utility.

It's the same as arguing for a hypothetical `toggle-siblings()` function, why implement that instead of the much more powerful `:nth-child()`?

**Comment by Loirooriol** [comment]
So I guess you say `toggle()` would be redundant because e.g.

```css
.list {
  list-style-type: toggle(disc, circle, "+ ", "> ", "* ");
}
```

could be expressed as

```css
:nth-descendant(6n+1 of .list) { list-style-type: disc }
:nth-descendant(6n+2 of .list) { list-style-type: circle }
:nth-descendant(6n+3 of .list) { list-style-type: "+ " }
:nth-descendant(6n+4 of .list) { list-style-type: "> " }
:nth-descendant(6n+5 of .list) { list-style-type: "* " }
```

But note that `toggle()` resolves depending on the inherited value, and the cascade is based on the flat tree. Presumably, `:nth-descendant()` wouldn't use the flat tree. This was one of the reasons to not deprecate `:focus-within` in #8357.

This is not to say that `toggle()` can't be dropped, but I think it may be better to consider your feature by itself, and if accepted, discuss if `toggle()` is still useful or not afterwards.
