### ISSUE TITLE
[css-anchor-position] Add 'anchor-default' to the list of allowed @position-try properties

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#9950]
During the Anchor topics at the f2f, @frivoal asked if there was a reason 'anchor-default' wasn't allowed to be set in the fallbacks. The answer is - there is no reason! It's perfectly fine to do so; all it does it change what anchor element you're pointing to in a few properties, and you can set those explicitly.

That is, since you can already say:

```css
.popup {
  position-try: --try1, --try2;
}
@position-try --try1 {
  top: anchor(--anchor1 bottom);
}
@position-try --try2 {
  top: anchor(--anchor2 bottom);
}
```

then it's equally fine to say:

```css
.popup {
  top: anchor(bottom);
  position-try: --try1, --try2;
}
@position-try --try1 {
  anchor-default: --anchor1;
}
@position-try --try2 {
  anchor-default: --anchor2;
}
```

So we should add 'anchor-default' to the list of allowed properties.
